// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.build_plan.examples;

message CqBuildPlanProperties {
  // The expected experiments for the builder.
  repeated string expected_experiments = 1;

  // The builder names of the expected child build requests.
  repeated string expected_build_requests = 2;

  // The builder names of the expected completed builds.
  repeated string expected_completed_builds = 3;

  // The IDs of snapshots to use for the build plan.
  repeated string snapshot_ids = 4;

  // The IDs of expected unfinished snapshots.
  repeated string expected_unfinished_snapshots = 5;

  // The IDs of expected failed snapshots.
  repeated string expected_failed_snapshots = 6;


}
