// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_bisect;

message CrosBisectProperties {
  // List of targets that failed needing to be run during bisection.
  // These are JSON encoded PackageInfo objects.
  repeated string targets = 1;

  // Properties sent for compile failure bisection.
  message CompileFailures {
    repeated string targets = 1;
  }
  CompileFailures compile = 2;

  // TODO(dburger): message TestFailures
}
