// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_bisect;

message CrosBisectProperties {
  // Properties sent for compile failure bisection.
  message CompileFailures {
    // List of targets that failed needing to be run during bisection.
    // These are JSON encoded PackageInfo objects.
    repeated string targets = 1;
  }
  CompileFailures compile = 2;

  // Properties sent for compile failure bisection.
  message TestFailures {
    // Encodes information for rerunning a test failure.
    message TestFailure {
      // JSON encoded test configuration proto.
      string test_spec = 1;
    }

    // Hardware TestFailures serialize HwTestUnit protos in test_spec
    repeated TestFailure hw_test_failures = 1;
  }
  TestFailures test = 3;

  // The threshold for the ratio of failed tests to total tests
  // below which test bisection gets triggered.
  float test_bisection_percent = 4;

  // The threshold for the number of failed tests below which
  // test bisection gets triggered.
  int32 test_bisection_count = 5;
}
