// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.failures.examples;

import "go.chromium.org/luci/buildbucket/proto/build.proto";

message BuildProperties {
  // The builds.
  repeated buildbucket.v2.Build builds = 1;

  // Same as builds, but only the ones we expect to be failures.
  repeated buildbucket.v2.Build expected_failing_builds = 3;

  // Expected is_critical_build_failure.
  bool expected_is_critical_build_failure = 4;

  reserved 2;
}
