// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_resultdb.tests.test;

import "test_platform/request.proto";

message TestInputProperties {

  test_platform.Request.Params.TestExecutionBehavior default_behavior = 1;

  // Maps the name of a test case to a TestExecutionBehavior.
  map<string, test_platform.Request.Params.TestExecutionBehavior>
      behavior_overrides_map = 2;

  // Variant attributes which must all be present in a test results variant.
  map<string, string> variant_filter = 3;
}
