// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.failures;

import "chromiumos/common.proto";
import "recipe_modules/chromeos/cq_fault_attribution/cq_fault_attribution.proto";

message PackageFailure {

  enum Phase {
    UNSPECIFIED = 0;
    COMPILE = 1;
    TEST = 2;
  }

  // The package which failed.
  chromiumos.PackageInfo package = 1;

  // The build phase during which the package failed to emerge.
  Phase phase = 2;

  // Whether the failed package was affected by the changes under test.
  // This could be the CLs applied to the CQ run or the packages upreved in a
  // snapshot build.
  bool affected_by_changes = 3;

  // Whether this failure was also seen on snapshot.
  recipe_modules.chromeos.cq_fault_attribution.CqFailureAttribute
      snapshot_comparison = 4;
}