// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_source.examples;

message PushUprevsArgs {
  // Commit the files only, don't push.
  bool commit_only = 1;
  // Describes is the uprev is being pushed to staging or prod.
  bool is_staging = 2;
  // Whether to pass `discard_unpushed_changes` to the `push_uprev` call.
  bool discard_unpushed_changes = 3;
}
