// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_sdk.examples;

import "go.chromium.org/luci/buildbucket/proto/common.proto";

message TestInputProperties {
  // SDK cache version
  int32 sdk_cache_version = 1;

  // Gitiles Commit
  buildbucket.v2.GitilesCommit gitiles_commit = 2;

  // Gerrit Changes
  repeated buildbucket.v2.GerritChange gerrit_changes = 3;

  // If Remoteexec properties should be checked.
  bool check_remoteexec = 4;
}
