// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.afdo_process;

import "chromiumos/common.proto";

message AfdoProcessProperties {
  // The build target being built.
  chromiumos.BuildTarget build_target = 1;

  // Override for pointless build check.
  bool force_relevant_build = 2;

  // Whether this is an artifact build.  Must be True.  crbug/1099259.
  bool artifact_build = 3;

  // Location information for the original build artifacts.  These are in
  // addition to those found in the builder config, and provide the location of
  // build artifacts (IMAGE_ZIP) from the child build that created the image
  // used to create the perf file.
  repeated chromiumos.ArtifactsByService.Toolchain.ArtifactInfo input_artifacts = 4;
}
