# -*- coding: utf-8 -*-
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Orchestrator for Android uprev builders.

The orchestrator determines the latest Android version for the specified Android
package, then passes the info down into child builders running the
build_android_uprev recipe.

Once all builds and tests passed, it submits a CL to update the Android LKGB
file. The change will in turn trigger the PUpr generator to publish an actual
Android uprev.
"""

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/step',
    'android',
    'build_menu',
    'cros_source',
    'easy',
    'gerrit',
    'git',
    'orch_menu',
    'repo',
]

from recipe_engine import post_process
from recipe_engine.recipe_api import StepFailure
from PB.recipes.chromeos.android_uprev import AndroidUprevProperties

PROPERTIES = AndroidUprevProperties


def RunSteps(api, properties):
  with api.orch_menu.setup_orchestrator(missing_ok=True) as config:
    if config:
      DoRunSteps(api, properties)
    return api.orch_menu.create_recipe_result()


def DoRunSteps(api, properties):
  android_package = properties.android_package
  if not android_package:
    raise StepFailure('android_package not set')

  android_version = (
      properties.android_version or
      api.android.get_latest_build(android_package))

  submit_uprev = properties.submit_uprev

  # Save android_version in output for dashboard queries.
  api.easy.set_properties_step(android_version=android_version)

  # Update LKGB here. If no files were modified i.e. LKGB is already the same
  # version, there's nothing to do.
  modified_files = api.android.write_lkgb(android_package, android_version)
  if not modified_files:
    return

  extra_child_props = {
      'android_package': android_package,
      'android_version': android_version,
  }

  # Run the child builders.
  builds_status = api.orch_menu.plan_and_run_children(
      extra_child_props=extra_child_props,
  )

  # Aggregate any metadata produced by the child builds into our own GS bucket
  api.orch_menu.aggregate_metadata(builds_status.completed_builds)

  # Run any HW tests.
  builds_status = api.orch_menu.plan_and_run_tests()

  if builds_status.fatal_failures:
    # Do not proceed if any critical builds/tests failed.
    # api.orch_menu.create_recipe_result() will return an error for us.
    return

  # Submit the LKGB update.
  with api.step.nest('commit and generate CL'):
    workspace_path = api.cros_source.workspace_path
    with api.context(cwd=workspace_path):
      # As of today |modified_files| should contain exactly one file.
      info = api.repo.project_info(project=api.path.dirname(modified_files[0]))

    commit_lines = [
        '{}: Mark version {} as LKGB.'.format(android_package, android_version),
        '',
        'Generated by android_uprev_orchestrator.',
        '',
        'BUG=None',
        'TEST={}'.format(api.buildbucket.build_url()),
        '',
    ]
    commit_message = '\n'.join(commit_lines) + '\n'

    project_path = workspace_path.join(info.path)
    with api.context(cwd=project_path):
      # Commit the change onto a new branch tracking upstream.
      api.git.checkout('HEAD', branch='lkgb')
      api.git.set_upstream(info.remote, info.branch_name)
      api.git.add(list(modified_files))
      api.git.commit(commit_message)

      # Pull and rebase onto latest upstream. Discard any conflicting upstream
      # changes by setting --strategy-option=theirs (see `git help rebase` for
      # detail.) No one else should be touching these files after all.
      api.git.fetch(info.remote)
      api.git.rebase(strategy_option='theirs')

    # Create a CL, and submit if needed.
    change = api.gerrit.create_change(info.path,
                                      reviewers=['shaochuan@google.com'])
    if submit_uprev:
      api.gerrit.set_change_labels(change, {api.gerrit.Label.BOT_COMMIT: 1})
      api.gerrit.submit_change(change)

      # The dashboard takes the commit hash of the LKGB update we just published
      # to find the PUpr generator build it triggers. Query gerrit to find the
      # commit hash of the latest (submitted) patchset and save in output props.
      patch_sets = api.gerrit.fetch_patch_sets([change])
      api.easy.set_properties_step(lkgb_commit=patch_sets[0].current_revision)
    else:
      api.gerrit.abandon_change(change)

  # Launch any specified follow on orchestrator.
  api.orch_menu.run_follow_on_orchestrator()


def GenTests(api):

  data = api.orch_menu.standard_test_data()

  yield api.orch_menu.test(
      'basic', data.ctp_normal,
      api.properties(android_package='android-package', submit_uprev=True),
      api.post_check(post_process.StatusSuccess), with_history=True,
      collect_builds=data.builds)

  yield api.orch_menu.test('no-submit', data.ctp_normal,
                           api.properties(android_package='android-package'),
                           api.post_check(post_process.StatusSuccess),
                           with_history=True, collect_builds=data.builds)

  yield api.orch_menu.test('android-package-not-set',
                           api.post_check(post_process.StatusFailure))

  yield api.orch_menu.test(
      'lkgb-unmodified', api.properties(android_package='android-package'),
      api.android.set_write_lkgb_response(modified_files=[]),
      api.post_check(post_process.StatusSuccess))

  yield api.orch_menu.test('build-failure', data.ctp_normal,
                           api.properties(android_package='android-package'),
                           api.post_check(post_process.StatusFailure),
                           with_history=True, collect_builds=data.crit_fail)

  yield api.orch_menu.test('test-failure', data.ctp_failure,
                           api.properties(android_package='android-package'),
                           api.post_check(post_process.StatusFailure),
                           with_history=True, collect_builds=data.builds)
