# -*- coding: utf-8 -*-
# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Orchestrator for Android uprev builders.

The orchestrator determines the latest Android version for the specified Android
package, then passes the info down into child builders running the
build_android_uprev recipe.

Once all builds and tests passed, it submits a CL to update the Android LKGB
file. The change will in turn trigger the PUpr generator to publish an actual
Android uprev.
"""

from typing import Generator

from recipe_engine import post_process
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_api import StepFailure
from recipe_engine.recipe_test_api import RecipeTestApi
from recipe_engine.recipe_test_api import TestData

from PB.recipe_engine.result import RawResult
from PB.recipes.chromeos.android_uprev import AndroidUprevProperties
from RECIPE_MODULES.chromeos.gerrit.api import Label

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/step',
    'android',
    'cros_infra_config',
    'cros_source',
    'easy',
    'gerrit',
    'git',
    'orch_menu',
    'repo',
]


PROPERTIES = AndroidUprevProperties

# The overlay that hosts Android packages.
_OVERLAY_PATH = 'src/private-overlays/project-cheets-private'

# Projects that need to be synced to input manifest.
_SYNC_PROJECTS = [
    _OVERLAY_PATH,
    'chromite',
    # Chromite reads chromeos_version.sh to determine the milestone.
    'src/third_party/chromiumos-overlay',
]


def RunSteps(api: RecipeApi, properties: AndroidUprevProperties) -> RawResult:
  with api.orch_menu.setup_orchestrator() as config:
    if config:
      DoRunSteps(api, properties)
    return api.orch_menu.create_recipe_result()


def DoRunSteps(api: RecipeApi, properties: AndroidUprevProperties) -> None:
  android_package = properties.android_package
  if not android_package:
    raise StepFailure('android_package not set')
  android_branch = properties.android_branch

  api.cros_source.ensure_synced_cache(
      projects=_SYNC_PROJECTS, is_staging=api.cros_infra_config.is_staging)

  android_version = (
      properties.android_version or
      api.android.get_latest_build(android_package, android_branch))

  submit_uprev = properties.submit_uprev
  always_build = properties.always_build

  # Save android_version in output for dashboard queries.
  api.easy.set_properties_step(android_version=android_version)

  # Create a branch in the overlay project and sync to ToT.
  overlay_path = api.cros_source.workspace_path / _OVERLAY_PATH
  with api.step.nest('create branch and sync overlay') as pres, \
      api.context(cwd=overlay_path):
    info = api.repo.project_info(project=overlay_path)
    api.git.checkout('HEAD', branch='lkgb')
    api.git.set_upstream(info.remote, info.branch_name)
    api.git.fetch(info.remote)
    api.git.rebase()
    pres.step_text = '{} synced to {}'.format(info.path, api.git.head_commit())

  # Update LKGB here. If no files were modified i.e. LKGB is already the same
  # version, there's nothing to do (unless |always_build| is set).
  modified_files = api.android.write_lkgb(android_package, android_version,
                                          android_branch)
  if not modified_files and not always_build:
    return

  extra_child_props = {
      'android_package': android_package,
      'android_version': android_version,
      'always_build': always_build,
  }
  if android_branch:
    extra_child_props['android_branch'] = android_branch

  # Run the child builders.
  builds_status = api.orch_menu.plan_and_run_children(
      extra_child_props=extra_child_props,
  )

  # Run any HW tests.
  builds_status = api.orch_menu.plan_and_run_tests()

  if builds_status.fatal_failures:
    # Do not proceed if any critical builds/tests failed.
    # api.orch_menu.create_recipe_result() will return an error for us.
    return

  # Submit the LKGB update if any. |modified_files| can be empty if
  # |always_build| is set to true.
  if modified_files:
    with api.step.nest('commit and generate CL'):
      commit_lines = [
          '{}: Mark version {} as LKGB.'.format(android_package,
                                                android_version),
          '',
          'Generated by android_uprev_orchestrator.',
          '',
          'BUG=None',
          'TEST={}'.format(api.buildbucket.build_url()),
          '',
      ]
      commit_message = '\n'.join(commit_lines) + '\n'

      with api.context(cwd=overlay_path):
        api.git.add(list(modified_files))
        api.git.commit(commit_message)

      # Create a CL, and submit if needed.
      change = api.gerrit.create_change(info.path, hashtags=[android_package])
      if submit_uprev:
        api.gerrit.set_change_labels(change, {Label.BOT_COMMIT: 1})
        api.gerrit.submit_change(change)

        # The dashboard takes the commit hash of the LKGB update we just published
        # to find the PUpr generator build it triggers. Query gerrit to find the
        # commit hash of the latest (submitted) patchset and save in output props.
        patch_sets = api.gerrit.fetch_patch_sets([change])
        api.easy.set_properties_step(lkgb_commit=patch_sets[0].current_revision)
      else:
        api.gerrit.abandon_change(change)

  # Launch any specified follow on orchestrator.
  api.orch_menu.run_follow_on_orchestrator()


def GenTests(api: RecipeTestApi) -> Generator[TestData, None, None]:

  data = api.orch_menu.standard_test_data()

  yield api.orch_menu.test(
      'basic', data.ctp_normal,
      api.properties(android_package='android-package',
                     android_branch='android-branch', submit_uprev=True),
      api.post_check(post_process.MustRun, 'run builds'),
      api.post_check(post_process.MustRun,
                     'commit and generate CL.submit CL 1'), with_history=True,
      collect_builds=data.builds)

  yield api.orch_menu.test(
      'no-submit', data.ctp_normal,
      api.properties(android_package='android-package'),
      api.post_check(post_process.DoesNotRun,
                     'commit and generate CL.submit CL 1'), with_history=True,
      collect_builds=data.builds)

  yield api.orch_menu.test('android-package-not-set', status='FAILURE')

  yield api.orch_menu.test(
      'lkgb-unmodified',
      api.properties(android_package='android-package'),
      api.android.set_write_lkgb_response(modified_files=[]),
      api.post_check(post_process.DoesNotRun, 'run builds'),
  )

  yield api.orch_menu.test(
      'always-build', data.ctp_normal,
      api.properties(android_package='android-package', always_build=True),
      api.android.set_write_lkgb_response(modified_files=[]),
      api.post_check(post_process.MustRun, 'run builds'), with_history=True,
      collect_builds=data.builds)

  yield api.orch_menu.test('build-failure', data.ctp_normal,
                           api.properties(android_package='android-package'),
                           with_history=True, collect_builds=data.crit_fail,
                           status='FAILURE')

  yield api.orch_menu.test('test-failure', data.ctp_failure,
                           api.properties(android_package='android-package'),
                           with_history=True, collect_builds=data.builds,
                           status='FAILURE')
