// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.annealing;

import "go.chromium.org/luci/buildbucket/proto/common.proto";
message AnnealingProperties {
  // The name of the git branch to create snapshots on. Required.
  string manifest_ref = 1;

  // Whether or not to publish uprevs.
  bool publish_uprevs = 2;

  // If true, the snapshot commit message will not list Gerrit changes. This
  // property should only be set temporarily to get Annealing back in a good
  // state. For example, Annealing has not succeeded in a long time, so the
  // message length exceeds Git limits.
  bool disable_gerrit_commits_in_commit_message = 3;

  // Jobs to trigger based on gitiles commits.
  // Once the uprev is published, if any of the regexp triggers hit, then the
  // named job(s) will be launched with the new gitiles_commit.
  message PathTrigger {
    // The path of the repo, relative to workspace_path.
    string repo_path = 1;

    // Paths to pass to git log.  If empty, then trigger on any commit to the
    // repo.
    repeated string file_paths = 2;

    // The BB task to schedule.
    message Job {
      string project = 1;
      string bucket = 2;
      string builder = 3;
    }
    repeated Job jobs = 3;
  }
  repeated PathTrigger path_triggers = 4;

  // If this is a dry run, do not actually push the manifest ref.
  bool dry_run = 5;

  // TODO(crbug/1148052): remove this logic.
  // Whether to disable "prior_commit" logic.
  bool use_ref_not_id = 6;

  // TODO(crbug/1169277): Remove this property once the code is fixed to allow
  // moving a pinned git repo backwards.
  // List of project paths to ignore downrevs, to work around crbug/1169277.
  // If specified, downrevs on these paths will be ignored during "check
  // reachability".  This should only be used to manually launch Annealing in
  // order to fix breakage caused by a pin-change that downrevs a pinned git
  // repository.
  repeated string ignore_downrev_paths = 7;

  // Feature flag used to signal where to uprev. b/179496445
  bool uprev_first = 8;
}

// Annealing determines what Gerrit changes have landed since its last run,
// and uploads its findings to Isolate. This proto stores that data.
message SnapshotGerritChanges {
  // All Gerrit changes since the last snapshot.
  repeated buildbucket.v2.GerritChange gerrit_changes = 2;
}
