// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.annealing;

import "go.chromium.org/luci/buildbucket/proto/common.proto";

message AnnealingProperties {
  // The name of the git branch to create snapshots on. Required.
  string manifest_ref = 1;

  // Whether or not to publish uprevs.
  bool publish_uprevs = 2;

  // If true, the snapshot commit message will not list Gerrit changes. This
  // property should only be set temporarily to get Annealing back in a good
  // state. For example, Annealing has not succeeded in a long time, so the
  // message length exceeds Git limits.
  bool disable_gerrit_commits_in_commit_message = 3;
}

// Annealing determines what Gerrit changes have landed since its last run,
// and uploads its findings to Isolate. This proto stores that data.
message SnapshotGerritChanges {
  // All Gerrit changes since the last snapshot.
  repeated buildbucket.v2.GerritChange gerrit_changes = 2;
}
