// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.branch_rename;

import "chromiumos/branch.proto";

// Input properties for rename branch recipe.
message RenameBranchProperties {
  // If not set, git push commands include --dry-run.
  bool push = 1;

  // If not set, any command that would overwrite an existing branch/version fails.
  bool force = 2;

  // Branch to be renamed.
  chromiumos.Branch branch = 3;

  // New branch name.
  string new_name = 4;
}
