// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.branch_create;

import "go.chromium.org/luci/buildbucket/proto/common.proto";
import "chromiumos/branch.proto";

message BranchManifest {
  // Gitiles commit to fetch.
  buildbucket.v2.GitilesCommit gitiles_commit = 1;
  // Name of manifest.
  string filename = 2;
}

// Input properties for create branch recipe.
message CreateBranchProperties {
  // If not set, git push commands include --dry-run.
  bool push = 1;

  // If not set, any command that would overwrite an existing branch/version fails.
  bool force = 2;

  // Manifest to branch from.
  // If the manifest at the URL has includes, the branch tool will erroneously
  // fail.
  BranchManifest manifest = 3;

  // Branch to be created.
  chromiumos.Branch branch = 4;
}
