# -*- coding: utf-8 -*-
# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe that builds chromeos-firmware on a firmware branch.

This recipe is not deprecated. All branched firmware builds should use this
recipe.
"""

import re
from collections import defaultdict
from contextlib import contextmanager

from PB.chromite.api.firmware import FirmwareArtifactInfo
from PB.chromite.api.sysroot import Sysroot
from PB.chromiumos import common as common_pb2
from PB.chromiumos.builder_config import BuilderConfig
from PB.go.chromium.org.luci.buildbucket.proto import common
from PB.recipe_engine import result as result_pb2
from PB.recipes.chromeos.build_legacy_fw import BuildLegacyFwProperties
from recipe_engine import post_process
from recipe_engine import recipe_api

DEPS = [
    'recipe_engine/bcid_reporter',
    'recipe_engine/context',
    'recipe_engine/cv',
    'recipe_engine/file',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'depot_tools/depot_tools',
    'build_menu',
    'cros_artifacts',
    'cros_build_api',
    'cros_infra_config',
    'cros_release',
    'cros_sdk',
    'cros_version',
    'easy',
    'failures',
    'git',
    'metadata_json',
    'repo',
    'src_state',
    'test_util',
]


PROPERTIES = BuildLegacyFwProperties
_FIRMWARE_TARBALL_NAME = 'firmware_from_source.tar.bz2'
_FIRMWARE_METADATA_NAME = 'firmware_metadata.jsonpb'

_GETVERSION_TEST_DATA = '''/* This file is generated by util/getversion.sh */
#define CROS_EC_VERSION32 "_v0.0.3733-0612ae7"
/* Version string for ectool. */
#define CROS_ECTOOL_VERSION "v0.0.3733-0612ae7"
/* Version string for stm32mon. */
#define CROS_STM32MON_VERSION "v0.0.3733-0612ae7"
/* Sub-fields for use in Makefile.rules and to form build info string
 * in common/version.c. */
#define VERSION "_v0.0.3733-0612ae7"
#define BUILDER "ldap@machine.example.com"
/* Repo is clean, use the commit date of the last commit. */
#define DATE "2021-03-10 20:52:43"
'''

# If the manifest does not have tip-of-tree chromite, then we will need to do a
# checkout of that.
#
# The tip-of-tree chromite is used for Uprev and PushImage steps only,
# everything else uses the branched version of chromite.  Once those have been
# properly created in recipes modules, we should use the module code instead.
_CHROMITE_HOST = 'https://chromium.googlesource.com'
_CHROMITE_PROJECT = 'chromiumos/chromite'
_CHROMITE_URL = '{}/{}'.format(_CHROMITE_HOST, _CHROMITE_PROJECT)

# TODO(b/187787264): On old branches, chromite may still depend on the chroot
# living within the source tree. On newer branches we need to use the
# new out path.
_BUILD_VERSION_BUILD_DIR_MOVED = 15613
_BUILD_VERSION_TMP_DIR_MOVED = 15457

class NoFilesToUploadFailure(recipe_api.StepFailure):
  """Error class for when there are no files to upload as a FirmwareArchive."""


# The age of the branches is such that we do not even have a Build API for the
# most part.
class FirmwareBuilder():

  def __init__(self, api, properties):
    self.m = api
    # If not specified, default to building virtual/chromeos-firmware.
    if not properties.packages:
      pkg = properties.packages.add()
      pkg.category = 'virtual'
      pkg.package_name = 'chromeos-firmware'

    # We may have been passed properties.build_target.
    if not properties.build_targets and properties.build_target.name:
      bt = properties.build_targets.add()
      bt.CopyFrom(properties.build_target)
    assert len(properties.build_targets), 'No build_targets specified.'

    self.properties = properties
    self._boards = [x.name for x in properties.build_targets]
    if properties.chroot_outside:
      self._chroot = self.m.path.mkdtemp() / 'chroot'
    else:
      self._chroot = self.m.src_state.workspace_path / 'chroot'
    self._config = None
    self._bcs_version = None
    self._firmware_version = None
    self._is_staging = True
    # Whether suite_scheduling should consider our firmware tarball.
    self._suite_scheduling = False
    self._old_setup_board = False
    self._tot_chromite = None
    # TODO(b/188555398): Make this False once the root-cause is identified.
    self._debug = True

  def sdk_call(self, name, sdk_args=(), cmd=(), **kwargs):
    """Run cros_sdk with the given command"""
    command = [
        self.m.cros_sdk.cros_sdk_path,
        '--log-level',
        self.m.cros_build_api.log_level,
    ]
    if self.properties.chroot_outside:
      # After _BUILD_VERSION_TMP_DIR_MOVED, pass an out dir since we'll be
      # using it for out/tmp (and out/build, after _BUILD_VERSION_BUILD_DIR_MOVED)
      if self.m.cros_version.version.build >= _BUILD_VERSION_TMP_DIR_MOVED:
        command.extend([
            '--chroot',
            self.m.cros_sdk.chroot.path,
            '--out-dir',
            self.m.cros_sdk.chroot.out_path,
        ])
      else:
        command.extend(['--chroot', str(self._chroot)])
    command += list(sdk_args)
    # Pass in any USE flags from the builder config.
    if cmd:
      if self._config:
        command.append('USE={}'.format(' '.join(
            x.flag for x in self._config.build.use_flags)))
      command.extend(['--'] + list(cmd))
    kwargs.setdefault('infra_step', True)
    # Tell chromite that this is an official build, so that chromeos_version.sh
    # reports the same version as cros_version.
    with self.m.context(env={'CHROMEOS_OFFICIAL': '1'}):
      return self.m.step(name, command, **kwargs)

  def _is_after(self, version_str):
    """Return whether the workspace version is >= |version_str|."""
    return self._bcs_version.is_after(version_str)

  @contextmanager
  def _setup(self):
    """Configure the builder"""
    # If we do not have a gitiles_commit from buildbucket, and input properties
    # has manifest_branch, use that branch of the internal manifest.
    self._is_staging = self.m.build_menu.is_staging
    commit = self.m.src_state.gitiles_commit
    targets = self.properties.build_targets
    if not commit.project and self.properties.manifest_branch:
      commit = self.m.src_state.internal_manifest.as_gitiles_commit_proto
      commit.ref = 'refs/heads/{}'.format(self.properties.manifest_branch)

    with self.m.build_menu.configure_builder(commit=commit, disable_sdk=True,
                                             targets=targets) as config:
      self._config = config
      with self.m.build_menu.setup_workspace(), \
          self.m.context(cwd=self.m.src_state.workspace_path):
        self._old_setup_board = self.m.path.exists(
            self.m.src_state.workspace_path / 'src/scripts/setup_board')

        if self.properties.bump_version:
          self._bump_version(
              buildspec_gs_path=self.properties.buildspec_gs_path)
        self._bcs_version = self.m.cros_version.version
        # Uprev after bumping the version. See http://b/331850204#comment6.
        self._uprev()

        entries = {
            'boards': self._boards,
            'version': {
                'with_snapshot': str(self._bcs_version),
                'full': self._bcs_version.legacy_version,
                'milestone': self._bcs_version.milestone,
                'platform': self._bcs_version.platform_version,
            },
            # Today's board-metadata may include firmware versions, though that
            # is unpopulated for many (if not all) of the current firmware
            # builders.
            'board-metadata': {x: {} for x in self._boards},
        }
        self.m.metadata_json.add_entries(**entries)
        self.m.metadata_json.upload_to_gs(config, targets, partial=True)

        with self.m.depot_tools.on_path(), self._setup_chroot():
          self._set_firmware_version()
          yield

  def _bump_version(self, buildspec_gs_path=None):
    dry_run = self._is_staging or self.m.cv.active
    self.m.cros_version.bump_version(dry_run=dry_run)
    if self.m.cv.active:
      with self.m.step.nest('CQ run: not pushing buildspec'):
        return

    self.m.cros_release.create_buildspec(step_name='create buildspec',
                                         dry_run=dry_run,
                                         gs_location=buildspec_gs_path)
    # Only these builds are valid for suite_scheduling to find.
    self._suite_scheduling = (
        self.properties.set_suite_scheduling and not dry_run)

  def _uprev(self):
    # TODO(b/181786185): Once we have a good "push the uprevs" method, we should
    # switch to calling cros_source.uprev_packages, and pushing them, for
    # branches that are new enough.

    with self.m.step.nest('uprev packages') as pres:
      # The build team supports using the tip-of-tree cros_mark_as_stable to
      # uprev older branches until such time as they have a long-term answer.
      # This is not true for other chromite commands.
      self._ensure_chromite_main()
      push = not bool(self.m.cv.active or self._is_staging or
                      self.m.src_state.gerrit_changes)
      drop_file = self.m.path.mkstemp()
      manifest = 0 if not self._config else self._config.general.manifest

      uprev_args = [
          '--all',
          '--boards=%s' % ':'.join(self._boards), '--buildroot',
          self.m.src_state.workspace_path, '--overlay-type',
          'public' if manifest == BuilderConfig.General.PUBLIC else 'both'
      ]
      cmd = [
          self._tot_chromite / 'bin/cros_mark_as_stable', 'commit',
          '--drop_file', drop_file
      ]
      if not push:
        cmd.append('--dryrun')
      cmd += uprev_args
      self.m.step('call cros_mark_as_stable commit', cmd)
      pres.logs['packages'] = self.m.file.read_raw(
          'read uprevved packages', drop_file,
          test_data='sys-boot/depthcharge sys-apps/coreboot-utils')

      if push:
        cmd = [self._tot_chromite / 'bin/cros_mark_as_stable', 'push'
              ] + uprev_args
        self.m.step('call cros_mark_as_stable push', cmd)

  def _ensure_chromite_main(self):
    if self._tot_chromite:
      return

    workspace = self.m.src_state.workspace_path
    with self.m.context(cwd=workspace):
      for info in self.m.repo.project_infos(
          projects=['chromiumos/chromite'],
          test_data=self.m.repo.test_api.project_infos_test_data(data=[
              {
                  'project': _CHROMITE_PROJECT,
                  'path': 'chromite',
                  'upstream': 'refs/heads/firmware-target-99999.B',
              },
              {
                  'project': _CHROMITE_PROJECT,
                  'path': 'infra/chromite-HEAD',
                  'upstream': 'refs/heads/main',
              },
          ])):
        if info.branch_name == 'main':
          self._tot_chromite = workspace / info.path
          break

    if not self._tot_chromite:
      self._tot_chromite = self.m.path.mkdtemp() / 'chromite'
      self.m.git.clone(_CHROMITE_URL, target_path=self._tot_chromite,
                       single_branch=True, reference=workspace / 'chromite')

  @contextmanager
  def _setup_chroot(self):
    try:
      if self._debug:
        with self.m.step.nest('gather debug info'):
          self.m.step('list workspace', ['ls'])
          self.m.step('mounts', ['cat', '/proc/mounts'])
          self.m.step('processes', ['ps', 'auxf'])
          self.m.step('df', ['df'])
          self.m.step('df -i', ['df', '-i'])
      self.sdk_call('init SDK', sdk_args=['--delete', '--create'])
      if self.properties.chroot_outside:
        self.m.cros_sdk.link_chroot(self.m.src_state.workspace_path,
                                    self._chroot)
      if not self._is_after('15840.0.0'):
        cmd = ['./update_chroot']
        if self._is_after('6480.0.0'):
          if not self.properties.disable_toolchain_boards:
            cmd.extend(['--toolchain_boards', ','.join(self._boards)])
        self.sdk_call('update SDK', cmd=cmd)
      yield
    finally:
      if self.properties.chroot_outside:
        self.m.cros_sdk.unlink_chroot(self.m.src_state.workspace_path)
      self.sdk_call('delete SDK', sdk_args=['--delete'])

  def _set_firmware_version(self):
    """Determine the firmware version."""
    with self.m.step.nest('determine ec firmware_version'):
      result = self.sdk_call(
          'call getversion.sh', cmd=['../platform/ec/util/getversion.sh'],
          infra_step=False, stdout=self.m.raw_io.output(add_output_log=True),
          step_test_data=lambda: self.m.raw_io.test_api.stream_output(
              _GETVERSION_TEST_DATA))

      versions = {}
      # For completeness grab all of the defines.
      for line in result.stdout.decode('utf-8').splitlines():
        match = re.match(r'#define\s+(?P<key>[\w]+)\s+"(?P<value>[^"]+)"', line)
        if match:
          versions[match.groupdict()['key']] = match.groupdict()['value']
      self.m.easy.set_properties_step(
          bcs_version=str(self._bcs_version), firmware_version=versions)
      self._firmware_version = versions['VERSION'][1:]

  def _setup_board_and_install_packages(self, build_target):
    # Firmware branches before 14909 are raising a permission error when
    # writing to /tmp within the chroot, so we'll force the write permission.
    # Also, we don't have a good way to test when a path does not exist. See:
    # http://cs/f:infra%2Frecipes%20path%5C.exists.*pragma
    # NB: this path construction is a hack and should be removed.
    chroot_tmp_path = self.m.src_state.workspace_path / 'chroot/tmp'
    if self.m.path.exists(chroot_tmp_path):  # pragma: nocover
      chmod_cmd = [
          'sudo', '-n', 'chmod', '-R', 'u=rwx,g=rwx,o=rwx,-t', chroot_tmp_path
      ]
      self.m.step('changing permissions of %s' % chroot_tmp_path, chmod_cmd,
                  infra_step=True)
    board = build_target.name
    with self.m.step.nest('build {}'.format(board)):
      board_arg = '--board={}'.format(board)
      if self._old_setup_board:
        cmd = [
            './setup_board', board_arg, '--accept_licenses=@CHROMEOS',
            '--skip_chroot_upgrade'
        ]
      else:
        cmd = [
            'setup_board', board_arg, '--accept-licenses=@CHROMEOS',
            '--skip-chroot-upgrade'
        ]
      self.sdk_call('setup board', cmd=cmd)

      if self._is_after('14950.0.0'):
        cmd = [
            'build_packages', board_arg, '--accept-licenses=@CHROMEOS',
            '--skip-chroot-upgrade'
        ]
      else:
        cmd = [
            './build_packages', board_arg, '--accept_licenses=@CHROMEOS',
            '--skip_chroot_upgrade'
        ]
      if self._config.build.install_packages.compile_source:
        if self._is_after('14950.0.0'):
          cmd.append('--no-usepkg')
        else:
          cmd.append('--nousepkg')
      # --withdebugsymbols was added to build_packages in 6302.0.0
      if self._is_after('6302.0.0'):
        cmd.append('--withdebugsymbols')

      cmd.extend([
          '{}/{}'.format(x.category, x.package_name)
          for x in self.properties.packages
      ])
      self.sdk_call('install packages', cmd=cmd, infra_step=False)

  def _build_firmware_archive(self, sysroot, out_path):
    with self.m.step.nest('create firmware archive'):
      # This code replicates chromite/service/artifacts.BuildFirmwareArchive.
      self.m.file.ensure_directory('create tempdir', out_path)

      # After _BUILD_VERSION_BUILD_DIR_MOVED, chroot/build was migrated to
      # out/build.
      if self.m.cros_version.version.build >= _BUILD_VERSION_BUILD_DIR_MOVED:
        # TODO(b/316429012): Update cros_sdk to expose out path as a Path,
        # rather than only as a string.
        dest_path = self.m.cros_sdk._out_path  # pylint: disable=protected-access
        chroot_path = lambda x: x
      # We use a different chroot path for versions above
      # _BUILD_VERSION_TMP_DIR_MOVED, see the sdk_call function.
      elif self.m.cros_version.version.build >= _BUILD_VERSION_TMP_DIR_MOVED:
        dest_path = self.m.path.abs_to_path(self.m.cros_sdk.chroot.path)
        chroot_path = lambda x: '/' + self.m.path.relpath(x, dest_path)
      else:
        dest_path = self._chroot
        chroot_path = lambda x: '/' + self.m.path.relpath(x, dest_path)
      root = dest_path.joinpath(sysroot.path.strip('/'), 'firmware')
      config_dir = dest_path.joinpath(
          sysroot.path.strip('/'), 'usr/share/chromeos-config/yaml')

      private_dirs = self.m.file.glob_paths(
          'glob private', root, '**/ec-private/fingerprint',
          test_data=['foo/ec-private/fingerprint'])

      files = self.m.file.listdir(
          'list files', root, recursive=True,
          test_data=['foo/ec-private/fingerprint/bar', 'bar/file'])
      source_list = [
          x for x in files
          if all(not str(x).startswith(str(p)) for p in private_dirs)
      ]
      if not source_list:
        raise NoFilesToUploadFailure('No firmware files to bundle')

      tarball = out_path / _FIRMWARE_TARBALL_NAME
      chroot_tarball = chroot_path(tarball)
      # After /tmp's been migrated but before /build's been migrated we're
      # still executing in the chroot. The outpath given to us in this function
      # is for the /out dir outside the chroot. But inside the chroot,
      # /out/tmp is mounted to /tmp so we want to trim away the `/../out`
      # prefix (/.. because chroot/ is in the same dir as out/).
      if (self.m.cros_version.version.build >= _BUILD_VERSION_TMP_DIR_MOVED and
          self.m.cros_version.version.build < _BUILD_VERSION_BUILD_DIR_MOVED):
        chroot_tarball = chroot_tarball.removeprefix('/../out')
      cmd = [
          'tar',
          'cvjf',
          chroot_tarball,
      ]
      if self.m.path.exists(config_dir):
        cmd.extend([
            '-C',
            chroot_path(config_dir),
            'config.yaml',
        ])
      cmd.extend([
          '-C',
          chroot_path(root),
          '--null',
          '-T',
          '/dev/stdin',
      ])
      # The list of files is generally too long for the command line.
      file_list = '\0'.join(self.m.path.relpath(x, root) for x in source_list)

      # After _BUILD_VERSION_BUILD_DIR_MOVED, chroot/build and chroot/tmp have
      # both been migrated to out/build and out/tmp respectively. So we
      # can run outside of the chroot.
      if self.m.cros_version.version.build >= _BUILD_VERSION_BUILD_DIR_MOVED:
        self.m.step('create tarball', cmd=cmd,
                    stdin=self.m.raw_io.input(data=file_list))
      # Otherwise we need to run inside the chroot. sdk_call has additional
      # branching to cover when /tmp had been migrated but /build had not.
      else:
        self.sdk_call('create tarball', cmd=cmd,
                      stdin=self.m.raw_io.input(data=file_list))
      return tarball

  def _bundle_firmware(self, _chroot, sysroot, _artifacts_info, outpath,
                       _test_data):
    """Returns a dictionary of files by artifact_type."""
    # This is called from beneath cros_artifacts.upload_artifacts as a private
    # bundler.

    # We always provide FIRMWARE_TARBALL and FIRMWARE_TARBALL_INFO.
    ret = defaultdict(list)
    # We need a directory inside of the chroot.  Use mkdtemp() to get a name, so
    # that test expectations are constant.
    metadata = FirmwareArtifactInfo()
    metadata.bcs_version_info.version_string = str(self._bcs_version)
    target = sysroot.build_target.name

    # After _BUILD_VERSION_BUILD_DIR_MOVED, everything here is done outside of
    # the chroot.
    if self.m.cros_version.version.build >= _BUILD_VERSION_BUILD_DIR_MOVED:
      tmppath = outpath
      tmpdir = outpath
    # After _BUILD_VERSION_TMP_DIR_MOVED, we still created the artifact inside
    # the chroot because  chroot/build hasn't yet been migrated to out/build
    # (though chroot/tmp has been migrated to out/tmp).
    elif self.m.cros_version.version.build >= _BUILD_VERSION_TMP_DIR_MOVED:
      tmppath = self.m.path.mkdtemp(prefix='firmware-bundle')
      tmpdir = self.m.cros_sdk._out_path.joinpath(  # pylint: disable=protected-access
          'tmp', self.m.path.basename(tmppath))
    else:
      tmppath = self.m.path.mkdtemp(prefix='firmware-bundle')
      tmpdir = self._chroot.joinpath('tmp', self.m.path.basename(tmppath))

    tarball = self._build_firmware_archive(sysroot, tmpdir)
    if tarball:
      dest_name = '{}/{}'.format(target, _FIRMWARE_TARBALL_NAME)
      self.m.file.ensure_directory('create {}'.format(target), outpath / target)
      self.m.file.copy('bundle tarball', tarball, outpath / dest_name)
      ret['FIRMWARE_TARBALL'].append(dest_name)

      info = metadata.objects.add()
      info.file_name = dest_name
      tb_info = info.tarball_info
      tb_info.type = metadata.TarballInfo.FirmwareType.EC
      tb_info.firmware_image_name = target
      tb_info.firmware_version_info.version_string = self._firmware_version

    if metadata.objects:
      metadata_name = '{}/{}'.format(target, _FIRMWARE_METADATA_NAME)
      self.m.file.write_proto('write firmware metadata',
                              outpath / metadata_name, metadata, 'JSONPB')
      ret['FIRMWARE_TARBALL_INFO'].append(metadata_name)
    return ret

  def _push_image(self, build_target):
    """Push images."""
    # TODO(b/181786185): As cros_artifacts.push_image evolves, this code should
    # be updated to use that where the Build API exists.
    #
    # For now, call `pushimage` directly:
    # - Rubik will be completely restructuring that workflow (moving the
    #   uploads and such to the recipes side of the API boundary)
    # - most firmware branches lack the Build API.
    with self.m.step.nest('push image'):
      self._ensure_chromite_main()
      board = build_target.name
      staging = self._is_staging
      # Defaults have changed over time. Other types are only signed based on
      # builder config.
      default_types = [common_pb2.IMAGE_TYPE_FIRMWARE]
      if self._is_after('7618.0.0'):
        default_types.append(common_pb2.IMAGE_TYPE_ACCESSORY_RWSIG)
      sign_types = self.properties.sign_types or default_types

      dest = ('gs://chromeos-throw-away-bucket'
              if staging else 'gs://chromeos-releases')
      profile = lambda x: ['--profile={}'.format(x)] if x else []
      has_dest_bucket = self._is_after('13682.0.0')
      dry_run = self.m.cv.active or not self.properties.bump_version
      dry_run = dry_run or (staging and not has_dest_bucket)

      image_dir = 'gs://{}/{}/{}'.format(
          self._config.artifacts.artifacts_gs_bucket,
          self.m.cros_artifacts.artifacts_gs_path(self._config.id.name,
                                                  build_target,
                                                  self._config.id.type), board)
      cmd = [
          self._tot_chromite / 'bin' / 'pushimage', image_dir, '--yes',
          '--board={}'.format(board),
          '--version={}'.format(self._bcs_version.legacy_version),
          '--buildroot', self.m.src_state.workspace_path
      ]
      if dry_run:
        cmd.append('-n')
      cmd.extend(profile(self._config.build.portage_profile.profile))
      if sign_types:
        cmd.append('--sign-types')
        cmd.extend(
            common_pb2.ImageType.Name(x).lower().replace('image_type_', '')
            for x in sign_types)
      if has_dest_bucket:
        cmd.append('--dest-bucket={}'.format(dest))

      self.m.step('call pushimage', cmd=cmd, infra_step=True)

  @contextmanager
  def _maybe_step(self, name, cond):
    if cond:
      with self.m.step.nest(name):
        yield
    else:
      yield

  def run(self):
    with self.m.failures.ignore_exceptions():
      with self.m.step.nest('checking attestation eligibility') as pres:
        # Config determines whether to report artifacts.
        if self.m.cros_infra_config.config.artifacts.attestation_eligible:
          self.m.bcid_reporter.report_stage('start')
          pres.step_text = f'{self.m.cros_infra_config.config.id.name} is attestation eligible'
        else:
          pres.step_text = f'{self.m.cros_infra_config.config.id.name} NOT attestation eligible'

    all_uploaded = []
    step_failures = []

    with self.m.failures.ignore_exceptions():
      if self.m.cros_infra_config.config.artifacts.attestation_eligible:
        self.m.bcid_reporter.report_stage('compile')

    with self._setup():
      for bt in self.properties.build_targets:
        with self._maybe_step(bt.name, len(self.properties.build_targets) > 1):
          self._setup_board_and_install_packages(bt)
          try:
            bt_uploaded, _ = self.m.build_menu.upload_artifacts(
                private_bundle_func=self._bundle_firmware,
                sysroot=Sysroot(path='/build/{}'.format(bt.name),
                                build_target=bt), report_to_spike=self.m
                .cros_infra_config.config.artifacts.attestation_eligible)
          except NoFilesToUploadFailure as e:
            # If one build target fails, continue with the other build targets
            # and fail at the end.
            step_failures.append(e)
            continue
          all_uploaded.append(bt_uploaded)
          self._push_image(bt)

    with self.m.failures.ignore_exceptions():
      if self.m.cros_infra_config.config.artifacts.attestation_eligible:
        self.m.bcid_reporter.report_stage('upload-complete')

      # Mark whether the suite_scheduling query for firmware should find this.
      self.m.easy.set_properties_step(
          suite_scheduling=str(self._suite_scheduling))
      # Update the artifacts property for the build, to reflect our multi-target
      # nature.
      if len(self.properties.build_targets) > 1:
        self.m.cros_artifacts.merge_artifacts_properties(all_uploaded)

    return result_pb2.RawResult(
        status=common.FAILURE if step_failures else common.SUCCESS,
        summary_markdown=self.m.failures.format_step_failures(
            step_failures=step_failures))


def RunSteps(api, properties):
  return FirmwareBuilder(api, properties).run()


def GenTests(api):

  def test(name, *args, **kwargs):
    status = kwargs.pop('status', 'SUCCESS')
    version_str = kwargs.pop('version', 'R109-15236.0.0')
    version = api.cros_version.workspace_version(version_str)
    cq = kwargs.get('cq', False)
    kwargs.setdefault('builder',
                      'fw-atlas-{}'.format('cq' if cq else 'postsubmit'))
    kwargs.setdefault('revision', None)
    input_props = {
        'firmware_location': 1,
        'manifest_branch': 'firmware-board-9999.B'
    }
    input_props.update(**kwargs.get('input_properties', {}))
    targets = kwargs.pop('build_targets', None)
    if targets:
      input_props['build_targets'] = targets
    kwargs['input_properties'] = input_props
    build = api.test_util.test_child_build('target', **kwargs).build
    return api.test(name, build, version, *args, status=status)

  exists = lambda *x: api.path.exists(api.src_state.workspace_path.joinpath(*x))

  def StepCommandLacks(check, steps, name, arg):
    return check(arg not in steps[name].cmd)

  def suite_scheduling(value):
    return api.post_check(post_process.PropertyEquals, 'suite_scheduling',
                          str(value))

  yield test(
      'release',
      api.cros_infra_config.use_custom_builder_config(
          BuilderConfig(
              id=BuilderConfig.Id(name='firmware-ti50-postsubmit',
                                  bucket='firmware'),
              artifacts=BuilderConfig.Artifacts(
                  attestation_eligible=True,
                  artifacts_gs_bucket='chromeos-image-archive',
                  artifacts_info=common_pb2.ArtifactsByService(
                      firmware=common_pb2.ArtifactsByService
                      .Firmware(output_artifacts=[
                          common_pb2.ArtifactsByService.Firmware.ArtifactInfo(
                              artifact_types=[
                                  'FIRMWARE_TARBALL', 'FIRMWARE_TARBALL_INFO'
                              ], gs_locations=[
                                  'chromeos-image-archive/{builder_name}-firmware/{legacy_version}/{target}'
                              ])
                      ])))), step_name='checking attestation eligibility'),
      api.post_check(post_process.MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(post_process.MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(post_process.StepTextEquals, 'bump version', ''),
      api.post_check(post_process.MustRun, 'create buildspec'),
      api.post_check(post_process.MustRun, 'snoop: report_stage'),
      suite_scheduling(True),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['build_packages']),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['--withdebugsymbols']),
      api.post_check(post_process.StepCommandContains,
                     'push image.call pushimage',
                     ['--dest-bucket=gs://chromeos-releases']),
      api.post_check(post_process.StepCommandDoesNotContain,
                     'upload artifacts.create firmware archive.create tarball',
                     [
                         '-C',
                         '/build/target/usr/share/chromeos-config/yaml',
                         'config.yaml',
                     ]),
      input_properties={
          'bump_version': True,
          'set_suite_scheduling': True,
          'buildspec_gs_path': 'gs://chromeos-manifest-versions/buildspecs/',
      })

  yield test(
      'release-unibuild',
      exists('chroot', 'build', 'target', 'usr', 'share', 'chromeos-config',
             'yaml', 'config.yaml'),
      api.cros_infra_config.use_custom_builder_config(
          BuilderConfig(
              id=BuilderConfig.Id(name='firmware-ti50-postsubmit',
                                  bucket='firmware'),
              artifacts=BuilderConfig.Artifacts(
                  attestation_eligible=True,
                  artifacts_gs_bucket='chromeos-image-archive',
                  artifacts_info=common_pb2.ArtifactsByService(
                      firmware=common_pb2.ArtifactsByService
                      .Firmware(output_artifacts=[
                          common_pb2.ArtifactsByService.Firmware.ArtifactInfo(
                              artifact_types=[
                                  'FIRMWARE_TARBALL', 'FIRMWARE_TARBALL_INFO'
                              ], gs_locations=[
                                  'chromeos-image-archive/{builder_name}-firmware/{legacy_version}/{target}'
                              ])
                      ])))), step_name='checking attestation eligibility'),
      api.post_check(post_process.MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(post_process.MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(post_process.StepTextEquals, 'bump version', ''),
      api.post_check(post_process.MustRun, 'create buildspec'),
      api.post_check(post_process.MustRun, 'snoop: report_stage'),
      suite_scheduling(True),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['build_packages']),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['--withdebugsymbols']),
      api.post_check(post_process.StepCommandContains,
                     'push image.call pushimage',
                     ['--dest-bucket=gs://chromeos-releases']),
      api.post_check(post_process.StepCommandContains,
                     'upload artifacts.create firmware archive.create tarball',
                     [
                         '-C',
                         '/build/target/usr/share/chromeos-config/yaml',
                         'config.yaml',
                     ]),
      input_properties={
          'bump_version': True,
          'set_suite_scheduling': True,
          'buildspec_gs_path': 'gs://chromeos-manifest-versions/buildspecs/',
      })

  yield test(
      'staging-release',
      api.post_check(post_process.MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(post_process.MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(post_process.StepTextEquals, 'bump version',
                     'dry-run only'),
      api.post_check(post_process.MustRun, 'create buildspec'),
      suite_scheduling(False),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['build_packages']),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['--withdebugsymbols']),
      api.post_check(StepCommandLacks, 'push image.call pushimage', ['-n']),
      api.post_check(post_process.StepCommandContains,
                     'push image.call pushimage',
                     ['--dest-bucket=gs://chromeos-throw-away-bucket']),
      bucket='staging', input_properties={
          'bump_version': True,
          'set_suite_scheduling': True,
          'buildspec_gs_path': 'gs://chromeos-manifest-versions/staging/',
      })

  yield test(
      'old-staging-release',
      api.post_check(post_process.MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(post_process.MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(post_process.MustRun, 'bump version'),
      api.post_check(post_process.MustRun, 'create buildspec'),
      suite_scheduling(False),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['./build_packages']),
      api.post_check(StepCommandLacks, 'build target.install packages',
                     ['--withdebugsymbols']),
      api.post_check(post_process.StepCommandContains,
                     'push image.call pushimage', ['-n']),
      api.post_check(StepCommandLacks, 'push image.call pushimage',
                     ['--dest-bucket=gs://chromeos-throw-away-bucket']),
      bucket='staging', version='R39-6301.202.44', input_properties={
          'bump_version': True,
          'set_suite_scheduling': True,
      })

  yield test(
      'postsubmit',
      api.post_check(post_process.MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(post_process.MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(post_process.DoesNotRun, 'bump version'),
      api.post_check(post_process.DoesNotRun, 'create buildspec'),
      api.post_check(post_process.DoesNotRun, 'snoop: report_stage'),
      suite_scheduling(False),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['build_packages']),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['--withdebugsymbols']),
  )

  yield test(
      'postsubmit-outside',
      api.properties(chroot_outside=True),
      api.post_check(post_process.MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(post_process.MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(post_process.DoesNotRun, 'bump version'),
      api.post_check(post_process.DoesNotRun, 'create buildspec'),
      suite_scheduling(False),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['build_packages']),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['--withdebugsymbols']),
  )

  yield test(
      'old-postsubmit',
      api.post_check(post_process.MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(post_process.MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(post_process.DoesNotRun, 'bump version'),
      api.post_check(post_process.DoesNotRun, 'create buildspec'),
      api.post_check(post_process.StepCommandContains,
                     'build target.install packages', ['./build_packages']),
      api.post_check(StepCommandLacks, 'build target.install packages',
                     '--withdebugsymbols'),
      api.repo.project_infos_step_data(
          'uprev packages', data=[{
              'project': 'chromiumos/chromite',
              'upstream': 'refs/heads/firmware-target-6301.202.B'
          }]), suite_scheduling(False), version='R39-6301.202.44')

  yield test(
      'cq',
      api.post_check(post_process.MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(post_process.MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(post_process.DoesNotRun, 'bump version'),
      api.post_check(post_process.DoesNotRun, 'create buildspec'),
      api.post_check(post_process.DoesNotRun, 'snoop: report_stage'),
      suite_scheduling(False), cq=True)

  yield test(
      'cq-bump',
      api.post_check(post_process.MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(post_process.MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(post_process.MustRun, 'bump version'),
      api.post_check(post_process.DoesNotRun, 'create buildspec'),
      suite_scheduling(False), cq=True, input_properties={
          'bump_version': True,
          'set_suite_scheduling': True
      })

  yield test(
      'two-targets',
      api.post_check(post_process.MustRun, 'board1.build board1.setup board'),
      api.post_check(post_process.MustRun, 'board2.build board2.setup board'),
      api.post_check(post_process.DoesNotRun, 'bump version'),
      suite_scheduling(False), build_targets=[{
          'name': 'board1'
      }, {
          'name': 'board2'
      }])

  yield test(
      'no-firmware',
      api.step_data('upload artifacts.create firmware archive.list files',
                    api.file.listdir()),
      suite_scheduling(False),
      api.post_check(post_process.DoesNotRun,
                     'upload artifacts.bundle tarball'),
      api.post_check(post_process.DoesNotRun, 'upload artifacts.gsutil rsync'),
      api.post_check(post_process.DoesNotRun, 'push image'),
      api.post_check(post_process.DoesNotRun, 'bump version'),
      status='FAILURE',
  )

  yield test(
      'some-boards-firmware',
      api.step_data(
          'board1.upload artifacts.create firmware archive.list files',
          api.file.listdir()),
      suite_scheduling(False),
      api.post_check(post_process.StepException, 'board1.upload artifacts'),
      api.post_check(post_process.DoesNotRun,
                     'board1.upload artifacts.bundle tarball'),
      api.post_check(post_process.DoesNotRun, 'board1.push image'),
      api.post_check(post_process.StepSuccess, 'board2.upload artifacts'),
      api.post_check(post_process.MustRun, 'board2.push image'),
      build_targets=[{
          'name': 'board1'
      }, {
          'name': 'board2'
      }],
      status='FAILURE',
  )

  yield test(
      'new-chroot-firmware',
      api.properties(chroot_outside=True),
      suite_scheduling(False),
      api.post_check(post_process.StepSuccess,
                     'upload artifacts.create firmware archive'),
      api.post_check(post_process.StepSuccess,
                     'upload artifacts.bundle tarball'),
      api.post_check(post_process.MustRun, 'push image'),
      version='R122-15709.22.0',
  )

  yield test(
      'new-chroot-tmp-dir-firmware',
      api.properties(chroot_outside=True),
      suite_scheduling(False),
      api.post_check(post_process.StepSuccess,
                     'upload artifacts.create firmware archive'),
      api.post_check(post_process.StepSuccess,
                     'upload artifacts.bundle tarball'),
      api.post_check(post_process.MustRun, 'push image'),
      version='R115-15460.22.0',
  )

  yield test('chroot-exists', exists('chroot'))

  yield test('old-cq', exists('src', 'scripts', 'setup_board'), cq=True)
