// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.build_sdk;

import "recipes/chromeos/generator.proto";

message BuildSDKProperties {
  // Defunct: used to be whether to build the SDK with the llvm-next flag.
  reserved 1;

  // Override the default version, which is used for GS:// filepaths.
  // Default: Build start timestamp, formatted as "%Y.%m.%d.%H%M%S"
  string version = 2;

  reserved 3;

  // Whether this build should launch a PUpr build to uprev the SDK version file
  // and amd64-host prebuilt file.
  // If False, then the generated artifacts will not affect production at all.
  bool launch_pupr = 4;

  // Which branch this build should checkout and build an SDK for.
  // This also affects which branch the launched PUpr build will uprev on.
  // Default: Check out the latest snapshot, and build an SDK for main.
  string manifest_branch = 5;

  // If given, override the PUpr builder's BranchPolicies with just this one.
  // This enables us, for example, to launch a PUpr job on `main` with a
  // different SendToCqPolicy or with additional reviewers.
  generator.BranchPolicy pupr_branch_policy = 6;
}
