# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Build optee firmware prebuilts. See http://shortn/_QerMUrnjYs."""

import re

from PB.chromiumos import common as common_pb2
from PB.go.chromium.org.luci.buildbucket.proto import common as bb_common_pb2
from PB.recipes.chromeos.build_op_tee_image import BuildOpTeeImageProperties
from PB.recipes.chromeos.build_op_tee_image import PublishStrategy
from PB.recipe_engine import result as result_pb2

from recipe_engine import post_process
from recipe_engine.config_types import Path
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/cv',
    'recipe_engine/file',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'build_menu',
    'cros_build_api',
    'cros_infra_config',
    'cros_release',
    'cros_sdk',
    'cros_source',
    'gerrit',
    'git',
    'mutable_output',
    'signing',
    'signing_utils',
    'src_state',
]

PROPERTIES = BuildOpTeeImageProperties
CL_REVIEWERS = ['hiroh@google.com', 'rrangel@google.com', 'nhebert@google.com']

AG_HOST = 'googleplex-android'
DESKTOP_HOST = 'arsp'


def create_or_update_symlink(api: RecipeApi, directory: Path, file: str,
                             symlink: str):
  with api.context(cwd=directory):
    if api.path.exists(directory / symlink):
      api.file.remove('remove existing symlink', directory / symlink)
    api.step('create symlink', ['ln', '-s', file, symlink])


def upload_optee_prebuilts(api: RecipeTestApi, optee_path: Path, target: str,
                           version: str, abandon: bool = True,
                           host: str = AG_HOST) -> str:
  """Uploads the optee firmware prebuilts to the android repo.

  Returns:
    The message to include in the summary markdown of the build."""
  checkout = api.path.mkdtemp()
  with api.context(cwd=checkout):
    api.git.clone(
        f'https://{host}.googlesource.com/device/google/desktop/{target}-prebuilts',
        depth=1)

    # Copy the prebuilt into the optee prebuild repo.
    api.file.ensure_directory(
        'make sure directory',
        api.path.join(checkout, 'vendor-firmware', 'optee'))
    api.file.copy(
        'copy optee firmware prebuilt to repo', optee_path,
        api.path.join(checkout, 'vendor-firmware', 'optee',
                      f'tee_{version}.bin'))
    create_or_update_symlink(api, checkout / 'vendor-firmware/optee',
                             f'tee_{version}.bin', 'tee_LATEST.bin')

    # Check to make sure there was actually a change.
    diff_lines = api.git.get_working_dir_diff_files()
    if not diff_lines:
      return 'No optee firmware prebuilts changed.'
    # Skip upload in CQ.
    if api.cv.active:
      api.step.empty('Skipping CL upload in CQ')
      return ''
    # Create a cl updating the file.
    api.git.add_all()
    bbid = api.buildbucket.build_url()
    commit_lines = [
        f'optee: Update prebuilts to version {version}',
        '',
        f'Generated by {bbid}.',
        '',
        f'Flag: build.RELEASE_{target.upper()}_OPTEE_FIRMWARE_BUILD_VERSION',
    ]
    api.git.commit('\n'.join(commit_lines))
    change = api.gerrit.create_change(
        f'/device/google/desktop/{target}-prebuilts',
        ref=api.git.get_branch_ref('main'), project_path=checkout,
        reviewers=CL_REVIEWERS if not api.cros_infra_config.is_staging else [],
        non_repo_checkout=True)
    if abandon:
      api.gerrit.abandon_change(change)
    return f'Updated optee firmware prebuilts for {target}'


def RunSteps(api: RecipeApi, properties: BuildOpTeeImageProperties):
  with api.mutable_output.wrap():
    with api.cros_source.checkout_overlays_context():
      config = api.cros_source.configure_builder(api.buildbucket.gitiles_commit)
      with api.build_menu.setup_workspace_and_chroot():
        api.cros_source.ensure_synced_cache()

        api.build_menu.setup_sysroot_and_determine_relevance()
        api.build_menu.bootstrap_sysroot(config)
        api.build_menu.install_packages(config, [
            common_pb2.PackageInfo(category='sys-firmware',
                                   package_name='optee_os_android')
        ])

        optee_dir = api.path.mkdtemp(prefix='op-tee')
        optee_local_path = api.path.join(optee_dir, 'tee.bin')

        # copy the file in.
        response_path = '%s/build/%s/lib/firmware/optee/tee.bin' % (
            api.build_menu.chroot.out_path, api.build_menu.build_target.name)
        api.file.copy('copy prebuilt optee firmware into temp dir',
                      response_path, optee_local_path)

        # Get prebuilt version for target.
        new_optee_version = api.signing.get_prebuilt_version(
            latest_filename='LATEST-OPTEEFIRMWARE')

        # Advance LATEST-OPTEE_IMAGE.
        api.signing.upload_prebuilt_latest_file(
            new_optee_version, latest_filename='LATEST-OPTEEFIRMWARE')

        # Open a cl with the new optee firmware prebuilts.
        if properties.publish_strategy in (PublishStrategy.UNSPECIFIED,
                                           PublishStrategy.AG_ONLY,
                                           PublishStrategy.AG_AND_DESKTOP):
          ag_msg = upload_optee_prebuilts(
              api, optee_local_path, api.build_menu.build_target.name,
              new_optee_version, abandon=api.cros_infra_config.is_staging,
              host=AG_HOST)
        else:
          ag_msg = 'Not published to AG host'
        if properties.publish_strategy in (PublishStrategy.DESKTOP_ONLY,
                                           PublishStrategy.AG_AND_DESKTOP):
          desktop_msg = upload_optee_prebuilts(
              api, optee_local_path, api.build_menu.build_target.name,
              new_optee_version, abandon=api.cros_infra_config.is_staging,
              host=DESKTOP_HOST)
        else:
          desktop_msg = 'Not published to desktop host'
        return result_pb2.RawResult(
            summary_markdown=f'AG: {ag_msg}\nDesktop:{desktop_msg}',
            status=bb_common_pb2.SUCCESS,
        )


def GenTests(api: RecipeTestApi):
  yield api.build_menu.test(
      'success-unspecified-host',
      api.post_process(post_process.StepCommandContains, 'git clone', [
          f'https://{AG_HOST}.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_process(post_process.DoesNotRun, 'git clone (2)'),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-OPTEEFIRMWARE version',
          stdout=api.raw_io.output('1.0')),
      api.post_check(post_process.MustRun,
                     'copy prebuilt optee firmware into temp dir'),
      api.post_check(post_process.MustRun, 'write latest file for version 2.0'),
      api.post_check(post_process.MustRun,
                     'gsutil upload LATEST-OPTEEFIRMWARE'),
      api.post_check(
          post_process.StepCommandContains, 'write commit message',
          [re.compile(r'optee: Update prebuilts to version 2\.0.*')]),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='optee-android-kukui-main',
  )

  yield api.build_menu.test(
      'success-ag-only',
      api.properties(**{
          'publish_strategy': PublishStrategy.AG_ONLY,
      }),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          f'https://{AG_HOST}.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_process(post_process.DoesNotRun, 'git clone (2)'),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-OPTEEFIRMWARE version',
          stdout=api.raw_io.output('1.0')),
      api.post_check(post_process.MustRun,
                     'copy prebuilt optee firmware into temp dir'),
      api.post_check(post_process.MustRun, 'write latest file for version 2.0'),
      api.post_check(post_process.MustRun,
                     'gsutil upload LATEST-OPTEEFIRMWARE'),
      api.post_check(
          post_process.StepCommandContains, 'write commit message',
          [re.compile(r'optee: Update prebuilts to version 2\.0.*')]),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_check(post_process.DoesNotRun, 'git commit (2)'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='optee-android-kukui-main',
  )

  yield api.build_menu.test(
      'success-desktop-only',
      api.properties(**{
          'publish_strategy': PublishStrategy.DESKTOP_ONLY,
      }),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          f'https://{DESKTOP_HOST}.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_process(post_process.DoesNotRun, 'git clone (2)'),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-OPTEEFIRMWARE version',
          stdout=api.raw_io.output('1.0')),
      api.post_check(post_process.MustRun,
                     'copy prebuilt optee firmware into temp dir'),
      api.post_check(post_process.MustRun, 'write latest file for version 2.0'),
      api.post_check(post_process.MustRun,
                     'gsutil upload LATEST-OPTEEFIRMWARE'),
      api.post_check(
          post_process.StepCommandContains, 'write commit message',
          [re.compile(r'optee: Update prebuilts to version 2\.0.*')]),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_check(post_process.DoesNotRun, 'git commit (2)'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='optee-android-kukui-main',
  )

  yield api.build_menu.test(
      'success-ag-and-desktop',
      api.properties(**{
          'publish_strategy': PublishStrategy.AG_AND_DESKTOP,
      }),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          f'https://{AG_HOST}.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_process(post_process.StepCommandContains, 'git clone (2)', [
          f'https://{DESKTOP_HOST}.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-OPTEEFIRMWARE version',
          stdout=api.raw_io.output('1.0')),
      api.post_check(post_process.MustRun,
                     'copy prebuilt optee firmware into temp dir'),
      api.post_check(post_process.MustRun, 'write latest file for version 2.0'),
      api.post_check(post_process.MustRun,
                     'gsutil upload LATEST-OPTEEFIRMWARE'),
      api.post_check(
          post_process.StepCommandContains, 'write commit message',
          [re.compile(r'optee: Update prebuilts to version 2\.0.*')]),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_check(post_process.MustRun, 'git commit (2)'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 2'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='optee-android-kukui-main',
  )

  yield api.build_menu.test(
      'symlink-exists',
      api.path.exists(api.path.cleanup_dir /
                      'tmp_tmp_5/vendor-firmware/optee/tee_LATEST.bin'),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-OPTEEFIRMWARE version',
          stdout=api.raw_io.output('2.0')),
      api.post_check(post_process.MustRun,
                     'copy prebuilt optee firmware into temp dir'),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_check(post_process.MustRun, 'remove existing symlink'),
      api.post_check(post_process.StepCommandContains, 'create symlink',
                     ["ln", "-s", "tee_3.0.bin", "tee_LATEST.bin"]),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='optee-android-kukui-main',
  )

  yield api.build_menu.test(
      'no-diff',
      api.step_data('git status', stdout=api.raw_io.output('')),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-OPTEEFIRMWARE version',
          stdout=api.raw_io.output('3.0')),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_check(post_process.MustRun,
                     'copy prebuilt optee firmware into temp dir'),
      api.post_check(
          post_process.SummaryMarkdown,
          'AG: No optee firmware prebuilts changed.\nDesktop:Not published to desktop host'
      ),
      api.post_check(post_process.DoesNotRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='optee-android-kukui-main',
  )

  yield api.build_menu.test(
      'staging',
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-OPTEEFIRMWARE version',
          stdout=api.raw_io.output('333.0')),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_check(post_process.MustRun,
                     'copy prebuilt optee firmware into temp dir'),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.MustRun, 'abandon CL 1'),
      # Omit reviewers in staging.
      api.post_check(
          post_process.StepCommandDoesNotContain,
          'create gerrit change for /device/google/desktop/kukui-prebuilts.git_cl upload',
          '--reviewers'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      bucket='staging',
      builder='optee-android-kukui-main',
  )

  test_gerrit_changes = [
      bb_common_pb2.GerritChange(host='chromium-review.googlesource.com',
                                 change=1234, project='chromiumos/chromite',
                                 patchset=1),
  ]
  yield api.build_menu.test(
      'cq',
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-OPTEEFIRMWARE version',
          stdout=api.raw_io.output('3.0')),
      api.post_check(
          post_process.StepCommandContains,
          'cherry-pick gerrit changes.apply gerrit patch sets.git fetch', [
              "git", "fetch",
              "https://chromium.googlesource.com/chromiumos/chromite",
              "refs/changes/34/1234/1:"
          ]),
      # Skip CL upload.
      api.post_check(post_process.DoesNotRun, 'git commit'),
      api.post_check(post_process.MustRun, 'Skipping CL upload in CQ'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      bucket='staging',
      builder='optee-android-kukui-main',
      cq=True,
      gerrit_changes=test_gerrit_changes,
  )

  yield api.build_menu.test(
      'new-latest-version',
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-OPTEEFIRMWARE version',
          retcode=1),
      api.post_check(post_process.MustRun, 'write latest file for version 1.0'),
      api.post_check(post_process.MustRun,
                     'gsutil upload LATEST-OPTEEFIRMWARE'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='optee-android-kukui-main',
  )
