// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.build_sdk;

message BuildSDKProperties {
  // Whether to build the SDK with the llvm-next USE flag
  bool use_llvm_next = 1;

  // Override the default version, which is used for GS:// filepaths.
  // Default: Build start timestamp, formatted as "%Y.%m.%d.%H%M%S"
  string version = 2;

  // If true, then the builder will upload to URIs with `staging/` prepended
  // (after the GS:// bucket). For example, a file that would normally be
  // uploaded to gs://chromiumos-sdk/cros-sdk-latest.conf will instead be
  // uploaded to gs://chromeos-sdk/staging/cros-sdk-latest.conf.
  // This will happen regardless of whether the builder is prod or staging.
  bool upload_to_staging_dir = 3;

  // Whether this build should launch a PUpr build to uprev the SDK version file
  // and amd64-host prebuilt file.
  // If False, then the generated artifacts will not affect production at all.
  bool launch_pupr = 4;
}
