// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.build_kabuto_shadercache;

import "chromiumos/common.proto";

message BuildKabutoShadercacheProperties {
  // Bucket and path to the payload to build shaders with.
  // Required
  string payload_gs_bucket = 1;
  string payload_gs_path = 2;

  // Commit hash to checkout Kabuto repository.
  // Deprecated, will move to reserved soon. Use gerrit_cl_ref instead.
  string kabuto_commit_ref = 3;

  // CL ref to checkout Kabuto repository.
  // Optional
  string kabuto_cl_ref = 4;

  // The manifest branch to check out (e.g. 'release-R105-14989.B')
  // Defaults to main tip of tree if not specified.
  string manifest_branch = 5;

  // The builder's shard number for paralellized builds.
  // Defaults to non-sharded version if not supplied (shard-test)
  string shard = 6;

  // Gerrit CL ref to checkout platform/borealis to.
  // Optional
  string gerrit_cl_ref = 7;

  // Milestone number we are building. Used to gate flags that only exit in
  // specific branches.
  // Optional.
  int32 milestone = 8;

  // Manual override for Kabuto config (kabuto.json)
  // Optional
  string kabuto_config_override = 9;

  // URL to Git repo containing 'tools/kabuto'.
  // Optional
  string borealis_remote_url = 10;
}
