// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.build_legacy_fw;

import "chromiumos/common.proto";

message BuildLegacyFwProperties {
  // The build target being built.  Replaced with build_targets below.
  // This will be used if build_targets is empty.
  chromiumos.BuildTarget build_target = 1 [ deprecated = true ];

  // Firmware location.  See chromite.api.firmware.
  chromiumos.FwLocation firmware_location = 2;

  // The manifest branch to check out.
  string manifest_branch = 3;

  // Packages to build.
  repeated chromiumos.PackageInfo packages = 4;

  // The build targets to build.  Replaces build_target above.
  repeated chromiumos.BuildTarget build_targets = 5;

  // Whether to bump the version.
  bool bump_version = 6;

  // Feature flag: whether to set suite_scheduling=True
  bool set_suite_scheduling = 7;

  // Mitigation flag: whether to disable --toolchain_boards to update_chroot
  bool disable_toolchain_boards = 8;

  // sign_types for push_image.
  repeated chromiumos.ImageType sign_types = 9;

  // Feature flag: chroot outside of tree
  bool chroot_outside = 11;

  // GS path to upload buildspecs to.
  // Defaults to 'gs://chromeos-manifest-versions/buildspecs/'.
  string buildspec_gs_path = 12;

  // Whether to sign firmware images.
  bool trigger_signing = 13;
}
