// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.build_release;

message DebugSymbolUploadProperties{
  // Maximum number of concurrent workers to be ran in the builder.
  int32 worker_count = 1;

  // The total number of retries allowed.
  int32 retry_quota = 2;

  // Bool stating whether or not to dry run the uploads.
  bool dryrun = 3;
}

message BuildReleaseProperties {
  DebugSymbolUploadProperties debug_symbols = 1;

  // GS bucket to upload LATEST files to, e.g. chromeos-image-archive
  string latest_files_gs_bucket = 2;

  // GS path (or template) to upload LATEST files to, e.g. {target}-release
  string latest_files_gs_path = 3;

  // Whether to skip paygen. Used by tryjobs.
  bool skip_paygen = 4;

  // QS Account to use instead of whatever is configured. Passed to paygen.
  string override_qs_account = 5;
}
