# -*- coding: utf-8 -*-
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe that builds chromeos-firmware on a firmware branch."""

DEPS = [
    'recipe_engine/context',
    'recipe_engine/cq',
    'recipe_engine/file',
    'recipe_engine/path',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'depot_tools/depot_tools',
    'build_menu',
    'cros_release',
    'cros_sdk',
    'cros_version',
    'easy',
    'git',
    'metadata_json',
    'src_state',
    'test_util',
]

from collections import defaultdict
from contextlib import contextmanager
import re

from recipe_engine.post_process import (DoesNotRun, MustRun, PropertyEquals,
                                        StatusSuccess, StepCommandContains)

from PB.recipes.chromeos.build_legacy_fw import BuildLegacyFwProperties
from PB.chromite.api.firmware import FirmwareArtifactInfo
from PB.chromiumos.builder_config import BuilderConfig

PROPERTIES = BuildLegacyFwProperties
_FIRMWARE_TARBALL_NAME = 'firmware_from_source.tar.bz2'
_FIRMWARE_METADATA_NAME = 'firmware_metadata.jsonpb'

_GETVERSION_TEST_DATA = '''/* This file is generated by util/getversion.sh */
#define CROS_EC_VERSION32 "_v0.0.3733-0612ae7"
/* Version string for ectool. */
#define CROS_ECTOOL_VERSION "v0.0.3733-0612ae7"
/* Version string for stm32mon. */
#define CROS_STM32MON_VERSION "v0.0.3733-0612ae7"
/* Sub-fields for use in Makefile.rules and to form build info string
 * in common/version.c. */
#define VERSION "_v0.0.3733-0612ae7"
#define BUILDER "ldap@machine.example.com"
/* Repo is clean, use the commit date of the last commit. */
#define DATE "2021-03-10 20:52:43"
'''


# The age of the branches is such that we do not even have a Build API for the
# most part.
class FirmwareBuilder(object):

  def __init__(self, api, properties):
    self.m = api
    # If not specified, default to building virtual/chromeos-firmware.
    if not properties.packages:
      pkg = properties.packages.add()
      pkg.category = "virtual"
      pkg.package_name = "chromeos-firmware"

    # We may have been passed properties.build_target.
    if not properties.build_targets and properties.build_target.name:
      bt = properties.build_targets.add()
      bt.CopyFrom(properties.build_target)
    assert len(properties.build_targets), 'No build_targets specified.'

    self.properties = properties
    self._boards = [x.name for x in properties.build_targets]
    self._chroot = self.m.src_state.workspace_path.join('chroot')
    self._config = None
    self._bcs_version = None
    self._firmware_version = None
    self._is_staging = True
    # Whether suite_scheduling should consider our firmware tarball.
    self._suite_scheduling = False
    self._old_setup_board = False

  def sdk_call(self, name, sdk_args=(), cmd=(), **kwargs):
    """Run cros_sdk with the given command"""
    command = [self.m.cros_sdk.cros_sdk_path] + list(sdk_args)
    # Pass in any USE flags from the builder config.
    if cmd:
      if self._config and self._config.build.use_flags:
        command.append('USE={}'.format(' '.join(
            x.flag for x in self._config.build.use_flags)))
      command += ['--'] + list(cmd)
    kwargs.setdefault('infra_step', True)
    return self.m.step(name, command, **kwargs)

  def _is_after(self, version_str):
    """Return whether the workspace version is >= |version_str|."""
    return self.m.cros_version.version.is_after(version_str)

  @contextmanager
  def _setup(self):
    """Configure the builder"""
    # If we do not have a gitiles_commit from buildbucket, and input properties
    # has manifest_branch, use that branch of the internal manifest.
    self._is_staging = self.m.build_menu.is_staging
    commit = self.m.src_state.gitiles_commit
    if not commit.project and self.properties.manifest_branch:
      commit = self.m.src_state.internal_manifest.as_gitiles_commit_proto
      commit.ref = 'refs/heads/{}'.format(self.properties.manifest_branch)

    with self.m.build_menu.configure_builder(commit=commit,
                                             disable_sdk=True) as config:
      self._config = config
      with self.m.build_menu.setup_workspace(), \
          self.m.context(cwd=self.m.src_state.workspace_path):
        self._uprev()
        self._old_setup_board = self.m.path.exists(
            self.m.src_state.workspace_path.join('src/scripts/setup_board'))

        if self.properties.bump_version:
          self._bump_version()
        self._bcs_version = self.m.cros_version.version

        entries = dict(
            boards=self._boards, version=dict(
                full=str(self._bcs_version),
                milestone=self._bcs_version.milestone,
                platform=self._bcs_version.platform_version))
        # Today's board-metadata may include firmware versions, though that is
        # unpopulated for many (if not all) of the current firmware builders.
        entries['board-metadata'] = {x: {} for x in self._boards}
        self.m.metadata_json.add_entries(**entries)
        self.m.metadata_json.upload_to_gs(config,
                                          self.properties.build_targets[0],
                                          partial=True)

        with self.m.depot_tools.on_path(), self._setup_chroot():
          self._set_firmware_version()
          yield

  def _bump_version(self):
    dry_run = self._is_staging or self.m.cq.active
    self.m.cros_version.bump_version(production=True, dry_run=dry_run)
    if self.m.cq.active:
      with self.m.step.nest('CQ run: not pushing buildspec'):
        return

    # Use 'rubik-staging' if we are on staging.  manifest-versions has
    # not migrated to main yet, so we pass create_releasespec
    # branch=None to use the default branch, whatever it is.
    self.m.cros_release.create_releasespec(
        'buildspecs', branch='rubik-staging' if self._is_staging else None,
        step_name='create buildspec', dry_run=dry_run)
    # Only these builds are valid for suite_scheduling to find.
    self._suite_scheduling = (
        self.properties.set_suite_scheduling and not dry_run)

  def _uprev(self):
    # TODO(b/181786185): Once we have a good "push the uprevs" method, we should
    # switch to calling cros_sdk.uprev_packages, and pushing them, for branches
    # that are new enough.

    # The build team supports using the tip-of-tree cros_mark_as_stable to uprev
    # older branches until such time as they have a long-term answer.  This is
    # not true for other chromite commands.
    workspace = self.m.src_state.workspace_path
    tot_chromite = self.m.path.mkdtemp().join('chromite')
    self.m.step('clone tip-of-tree chromite', [
        'git', 'clone', '--local', '--shared', '--config',
        'remote.origin.fetch=+refs/remotes/cros/main:refs/heads/main',
        workspace.join('chromite'), tot_chromite
    ])
    with self.m.context(cwd=tot_chromite):
      self.m.git.checkout('main', force=True)

    no_push = bool(self.m.cq.active or self._is_staging or
                   self.m.src_state.gerrit_changes)
    drop_file = self.m.path.mkstemp()
    manifest = 0 if not self._config else self._config.general.manifest

    cmd = [tot_chromite.join('bin/cros_mark_as_stable')]
    if no_push:
      cmd.extend(['commit', '--dryrun'])
    else:
      cmd.append('push')
    cmd.extend([
        '--all',
        '--boards=%s' % ':'.join(self._boards), '--drop_file', drop_file,
        '--buildroot', workspace, '--overlay-type',
        'public' if manifest == BuilderConfig.General.PUBLIC else 'both'
    ])

    with self.m.step.nest('uprev packages') as pres:
      self.m.step('call cros_mark_as_stable', cmd)
      pres.logs['packages'] = self.m.file.read_raw(
          'read uprevved packages', drop_file,
          test_data='sys-boot/depthcharge sys-apps/coreboot-utils')

  @contextmanager
  def _setup_chroot(self):
    try:
      self.sdk_call('init SDK', sdk_args=['--delete', '--create'])
      cmd = ['./update_chroot']
      if self._is_after('6480.0.0'):
        if not self.properties.disable_toolchain_boards:
          cmd.extend(['--toolchain_boards', ','.join(self._boards)])
      self.sdk_call('update SDK', cmd=cmd)
      yield
    finally:
      self.sdk_call('delete SDK', sdk_args=['--delete'])

  def _set_firmware_version(self):
    """Determine the firmware version."""
    result = self.sdk_call(
        'determine firmware_version', cmd=['../platform/ec/util/getversion.sh'],
        infra_step=False, stdout=self.m.raw_io.output(add_output_log=True),
        step_test_data=lambda: self.m.raw_io.test_api.stream_output(
            _GETVERSION_TEST_DATA))

    versions = {}
    # For completeness grab all of the defines.
    for line in result.stdout.splitlines():
      match = re.match(r'#define\s+(?P<key>[\w]+)\s+"(?P<value>[^"]+)"', line)
      if match:
        versions[match.groupdict()['key']] = match.groupdict()['value']
    self.m.easy.set_properties_step(
        bcs_version=str(self._bcs_version), firmware_version=versions)
    self._firmware_version = versions['VERSION'][1:]

  def _setup_board_and_install_packages(self, build_target):
    board = build_target.name
    with self.m.step.nest("build {}".format(board)):
      board_arg = '--board={}'.format(board)
      if self._old_setup_board:
        cmd = [
            './setup_board', board_arg, '--accept_licenses=@CHROMEOS',
            '--skip_chroot_upgrade'
        ]
      else:
        cmd = [
            'setup_board', board_arg, '--accept-licenses=@CHROMEOS',
            '--skip-chroot-upgrade'
        ]
      self.sdk_call('setup board', cmd=cmd)

      cmd = [
          './build_packages', board_arg, '--accept_licenses=@CHROMEOS',
          '--skip_chroot_upgrade', '--nousepkg'
      ]
      # --withdebugsymbols was added to build_packages in 6302.0.0
      if self._is_after('6302.0.0'):
        cmd.append('--withdebugsymbols')

      cmd += [
          '{}/{}'.format(x.category, x.package_name)
          for x in self.properties.packages
      ]
      self.sdk_call('install packages', cmd=cmd, infra_step=False)

  def _build_firmware_archive(self, build_target, out_path):
    with self.m.step.nest('create firmware archive'):
      # This code replicates chromite/service/artifacts.BuildFirmwareArchive.
      self.m.file.ensure_directory('create tempdir', out_path)
      root = self._chroot.join('build', build_target.name, 'firmware')

      private_dirs = self.m.file.glob_paths(
          'glob private', root, '**/ec-private/fingerprint',
          test_data=['foo/ec-private/fingerprint'])

      files = self.m.file.listdir(
          'list files', root, recursive=True,
          test_data=['foo/ec-private/fingerprint/bar', 'bar/file'])
      source_list = [
          x for x in files
          if all(not str(x).startswith(str(p)) for p in private_dirs)
      ]
      if not source_list:
        return None

      chroot_path = lambda x: '/' + self.m.path.relpath(x, self._chroot)
      tarball = out_path.join(_FIRMWARE_TARBALL_NAME)
      cmd = ['tar', 'cvjf', chroot_path(tarball), '-C', chroot_path(root)]
      # The list of files is generally too long.
      cmd += ['--null', '-T', '/dev/stdin']
      file_list = '\0'.join(self.m.path.relpath(x, root) for x in source_list)
      self.sdk_call('create tarball', cmd=cmd,
                    stdin=self.m.raw_io.input(data=file_list))
      return tarball

  def _bundle_firmware(self, _chroot, _sysroot, _artifacts_info, outpath,
                       _test_data):
    """Returns a dictionary of files by artifact_type."""
    # We always provide FIRMWARE_TARBALL and FIRMWARE_TARBALL_INFO.

    ret = defaultdict(list)
    # We need a directory inside of the chroot.  Use mkdtemp() to get a name, so
    # that test expectations are constant.
    metadata = FirmwareArtifactInfo()
    metadata.bcs_version_info.version_string = str(self._bcs_version)
    for build_target in self.properties.build_targets:
      tmppath = self.m.path.mkdtemp(prefix='firmware-bundle')
      tmpdir = self._chroot.join('tmp', self.m.path.basename(tmppath))
      tarball = self._build_firmware_archive(build_target, tmpdir)
      if tarball:
        dest_name = '{}/{}'.format(build_target.name, _FIRMWARE_TARBALL_NAME)
        self.m.file.ensure_directory('create {}'.format(build_target.name),
                                     outpath.join(build_target.name))
        self.m.file.copy('bundle tarball', tarball, outpath.join(dest_name))
        ret['FIRMWARE_TARBALL'].append(dest_name)

        info = metadata.objects.add()
        info.file_name = dest_name
        tb_info = info.tarball_info
        tb_info.type = metadata.TarballInfo.FirmwareType.EC
        tb_info.firmware_image_name = build_target.name
        tb_info.firmware_version_info.version_string = self._firmware_version

    if metadata.objects:
      self.m.file.write_proto('write firmware metadata',
                              outpath.join(_FIRMWARE_METADATA_NAME), metadata,
                              'JSONPB')
      ret['FIRMWARE_TARBALL_INFO'].append(_FIRMWARE_METADATA_NAME)
    return ret

  def run(self):
    with self._setup():
      for bt in self.properties.build_targets:
        self._setup_board_and_install_packages(bt)
      self.m.build_menu.upload_artifacts(
          private_bundle_func=self._bundle_firmware)
      # Mark whether the suite_scheduling query for firmware should find this.
      self.m.easy.set_properties_step(
          suite_scheduling=str(self._suite_scheduling))


def RunSteps(api, properties):
  return FirmwareBuilder(api, properties).run()


def GenTests(api):

  def test(name, *args, **kwargs):
    version_str = kwargs.pop('version', 'R86-13434.100.99')
    version = api.cros_version.workspace_version(version_str)
    cq = kwargs.get('cq', False)
    kwargs.setdefault('builder',
                      'fw-atlas-{}'.format('cq' if cq else 'postsubmit'))
    kwargs.setdefault('revision', None)
    input_props = dict(firmware_location=1,
                       manifest_branch='firmware-board-9999.B')
    input_props.update(**kwargs.get('input_properties', {}))
    targets = kwargs.pop('build_targets', None)
    if targets:
      input_props['build_targets'] = targets
    kwargs['input_properties'] = input_props
    build = api.test_util.test_child_build('target', **kwargs).build
    return api.test(name, build, version, *args)

  exists = lambda *x: api.path.exists(api.src_state.workspace_path.join(*x))

  def StepCommandLacks(check, steps, name, arg):
    return check(arg not in steps[name].cmd)

  def suite_scheduling(value):
    return api.post_check(PropertyEquals, 'suite_scheduling', str(value))

  yield test(
      'release', api.post_check(MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(MustRun, 'bump version'),
      api.post_check(MustRun, 'create buildspec'), suite_scheduling(True),
      api.post_check(StepCommandContains, 'build target.install packages',
                     ['--withdebugsymbols']), api.post_check(StatusSuccess),
      input_properties=dict(bump_version=True, set_suite_scheduling=True))

  yield test(
      'postsubmit', api.post_check(MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(DoesNotRun, 'bump version'),
      api.post_check(DoesNotRun, 'create buildspec'), suite_scheduling(False),
      api.post_check(StepCommandContains, 'build target.install packages',
                     ['--withdebugsymbols']), api.post_check(StatusSuccess))

  yield test(
      'old-postsubmit',
      api.post_check(MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(DoesNotRun, 'bump version'),
      api.post_check(DoesNotRun, 'create buildspec'), suite_scheduling(False),
      api.post_check(StepCommandLacks,
                     'build target.install packages', '--withdebugsymbols'),
      api.post_check(StatusSuccess), version='R39-6301.202.44')

  yield test('cq', api.post_check(MustRun, 'upload artifacts.bundle tarball'),
             api.post_check(MustRun, 'upload artifacts.gsutil rsync'),
             api.post_check(DoesNotRun, 'bump version'),
             api.post_check(DoesNotRun, 'create buildspec'),
             suite_scheduling(False), api.post_check(StatusSuccess), cq=True)

  yield test(
      'cq-bump', api.post_check(MustRun, 'upload artifacts.bundle tarball'),
      api.post_check(MustRun, 'upload artifacts.gsutil rsync'),
      api.post_check(MustRun, 'bump version'),
      api.post_check(DoesNotRun, 'create buildspec'), suite_scheduling(False),
      api.post_check(StatusSuccess), cq=True,
      input_properties=dict(bump_version=True, set_suite_scheduling=True))

  yield test('two-targets', api.post_check(MustRun, 'build board1.setup board'),
             api.post_check(MustRun, 'build board2.setup board'),
             api.post_check(DoesNotRun, 'bump version'),
             api.post_check(StatusSuccess), suite_scheduling(False),
             build_targets=[dict(name='board1'),
                            dict(name='board2')])

  yield test(
      'no-firmware',
      api.step_data('upload artifacts.create firmware archive.list files',
                    api.file.listdir()), suite_scheduling(False),
      api.post_check(DoesNotRun, 'upload artifacts.bundle tarball'),
      api.post_check(DoesNotRun, 'upload artifacts.gsutil rsync'),
      api.post_check(DoesNotRun, 'bump version'), api.post_check(StatusSuccess))

  yield test('chroot-exists', exists('chroot'))

  yield test('old-cq', exists('src', 'scripts', 'setup_board'), cq=True)
