// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.build_borealis_rootfs;

import "chromiumos/common.proto";

message BuildBorealisRootfsProperties {
  // Path to the version file to update.
  // Required
  string version_file = 1;

  // The package to generate CLs for.
  // Required
  chromiumos.PackageInfo package_info = 2;

  // Destination gs bucket where the VM image will be copied.
  // Required
  string destination_gs_bucket = 3;

  // Destination gs path where the VM image will be copied.
  // Required
  string destination_gs_path = 4;

  // The manifest branch to check out (e.g. 'release-R105-14989.B')
  // Defaults to main tip of tree if not specified.
  string manifest_branch = 5;

  // The docker variant to build with.
  string docker_variant = 6;

  // Whether to build the tast binaries tarball.
  bool build_tast_binaries = 7;

  // Whether to run build_full with --disable_arch_sig_validation or not. This
  // switches to using a locally sourced hash verification method rather than
  // Arch's built in PGP keys. Used for cases when keys expire (specifically on
  // manifest branches where the Arch version can't be uprev'd.)
  bool disable_arch_sig_validation = 8;

  // Path to the Borealis repository relative to the CrOS SDK root.
  // Optional. Defaults to 'src/platform/borealis-vm'.
  string borealis_path = 9;

  // Whether or not to use the legacy 'src/platform/borealis/tools' path.
  // Some tools have been moved to platform/borealis-private/tools, but older
  // builds (< M127) need to use the version in src/platform/borealis.
  // Optional.
  bool legacy_tools_dir = 10;
}
