# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Build and sign recovery kernel images."""

import re

from google.protobuf.json_format import MessageToDict
from google.protobuf.json_format import MessageToJson

from PB.chromiumos import build_report as build_report_pb2
from PB.chromiumos import common as common_pb2
from PB.chromiumos import signing as signing_pb2
from PB.chromite.api.image import SignImageResponse
from PB.chromite.api.recovery import CreateRecoveryKernelRequest
from PB.go.chromium.org.luci.buildbucket.proto import common as bb_common_pb2
from PB.recipes.chromeos.build_and_sign_recovery import BuildAndSignRecoveryProperties
from PB.recipes.chromeos.build_and_sign_recovery import PublishStrategy
from PB.recipe_engine import result as result_pb2
from PB.recipe_modules.chromeos.signing.signing import SigningProperties

from recipe_engine import post_process
from recipe_engine.config_types import Path
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_api import StepFailure
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/cv',
    'recipe_engine/file',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'build_menu',
    'cros_build_api',
    'cros_infra_config',
    'cros_release',
    'cros_sdk',
    'cros_source',
    'gerrit',
    'git',
    'mutable_output',
    'signing',
    'signing_utils',
    'src_state',
]

PROPERTIES = BuildAndSignRecoveryProperties

TEST_SIGNING_CONFIG = '''build_target_signing_configs {
      build_target: "kukui"
      keyset: "kukui-premp"
      signing_configs {
        image_type: IMAGE_TYPE_RECOVERY_KERNEL
      }
    }'''

CL_REVIEWERS = ['kimjae@google.com', 'konrada@google.com', 'rrangel@google.com']

AG_HOST = 'googleplex-android'
DESKTOP_HOST = 'arsp'


def create_or_update_symlink(api: RecipeApi, directory: Path, file: str,
                             symlink: str):
  with api.context(cwd=directory):
    if api.path.exists(directory / symlink):
      api.file.remove('remove existing symlink', directory / symlink)
    api.step('create symlink', ['ln', '-s', file, symlink])


def upload_recovery_prebuilts(api: RecipeTestApi, unsigned_recovery_path: Path,
                              signed_recovery_path: Path, target: str,
                              keyset_is_mp: bool, version: str,
                              abandon: bool = True, host: str = AG_HOST) -> str:
  """Uploads the recovery kernel prebuilts to the android repo.

  Returns:
    The message to include in the summary markdown of the build."""
  checkout = api.path.mkdtemp()
  with api.context(cwd=checkout):
    api.git.clone(
        f'https://{host}.googlesource.com/device/google/desktop/{target}-prebuilts',
        depth=1)

    # Copy the prebuild into the kernel prebuild repo.
    api.file.ensure_directory('make sure dev-signed exists',
                              api.path.join(checkout, 'recovery', 'dev-signed'))
    api.file.copy(
        'copy recovery kernel image to repo', unsigned_recovery_path,
        api.path.join(checkout, 'recovery', 'dev-signed',
                      f'vmlinuz_{version}.image'))
    create_or_update_symlink(api, checkout / 'recovery/dev-signed',
                             f'vmlinuz_{version}.image', 'vmlinuz_LATEST.image')
    directory = 'mp-signed' if keyset_is_mp else 'premp-signed'
    api.file.ensure_directory(f'make sure {directory} exists',
                              api.path.join(checkout, 'recovery', directory))
    api.file.copy(
        'copy recovery kernel image to repo', signed_recovery_path,
        api.path.join(checkout, 'recovery', directory,
                      f'vmlinuz_{version}.image'))
    create_or_update_symlink(api, checkout / f'recovery/{directory}',
                             f'vmlinuz_{version}.image', 'vmlinuz_LATEST.image')

    # Check to make sure there was actually a change.
    diff_lines = api.git.get_working_dir_diff_files()
    if not diff_lines:
      return 'No recovery kernel images changed.'
    # Skip upload in CQ.
    if api.cv.active:
      api.step.empty('Skipping CL upload in CQ')
      return ''
    # Create a cl updating the file.
    api.git.add_all()
    bbid = api.buildbucket.build_url()
    commit_lines = [
        f'recovery-kernel: Update prebuilts to version {version}',
        '',
        f'Generated by {bbid}.',
        '',
        f'Flag: build.RELEASE_{target.upper()}_RECOVERY_KERNEL_BUILD_VERSION',
    ]
    api.git.commit('\n'.join(commit_lines))
    change = api.gerrit.create_change(
        f'/device/google/desktop/{target}-prebuilts',
        ref=api.git.get_branch_ref('main'), project_path=checkout,
        reviewers=CL_REVIEWERS if not api.cros_infra_config.is_staging else [],
        non_repo_checkout=True)
    if abandon:
      api.gerrit.abandon_change(change)
    return f'Updated recovery kernel prebuilts for {target}'


def get_recovery_path(api: RecipeApi, response: SignImageResponse) -> Path:
  local_artifact_dir = response.output_archive_dir
  [only_artifact] = response.signed_artifacts.archive_artifacts
  [only_signed] = only_artifact.signed_artifacts

  return api.path.join(local_artifact_dir, only_signed.signed_artifact_name)


def get_keyset_is_mp(response: SignImageResponse) -> bool:
  [only_artifact] = response.signed_artifacts.archive_artifacts
  return only_artifact.keyset_is_mp


def RunSteps(api: RecipeApi, properties: BuildAndSignRecoveryProperties):
  with api.mutable_output.wrap():
    with api.cros_source.checkout_overlays_context():
      config = api.cros_source.configure_builder(api.buildbucket.gitiles_commit)
      with api.build_menu.setup_workspace_and_chroot():
        api.cros_source.ensure_synced_cache()

        api.build_menu.setup_sysroot_and_determine_relevance()
        api.build_menu.bootstrap_sysroot(config)
        # build_packages not required; all dependencies are build in the next step.

        recovery_dir = api.path.mkdtemp(prefix='recovery')
        recovery_local_path = api.path.join(recovery_dir, 'vmlinuz.image')

        with api.step.nest('create recovery kernel'):
          kernel_response = api.cros_build_api.RecoveryService.CreateRecoveryKernel(
              CreateRecoveryKernelRequest(
                  chroot=api.build_menu.chroot,
                  build_target=api.build_menu.build_target,
                  flags=CreateRecoveryKernelRequest.Flags(
                      ramfs_type=CreateRecoveryKernelRequest.RamfsType
                      .DESKTOP_RECOVERY_RAMFS)))

        # copy the file in.
        response_path = '%s%s' % (api.build_menu.chroot.out_path,
                                  kernel_response.recovery_kernel.path)
        api.file.copy('copy prebuild recovery image into temp dir',
                      response_path, recovery_local_path)

        # Get prebuilt version for target.
        new_recovery_version = api.signing.get_prebuilt_version(
            latest_filename='LATEST-RECOVERYKERNEL')
        api.signing_utils.custom_artifact_version = new_recovery_version

        # Sign recovery kernel image and upload to GS.
        if api._test_data.enabled:  # pylint: disable=protected-access
          api.signing.test_api.signing_config_test_data = api._test_data.get(  # pylint: disable=protected-access
              'signing_config', TEST_SIGNING_CONFIG)
        api.cros_release.validate_sign_types()
        with api.step.nest('sign recovery kernel image') as pres:
          signed_image_response = api.signing.sign_artifacts(
              sign_types=[common_pb2.IMAGE_TYPE_RECOVERY_KERNEL],
              channels=[common_pb2.CHANNEL_AGNOSTIC], include_paygen=False,
              local_artifact_dir=recovery_dir, upload_unsigned=False)
          if not signed_image_response:
            raise StepFailure('Empty signing config for build target')
          signed_recovery_path = get_recovery_path(api, signed_image_response)
          pres.logs['signed builds'] = signed_recovery_path

        # Advance LATEST-RECOVERYKERNEL.
        api.signing.upload_prebuilt_latest_file(
            new_recovery_version, latest_filename='LATEST-RECOVERYKERNEL')

        # Open a cl with the new recovery kernel prebuilts.
        if properties.publish_strategy in (PublishStrategy.UNSPECIFIED,
                                           PublishStrategy.AG_ONLY,
                                           PublishStrategy.AG_AND_DESKTOP):
          ag_msg = upload_recovery_prebuilts(
              api, recovery_local_path, signed_recovery_path,
              api.build_menu.build_target.name,
              get_keyset_is_mp(signed_image_response), new_recovery_version,
              abandon=api.cros_infra_config.is_staging, host=AG_HOST)
        else:
          ag_msg = 'Not published to AG host'
        if properties.publish_strategy in (PublishStrategy.DESKTOP_ONLY,
                                           PublishStrategy.AG_AND_DESKTOP):
          desktop_msg = upload_recovery_prebuilts(
              api, recovery_local_path, signed_recovery_path,
              api.build_menu.build_target.name,
              get_keyset_is_mp(signed_image_response), new_recovery_version,
              abandon=api.cros_infra_config.is_staging, host=DESKTOP_HOST)
        else:
          desktop_msg = 'Not published to desktop host'
        return result_pb2.RawResult(
            summary_markdown=f'AG: {ag_msg}\nDesktop:{desktop_msg}',
            status=bb_common_pb2.SUCCESS,
        )


# Sample SignImageResponse for testing.
def sample_response(
    name: str = 'chromeos_16110.0.0_android-kukui-channel_DevPreMPKeys'
) -> SignImageResponse:
  return SignImageResponse(
      output_archive_dir='/archive_dir/',
      signed_artifacts=signing_pb2.BuildTargetSignedArtifacts(
          archive_artifacts=[
              signing_pb2.ArchiveArtifacts(
                  build_target='android-kukui',
                  channel=common_pb2.CHANNEL_AGNOSTIC,
                  image_type=common_pb2.IMAGE_TYPE_RECOVERY_KERNEL,
                  signed_artifacts=[
                      signing_pb2.SignedArtifact(
                          signed_artifact_name=name,
                      ),
                  ],
                  signing_status=build_report_pb2.BuildReport
                  .SignedBuildMetadata.SIGNING_STATUS_PASSED,
              )
          ]))


def GenTests(api: RecipeTestApi):
  yield api.build_menu.test(
      'success-unspecified-host',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign recovery kernel image.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response())),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          f'https://{AG_HOST}.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_process(post_process.DoesNotRun, 'git clone (2)'),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-RECOVERYKERNEL version',
          stdout=api.raw_io.output('1.0')),
      api.post_check(post_process.MustRun,
                     'copy prebuild recovery image into temp dir'),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.call BAPI.call chromite.api.ImageService/SignImage.write input file',
          [re.compile('.*"imageType": 21.*')]),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/2.0/',
          ]),
      api.post_check(post_process.MustRun, 'write latest file for version 2.0'),
      api.post_check(post_process.MustRun,
                     'gsutil upload LATEST-RECOVERYKERNEL'),
      api.post_check(
          post_process.StepCommandContains, 'write commit message',
          [re.compile(r'recovery-kernel: Update prebuilts to version 2\.0.*')]),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='recovery-android-kukui-main',
  )

  yield api.build_menu.test(
      'success-ag-only',
      api.properties(
          **{
              'publish_strategy':
                  PublishStrategy.AG_ONLY,
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign recovery kernel image.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response())),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          f'https://{AG_HOST}.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_process(post_process.DoesNotRun, 'git clone (2)'),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-RECOVERYKERNEL version',
          stdout=api.raw_io.output('1.0')),
      api.post_check(post_process.MustRun,
                     'copy prebuild recovery image into temp dir'),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.call BAPI.call chromite.api.ImageService/SignImage.write input file',
          [re.compile('.*"imageType": 21.*')]),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/2.0/',
          ]),
      api.post_check(post_process.MustRun, 'write latest file for version 2.0'),
      api.post_check(post_process.MustRun,
                     'gsutil upload LATEST-RECOVERYKERNEL'),
      api.post_check(
          post_process.StepCommandContains, 'write commit message',
          [re.compile(r'recovery-kernel: Update prebuilts to version 2\.0.*')]),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_check(post_process.DoesNotRun, 'git commit (2)'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='recovery-android-kukui-main',
  )

  yield api.build_menu.test(
      'success-desktop-only',
      api.properties(
          **{
              'publish_strategy':
                  PublishStrategy.DESKTOP_ONLY,
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign recovery kernel image.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response())),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          f'https://{DESKTOP_HOST}.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_process(post_process.DoesNotRun, 'git clone (2)'),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-RECOVERYKERNEL version',
          stdout=api.raw_io.output('1.0')),
      api.post_check(post_process.MustRun,
                     'copy prebuild recovery image into temp dir'),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.call BAPI.call chromite.api.ImageService/SignImage.write input file',
          [re.compile('.*"imageType": 21.*')]),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/2.0/',
          ]),
      api.post_check(post_process.MustRun, 'write latest file for version 2.0'),
      api.post_check(post_process.MustRun,
                     'gsutil upload LATEST-RECOVERYKERNEL'),
      api.post_check(
          post_process.StepCommandContains, 'write commit message',
          [re.compile(r'recovery-kernel: Update prebuilts to version 2\.0.*')]),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_check(post_process.DoesNotRun, 'git commit (2)'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='recovery-android-kukui-main',
  )

  yield api.build_menu.test(
      'success-ag-and-desktop',
      api.properties(
          **{
              'publish_strategy':
                  PublishStrategy.AG_AND_DESKTOP,
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign recovery kernel image.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response())),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          f'https://{AG_HOST}.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_process(post_process.StepCommandContains, 'git clone (2)', [
          f'https://{DESKTOP_HOST}.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-RECOVERYKERNEL version',
          stdout=api.raw_io.output('1.0')),
      api.post_check(post_process.MustRun,
                     'copy prebuild recovery image into temp dir'),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.call BAPI.call chromite.api.ImageService/SignImage.write input file',
          [re.compile('.*"imageType": 21.*')]),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/2.0/',
          ]),
      api.post_check(post_process.MustRun, 'write latest file for version 2.0'),
      api.post_check(post_process.MustRun,
                     'gsutil upload LATEST-RECOVERYKERNEL'),
      api.post_check(
          post_process.StepCommandContains, 'write commit message',
          [re.compile(r'recovery-kernel: Update prebuilts to version 2\.0.*')]),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_check(post_process.MustRun, 'git commit (2)'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 2'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='recovery-android-kukui-main',
  )

  yield api.build_menu.test(
      'symlink-exists',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.path.exists(
          api.path.cleanup_dir /
          'tmp_tmp_3/recovery/dev-signed/vmlinuz_LATEST.image',
          api.path.cleanup_dir /
          'tmp_tmp_3/recovery/premp-signed/vmlinuz_LATEST.image'),
      api.cros_build_api.set_api_return(
          'sign recovery kernel image.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response())),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-RECOVERYKERNEL version',
          stdout=api.raw_io.output('2.0')),
      api.post_check(post_process.MustRun,
                     'copy prebuild recovery image into temp dir'),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.call BAPI.call chromite.api.ImageService/SignImage.write input file',
          [re.compile('.*"imageType": 21.*')]),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/3.0/',
          ]),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_check(post_process.MustRun, 'remove existing symlink'),
      api.post_check(post_process.StepCommandContains, 'create symlink',
                     ["ln", "-s", "vmlinuz_3.0.image", "vmlinuz_LATEST.image"]),
      api.post_check(post_process.MustRun, 'remove existing symlink (2)'),
      api.post_check(post_process.StepCommandContains, 'create symlink (2)',
                     ["ln", "-s", "vmlinuz_3.0.image", "vmlinuz_LATEST.image"]),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='recovery-android-kukui-main',
  )

  yield api.build_menu.test(
      'signing-skipped',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-RECOVERYKERNEL version',
          stdout=api.raw_io.output('3.0')),
      api.recipe_test_data(signing_config="""build_target_signing_configs {
  build_target: "kukui"
}"""),
      api.post_check(post_process.MustRun,
                     'copy prebuild recovery image into temp dir'),
      api.post_check(
          post_process.DoesNotRun,
          'sign recovery kernel image.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.'
      ),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='recovery-android-kukui-main',
      status='FAILURE',
  )

  yield api.build_menu.test(
      'no-diff',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign recovery kernel image.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response())),
      api.step_data('git status', stdout=api.raw_io.output('')),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-RECOVERYKERNEL version',
          stdout=api.raw_io.output('3.0')),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_check(post_process.MustRun,
                     'copy prebuild recovery image into temp dir'),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.call BAPI.call chromite.api.ImageService/SignImage.write input file',
          [re.compile('.*"imageType": 21.*')]),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/4.0/',
          ]),
      api.post_check(
          post_process.SummaryMarkdown,
          'AG: No recovery kernel images changed.\nDesktop:Not published to desktop host'
      ),
      api.post_check(post_process.DoesNotRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='recovery-android-kukui-main',
  )

  yield api.build_menu.test(
      'staging',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign recovery kernel image.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response())),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-RECOVERYKERNEL version',
          stdout=api.raw_io.output('333.0')),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_check(post_process.MustRun,
                     'copy prebuild recovery image into temp dir'),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.call BAPI.call chromite.api.ImageService/SignImage.write input file',
          [re.compile('.*"imageType": 21.*')]),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/334.0/',
          ]),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.MustRun, 'abandon CL 1'),
      # Omit reviewers in staging.
      api.post_check(
          post_process.StepCommandDoesNotContain,
          'create gerrit change for /device/google/desktop/kukui-prebuilts.git_cl upload',
          '--reviewers'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      bucket='staging',
      builder='recovery-android-kukui-main',
  )

  test_gerrit_changes = [
      bb_common_pb2.GerritChange(host='chromium-review.googlesource.com',
                                 change=1234, project='chromiumos/chromite',
                                 patchset=1),
  ]
  yield api.build_menu.test(
      'cq',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware',
                                        use_dev_keys=True)),
          }),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-RECOVERYKERNEL version',
          stdout=api.raw_io.output('3.0')),
      api.post_check(
          post_process.StepCommandContains,
          'cherry-pick gerrit changes.apply gerrit patch sets.git fetch', [
              "git", "fetch",
              "https://chromium.googlesource.com/chromiumos/chromite",
              "refs/changes/34/1234/1:"
          ]),
      api.cros_build_api.set_api_return(
          'sign recovery kernel image.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response())),
      api.post_check(
          post_process.LogContains,
          'sign recovery kernel image.sign artifacts.call BAPI.call chromite.api.'
          'ImageService/SignImage', 'request',
          ['\"keyset\": \"DevPreMPKeys\"']),
      # Skip CL upload.
      api.post_check(post_process.DoesNotRun, 'git commit'),
      api.post_check(post_process.MustRun, 'Skipping CL upload in CQ'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      bucket='staging',
      builder='recovery-android-kukui-main',
      cq=True,
      gerrit_changes=test_gerrit_changes,
  )

  yield api.build_menu.test(
      'new-latest-version',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign recovery kernel image.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response())),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-RECOVERYKERNEL version',
          retcode=1),
      api.post_check(
          post_process.StepCommandContains,
          'sign recovery kernel image.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/1.0/',
          ]),
      api.post_check(post_process.MustRun, 'write latest file for version 1.0'),
      api.post_check(post_process.MustRun,
                     'gsutil upload LATEST-RECOVERYKERNEL'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='recovery-android-kukui-main',
  )
