// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.build_firmware;

import "chromite/api/firmware.proto";

message BuildFirmwareProperties {
  // Firmware location.  See chromite.api.firmware.
  chromite.api.FwLocation firmware_location = 1;

  // Whether upload_artifacts works for this builder.
  // TODO(b:177907747): Remove this.
  bool working_artifacts = 2;
}
