# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Build provision kernel images."""

import re

from PB.chromite.api.recovery import CreateRecoveryKernelRequest
from PB.go.chromium.org.luci.buildbucket.proto import common as bb_common_pb2
from PB.recipe_engine import result as result_pb2

from recipe_engine import post_process
from recipe_engine.config_types import Path
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/cv',
    'recipe_engine/file',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'build_menu',
    'cros_build_api',
    'cros_infra_config',
    'cros_sdk',
    'cros_source',
    'gerrit',
    'git',
    'mutable_output',
    'src_state',
]

CL_REVIEWERS = ['kimjae@google.com', 'konrada@google.com', 'rrangel@google.com']


def upload_provision_kernel_prebuilts(
    api: RecipeApi, provision_kernel_path: Path, target: str,
    abandon: bool = True) -> result_pb2.RawResult:
  """Uploads the provision kernel prebuilts to the android repo."""
  checkout = api.path.mkdtemp()
  with api.context(cwd=checkout):
    api.git.clone(
        f'https://googleplex-android.googlesource.com/device/google/desktop/{target}-prebuilts',
        depth=1)

    # Copy the prebuild into the kernel prebuild repo.
    provision_dir = checkout / 'provision'
    api.file.ensure_directory('make sure provision exists', provision_dir)

    # Calculate the next version.
    highest_version = 0
    for f in api.file.listdir('list files', provision_dir):
      match = re.match(r'.*-v(\d+)\.\d+\.\d+\.bin', str(f))
      if match:
        highest_version = max(highest_version, int(match.group(1)))
    new_version = f'{highest_version + 1}.0.0'

    new_kernel_name = f'{target}-provision-v{new_version}.bin'
    api.file.copy('copy provision kernel image to repo', provision_kernel_path,
                  provision_dir / new_kernel_name)

    # Check to make sure there was actually a change.
    diff_lines = api.git.get_working_dir_diff_files()
    if not diff_lines:
      return result_pb2.RawResult(
          summary_markdown='No provision kernel images changed.',
          status=bb_common_pb2.SUCCESS,
      )
    # Skip upload in CQ.
    if api.cv.active:
      api.step.empty('Skipping CL upload in CQ')
      return result_pb2.RawResult(
          status=bb_common_pb2.SUCCESS,
      )
    # Create a cl updating the file.
    api.git.add_all()
    bbid = api.buildbucket.build_url()
    commit_lines = [
        f'provision-kernel: Update prebuilts to version {new_version}',
        '',
        f'Generated by {bbid}.',
        '',
        f'Flag: build.RELEASE_{target.upper()}_PROVISION_IMAGE_VERSION',
    ]
    api.git.commit('\n'.join(commit_lines))
    change = api.gerrit.create_change(
        f'/device/google/desktop/{target}-prebuilts',
        ref=api.git.get_branch_ref('main'), project_path=checkout,
        reviewers=CL_REVIEWERS if not api.cros_infra_config.is_staging else [],
        non_repo_checkout=True)
    if abandon:
      api.gerrit.abandon_change(change)
    return result_pb2.RawResult(
        summary_markdown=f'Updated provision kernel prebuilts for {target}',
        status=bb_common_pb2.SUCCESS,
    )


def RunSteps(api: RecipeApi):
  with api.cros_source.checkout_overlays_context():
    config = api.cros_source.configure_builder(api.buildbucket.gitiles_commit)
    with api.build_menu.setup_workspace_and_chroot():
      api.cros_source.ensure_synced_cache()

      # Full package install to ensure packages deps for cros build-kernel are present.
      env_info = api.build_menu.setup_sysroot_and_determine_relevance()
      api.build_menu.bootstrap_sysroot(config)
      api.build_menu.install_packages(config, env_info.packages)

      with api.step.nest('create provision kernel'):
        kernel_response = api.cros_build_api.RecoveryService.CreateRecoveryKernel(
            CreateRecoveryKernelRequest(
                chroot=api.build_menu.chroot,
                build_target=api.build_menu.build_target,
                flags=CreateRecoveryKernelRequest.Flags(
                    ramfs_type=CreateRecoveryKernelRequest.RamfsType
                    .DESKTOP_PROVISION_RAMFS)))

      kernel_path = api.path.join(api.build_menu.chroot.out_path,
                                  kernel_response.recovery_kernel.path)

      # Open a cl with the new provision kernel prebuilts.
      return upload_provision_kernel_prebuilts(
          api, kernel_path, api.build_menu.build_target.name,
          abandon=api.cros_infra_config.is_staging)


def GenTests(api: RecipeTestApi):

  def check_copy_command(check, steps):
    step = steps['copy provision kernel image to repo']
    check('copy' in step.cmd)
    check(any(re.match(r'.*vmlinuz.image', x) for x in step.cmd))
    check(any(re.match(r'.*brya-provision-v11.0.0.bin', x) for x in step.cmd))

  yield api.build_menu.test(
      'success',
      api.step_data('list files',
                    api.file.listdir(['brya-provision-v10.0.0.bin'])),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/brya-prebuilts'
      ]),
      api.post_check(
          post_process.LogContains,
          'create provision kernel.call chromite.api.RecoveryService/CreateRecoveryKernel',
          'request',
          ['"ramfsType": 8'],  # DESKTOP_PROVISION_RAMFS
      ),
      api.post_process(post_process.DropExpectation),
      build_target='brya',
      builder='provision-android-brya-main',
  )

  yield api.build_menu.test(
      'no-diff',
      api.step_data('list files',
                    api.file.listdir(['brya-provision-v10.0.0.bin'])),
      api.step_data('git status', stdout=api.raw_io.output('')),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/brya-prebuilts'
      ]),
      api.post_process(check_copy_command),
      api.post_check(
          post_process.LogContains,
          'create provision kernel.call chromite.api.RecoveryService/CreateRecoveryKernel',
          'request',
          ['"ramfsType": 8'],  # DESKTOP_PROVISION_RAMFS
      ),
      api.post_check(post_process.SummaryMarkdown,
                     'No provision kernel images changed.'),
      api.post_check(post_process.DoesNotRun, 'git commit'),
      api.post_process(post_process.DropExpectation),
      build_target='brya',
      builder='provision-android-brya-main',
  )

  yield api.build_menu.test(
      'cq',
      api.step_data('list files',
                    api.file.listdir(['brya-provision-v10.0.0.bin'])),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/brya-prebuilts'
      ]),
      api.post_process(check_copy_command),
      api.post_check(
          post_process.LogContains,
          'create provision kernel.call chromite.api.RecoveryService/CreateRecoveryKernel',
          'request',
          ['"ramfsType": 8'],  # DESKTOP_PROVISION_RAMFS
      ),
      api.post_check(post_process.MustRun, 'Skipping CL upload in CQ'),
      api.post_check(post_process.DoesNotRun, 'git commit'),
      api.post_process(post_process.DropExpectation),
      build_target='brya',
      builder='provision-android-brya-main',
      cq=True,
  )

  yield api.build_menu.test(
      'prod',
      api.step_data('list files',
                    api.file.listdir(['brya-provision-v10.0.0.bin'])),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/brya-prebuilts'
      ]),
      api.post_process(check_copy_command),
      api.post_check(
          post_process.LogContains,
          'create provision kernel.call chromite.api.RecoveryService/CreateRecoveryKernel',
          'request',
          ['"ramfsType": 8'],  # DESKTOP_PROVISION_RAMFS
      ),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_process(post_process.DropExpectation),
      build_target='brya',
      builder='provision-android-brya-main',
      bucket='prod',
  )

  yield api.build_menu.test(
      'staging',
      api.step_data('list files',
                    api.file.listdir(['brya-provision-v10.0.0.bin'])),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          'https://googleplex-android.googlesource.com/device/google/desktop/brya-prebuilts'
      ]),
      api.post_process(check_copy_command),
      api.post_check(
          post_process.LogContains,
          'create provision kernel.call chromite.api.RecoveryService/CreateRecoveryKernel',
          'request',
          ['"ramfsType": 8'],  # DESKTOP_PROVISION_RAMFS
      ),
      api.post_check(post_process.MustRun, 'abandon CL 1'),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_process(post_process.DropExpectation),
      build_target='brya',
      builder='provision-android-brya-main',
      bucket='staging',
  )
