syntax = "proto3";

package recipes.chromeos.check_project_config;

// Describes where a generated ConfigBundle lives in the checked out source
// tree.
message ConfigBundleCheckoutPath {
    // Defines the path the repo is checked out to in the source tree, i.e. the
    // "path" attribute in the manifest.
    string repo_checkout_path = 1;

    // Defines the path that stores all of the project configuration.
    // Relative to the repo.
    string config_path = 2;
}

// Describes the location of a local manifest file.
// See https://gerrit.googlesource.com/git-repo/+/master/docs/manifest-format.md#local-manifests.
message LocalManifest {
    // URL of the repo with the local manifest. E.g.
    // https://chrome-internal.googlesource.com/chromeos/project/...
    string repo_url = 1;

    // Path to the local manifest.
    // Relative to the repo.
    string manifest_path = 2;
}

message CheckProjectConfigProperties {
    // Manifest groups to init and sync.
    //
    // The union of repos specified by these groups should contain:
    // - Exactly one program repo (e.g. "chromeos/program/<program>").
    // - Exactly one project repo (e.g. "chromeos/project/<program>/<project>").
    // - All shared config repos needed by the project
    //   (e.g "chromiumos/config").
    repeated string manifest_groups = 1;

    // Local manifest to add to the checkout.
    LocalManifest local_manifest = 5;

    // Path the "chromiumos/config" repo is checked out to in the source tree.
    string chromiumos_config_checkout_path = 2;

    // Paths the program and project ConfigBundles are checked out to in the
    // source tree.
    ConfigBundleCheckoutPath program_config_bundle_checkout_path = 3;
    ConfigBundleCheckoutPath project_config_bundle_checkout_path = 4;
}