syntax = "proto3";

package recipes.chromeos.check_project_config;

import "project_mgmt/project.proto";

// Describes where a generated ConfigBundle lives in the checked out source
// tree.
message ConfigBundleCheckoutPath {
    // Defines the path the repo is checked out to in the source tree, i.e. the
    // "path" attribute in the manifest.
    string repo_checkout_path = 1;

    // Defines the path that stores all of the project configuration.
    // Relative to the repo.
    string config_path = 2;
}

message CheckProjectConfigProperties {
    // Manifest groups specifying a subset of repos to sync.
    //
    // The subset of repos in the external manifest + local_manifest matching
    // manifest_groups are synced. For example, say the external manifest
    // contains repos:
    //
    //   <project path="a" name="a" groups="g1" />
    //   <project path="b" name="b" groups="g1" />
    //   <project path="c" name="c" groups="g2" />
    //
    // and the local manifest contains repos:
    //
    //   <project path="d" name="d" groups="g3" />
    //   <project path="e" name="e" groups="g4" />
    //
    // and manifest_groups is ["g1", "g4"]. Repos "a", "b", and "e" will be
    // synced.
    //
    // If empty, all repos are synced.
    repeated string manifest_groups = 1;

    // Branch to init the checkout with. If not specified, the default branch
    // of the manifest repo will be used.
    //
    // Note that if manifest_branch is specified, the internal manifest will be
    // used and local_manifest cannot be specified. This is because local
    // manifests are not branched along with main manifests, so using the
    // branched public manifest along with a local manifest will mean some repos
    // are on branches, some are not.
    string manifest_branch = 9;

    // Local manifests to add to the checkout.
    repeated project_mgmt.LocalManifest local_manifests = 10;

    // Path the "chromiumos/config" repo is checked out to in the source tree.
    string chromiumos_config_checkout_path = 2;

    // Paths the program and project ConfigBundles are checked out to in the
    // source tree.
    ConfigBundleCheckoutPath program_config_bundle_checkout_path = 3;
    ConfigBundleCheckoutPath project_config_bundle_checkout_path = 4;

    // Google Storage prefix to log output from steps to.
    //
    // Currently, LogDog ACLs are applied at the project level, not the bucket
    // level. Thus, it is possible an account can view the Milo page for a
    // build, but not the logs for the step (e.g. stdout). As a workaround, some
    // logs are mirrored to GS buckets where more granular ACLs can be applied.
    //
    // This prefix should contain the bucket name, but not the 'gs://' prefix.
    string logging_gs_prefix = 6;

    // Path to the factory config directory, relative to the project repo.
    string factory_dir = 7;

    // Whether to use the external manifest repo.
    bool use_external_manifest = 8;
}
