# -*- coding: utf-8 -*-
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Check that any binary blobs in a commit come from a valid FIT version"""

# The FIT tool from Intel merges several closed-source binary blobs together
# from configuration information to build a binary blob that's used to
# initialize their SoC.  We need to make sure that the binary blobs being used
# and the FIT version are consistent and approved for particular devices.  This
# builder should be triggered on changes to and -versions.txt or .bin files that
# are related to the FIT tool.
#
# It does the following:
#   for every changed -versions.txt:
#     check that the corresponding .bin file has been changed too
#
#   for every changed .bin:
#     check that the corresponding -versions.txt file has been changed too
#
#   for every changed -versions.txt:
#     read the FIT version from the file
#     read the (hash, file) pairs from the file
#
#     check that the FIT version matches the version in the input reference file
#     check that each file is present in the reference file and that the
#     binary hashes match

import fnmatch
import re
import os

from collections import defaultdict

from recipe_engine import post_process

from PB.go.chromium.org.luci.buildbucket.proto import common as common_pb2
from PB.recipes.chromeos.check_fit_image import CheckFitImageProperties

PROPERTIES = CheckFitImageProperties

DEPS = [
    'recipe_engine/context',
    'recipe_engine/file',
    'recipe_engine/properties',
    'recipe_engine/step',
    'cros_infra_config',
    'cros_source',
    'gerrit',
    'src_state',
    'repo',
    'test_util',
]


def parse_versions_file(step_name, api, path):
  """Parse a versions file containing SHA-256 hashes and binary names into a map

  This file is generated by gen_hash_references.sh in the sys-boot overlays
  of individual baseboards.  It's a list of SHA-256 hashes and associated file
  names.

  Args:
    path (str): path to versions file

  Return:
    (Fit Version, { filename => SHA-256 hash })
  """

  def is_all_char(string, char):
    """Return true if a string is composed entirely of one character"""
    return string and all([c == char for c in string])

  contents = api.file.read_text(step_name, path).split("\n")

  # Seek to end of FIT header output, this is denoted by a line of hyphens
  offset = 0
  version = None
  for offset in range(len(contents)):
    line = contents[offset]

    # Check for version string
    match = re.search("Version:\s*([^\s]*)$", line)
    if match:
      version = match.group(1)

    if is_all_char(line, "-"):
      offset += 1
      break

  if not version:
    raise api.step.StepFailure('FIT version information not found in \'%s\'' %
                               path)

  # Build file => hash map
  hashes = {}
  for line in contents[offset:]:
    if line:
      sha256, fname = line.split()
      hashes[fname] = sha256

  return (version, hashes)


def RunSteps(api, properties):

  def comment_and_quit(comment):
    """Post a comment back to all the changes we're operating on"""
    for change in api.src_state.gerrit_changes:
      api.gerrit.add_change_comment(change, comment)
    raise api.step.StepFailure(comment)

  # Setup builder with default settings (snapshot + gerrit changes applied)
  api.cros_infra_config.configure_builder()

  with api.cros_source.checkout_overlays_context(), \
       api.context(cwd=api.cros_source.workspace_path):

    gerrit_changes = api.src_state.gerrit_changes

    version_files = set()
    bin_files = set()
    changes = api.gerrit.fetch_patch_sets(gerrit_changes, include_files=True)
    for change in changes:
      for fname in change.file_infos:
        if fnmatch.fnmatch(os.path.basename(fname), "fitimage-*-versions.txt"):
          version_files.add(fname)

        if fnmatch.fnmatch(os.path.basename(fname), "fitimage-*.bin"):
          bin_files.add(fname)

    # Make sure that changed files are consistent, if we change a -versions.txt,
    # we better have made a change to the associated binary
    for fname in version_files:
      if not fname.replace("-versions.txt", ".bin") in bin_files:
        comment_and_quit(
            "Change to '%s' does not have a matching change to .bin" % fname)

    for fname in bin_files:
      if not fname.replace(".bin", "-versions.txt") in version_files:
        comment_and_quit(
            "Change to '%s' does not have a matching change to -versions.txt" %
            fname)

    # Figure out what projects to sync
    project_infos = api.repo.project_infos(
        [gc.project for gc in gerrit_changes])
    projects = list(set([p.name for p in project_infos]))

    verbose = dict(verbose=True)
    api.cros_source.ensure_synced_cache(
        init_opts=verbose, sync_opts=verbose,
        cache_path_override=api.cros_source.workspace_path, projects=projects)

    # And patch projects
    api.cros_source.apply_gerrit_patch_sets(changes)

    # Read reference file
    ref_version, ref_hashes = parse_versions_file(
        "reading reference file", api,
        api.context.cwd.join(properties.csme_ref_path))

    # Check that hashes in modified versions file match reference file
    errors = defaultdict(list)
    for verfile in version_files:
      version, hashes = parse_versions_file("reading modified versions file",
                                            api, api.context.cwd.join(verfile))

      if version != ref_version:
        errors[verfile].append(
            "FIT tool versions don't match (ref: %s  ours: %s)" %
            (version, ref_version))

      for blobname, sha256 in hashes.items():
        if blobname not in ref_hashes:
          errors[verfile].append("file '%s' not in reference versions file" %
                                 blobname)
        elif ref_hashes[blobname] != sha256:
          errors[verfile].append(
              "hash for '%s' doesn't match ('%s... != '%s...')" %
              (blobname, sha256[:8], ref_hashes[blobname][:8]))

    # Format error message if needed
    if errors:
      message = "Error(s) occurred when checking FIT image versions:"

      for fname, errlist in errors.items():
        message += "\n"
        message += "  %s:" % fname
        for line in errlist:
          message += "    " + line + "\n"

      comment_and_quit(message)

  # success


def mock_fit_header(version):
  """Mock the header from the FIT tool with given version"""
  return \
"""
===============================================================================
Intel (R) Flash Image Tool. Version: %s
Copyright (c) 2013 - 2020, Intel Corporation. All rights reserved.
7/29/2020 - 4:31:58 pm
===============================================================================




Program terminated.
-------------------
""" % version


def mock_version_file(version="14.0.40.1206", hashes={}):
  """Mock version file contents

  Args:
    version (str): optional version string to put in FIT header
    hashes (dict): file => sha256 values to override/add to file

  Return:
    version file contents as string
  """
  contents = mock_fit_header(version)

  file_hashes = {
      "me.bin":
          "2a8c638dcda84fb63fa25e50014dc904d1d4a9a3687c39aefc9fcc9628db67b1",
      "pchc.bin":
          "aea20cd7543c5be16bd85d2922b83ab0596f89e3649827bf98a56ac5dc3abace",
      "pmc.bin":
          "266a4a9b993cc503ceccf959b2061a5603ab7131fb3509f363e5d22e83e4aa87",
      "oem_km.bin":
          "fe8a9636055dc5b6eba9bcac99092d6bacc8e38e4338ff64635ec07630711014",
      "fit":
          "b729d22e7107f13a043f23bded067027438d02abbc084705a73158e3eba9a1d9",
      "meu":
          "83bf2329475611ae67016f17a3970434f416a4c5e512df0040616718ba982c41",
      "vsccommn.bin":
          "09dfa9ee3f4ab4fcc8b86f71d5a10b1ac7118127a2f4f55695add1d631a80315",
  }
  file_hashes.update(hashes)

  for fname, sha256 in file_hashes.items():
    contents += "%s  %s\n" % (sha256, fname)
  return contents


def GenTests(api):

  def properties_dict(extra_props={}):
    """Returns a dict of basic valid properties, updated with extra_props."""
    props = {'csme_ref_path': 'some/path/to/ref.txt'}
    props.update(extra_props)
    return props

  def test_build():
    """Generate test build definition"""
    return api.test_util.test_build(cq=True).build

  def set_gerrit_changes(step_name, files):
    """Mock gerrit changes with given file list"""
    return api.gerrit.set_gerrit_fetch_changes_response(
        step_name=step_name, changes=[
            common_pb2.GerritChange(host='chromium-review.googlesource.com',
                                    project='project', patchset=7,
                                    change=123456)
        ], values_dict={
            123456: {
                'files': {
                    fname: {
                        'status': 'M',
                        'size_delta': 0,
                        'size': 0
                    } for fname in files
                }
            }
        })

  yield api.test(
      'basic',
      api.properties(**properties_dict()),
      test_build(),
      set_gerrit_changes(
          "", ["blobs/fitimage-test.bin", "blobs/fitimage-test-versions.txt"]),
      api.step_data("reading reference file",
                    api.file.read_text(mock_version_file())),
      api.step_data("reading modified versions file",
                    api.file.read_text(mock_version_file())),
      api.post_process(post_process.StatusSuccess),
  )

  yield api.test(
      'non_match_hashes', api.properties(**properties_dict()), test_build(),
      set_gerrit_changes(
          "", ["blobs/fitimage-test.bin", "blobs/fitimage-test-versions.txt"]),
      api.step_data("reading reference file",
                    api.file.read_text(mock_version_file())),
      api.step_data(
          "reading modified versions file",
          api.file.read_text(
              mock_version_file(
                  hashes={
                      "pchc.bin":
                          "2f93215a5141aa29f21b55d7a2684316647f0526e7416808a6d3447099d75104"
                  }))),
      api.post_process(post_process.ResultReasonRE,
                       "Error\(s\) occurred when checking FIT image versions:"))

  yield api.test(
      'no_version_information_in_ref', api.properties(**properties_dict()),
      test_build(),
      set_gerrit_changes(
          "", ["blobs/fitimage-test.bin", "blobs/fitimage-test-versions.txt"]),
      api.step_data("reading reference file",
                    api.file.read_text(mock_version_file(""))),
      api.post_process(post_process.ResultReasonRE,
                       "FIT version information not found in"))

  yield api.test(
      'no_version_information_in_input', api.properties(**properties_dict()),
      test_build(),
      set_gerrit_changes(
          "", ["blobs/fitimage-test.bin", "blobs/fitimage-test-versions.txt"]),
      api.step_data("reading reference file",
                    api.file.read_text(mock_version_file())),
      api.step_data(
          "reading modified versions file",
          api.file.read_text(
              mock_version_file(
                  version="", hashes={
                      "pchc.bin":
                          "2f93215a5141aa29f21b55d7a2684316647f0526e7416808a6d3447099d75104"
                  }))),
      api.post_process(post_process.ResultReasonRE,
                       "FIT version information not found in"))

  yield api.test(
      'no_matching_bin_change',
      api.properties(**properties_dict()), test_build(),
      set_gerrit_changes("", ["blobs/fitimage-test-versions.txt"]),
      api.post_process(post_process.ResultReasonRE,
                       "does not have a matching change to .bin"))

  yield api.test(
      'no_matching_version_change', api.properties(**properties_dict()),
      test_build(), set_gerrit_changes("", ["blobs/fitimage-test.bin"]),
      api.post_process(post_process.ResultReasonRE,
                       "does not have a matching change to -versions.txt"))

  yield api.test(
      'mismatched_versions', api.properties(**properties_dict()), test_build(),
      set_gerrit_changes(
          "", ["blobs/fitimage-test.bin", "blobs/fitimage-test-versions.txt"]),
      api.step_data("reading reference file",
                    api.file.read_text(mock_version_file("14.1.2.2"))),
      api.step_data(
          "reading modified versions file",
          api.file.read_text(
              mock_version_file(
                  version="14.1.2.3", hashes={
                      "pchc.bin":
                          "2f93215a5141aa29f21b55d7a2684316647f0526e7416808a6d3447099d75104"
                  }))),
      api.post_process(post_process.ResultReasonRE,
                       "FIT tool versions don't match"))

  yield api.test(
      'file_not_in_reference', api.properties(**properties_dict()),
      test_build(),
      set_gerrit_changes(
          "", ["blobs/fitimage-test.bin", "blobs/fitimage-test-versions.txt"]),
      api.step_data("reading reference file",
                    api.file.read_text(mock_version_file())),
      api.step_data(
          "reading modified versions file",
          api.file.read_text(
              mock_version_file(
                  hashes={
                      "some_file":
                          "99081120082572661c06113483d122c80ae0aed8c05e304ad4141a7a84a4b0df"
                  }))),
      api.post_process(post_process.ResultReasonRE,
                       "not in reference versions file"))
