# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for creating pre-release CL for ChromiumIDE."""

from RECIPE_MODULES.chromeos.gerrit.api import Label

from PB.recipes.chromeos.chromium_ide_pre_release import (
    ChromiumIDEPreReleaseProperties)
from recipe_engine import post_process
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'recipe_engine/url',
    'build_menu',
    'cros_source',
    'src_state',
    'gerrit',
    'git',
    'repo',
]

PROPERTIES = ChromiumIDEPreReleaseProperties


def RunSteps(api: RecipeApi, properties: ChromiumIDEPreReleaseProperties):
  nodebinpath = ''
  with api.step.nest('setup nodejs environment'):
    nvmroot = api.path.mkdtemp('nvm')
    with api.step.nest('install nvm'):
      api.git.clone('https://github.com/nvm-sh/nvm.git', nvmroot)
      with api.context(cwd=nvmroot, env={'NVM_DIR': nvmroot}):
        api.git.checkout('v0.39.7')
        api.step('install node', ['sh', '-c', '. ./nvm.sh && nvm install 18'])
      version = api.step('locating node version',
                         ['ls', nvmroot.join('versions/node')],
                         stdout=api.raw_io.output_text()).stdout.strip()
    nodebinpath = nvmroot.join('versions/node').join(version).join('bin')

  with api.context(
      env={'PATH': api.path.pathsep.join([str(nodebinpath), '%(PATH)s'])}):
    api.step('verify node installation', ['node', '-v'])
    api.step('verify npm installation', ['npm', 'version'])

    commit = api.src_state.gitiles_commit
    if not commit.project:
      commit = api.src_state.internal_manifest.as_gitiles_commit_proto
    with api.build_menu.configure_builder(missing_ok=True, commit=commit):
      with api.build_menu.setup_workspace():
        project_dir = api.cros_source.workspace_path.join(
            'infra/ide/chromiumide')

        with api.context(cwd=project_dir):
          project_info = api.repo.project_info()
          # git pull again to avoid commit-race during long repo sync.
          with api.step.nest('ensure up-to-date IDE repo'):
            api.git.fetch(project_info.remote, ['main'])
            api.git.checkout('%s/main' % (project_info.remote))
          before_bump = api.git.head_commit()

          api.repo.start('release', projects=[project_info.name])

          api.step('npm ci', ['npm', 'ci'])

          api.step('release update', [
              './release.sh', 'update', '--pre-release', '--extra-message',
              'Generated by: '
              f'https://cr-buildbucket.appspot.com/build/{api.buildbucket.build.id}'
          ], stdout=api.raw_io.output_text())

          api.step('verify with npm t', ['npm', 't'])

          reviewers = []
          for reviewer in properties.reviewers:
            reviewers.append(reviewer)
          for oncall in properties.reviewer_oncalls:
            rotation = api.url.get_json(
                'https://chrome-ops-rotation-proxy.appspot.com/current/%s' %
                (oncall), step_name='Get oncaller of %s' % (oncall)).output
            reviewers = reviewers + rotation['emails']

          change = api.gerrit.create_change(
              'chromiumos/infra/ide', reviewers=reviewers,
              topic='chromium-ide-pre-release-update')
          api.gerrit.set_change_labels_remote(change, {
              Label.VERIFIED: 1,
              Label.BOT_COMMIT: 1
          })
          api.gerrit.submit_change(change)

          # It is possible another commit is submitted during the stage.
          # We checkout to the submitted commits and run npm t again for
          # verification.
          # This is important before publishing a prerelease automatically.
          with api.step.nest('verify update post submit'):
            with api.step.nest('checkout to bump commit'):
              api.git.fetch(project_info.remote, ['main'])
              api.git.checkout('%s/main' % (project_info.remote))
              after_bump = api.git.head_commit()
              bump_commit = None
              commits = api.git.log(before_bump, after_bump)
              for commit in commits:
                if 'Bump the version' in commit.message:
                  bump_commit = commit.rev
              if not bump_commit:
                raise api.step.StepFailure('cannot find bump commit.')
              api.git.checkout(bump_commit)
            api.step('npm t', ['npm', 't'])

          with api.context(
              env={'FETCH_IDE_RELEASE_CREDENTIALS_FROM_GCLOUD': '1'}):
            api.step('publish prerelease',
                     ['./release.sh', 'publish', '--pre-release'])



def GenTests(api: RecipeTestApi):
  yield api.test(
      'success',
      api.properties(
          ChromiumIDEPreReleaseProperties(
              reviewers=['oka@chromium.org'],
              reviewer_oncalls=['oncallator:ide_onduty'])),
      api.step_data('npm ci', retcode=0),
      api.step_data('release update', retcode=0),
      api.path.exists(api.src_state.workspace_path),
      api.step_data('verify with npm t', retcode=0),
      api.url.json('Get oncaller of oncallator:ide_onduty',
                   {'emails': ['fqj@google.com']}),
      api.gerrit.simulated_create_change(
          'create gerrit change for chromiumos/infra/ide',
          'https://chromium-review.googlesource.com/c/chromiumos/infra/ide/+/123'
      ),
      api.post_check(post_process.MustRun, 'npm ci'),
      api.post_check(post_process.MustRun, 'release update'),
      api.post_check(post_process.MustRun, 'verify with npm t'),
      api.post_check(post_process.MustRun, 'set labels on CL 123'),
      api.post_check(post_process.MustRun, 'submit CL 123'),
      api.step_data(
          'verify update post submit.checkout to bump commit.git log',
          stdout=api.raw_io.output_text(
              'deaddeaddeadbeefdeadbeefdeadbeefdeadbeef\x1FBump the version\x00'
          )),
      api.post_check(post_process.MustRun, 'verify update post submit.npm t'),
      api.post_check(post_process.MustRun, 'publish prerelease'),
  )

  yield api.test(
      'fail_npm_ci',
      api.properties(
          ChromiumIDEPreReleaseProperties(reviewers=['oka@chromium.org'])),
      api.step_data('npm ci', retcode=1),
      api.post_check(post_process.StepFailure, 'npm ci'),
      api.post_check(post_process.DoesNotRun, 'release update'),
      api.post_check(post_process.DoesNotRun, 'verify with npm t'),
      api.post_check(post_process.DoesNotRun,
                     'create gerrit change for chromiumos/infra/ide'),
      api.post_check(post_process.DoesNotRunRE, r'set labels on CL .*'),
      api.post_check(post_process.DoesNotRunRE, 'submit CL .*'),
      api.post_check(post_process.DoesNotRunRE, 'verify update post submit.*'),
      api.post_check(post_process.DoesNotRun, 'publish prerelease'),
      api.expect_status('FAILURE'),
  )

  yield api.test(
      'fail_release_update',
      api.properties(
          ChromiumIDEPreReleaseProperties(reviewers=['oka@chromium.org'])),
      api.step_data('npm ci', retcode=0),
      api.step_data('release update', retcode=1),
      api.post_check(post_process.StepFailure, 'release update'),
      api.post_check(
          post_process.DoesNotRun,
          'submit change.create gerrit change for chromiumos/infra/ide'),
      api.post_check(post_process.DoesNotRun, 'verify with npm t'),
      api.post_check(post_process.DoesNotRunRE,
                     r'submit change.set labels on CL .*'),
      api.post_check(post_process.DoesNotRunRE, 'submit change.submit CL .*'),
      api.post_check(post_process.DoesNotRunRE, 'verify update post submit.*'),
      api.post_check(post_process.DoesNotRun, 'publish prerelease'),
      api.expect_status('FAILURE'),
  )

  yield api.test(
      'fail_npm_t',
      api.properties(
          ChromiumIDEPreReleaseProperties(reviewers=['oka@chromium.org'])),
      api.step_data('npm ci', retcode=0),
      api.step_data('release update', retcode=0),
      api.path.exists(api.src_state.workspace_path),
      api.step_data('verify with npm t', retcode=1),
      api.post_check(
          post_process.DoesNotRun,
          'submit change.create gerrit change for chromiumos/infra/ide'),
      api.post_check(post_process.DoesNotRunRE, 'set labels on CL.*'),
      api.post_check(post_process.DoesNotRunRE, 'submit CL .*'),
      api.post_check(post_process.DoesNotRunRE, 'verify update post submit.*'),
      api.post_check(post_process.DoesNotRun, 'publish prerelease'),
      api.expect_status('FAILURE'),
  )

  yield api.test(
      'fail_post_submit_checkout',
      api.properties(
          ChromiumIDEPreReleaseProperties(
              reviewers=['oka@chromium.org'],
              reviewer_oncalls=['oncallator:ide_onduty'])),
      api.step_data('npm ci', retcode=0),
      api.step_data('release update', retcode=0),
      api.path.exists(api.src_state.workspace_path),
      api.step_data('verify with npm t', retcode=0),
      api.url.json('Get oncaller of oncallator:ide_onduty',
                   {'emails': ['fqj@google.com']}),
      api.gerrit.simulated_create_change(
          'create gerrit change for chromiumos/infra/ide',
          'https://chromium-review.googlesource.com/c/chromiumos/infra/ide/+/123'
      ),
      api.post_check(post_process.MustRun, 'npm ci'),
      api.post_check(post_process.MustRun, 'release update'),
      api.post_check(post_process.MustRun, 'verify with npm t'),
      api.post_check(post_process.MustRun, 'set labels on CL 123'),
      api.post_check(post_process.MustRun, 'submit CL 123'),
      api.step_data(
          'verify update post submit.checkout to bump commit.git log',
          stdout=api.raw_io.output_text(
              'deaddeaddeadbeefdeadbeefdeadbeefdeadbeef\x1FAdd feature X\x00')),
      api.post_check(post_process.DoesNotRun,
                     'verify update post submit.npm t'),
      api.post_check(post_process.DoesNotRun, 'publish prerelease'),
      api.expect_status('FAILURE'),
  )

  yield api.test(
      'fail_post_submit_npm_t',
      api.properties(
          ChromiumIDEPreReleaseProperties(
              reviewers=['oka@chromium.org'],
              reviewer_oncalls=['oncallator:ide_onduty'])),
      api.step_data('npm ci', retcode=0),
      api.step_data('release update', retcode=0),
      api.path.exists(api.src_state.workspace_path),
      api.step_data('verify with npm t', retcode=0),
      api.step_data('verify update post submit.npm t', retcode=1),
      api.url.json('Get oncaller of oncallator:ide_onduty',
                   {'emails': ['fqj@google.com']}),
      api.gerrit.simulated_create_change(
          'create gerrit change for chromiumos/infra/ide',
          'https://chromium-review.googlesource.com/c/chromiumos/infra/ide/+/123'
      ),
      api.post_check(post_process.MustRun, 'npm ci'),
      api.post_check(post_process.MustRun, 'release update'),
      api.post_check(post_process.MustRun, 'verify with npm t'),
      api.post_check(post_process.MustRun, 'set labels on CL 123'),
      api.post_check(post_process.MustRun, 'submit CL 123'),
      api.step_data(
          'verify update post submit.checkout to bump commit.git log',
          stdout=api.raw_io.output_text(
              'deaddeaddeadbeefdeadbeefdeadbeefdeadbeef\x1FBump the version\x00'
          )),
      api.post_check(post_process.MustRun, 'verify update post submit.npm t'),
      api.post_check(post_process.DoesNotRun, 'publish prerelease'),
      api.expect_status('FAILURE'),
  )
