# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for creating pre-release CL for ChromiumIDE."""

from RECIPE_MODULES.chromeos.gerrit.api import Label

from PB.recipes.chromeos.chromium_ide_pre_release import (
    ChromiumIDEPreReleaseProperties)
from recipe_engine import post_process
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'recipe_engine/url',
    'build_menu',
    'cros_source',
    'src_state',
    'gerrit',
    'git',
    'repo',
]

PROPERTIES = ChromiumIDEPreReleaseProperties


def RunSteps(api: RecipeApi, properties: ChromiumIDEPreReleaseProperties):
  nodebinpath = ''
  with api.step.nest('setup nodejs environment'):
    nvmroot = api.path.mkdtemp('nvm')
    with api.step.nest('install nvm'):
      api.git.clone('https://github.com/nvm-sh/nvm.git', nvmroot)
      with api.context(cwd=nvmroot, env={'NVM_DIR': nvmroot}):
        api.git.checkout('v0.39.7')
        api.step('install node', ['sh', '-c', '. ./nvm.sh && nvm install 18'])
      version = api.step('locating node version',
                         ['ls', nvmroot.join('versions/node')],
                         stdout=api.raw_io.output_text()).stdout.strip()
    nodebinpath = nvmroot.join('versions/node').join(version).join('bin')

  with api.context(
      env={'PATH': api.path.pathsep.join([str(nodebinpath), '%(PATH)s'])}):
    api.step('verify node installation', ['node', '-v'])
    api.step('verify npm installation', ['npm', 'version'])

    commit = api.src_state.gitiles_commit
    if not commit.project:
      commit = api.src_state.internal_manifest.as_gitiles_commit_proto
    with api.build_menu.configure_builder(missing_ok=True, commit=commit):
      with api.build_menu.setup_workspace():
        project_dir = api.cros_source.workspace_path.join(
            'infra/ide/chromiumide')

        with api.context(cwd=project_dir):
          project_info = api.repo.project_info()

          api.repo.start('release', projects=[project_info.name])

          api.step('npm ci', ['npm', 'ci'])

          api.step('release update', [
              './release.sh', 'update', '--pre-release', '--extra-message',
              'Generated by: '
              f'https://cr-buildbucket.appspot.com/build/{api.buildbucket.build.id}'
          ], stdout=api.raw_io.output_text())

          test_passed = 1
          with api.step.nest('verify update') as pres:
            try:
              api.step('npm t', ['npm', 't'])
            except api.step.StepFailure:
              test_passed = -1

            pres.properties['test_passed'] = test_passed

          reviewers = []
          for reviewer in properties.reviewers:
            reviewers.append(reviewer)
          for oncall in properties.reviewer_oncalls:
            rotation = api.url.get_json(
                'https://chrome-ops-rotation-proxy.appspot.com/current/%s' %
                (oncall), step_name='Get oncaller of %s' % (oncall)).output
            reviewers = reviewers + rotation['emails']

          with api.step.nest('upload change') as pres:
            change = api.gerrit.create_change(
                'chromiumos/infra/ide', reviewers=reviewers,
                topic='chromium-ide-pre-release-update')
            pres.properties[
                'applied labels'] = api.gerrit.set_change_labels_remote(
                    change, {Label.VERIFIED: test_passed})


def GenTests(api: RecipeTestApi):
  yield api.test(
      'success',
      api.properties(
          ChromiumIDEPreReleaseProperties(
              reviewers=['oka@chromium.org'],
              reviewer_oncalls=['oncallator:ide_onduty'])),
      api.step_data('npm ci', retcode=0),
      api.step_data('release update', retcode=0),
      api.path.exists(api.src_state.workspace_path),
      api.step_data('verify update.npm t', retcode=0),
      api.url.json('Get oncaller of oncallator:ide_onduty',
                   {'emails': ['fqj@google.com']}),
      api.gerrit.simulated_create_change(
          'upload change.create gerrit change for chromiumos/infra/ide',
          'https://chromium-review.googlesource.com/c/chromiumos/infra/ide/+/123'
      ),
      api.post_check(post_process.MustRun, 'npm ci'),
      api.post_check(post_process.MustRun, 'release update'),
      api.post_check(post_process.MustRun, 'verify update.npm t'),
      api.post_check(post_process.MustRun,
                     'upload change.set labels on CL 123'),
      api.post_check(post_process.PropertyEquals, 'applied labels',
                     '{"labels": {"Verified": 1}}'),
  )

  yield api.test(
      'fail_npm_ci',
      api.properties(
          ChromiumIDEPreReleaseProperties(reviewers=['oka@chromium.org'])),
      api.step_data('npm ci', retcode=1),
      api.post_check(post_process.StepFailure, 'npm ci'),
      api.post_check(post_process.DoesNotRun, 'release update'),
      api.post_check(post_process.DoesNotRun, 'verify update.npm t'),
      api.post_check(
          post_process.DoesNotRun,
          'upload change.create gerrit change for chromiumos/infra/ide'),
      api.post_check(post_process.DoesNotRunRE,
                     r'upload change.set labels on CL .*'),
      api.expect_status('FAILURE'),
  )

  yield api.test(
      'fail_release_update',
      api.properties(
          ChromiumIDEPreReleaseProperties(reviewers=['oka@chromium.org'])),
      api.step_data('npm ci', retcode=0),
      api.step_data('release update', retcode=1),
      api.post_check(post_process.StepFailure, 'release update'),
      api.post_check(
          post_process.DoesNotRun,
          'upload change.create gerrit change for chromiumos/infra/ide'),
      api.post_check(post_process.DoesNotRun, 'verify update.npm t'),
      api.post_check(post_process.DoesNotRunRE,
                     r'upload change.set labels on CL .*'),
      api.expect_status('FAILURE'),
  )

  yield api.test(
      'fail_npm_t',
      api.properties(
          ChromiumIDEPreReleaseProperties(reviewers=['oka@chromium.org'])),
      api.step_data('npm ci', retcode=0),
      api.step_data('release update', retcode=0),
      api.path.exists(api.src_state.workspace_path),
      api.step_data('verify update.npm t', retcode=1),
      api.gerrit.simulated_create_change(
          'upload change.create gerrit change for chromiumos/infra/ide',
          'https://chromium-review.googlesource.com/c/chromiumos/infra/ide/+/123'
      ),
      api.post_check(post_process.MustRun,
                     'upload change.set labels on CL 123'),
      api.post_check(post_process.PropertyEquals, 'applied labels',
                     '{"labels": {"Verified": -1}}'),
  )
