# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for creating pre-release CL for ChromiumIDE."""

from RECIPE_MODULES.chromeos.gerrit.api import Label

from PB.recipes.chromeos.chromium_ide_pre_release import (
    ChromiumIDEPreReleaseProperties)
from recipe_engine import post_process
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'build_menu',
    'cros_source',
    'src_state',
    'gerrit',
]

PROPERTIES = ChromiumIDEPreReleaseProperties


def RunSteps(api: RecipeApi, properties: ChromiumIDEPreReleaseProperties):
  commit = api.src_state.gitiles_commit
  if not commit.project:
    commit = api.src_state.internal_manifest.as_gitiles_commit_proto

  with api.build_menu.configure_builder(missing_ok=True, commit=commit):
    project_dir = api.cros_source.workspace_path.join(
        'chromite/ide_tooling/chromiumide/src')
    with api.context(cwd=project_dir):
      api.step('npm ci', [
          'npm',
          'ci',
      ], stdout=api.raw_io.output_text())

      api.step('release update', [
          './release.sh', 'update', '--pre-release', '--extra-message',
          '"Generated by: '
          f'https://cr-buildbucket.appspot.com/build/{api.buildbucket.build.id}"'
      ], stdout=api.raw_io.output_text())

      change = api.gerrit.create_change('chromiumos/chromite',
                                        reviewers=properties.reviewers,
                                        topic='chromium-ide-pre-release-update')

      with api.step.nest('verify update') as pres:
        test_passed = 1
        try:
          api.step('npm t', [
              'npm',
              't',
          ], stdout=api.raw_io.output_text())
        except api.step.StepFailure:
          test_passed = -1

        pres.properties['applied labels'] = api.gerrit.set_change_labels_remote(
            change, {Label.VERIFIED: test_passed})


def GenTests(api: RecipeTestApi):
  yield api.test(
      'success',
      api.properties(
          ChromiumIDEPreReleaseProperties(reviewers=['oka@chromium.org'])),
      api.step_data('npm ci', retcode=0),
      api.step_data('release update', retcode=0),
      api.path.exists(api.src_state.workspace_path),
      api.gerrit.simulated_create_change(
          'create gerrit change for chromiumos/chromite',
          'https://chromium-review.googlesource.com/c/chromiumos/chromite/+/123'
      ), api.step_data('verify update.npm t', retcode=0),
      api.post_check(post_process.MustRun, 'npm ci'),
      api.post_check(post_process.MustRun, 'release update'),
      api.post_check(post_process.MustRun,
                     'create gerrit change for chromiumos/chromite'),
      api.post_check(post_process.MustRun, 'verify update.npm t'),
      api.post_check(post_process.MustRun,
                     'verify update.set labels on CL 123'),
      api.post_check(post_process.PropertyEquals, 'applied labels',
                     '{"labels": {"Verified": 1}}'))

  yield api.test(
      'fail_npm_ci',
      api.properties(
          ChromiumIDEPreReleaseProperties(reviewers=['oka@chromium.org'])),
      api.step_data('npm ci', retcode=1),
      api.post_check(post_process.StepFailure, 'npm ci'),
      api.post_check(post_process.DoesNotRun, 'release update'),
      api.post_check(post_process.DoesNotRun,
                     'create gerrit change for chromiumos/chromite'),
      api.post_check(post_process.DoesNotRun, 'verify update.npm t'),
      api.post_check(post_process.DoesNotRunRE,
                     r'verify update.set labels on CL .*'),
      api.expect_status('FAILURE'),
  )

  yield api.test(
      'fail_release_update',
      api.properties(
          ChromiumIDEPreReleaseProperties(reviewers=['oka@chromium.org'])),
      api.step_data('npm ci', retcode=0),
      api.step_data('release update', retcode=1),
      api.post_check(post_process.StepFailure, 'release update'),
      api.post_check(post_process.DoesNotRun,
                     'create gerrit change for chromiumos/chromite'),
      api.post_check(post_process.DoesNotRun, 'verify update.npm t'),
      api.post_check(post_process.DoesNotRunRE,
                     r'verify update.set labels on CL .*'),
      api.expect_status('FAILURE'),
  )

  yield api.test(
      'fail_npm_t',
      api.properties(
          ChromiumIDEPreReleaseProperties(reviewers=['oka@chromium.org'])),
      api.step_data('npm ci', retcode=0),
      api.step_data('release update', retcode=0),
      api.path.exists(api.src_state.workspace_path),
      api.gerrit.simulated_create_change(
          'create gerrit change for chromiumos/chromite',
          'https://chromium-review.googlesource.com/c/chromiumos/chromite/+/123'
      ), api.step_data('verify update.npm t', retcode=1),
      api.post_check(post_process.MustRun,
                     'create gerrit change for chromiumos/chromite'),
      api.post_check(post_process.MustRun,
                     'verify update.set labels on CL 123'),
      api.post_check(post_process.PropertyEquals, 'applied labels',
                     '{"labels": {"Verified": -1}}'))
