# -*- coding: utf-8 -*-
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from PB.recipes.chromeos import cipd_uprev
from recipe_engine import post_process
from recipe_engine.recipe_api import StepFailure

DEPS = [
    'recipe_engine/cipd',
    'recipe_engine/properties',
    'recipe_engine/step',
    'recipe_engine/time',
]

PROPERTIES = cipd_uprev.Properties

_RECIPE_CIPD_PACKAGE = (
    'infra/recipe_bundles/chromium.googlesource.com/chromiumos/infra/recipes')
_GO_BINARY_CIPD_PACKAGE_PATTERN = 'chromiumos/infra/%s/linux-amd64'
_CTP_GO_BINARIES = ['cros_test_platform', 'phosphorus']
_CI_GO_BINARIES = [
    'branch_util',
    'build_plan_generator',
    'manifest_doctor',
    'setup_project',
    'test_plan_generator',
    'pointless_build_checker',
    'version_bumper',
]

_CTP_RELEASE_VERSION_TAG = 'ctp_release_version'
_CI_RELEASE_VERSION_TAG = 'ci_release_version'


def validate(api, instruction):
  """Validate instructions for uprevving a specific package.

  Args:
    * instruction (cipd_uprev.Instruction): A complete set of args for
      `cipd set-ref`.
  Raises:
    A ValueError if validation fails.
  """
  with api.step.nest('validate package instructions'):
    if not instruction.ref:
      raise StepFailure('No ref to update for package %s' %
                        instruction.package_name)
    if not instruction.version:
      raise StepFailure('No new version provided for package %s' %
                        instruction.package_name)
    package_passlist = _package_passlist()
    if not instruction.package_name in package_passlist:
      raise StepFailure(
          'Invalid package %s - only the following packages are allowed: %s' %
          (instruction.package_name, package_passlist))


def _package_passlist():
  """Get a list of packages supported by this recipe.

    The actual packages that the recipe will /attempt/ to uprev comes from
    properties (as set in infra/config).
    The recipe will ignore any passed packages that are not in the allowlist
    generated by this function.

  Returns:
    list[str]
  """
  return (
      [_RECIPE_CIPD_PACKAGE] +
      [_GO_BINARY_CIPD_PACKAGE_PATTERN % name for name in _CTP_GO_BINARIES] +
      [_GO_BINARY_CIPD_PACKAGE_PATTERN % name for name in _CI_GO_BINARIES])


def get_current_instance(api, instruction):
  """Get the current version of the ref.

  Args:
    * instruction (cipd_uprev.Instruction): A complete set of args for
      `cipd set-ref`.
  Returns:
    cipd_uprev.Instance
  Raises:
    A StepFailure if the CIPD tool call fails.
  """
  with api.step.nest('get instance ID of package "%s" with ref "%s"' %
                     (instruction.package_name, instruction.ref)):
    instance_id = api.cipd.describe(package_name=instruction.package_name,
                                    version=instruction.ref).pin.instance_id
    return cipd_uprev.PackageInstance(package_name=instruction.package_name,
                                      id=instance_id)


def _release_version_tag(package_name):
  ci_packages = [_GO_BINARY_CIPD_PACKAGE_PATTERN % x for x in _CI_GO_BINARIES]
  if package_name in ci_packages:
    return (_CI_RELEASE_VERSION_TAG, 'ci_{}')
  # CTP is the default because it is the orginal use case.
  return (_CTP_RELEASE_VERSION_TAG, 'ctp_{}')


def uprev_package(api, instruction, package_tags=None):
  """Change CIPD ref of a package according to the instructions.

  Args:
    * instruction (cipd_uprev.Instruction): A complete set of args for
      `cipd set-ref`.
    * package_tags: Tags to add to the package.
  Returns:
    cipd_uprev.Instance
  Raises:
    A StepFailure if the CIPD tool call fails.
  """
  package_tags = package_tags or {}
  with api.step.nest(
      'uprev the "%s" ref of the "%s" package to "%s"' %
      (instruction.ref, instruction.package_name, instruction.version)):
    for tag_key, tag_value in package_tags.items():
      api.cipd.set_tag(instruction.package_name, instruction.version,
                       {tag_key: tag_value})
    instance_id = api.cipd.set_ref(instruction.package_name,
                                   instruction.version,
                                   [instruction.ref]).instance_id
    return cipd_uprev.PackageInstance(package_name=instruction.package_name,
                                      id=instance_id)


def RunSteps(api, properties):
  release_tag_time = api.time.utcnow().isoformat()
  for instruction in properties.config.instructions:
    with api.step.nest('package %s' % instruction.package_name):
      validate(api, instruction)
      properties.response.old_versions.extend(
          [get_current_instance(api, instruction)])
      package_tags = {}
      if properties.config.tag_release_version:
        release_tag_key, release_tag_value = _release_version_tag(
            instruction.package_name)
        package_tags[release_tag_key] = release_tag_value.format(
            release_tag_time)
      properties.response.new_versions.extend(
          [uprev_package(api, instruction, package_tags)])


def GenTests(api):
  yield api.test(
      'basic without release tagging',
      api.properties(
          cipd_uprev.Properties(
              config=cipd_uprev.Config(instructions=[
                  cipd_uprev.Instruction(
                      package_name='chromiumos/infra/phosphorus/linux-amd64',
                      ref='foo-phosphorus-ref',
                      version='foo-phosphorus-version'),
                  cipd_uprev.Instruction(
                      package_name='infra/recipe_bundles/chromium.googlesource.com/chromiumos/infra/recipes',
                      ref='foo-recipe-ref', version='foo-recipe-version'),
              ]))),
  )

  yield api.test(
      'basic with release tagging',
      api.time.seed(123),
      api.properties(
          cipd_uprev.Properties(
              config=cipd_uprev.Config(
                  instructions=[
                      cipd_uprev.Instruction(
                          package_name='chromiumos/infra/phosphorus/linux-amd64',
                          ref='foo-phosphorus-ref',
                          version='foo-phosphorus-version'),
                      cipd_uprev.Instruction(
                          package_name='infra/recipe_bundles/chromium.googlesource.com/chromiumos/infra/recipes',
                          ref='foo-recipe-ref', version='foo-recipe-version'),
                  ], tag_release_version=True))),
  )

  yield api.test(
      'CI packages with release tagging',
      api.time.seed(123),
      api.properties(
          cipd_uprev.Properties(
              config=cipd_uprev.Config(
                  instructions=[
                      cipd_uprev.Instruction(
                          package_name='chromiumos/infra/version_bumper/linux-amd64',
                          ref='foo-version_bumper-ref',
                          version='foo-version_bumper-version'),
                  ], tag_release_version=True))),
  )

  yield api.test(
      'missing ref',
      api.properties(
          cipd_uprev.Properties(
              config=cipd_uprev.Config(instructions=[
                  cipd_uprev.Instruction(
                      package_name='chromiumos/infra/phosphorus/linux-amd64',
                      version='foo-version')
              ]))),
      api.post_check(
          post_process.StepFailure,
          'package chromiumos/infra/phosphorus/linux-amd64.validate package instructions'
      ),
  )

  yield api.test(
      'missing version',
      api.properties(
          cipd_uprev.Properties(
              config=cipd_uprev.Config(instructions=[
                  cipd_uprev.Instruction(
                      package_name='chromiumos/infra/phosphorus/linux-amd64',
                      ref='foo-ref')
              ]))),
      api.post_check(
          post_process.StepFailure,
          'package chromiumos/infra/phosphorus/linux-amd64.validate package instructions'
      ),
  )

  yield api.test(
      'invalid package',
      api.properties(
          cipd_uprev.Properties(
              config=cipd_uprev.Config(instructions=[
                  # Valid package first to make sure it still succeeds.
                  cipd_uprev.Instruction(
                      package_name='chromiumos/infra/version_bumper/linux-amd64',
                      ref='foo-version_bumper-ref',
                      version='foo-version_bumper-version'),
                  cipd_uprev.Instruction(package_name='invalid-package',
                                         ref='foo-ref', version='foo-version')
              ]))),
      api.post_check(post_process.StepSuccess,
                     'package chromiumos/infra/version_bumper/linux-amd64'),
      api.post_check(post_process.StepFailure,
                     'package invalid-package.validate package instructions'),
  )
