// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.cl_factory;

message ClFactoryProperties {
  // Regex specifying repos to operate on. The matching is the same
  // as in `repo forall --regex regexes...`, for example,
  // 'src/project/galaxy' will match all galaxy projects.
  repeated string repo_regexes = 1;

  // TODO: WIP, figure out approach.
  // Command to execute on the repos to create the CL.
  string command = 2;

  // Template for forming commit messages. Variables interpolated in the
  // template include:
  //
  //   project - the name of the project
  //   path    - the path within the repo checkout to the project
  //   remote  - the gerrit instance for the project
  //
  // Interpolation is done with curly bracket syntax as in {project}.
  string message_template = 3;

  // Reviewers to add to the created CLs.
  repeated string reviewers = 4;

  // Hashtags to add to the created CLs.
  repeated string hashtags = 5;

  // Whether you want to force a full repo sync. Typically a targeted
  // sync of only the involved repos per repo_regexes should suffice.
  bool full_repo_sync = 6;

  // Message defining string replacements to perform.
  message ReplaceString {
    // File glob used to identify files to perform replacements in.
    // Glob rules for `file_glob` follow the same syntax as for
    // the `python-glob2` module, which supports '**' syntax.
    string file_glob = 1;

    // String to replace.
    string before = 2;

    // String to replace with.
    string after = 3;
  }

  // Indicates the string replacements to perform.
  repeated ReplaceString replace_strings = 8;
}
