// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.cl_factory;

import "go.chromium.org/luci/buildbucket/proto/common.proto";

message ClFactoryProperties {
  // Regex specifying repos to operate on. The matching is the same
  // as in `repo forall --regex regexes...`, for example,
  // 'src/project/galaxy' will match all galaxy projects.
  repeated string repo_regexes = 1;

  // TODO: WIP, figure out approach.
  // Command to execute on the repos to create the CL.
  string command = 2;

  // Template for forming commit messages. Variables interpolated in the
  // template include:
  //
  //   project - the name of the project
  //   path    - the path within the repo checkout to the project
  //   remote  - the gerrit instance for the project
  //
  // Interpolation is done with curly bracket syntax as in {project}.
  string message_template = 3;

  // Reviewers to add to the created CLs.
  repeated string reviewers = 4;

  // Hashtags to add to the created CLs.
  repeated string hashtags = 5;
}
