// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.dupit;

import "chromiumos/builder_config.proto";

message DupitProperties {
  // List of mirror sources.
  repeated Mirror mirrors = 1;

  // Google Storage URI to store the mirror at.
  string gs_uri = 2;

  // Ignore files that go missing during the synchronization process.
  bool ignore_missing_args = 3;

  // Filter out symlinks that do not point to a valid target.
  bool filter_missing_links = 4;

  // Regular expression representing additional files to be synced (if any.)
  string regex_for_archival_sync = 5;

  // Google Storage base URI to store files matching the archival sync regex.
  // regex_for_archival_sync must be set for this to have an effect.
  string gs_uri_for_archival_sync = 6;

  // Additional path element for archival sync. Is appended to
  // 'gs_uri_for_archival_sync' to create a full GS URI.
  // regex_for_archival_sync and gs_uri_for_archival_sync must be set for this
  // to have an effect.
  // The string will be formatted by datetime.utcnow().strftime(...) before
  // uploading.
  string path_datetime_for_archival_sync = 7;

  // Backfill the Google Storage topdir.
  // Due to GLEP-0075 the topdir needs to be backfilled for Gentoo mirrors
  // (b/302226413). This doesn't work for all distros (namely Arch Linux) so
  // the behavior is hidden behind this config flag.
  // Defaults to False.
  bool gs_topdir_backfill = 8;
}

message Mirror {
  // Rsync URI to mirror from.
  string uri = 1;

  // Rsync rate to limit synchronization at. (eg "50m")
  string rate = 2;
}
