# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe to fetch gardener related CLs.

For a gardener dashboard with up-to-date chrome uprev and LKGM commits status.
"""

from typing import Callable

import re
import base64
import datetime
import functools
from google.protobuf import json_format
from google.protobuf.message import Message

from PB.recipes.chromeos.gardener_data_collector import (
    GardenerDataResult, GardenerDataCollectorProperties, GerritQueryCondition)

from RECIPE_MODULES.chromeos.gerrit.api import ChangeInfo

from recipe_engine import recipe_api
from recipe_engine import post_process

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/file',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/resultdb',
    'recipe_engine/step',
    'recipe_engine/time',
    'easy',
    'gerrit',
    'gitiles',
    'pupr',
]

PROPERTIES = GardenerDataCollectorProperties

GITILES_HOST = 'chromium.googlesource.com'
GERRIT_HOST = 'https://chromium-review.googlesource.com'
DEFAULT_QUERY_AGE_DAYS = 7

CHROME_UPREV_REPO_PARAM = ('repo', 'chromiumos/overlays/chromiumos-overlay')
LKGM_REPO_PARAM = ('repo', 'chromium/src')
IGNORE_WIP_PARAM = ('-is', 'wip')

# Request messages (comments) to determine number of CQ tries.
COMMON_QUERY_O_PARAMS = ['MESSAGES', 'CURRENT_REVISION']
# Request also the modified files in the current revision for parsing the
# upreved Chrome version range.
CHROME_UPREV_QUERY_O_PARAMS = COMMON_QUERY_O_PARAMS + [
    'CURRENT_FILES', 'CURRENT_COMMIT'
]
# Request the full commit message in the current revision for parsing the
# upreved ChromeOS version range.
LKGM_QUERY_O_PARAMS = COMMON_QUERY_O_PARAMS + ['CURRENT_COMMIT']

CQ_RUN_TAG_RE = re.compile(r'^autogenerated:c[qv]:(full|dry)-run(:.*)?$')
RUNNING_RE = re.compile(r'C[QV] is trying the patch')
CHROME_VERSION_FROM_EBUILD_FILENAME_RE = re.compile(
    r'chromeos-base/[a-z-]+/[a-z-]+(?P<version>[0-9\.]+)(_pre(?P<position>[0-9]*))?_rc-r\d+.ebuild'
)

INTERNAL_BOARDS = [
    'betty',
    'betty-cfi-thin-lto',
    'brya',
    'octopus',
    'jacuzzi',
    'reven',
    'trogdor',
    'volteer',
]

BUILD_FIELDS_TO_RETRIEVE = [
    'builder',
    'cancellation_markdown',
    'id',
    'input',
    'output',
    'status',
    'summary_markdown',
    'infra.resultdb',
]


def ResolveAgeDays(condition: GerritQueryCondition | None) -> int:
  """Resolves the age in days from condition.age_days if > 0, defaulting to DEFAULT_QUERY_AGE_DAYS."""
  if condition and condition.age_days > 0:
    return condition.age_days
  if condition and condition.merged_hours > 0:
    return max(DEFAULT_QUERY_AGE_DAYS, (condition.merged_hours + 23) // 24)
  return DEFAULT_QUERY_AGE_DAYS


ORDERING_FIELD_ALLOWLIST = frozenset(
    GardenerDataResult.Commit.DESCRIPTOR.fields_by_name)


def ParseOrdering(ordering: list[str]) -> list[tuple[str, bool]]:
  """Parses ordering specifications into a list of (field_name, is_descending)."""
  specs = []
  for item in ordering:
    tok = item.strip()
    is_desc = tok.startswith('-')
    field = tok.lstrip('+-').lower()
    if field in ORDERING_FIELD_ALLOWLIST:
      specs.append((field, is_desc))
  return specs


def ParseVersionKey(val: str):
  """Splits version string into numeric and non-numeric components for natural sorting."""
  tokens = re.findall(r'\d+|\D+', val)
  return tuple((0, int(t)) if t.isdigit() else (1, t) for t in tokens)


def GetSortValue(item: GardenerDataResult.Commit, field: str):
  """Extracts value for sorting from Commit."""
  val = getattr(item, field, None)
  if isinstance(val, str) and 'version' in field and val:
    return ParseVersionKey(val)
  return val or None


def CompareCommits(a: GardenerDataResult.Commit, b: GardenerDataResult.Commit,
                   specs: list[tuple[str, bool]]) -> int:
  """Comparator function for multi-level sorting."""
  for field, descending in specs:
    val_a = GetSortValue(a, field)
    val_b = GetSortValue(b, field)
    if val_a == val_b:
      continue
    if val_a is None:
      return 1
    if val_b is None:
      return -1
    if val_a < val_b:
      return 1 if descending else -1
    return -1 if descending else 1
  return 0


def SortCommits(commits: list[GardenerDataResult.Commit],
                ordering: list[str]) -> list[GardenerDataResult.Commit]:
  """Sorts commits according to multi-level ordering specification."""
  specs = ParseOrdering(ordering)
  return sorted(
      commits,
      key=functools.cmp_to_key(lambda a, b: CompareCommits(a, b, specs)))


def ParseChangeInfo(change_info: ChangeInfo) -> GardenerDataResult.Commit:
  return GardenerDataResult.Commit(
      number=change_info['_number'], created=change_info['created'],
      submitted=change_info.get('submitted'), branch=change_info['branch'],
      subject=change_info['subject'], status=change_info['status'],
      cq_tries=len([
          1 for message in change_info['messages']
          if 'tag' in message and CQ_RUN_TAG_RE.match(message['tag']) and
          RUNNING_RE.search(message['message'])
      ]), revert_of=change_info.get('revert_of'))


def GetChromeCommitFromEbuild(api: recipe_api.RecipeApi, revision: str,
                              path: str) -> str:
  ebuild = api.gitiles.get_file(
      GITILES_HOST, 'chromiumos/overlays/chromiumos-overlay', path,
      ref=revision, retries=10, public=False,
      test_output_data=base64.b64encode(b'\n\nGIT_COMMIT="deadbeef"\n\n'))
  for l in ebuild.splitlines():
    if l.startswith(b'GIT_COMMIT='):
      return l.removeprefix(b'GIT_COMMIT=').rstrip(b'"').lstrip(b'"').decode()
  return None  # pragma: nocover


def ParseChromeUprevChangeInfo(
    api: recipe_api.RecipeApi,
    change_info: ChangeInfo) -> GardenerDataResult.Commit:
  result = ParseChangeInfo(change_info)
  # Only the current revision should exist.
  for revision_hash, revision in change_info['revisions'].items():
    # Find Chrome uprev version range by parsing the ebuild files.
    # Ignore any non-renaming file changes and retry until there is one that
    # matches the expected pattern for extracting chrome version.
    # Any one of the chrome-base/{chrome-icu, chromeos-chrome, chromium-source}
    # ebuilds should work and provide identical result.
    old_version = None
    old_chrome_commit = None
    new_version = None
    new_chrome_commit = None
    for new_filename, changes in revision['files'].items():
      if not changes.get('status'):
        continue
      old_version_match = new_version_match = old_path = None
      if changes['status'] == 'D':
        old_version_match = CHROME_VERSION_FROM_EBUILD_FILENAME_RE.match(
            new_filename)
        old_path = new_filename
      if changes['status'] == 'R':
        new_version_match = CHROME_VERSION_FROM_EBUILD_FILENAME_RE.match(
            new_filename)
        if new_version_match:
          old_version_match = CHROME_VERSION_FROM_EBUILD_FILENAME_RE.match(
              changes['old_path'])
          old_path = changes['old_path']
      if old_version_match:
        file_old_version = old_version_match.group(
            'position') or old_version_match.group('version')
        # Raw string version comparison has bugs but it happens very rare in
        # only following cases:
        # 1. Two main old branch uprev bumps commit position's digit count.
        # 2. Old version has both canary and main branch uprev.
        # 3. Two canary old version bumps either MAJOR or BUILD's digit count.
        # Instead of handling version carefully (especially case 2), leave the
        # bug here.
        if old_version is None or file_old_version > old_version:
          old_version = file_old_version
          old_chrome_commit = GetChromeCommitFromEbuild(
              api, revision['commit']['parents'][0]['commit'], old_path)
      if new_version_match:
        new_version = new_version_match.group(
            'position') or new_version_match.group('version')
        new_chrome_commit = GetChromeCommitFromEbuild(api, revision_hash,
                                                      new_filename)
    if old_version and new_version:
      result.old_version = old_version
      result.new_version = new_version
      if old_chrome_commit:
        result.old_version += f'@{old_chrome_commit}'
      if new_chrome_commit:
        result.new_version += f'@{new_chrome_commit}'
      return result
  # Return result without uprev version range if failed to find them.
  return result  # pragma: nocover


def ParseLkgmChangeInfo(api: recipe_api.RecipeApi,
                        change_info: ChangeInfo) -> GardenerDataResult.Commit:
  result = ParseChangeInfo(change_info)
  # Only the current revision should exist.
  for revision, revision_info in change_info['revisions'].items():
    new_version = api.gitiles.get_file(
        GITILES_HOST, 'chromium/src', 'chromeos/CHROMEOS_LKGM', ref=revision,
        retries=10, public=False,
        test_output_data=base64.b64encode(b'16110.0.0-1065034'))
    old_version = api.gitiles.get_file(
        GITILES_HOST, 'chromium/src', 'chromeos/CHROMEOS_LKGM', retries=10,
        public=False, ref=revision_info['commit']['parents'][0]['commit'],
        test_output_data=base64.b64encode(b'16109.0.0-1065024'))
    if new_version and old_version and new_version != old_version:
      # split('-')[-1] takes the snapshot identifier if it is a snapshot, or the
      # release version if it is not.
      result.new_version = new_version.strip().split(b'-')[-1]
      result.old_version = old_version.strip().split(b'-')[-1]
      return result
  # Return result without uprev version range if failed to find them.
  # In theory, this shouldn't happen since we fetch the file of the commit hash
  # directly without relying on any commit message. Just in case so it doesn't
  # crash the recipes.
  return result  # pragma: nocover


def QueryAndCollectCommits(
    api: recipe_api.RecipeApi,
    condition: GerritQueryCondition | None,
    base_query_params: list[tuple[str, str]],
    o_params: list[str],
    top_step_name: str,
    parse_fn: Callable[[recipe_api.RecipeApi, ChangeInfo],
                       GardenerDataResult.Commit],
) -> list[GardenerDataResult.Commit]:
  """Queries Gerrit changes and parses commits from results using condition."""
  if not condition or not condition.situations:
    return []  # pragma: nocover

  cutoff = None
  if condition.merged_hours > 0:
    cutoff = api.time.utcnow() - datetime.timedelta(
        hours=condition.merged_hours)

  queries = []
  for i, s in enumerate(condition.situations):
    terms = [(t.key, t.value) for t in s.terms]
    step_name = f'situation {i + 1}' if len(condition.situations) > 1 else None
    queries.append((step_name, terms))

  results = []
  seen_change_numbers = set()

  with api.step.nest(top_step_name):
    for step_name, terms in queries:
      query_params = base_query_params + terms
      if step_name:
        with api.step.nest(step_name):
          change_infos = api.gerrit.query_change_infos(GERRIT_HOST,
                                                       query_params,
                                                       o_params=o_params)
      else:
        change_infos = api.gerrit.query_change_infos(GERRIT_HOST, query_params,
                                                     o_params=o_params)

      for change in change_infos:
        if cutoff:
          if change.get('status') != 'MERGED':
            continue
          if datetime.datetime.fromisoformat(change['submitted']) < cutoff:
            continue

        num = change.get('_number')
        if num not in seen_change_numbers:
          seen_change_numbers.add(num)
          results.append(change)

    commits = [parse_fn(api, x) for x in results]
    if condition and condition.ordering:
      commits = SortCommits(commits, list(condition.ordering))
    return commits


def CollectChromeUprevCommit(
    api: recipe_api.RecipeApi, properties: GardenerDataCollectorProperties
) -> list[GardenerDataResult.Commit]:
  condition = properties.chrome_uprev_query_condition if properties.HasField(
      'chrome_uprev_query_condition') else None
  age_days = ResolveAgeDays(condition)
  top_step_name = f'find last {age_days}-day Chrome uprev CLs'

  base_query_params = [
      CHROME_UPREV_REPO_PARAM,
      ('-age', f'{age_days}d'),
      IGNORE_WIP_PARAM,
  ]
  return QueryAndCollectCommits(
      api,
      condition,
      base_query_params,
      CHROME_UPREV_QUERY_O_PARAMS,
      top_step_name,
      parse_fn=ParseChromeUprevChangeInfo,
  )


def CollectLkgmUprevCommit(
    api: recipe_api.RecipeApi, properties: GardenerDataCollectorProperties
) -> list[GardenerDataResult.Commit]:
  condition = properties.lkgm_query_condition if properties.HasField(
      'lkgm_query_condition') else None
  age_days = ResolveAgeDays(condition)
  top_step_name = f'find last {age_days}-day LKGM CLs'
  base_query_params = [
      LKGM_REPO_PARAM,
      ('-age', f'{age_days}d'),
      IGNORE_WIP_PARAM,
  ]
  return QueryAndCollectCommits(
      api,
      condition,
      base_query_params,
      LKGM_QUERY_O_PARAMS,
      top_step_name=top_step_name,
      parse_fn=ParseLkgmChangeInfo,
  )


def ToListDict(v: list[Message]) -> list[dict]:
  return [
      json_format.MessageToDict(m, preserving_proto_field_name=True) for m in v
  ]



def RunSteps(api: recipe_api.RecipeApi,
             properties: GardenerDataCollectorProperties):
  chrome_uprev_commits = CollectChromeUprevCommit(
      api, properties) if not properties.disable_chrome_uprev_commits else []

  lkgm_commits = CollectLkgmUprevCommit(
      api, properties) if not properties.disable_lkgm_uprev_commits else []


  api.easy.set_properties_step(
      'set output properties',
      chrome_uprev_commits=ToListDict(chrome_uprev_commits),
      lkgm_commits=ToListDict(lkgm_commits))


def GenTests(api: recipe_api.RecipeApi):
  # A simplified returned json object for the chrome uprev commits query.
  chrome_uprev_gerrit_change_info_good = {
      'project':
          'chromiumos/overlays/chromiumos-overlay',
      'branch':
          'main',
      'change_id':
          'I29cf31ceeea219231177258a7bf87cb5d56d4a27',
      'subject':
          'chromeos-chrome: Automatic uprev to 133.0.6862.0.',
      'status':
          'NEW',
      'created':
          '2024-11-27 04:13:33.000000000',
      '_number':
          6047779,
      'revisions': {
          'c89a0ff2988dbd697d4375924dadec75832c79f3': {
              'commit': {
                  'parents': [{
                      'commit': 'deadbeef',
                  }],
              },
              'files': {
                  'chromeos-base/chromium-source/chromium-source-133.0.6862.0_rc-r1.ebuild':
                      {
                          'status':
                              'R',
                          'old_mode':
                              33188,
                          'new_mode':
                              33188,
                          'old_path':
                              'chromeos-base/chromium-source/chromium-source-133.0.6861.0_rc-r1.ebuild',
                          'size_delta':
                              0,
                          'size':
                              494
                      },
              }
          }
      },
      'messages': [
          {
              'id':
                  '59cf36a6bf221ebbd133d35c2da786a2107d395f',
              'tag':
                  'autogenerated:gerrit:code-owners:addReviewer',
              'author': {
                  '_account_id': 1347071
              },
              'date':
                  '2024-11-27 04:13:36.000000000',
              'message':
                  '<GERRIT_ACCOUNT_1513692>, who was added as reviewer owns the following files:\n* `chromeos-base/chromeos-chrome/chromeos-chrome-133.0.6861.0_rc-r1.ebuild`\n* `chromeos-base/chromeos-chrome/chromeos-chrome-133.0.6862.0_rc-r1.ebuild`\n* `chromeos-base/chromium-source/chromium-source-133.0.6861.0_rc-r1.ebuild`\n* `chromeos-base/chromium-source/chromium-source-133.0.6862.0_rc-r1.ebuild`\n',
              'accounts_in_message': [{
                  '_account_id': 1513692
              }],
              '_revision_number':
                  1
          },
          {
              'id':
                  'fdd27b2724acde316dbfb261afa7cfdf6b514303',
              'tag':
                  'autogenerated:cq:dry-run',
              'author': {
                  '_account_id': 1530088
              },
              'date':
                  '2024-11-27 04:18:44.000000000',
              'message':
                  'Patch Set 1:\n\nDry run: CV is trying the patch.\n\nBot data: {\"action\":\"start\",\"triggered_at\":\"2024-11-27T04:13:41Z\",\"revision\":\"c89a0ff2988dbd697d4375924dadec75832c79f3\"}',
              'accounts_in_message': [],
              '_revision_number':
                  1
          },
      ],
  }

  chrome_uprev_gerrit_change_info_revert = {
      'project':
          'chromiumos/overlays/chromiumos-overlay',
      'branch':
          'main',
      'change_id':
          'I04d2973f924558150a243227092f01cf44e49a03',
      'subject':
          'Revert \"chromeos-chrome, chromeos-lacros-parallel: Automatic uprev to 112.0.5589.0.\"',
      'status':
          'MERGED',
      'created':
          '2023-02-11 14:56:09.000000000',
      'submitted':
          '2023-02-12 03:45:17.000000000',
      '_number':
          4242579,
      'revert_of':
          4242666,
      'revisions': {
          '9bbb014843d74f7536a66139067fd082b1a73d19': {
              'kind': 'REWORK',
              '_number': 5,
              'created': '2023-02-11 15:45:17.000000000',
              'uploader': {
                  '_account_id': 1355298
              },
              'ref': 'refs/changes/79/4242579/5',
              'fetch': {
                  'repo': {
                      'url': 'chromiumos/overlays/chromiumos-overlay',
                      'ref': 'refs/changes/79/4242579/5'
                  },
                  'http': {
                      'url':
                          'https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay',
                      'ref':
                          'refs/changes/79/4242579/5'
                  }
              },
              'branch': 'refs/heads/main',
              'commit': {
                  'parents': [{
                      'commit': 'deadbeef',
                  }],
              },
              'files': {
                  'chromeos-base/chromeos-chrome/chromeos-chrome-112.0.5584.0_rc-r1.ebuild':
                      {
                          'status':
                              'R',
                          'old_mode':
                              33188,
                          'new_mode':
                              33188,
                          'old_path':
                              'chromeos-base/chromeos-chrome/chromeos-chrome-112.0.5589.0_rc-r1.ebuild',
                          'size_delta':
                              0,
                          'size':
                              48981
                      },
                  'chromeos-base/chromeos-lacros/Manifest': {
                      'old_mode': 33188,
                      'new_mode': 33188,
                      'lines_inserted': 6,
                      'lines_deleted': 6,
                      'size_delta': 0,
                      'size': 1976
                  }
              },
              'description': 'Rebase'
          },
      },
      'messages': [],
  }

  chrome_uprev_gerrit_change_info_multiple_old = {
      'project':
          'chromiumos/overlays/chromiumos-overlay',
      'branch':
          'main',
      'change_id':
          'I29cf31ceeea219231177258a7bf87cb5d56d4a27',
      'subject':
          'chromeos-chrome: Automatic uprev to 133.0.6862.0.',
      'status':
          'NEW',
      'created':
          '2024-11-27 04:13:33.000000000',
      '_number':
          6047779,
      'revisions': {
          'c89a0ff2988dbd697d4375924dadec75832c79f3': {
              'commit': {
                  'parents': [{
                      'commit': 'deadbeef',
                  }],
              },
              'files': {
                  'chromeos-base/chromium-source/chromium-source-133.0.6862.0_rc-r1.ebuild':
                      {
                          'status':
                              'R',
                          'old_mode':
                              33188,
                          'new_mode':
                              33188,
                          'old_path':
                              'chromeos-base/chromium-source/chromium-source-133.0.6860.0_rc-r1.ebuild',
                          'size_delta':
                              0,
                          'size':
                              494
                      },
                  'chromeos-base/chromium-source/chromium-source-133.0.6861.0_rc-r1.ebuild':
                      {
                          'status': 'D',
                          'old_mode': 33188,
                          'size_delta': -123456,
                          'size': 0,
                      }
              }
          }
      },
      'messages': [
          {
              'id':
                  '59cf36a6bf221ebbd133d35c2da786a2107d395f',
              'tag':
                  'autogenerated:gerrit:code-owners:addReviewer',
              'author': {
                  '_account_id': 1347071
              },
              'date':
                  '2024-11-27 04:13:36.000000000',
              'message':
                  '<GERRIT_ACCOUNT_1513692>, who was added as reviewer owns the following files:\n* `chromeos-base/chromeos-chrome/chromeos-chrome-133.0.6861.0_rc-r1.ebuild`\n* `chromeos-base/chromeos-chrome/chromeos-chrome-133.0.6862.0_rc-r1.ebuild`\n* `chromeos-base/chromium-source/chromium-source-133.0.6861.0_rc-r1.ebuild`\n* `chromeos-base/chromium-source/chromium-source-133.0.6862.0_rc-r1.ebuild`\n',
              'accounts_in_message': [{
                  '_account_id': 1513692
              }],
              '_revision_number':
                  1
          },
          {
              'id':
                  'fdd27b2724acde316dbfb261afa7cfdf6b514303',
              'tag':
                  'autogenerated:cq:dry-run',
              'author': {
                  '_account_id': 1530088
              },
              'date':
                  '2024-11-27 04:18:44.000000000',
              'message':
                  'Patch Set 1:\n\nDry run: CV is trying the patch.\n\nBot data: {\"action\":\"start\",\"triggered_at\":\"2024-11-27T04:13:41Z\",\"revision\":\"c89a0ff2988dbd697d4375924dadec75832c79f3\"}',
              'accounts_in_message': [],
              '_revision_number':
                  1
          },
      ],
  }


  # A simplified returned json object for the LKGM commits query.
  lkgm_gerrit_change_info_good = {
      'project': 'chromium/src',
      'branch': 'main',
      'change_id': 'Ie5d42742d988003a3deb580e6dec7d5039a45016',
      'subject': 'Automated Commit: LKGM 16110.0.0-1065034 for chromeos.',
      'status': 'MERGED',
      'created': '2024-11-27 00:20:00.000000000',
      'submitted': '2024-11-27 03:27:44.000000000',
      '_number': 6052367,
      'messages': [{
          'id':
              'a0981969bab8f83a4b418efdf24025770bc03742',
          'tag':
              'autogenerated:cq:full-run',
          'author': {
              '_account_id': 1347153
          },
          'date':
              '2024-11-27 00:20:34.000000000',
          'message':
              'Patch Set 2:\n\nCV is trying the patch.\n\nFollow status at: https://luci-change-verifier.appspot.com/ui/run/chromium/8890303965854-1-a9931487c1eabfe0\n\nBot data: {\"action\":\"start\",\"triggered_at\":\"2024-11-27T00:20:31Z\",\"revision\":\"bad8c5823c23887f798b98daaeb94a4d04b8cca7\"}',
          'accounts_in_message': [],
          '_revision_number':
              2
      }, {
          'id':
              '44155dacf26a2bb94a5675e1a40fb954a6625bdb',
          'tag':
              'autogenerated:gerrit:merged',
          'author': {
              '_account_id': 1347153
          },
          'date':
              '2024-11-27 03:27:44.000000000',
          'message':
              'Change has been successfully rebased and submitted as 3256278a456c50c062fd5b8b082b8107e9c77a1f',
          'accounts_in_message': [],
          '_revision_number':
              3
      }],
      'revisions': {
          '3256278a456c50c062fd5b8b082b8107e9c77a1f': {
              'commit': {
                  'parents': [{
                      'commit':
                          '821901f8a13683d50420293f2e14cce7b9ccd49b',
                      'subject':
                          '[Autofill] Fix use-of-uninitialized-value in TestAutofillClient'
                  }],
                  'author': {
                      'name': 'ChromeOS bot',
                      'email': '3su6n15k.default@developer.gserviceaccount.com',
                      'date': '2024-11-27 03:27:44.000000000',
                      'tz': 0
                  },
                  'committer': {
                      'name':
                          'Chromium LUCI CQ',
                      'email':
                          'chromium-scoped@luci-project-accounts.iam.gserviceaccount.com',
                      'date':
                          '2024-11-27 03:27:44.000000000',
                      'tz':
                          0
                  },
                  'subject':
                      'Automated Commit: LKGM 16110.0.0-1065034 for chromeos.',
                  'message':
                      'Automated Commit: LKGM 16110.0.0-1065034 for chromeos.\n'
              },
              'branch': 'refs/heads/main',
              'description': 'Rebase'
          }
      },
  }

  yield api.test(
      'chrome-uprevs',
      api.properties(
          GardenerDataCollectorProperties(
              disable_lkgm_uprev_commits=True,
              chrome_uprev_query_condition=GerritQueryCondition(
                  situations=[
                      GerritQueryCondition.Situation(
                          terms=[
                              GerritQueryCondition.Term(
                                  key='topic',
                                  value='chromeos-base/chromeos-chrome'),
                          ],
                      ),
                  ],
              ),
          )),
      api.gerrit.set_query_changes_response(
          'find last 7-day Chrome uprev CLs', [
              chrome_uprev_gerrit_change_info_good,
              chrome_uprev_gerrit_change_info_revert
          ], 'https://chromium-review.googlesource.com'),
      api.post_process(
          post_process.StepCommandContains,
          'find last 7-day Chrome uprev CLs.query https://chromium-review.googlesource.com.gerrit changes',
          [
              '-p', 'repo=chromiumos/overlays/chromiumos-overlay', '-p',
              '-age=7d', '-p', '-is=wip', '-p',
              'topic=chromeos-base/chromeos-chrome'
          ],
      ),
      api.post_process(
          post_process.StepCommandDoesNotContain,
          'find last 7-day Chrome uprev CLs.query https://chromium-review.googlesource.com.gerrit changes',
          ['branch=main'],
      ),
      api.post_process(post_process.PropertyEquals, 'chrome_uprev_commits', [{
          'branch': 'main',
          'cq_tries': '1',
          'created': '2024-11-27 04:13:33.000000000',
          'new_version': '133.0.6862.0@deadbeef',
          'number': '6047779',
          'old_version': '133.0.6861.0@deadbeef',
          'status': 'NEW',
          'subject': 'chromeos-chrome: Automatic uprev to 133.0.6862.0.',
      }, {
          'branch':
              'main',
          'created':
              '2023-02-11 14:56:09.000000000',
          'new_version':
              '112.0.5584.0@deadbeef',
          'number':
              '4242579',
          'old_version':
              '112.0.5589.0@deadbeef',
          'revert_of':
              '4242666',
          'status':
              'MERGED',
          'subject':
              'Revert \"chromeos-chrome, chromeos-lacros-parallel: Automatic uprev to 112.0.5589.0.\"',
          'submitted':
              '2023-02-12 03:45:17.000000000',
      }]),
      status='SUCCESS',
  )

  yield api.test(
      'chrome-uprevs-mutliple-old-version',
      api.properties(
          GardenerDataCollectorProperties(
              disable_lkgm_uprev_commits=True,
              chrome_uprev_query_condition=GerritQueryCondition(
                  situations=[
                      GerritQueryCondition.Situation(
                          terms=[
                              GerritQueryCondition.Term(
                                  key='topic',
                                  value='chromeos-base/chromeos-chrome'),
                          ],
                      ),
                  ],
              ),
          )),
      api.gerrit.set_query_changes_response(
          'find last 7-day Chrome uprev CLs', [
              chrome_uprev_gerrit_change_info_multiple_old,
          ], 'https://chromium-review.googlesource.com'),
      api.post_process(
          post_process.StepCommandContains,
          'find last 7-day Chrome uprev CLs.query https://chromium-review.googlesource.com.gerrit changes',
          [
              '-p', 'repo=chromiumos/overlays/chromiumos-overlay', '-p',
              '-age=7d', '-p', '-is=wip', '-p',
              'topic=chromeos-base/chromeos-chrome'
          ],
      ),
      api.post_process(
          post_process.StepCommandDoesNotContain,
          'find last 7-day Chrome uprev CLs.query https://chromium-review.googlesource.com.gerrit changes',
          ['branch=main'],
      ),
      api.post_process(post_process.PropertyEquals, 'chrome_uprev_commits', [{
          'branch': 'main',
          'cq_tries': '1',
          'created': '2024-11-27 04:13:33.000000000',
          'new_version': '133.0.6862.0@deadbeef',
          'number': '6047779',
          'old_version': '133.0.6861.0@deadbeef',
          'status': 'NEW',
          'subject': 'chromeos-chrome: Automatic uprev to 133.0.6862.0.',
      }]),
      status='SUCCESS',
  )

  yield api.test(
      'lkgm-uprevs',
      api.properties(
          GardenerDataCollectorProperties(
              disable_chrome_uprev_commits=True,
              lkgm_query_condition=GerritQueryCondition(
                  situations=[
                      GerritQueryCondition.Situation(
                          terms=[
                              GerritQueryCondition.Term(key='hashtag',
                                                        value='chrome-lkgm'),
                          ],
                      ),
                  ],
              ),
          )),
      api.gerrit.set_query_changes_response(
          'find last 7-day LKGM CLs', [lkgm_gerrit_change_info_good],
          'https://chromium-review.googlesource.com'),
      api.post_process(
          post_process.StepCommandContains,
          'find last 7-day LKGM CLs.query https://chromium-review.googlesource.com.gerrit changes',
          [
              '-p', 'repo=chromium/src', '-p', '-age=7d', '-p', '-is=wip', '-p',
              'hashtag=chrome-lkgm'
          ],
      ),
      api.post_process(post_process.PropertyEquals, 'lkgm_commits', [{
          'branch': 'main',
          'cq_tries': '1',
          'created': '2024-11-27 00:20:00.000000000',
          'new_version': '1065034',
          'number': '6052367',
          'old_version': '1065024',
          'status': 'MERGED',
          'subject': 'Automated Commit: LKGM 16110.0.0-1065034 for chromeos.',
          'submitted': '2024-11-27 03:27:44.000000000',
      }]),
      status='SUCCESS',
  )

  yield api.test(
      'lkgm-uprevs-structured-query-condition',
      api.properties(
          GardenerDataCollectorProperties(
              disable_chrome_uprev_commits=True,
              lkgm_query_condition=GerritQueryCondition(
                  situations=[
                      GerritQueryCondition.Situation(
                          terms=[
                              GerritQueryCondition.Term(key='hashtag',
                                                        value='condA'),
                              GerritQueryCondition.Term(key='topic',
                                                        value='condB'),
                          ],
                      ),
                      GerritQueryCondition.Situation(
                          terms=[
                              GerritQueryCondition.Term(key='hashtag',
                                                        value='condC'),
                              GerritQueryCondition.Term(key='topic',
                                                        value='condD'),
                          ],
                      ),
                  ],
              ),
          )),
      api.gerrit.set_query_changes_response(
          'find last 7-day LKGM CLs.situation 1',
          [lkgm_gerrit_change_info_good],
          'https://chromium-review.googlesource.com'),
      api.gerrit.set_query_changes_response(
          'find last 7-day LKGM CLs.situation 2', [],
          'https://chromium-review.googlesource.com'),
      api.post_process(
          post_process.StepCommandContains,
          'find last 7-day LKGM CLs.situation 1.query https://chromium-review.googlesource.com.gerrit changes',
          [
              '-p', 'repo=chromium/src', '-p', '-age=7d', '-p', '-is=wip', '-p',
              'hashtag=condA', '-p', 'topic=condB'
          ],
      ),
      api.post_process(
          post_process.StepCommandContains,
          'find last 7-day LKGM CLs.situation 2.query https://chromium-review.googlesource.com.gerrit changes',
          [
              '-p', 'repo=chromium/src', '-p', '-age=7d', '-p', '-is=wip', '-p',
              'hashtag=condC', '-p', 'topic=condD'
          ],
      ),
      api.post_process(post_process.PropertyEquals, 'lkgm_commits', [{
          'branch': 'main',
          'cq_tries': '1',
          'created': '2024-11-27 00:20:00.000000000',
          'new_version': '1065034',
          'number': '6052367',
          'old_version': '1065024',
          'status': 'MERGED',
          'subject': 'Automated Commit: LKGM 16110.0.0-1065034 for chromeos.',
          'submitted': '2024-11-27 03:27:44.000000000',
      }]),
      status='SUCCESS',
  )

  yield api.test(
      'chrome-uprevs-structured-query-condition',
      api.properties(
          GardenerDataCollectorProperties(
              disable_lkgm_uprev_commits=True,
              chrome_uprev_query_condition=GerritQueryCondition(
                  situations=[
                      GerritQueryCondition.Situation(
                          terms=[
                              GerritQueryCondition.Term(key='branch',
                                                        value='main'),
                              GerritQueryCondition.Term(
                                  key='topic', value='custom-chrome-uprev'),
                          ],
                      ),
                  ],
              ),
          )),
      api.gerrit.set_query_changes_response(
          'find last 7-day Chrome uprev CLs', [
              chrome_uprev_gerrit_change_info_good,
          ], 'https://chromium-review.googlesource.com'),
      api.post_process(
          post_process.StepCommandContains,
          'find last 7-day Chrome uprev CLs.query https://chromium-review.googlesource.com.gerrit changes',
          [
              '-p', 'repo=chromiumos/overlays/chromiumos-overlay', '-p',
              '-age=7d', '-p', '-is=wip', '-p', 'branch=main', '-p',
              'topic=custom-chrome-uprev'
          ],
      ),
      api.post_process(post_process.PropertyEquals, 'chrome_uprev_commits', [{
          'branch': 'main',
          'cq_tries': '1',
          'created': '2024-11-27 04:13:33.000000000',
          'new_version': '133.0.6862.0@deadbeef',
          'number': '6047779',
          'old_version': '133.0.6861.0@deadbeef',
          'status': 'NEW',
          'subject': 'chromeos-chrome: Automatic uprev to 133.0.6862.0.',
      }]),
      status='SUCCESS',
  )

  yield api.test(
      'custom-query-age',
      api.properties(
          GardenerDataCollectorProperties(
              lkgm_query_condition=GerritQueryCondition(
                  age_days=14,
                  situations=[
                      GerritQueryCondition.Situation(
                          terms=[
                              GerritQueryCondition.Term(key='hashtag',
                                                        value='chrome-lkgm'),
                          ],
                      ),
                  ],
              ),
              chrome_uprev_query_condition=GerritQueryCondition(
                  age_days=30,
                  situations=[
                      GerritQueryCondition.Situation(
                          terms=[
                              GerritQueryCondition.Term(key='topic',
                                                        value='custom-chrome'),
                          ],
                      ),
                  ],
              ),
          )),
      api.gerrit.set_query_changes_response(
          'find last 30-day Chrome uprev CLs', [],
          'https://chromium-review.googlesource.com'),
      api.gerrit.set_query_changes_response(
          'find last 14-day LKGM CLs', [],
          'https://chromium-review.googlesource.com'),
      api.post_process(
          post_process.StepCommandContains,
          'find last 30-day Chrome uprev CLs.query https://chromium-review.googlesource.com.gerrit changes',
          ['-p', '-age=30d'],
      ),
      api.post_process(
          post_process.StepCommandContains,
          'find last 14-day LKGM CLs.query https://chromium-review.googlesource.com.gerrit changes',
          ['-p', '-age=14d'],
      ),
      status='SUCCESS',
  )

  yield api.test(
      'custom-query-merged-hours',
      api.time.seed(1732678064),
      api.time.step(0),
      api.properties(
          GardenerDataCollectorProperties(
              lkgm_query_condition=GerritQueryCondition(
                  merged_hours=24,
                  situations=[
                      GerritQueryCondition.Situation(
                          terms=[
                              GerritQueryCondition.Term(key='hashtag',
                                                        value='chrome-lkgm'),
                          ],
                      ),
                  ],
              ),
              chrome_uprev_query_condition=GerritQueryCondition(
                  merged_hours=12,
                  situations=[
                      GerritQueryCondition.Situation(
                          terms=[
                              GerritQueryCondition.Term(key='topic',
                                                        value='custom-chrome'),
                          ],
                      ),
                  ],
              ),
          )),
      api.gerrit.set_query_changes_response(
          'find last 7-day Chrome uprev CLs', [
              chrome_uprev_gerrit_change_info_good,
              chrome_uprev_gerrit_change_info_revert,
          ], 'https://chromium-review.googlesource.com'),
      api.gerrit.set_query_changes_response(
          'find last 7-day LKGM CLs', [lkgm_gerrit_change_info_good],
          'https://chromium-review.googlesource.com'),
      api.post_process(
          post_process.StepCommandContains,
          'find last 7-day Chrome uprev CLs.query https://chromium-review.googlesource.com.gerrit changes',
          [
              '-p', 'repo=chromiumos/overlays/chromiumos-overlay', '-p',
              '-age=7d', '-p', '-is=wip', '-p', 'topic=custom-chrome'
          ],
      ),
      api.post_process(
          post_process.StepCommandDoesNotContain,
          'find last 7-day Chrome uprev CLs.query https://chromium-review.googlesource.com.gerrit changes',
          ['mergedafter', 'status=merged'],
      ),
      api.post_process(
          post_process.StepCommandContains,
          'find last 7-day LKGM CLs.query https://chromium-review.googlesource.com.gerrit changes',
          [
              '-p', 'repo=chromium/src', '-p', '-age=7d', '-p', '-is=wip', '-p',
              'hashtag=chrome-lkgm'
          ],
      ),
      api.post_process(
          post_process.StepCommandDoesNotContain,
          'find last 7-day LKGM CLs.query https://chromium-review.googlesource.com.gerrit changes',
          ['mergedafter', 'status=merged'],
      ),
      api.post_process(post_process.PropertyEquals, 'chrome_uprev_commits', []),
      api.post_process(post_process.PropertyEquals, 'lkgm_commits', [{
          'branch': 'main',
          'cq_tries': '1',
          'created': '2024-11-27 00:20:00.000000000',
          'new_version': '1065034',
          'number': '6052367',
          'old_version': '1065024',
          'status': 'MERGED',
          'subject': 'Automated Commit: LKGM 16110.0.0-1065034 for chromeos.',
          'submitted': '2024-11-27 03:27:44.000000000',
      }]),
      status='SUCCESS',
  )

  chrome_uprev_gerrit_change_info_revert_same = dict(
      chrome_uprev_gerrit_change_info_revert,
      _number=4242581,
  )
  chrome_uprev_gerrit_change_info_revert_r130 = dict(
      chrome_uprev_gerrit_change_info_revert,
      _number=4242582,
      branch='release-R130',
  )
  chrome_uprev_gerrit_change_info_good_no_version = dict(
      chrome_uprev_gerrit_change_info_good,
      _number=6047780,
      revisions={},
  )
  chrome_uprev_gerrit_change_info_good_no_version_2 = dict(
      chrome_uprev_gerrit_change_info_good,
      _number=6047783,
      revisions={},
  )

  yield api.test(
      'custom-query-ordering',
      api.properties(
          GardenerDataCollectorProperties(
              disable_lkgm_uprev_commits=True,
              chrome_uprev_query_condition=GerritQueryCondition(
                  ordering=['+branch', '-new_version', '+invalid_field'],
                  situations=[
                      GerritQueryCondition.Situation(
                          terms=[
                              GerritQueryCondition.Term(
                                  key='topic',
                                  value='chromeos-base/chromeos-chrome'),
                          ],
                      ),
                  ],
              ),
          )),
      api.gerrit.set_query_changes_response(
          'find last 7-day Chrome uprev CLs', [
              chrome_uprev_gerrit_change_info_revert_r130,
              chrome_uprev_gerrit_change_info_good_no_version,
              chrome_uprev_gerrit_change_info_revert,
              chrome_uprev_gerrit_change_info_revert_same,
              chrome_uprev_gerrit_change_info_good,
              chrome_uprev_gerrit_change_info_good_no_version_2,
          ], 'https://chromium-review.googlesource.com'),
      api.post_process(post_process.PropertyEquals, 'chrome_uprev_commits', [
          {
              'branch': 'main',
              'cq_tries': '1',
              'created': '2024-11-27 04:13:33.000000000',
              'new_version': '133.0.6862.0@deadbeef',
              'number': '6047779',
              'old_version': '133.0.6861.0@deadbeef',
              'status': 'NEW',
              'subject': 'chromeos-chrome: Automatic uprev to 133.0.6862.0.',
          },
          {
              'branch':
                  'main',
              'created':
                  '2023-02-11 14:56:09.000000000',
              'new_version':
                  '112.0.5584.0@deadbeef',
              'number':
                  '4242579',
              'old_version':
                  '112.0.5589.0@deadbeef',
              'revert_of':
                  '4242666',
              'status':
                  'MERGED',
              'subject':
                  'Revert "chromeos-chrome, chromeos-lacros-parallel: Automatic uprev to 112.0.5589.0."',
              'submitted':
                  '2023-02-12 03:45:17.000000000',
          },
          {
              'branch':
                  'main',
              'created':
                  '2023-02-11 14:56:09.000000000',
              'new_version':
                  '112.0.5584.0@deadbeef',
              'number':
                  '4242581',
              'old_version':
                  '112.0.5589.0@deadbeef',
              'revert_of':
                  '4242666',
              'status':
                  'MERGED',
              'subject':
                  'Revert "chromeos-chrome, chromeos-lacros-parallel: Automatic uprev to 112.0.5589.0."',
              'submitted':
                  '2023-02-12 03:45:17.000000000',
          },
          {
              'branch': 'main',
              'cq_tries': '1',
              'created': '2024-11-27 04:13:33.000000000',
              'number': '6047780',
              'status': 'NEW',
              'subject': 'chromeos-chrome: Automatic uprev to 133.0.6862.0.',
          },
          {
              'branch': 'main',
              'cq_tries': '1',
              'created': '2024-11-27 04:13:33.000000000',
              'number': '6047783',
              'status': 'NEW',
              'subject': 'chromeos-chrome: Automatic uprev to 133.0.6862.0.',
          },
          {
              'branch':
                  'release-R130',
              'created':
                  '2023-02-11 14:56:09.000000000',
              'new_version':
                  '112.0.5584.0@deadbeef',
              'number':
                  '4242582',
              'old_version':
                  '112.0.5589.0@deadbeef',
              'revert_of':
                  '4242666',
              'status':
                  'MERGED',
              'subject':
                  'Revert "chromeos-chrome, chromeos-lacros-parallel: Automatic uprev to 112.0.5589.0."',
              'submitted':
                  '2023-02-12 03:45:17.000000000',
          },
      ]),
      status='SUCCESS',
  )
