# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe to fetch gardener related CLs.

For a gardener dashboard with up-to-date chrome uprev and LKGM commits status.
"""

import re
import base64
from google.protobuf import json_format

from PB.recipes.chromeos.gardener_data_collector import GardenerDataResult
from RECIPE_MODULES.chromeos.gerrit.api import ChangeInfo

from recipe_engine import recipe_api
from recipe_engine import post_process

DEPS = [
    'recipe_engine/context',
    'recipe_engine/file',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/step',
    'recipe_engine/time',
    'easy',
    'gerrit',
    'gitiles',
    'pupr',
]

GITILES_HOST = 'chromium.googlesource.com'
GERRIT_HOST = 'https://chromium-review.googlesource.com'
# Request only changes from last 7 days.
AGE_QUERY_PARAM = ('-age', '7d')
CHROME_UPREV_QUERY_PARAMS_BASE = [('repo',
                                   'chromiumos/overlays/chromiumos-overlay'),
                                  ('branch', 'main'), AGE_QUERY_PARAM]
LKGM_QUERY_PARAMS = [('repo', 'chromium/src'), ('hashtag', 'chrome-lkgm'),
                     AGE_QUERY_PARAM]
# Request messages (comments) to determine number of CQ tries.
COMMON_QUERY_O_PARAMS = ['MESSAGES', 'CURRENT_REVISION']
# Request also the modified files in the current revision for parsing the
# upreved Chrome version range.
CHROME_UPREV_QUERY_O_PARAMS = COMMON_QUERY_O_PARAMS + ['CURRENT_FILES']
# Request the full commit message in the current revision for parsing the
# upreved ChromeOS version range.
LKGM_QUERY_O_PARAMS = COMMON_QUERY_O_PARAMS + ['CURRENT_COMMIT']

CQ_RUN_TAG_RE = re.compile(r'^autogenerated:c[qv]:(full|dry)-run(:.*)?$')
RUNNING_RE = re.compile(r'C[QV] is trying the patch')
CHROME_VERSION_FROM_EBUILD_FILENAME_RE = re.compile(
    r'chromeos-base/[a-z-]+/[a-z-]+([0-9\.]+)_rc-r\d+.ebuild')


def parse_change_info(change_info: ChangeInfo) -> GardenerDataResult.Commit:
  return GardenerDataResult.Commit(
      number=change_info['_number'], created=change_info['created'],
      submitted=change_info.get('submitted'), branch=change_info['branch'],
      subject=change_info['subject'], status=change_info['status'],
      cq_tries=len([
          1 for message in change_info['messages']
          if 'tag' in message and CQ_RUN_TAG_RE.match(message['tag']) and
          RUNNING_RE.search(message['message'])
      ]), revert_of=change_info.get('revert_of'))


def parse_chrome_uprev_change_info(
    change_info: ChangeInfo) -> GardenerDataResult.Commit:
  result = parse_change_info(change_info)
  # Only the current revision should exist.
  for revision in change_info['revisions'].values():
    # Find Chrome uprev version range by parsing the ebuild files.
    # Ignore any non-renaming file changes and retry until there is one that
    # matches the expected pattern for extracting chrome version.
    # Any one of the chrome-base/{chrome-icu, chromeos-chrome, chromium-source}
    # ebuilds should work and provide identical result.
    for new_filename, changes in revision['files'].items():
      if changes['status'] and changes['status'] == 'R':
        new_version_match = CHROME_VERSION_FROM_EBUILD_FILENAME_RE.match(
            new_filename)
        if new_version_match:
          old_version_match = CHROME_VERSION_FROM_EBUILD_FILENAME_RE.match(
              changes['old_path'])
          if old_version_match:
            result.old_version = old_version_match[1]
            result.new_version = new_version_match[1]
            return result
  # Return result without uprev version range if failed to find them.
  return result  # pragma: nocover


def parse_lkgm_change_info(
    api: recipe_api.RecipeApi,
    change_info: ChangeInfo) -> GardenerDataResult.Commit:
  result = parse_change_info(change_info)
  # Only the current revision should exist.
  for revision, revision_info in change_info['revisions'].items():
    new_version = api.gitiles.get_file(
        GITILES_HOST, 'chromium/src', 'chromeos/CHROMEOS_LKGM', ref=revision,
        test_output_data=base64.b64encode(b'16110.0.0-1065034'))
    old_version = api.gitiles.get_file(
        GITILES_HOST, 'chromium/src', 'chromeos/CHROMEOS_LKGM',
        ref=revision_info['commit']['parents'][0]['commit'],
        test_output_data=base64.b64encode(b'16109.0.0-1065024'))
    if new_version and old_version and new_version != old_version:
      # split('-')[-1] takes the snapshot identifier if it is a snapshot, or the
      # release version if it is not.
      result.new_version = new_version.strip().split(b'-')[-1]
      result.old_version = old_version.strip().split(b'-')[-1]
      return result
  # Return result without uprev version range if failed to find them.
  # In theory, this shouldn't happen since we fetch the file of the commit hash
  # directly without relying on any commit message. Just in case so it doesn't
  # crash the recipes.
  return result  # pragma: nocover


def RunSteps(api: recipe_api.RecipeApi):
  with api.step.nest(
      'find last 7-day Chrome uprev (chromeos-base/chromeos-chrome) CLs'):
    results = api.gerrit.query_change_infos(
        GERRIT_HOST, CHROME_UPREV_QUERY_PARAMS_BASE +
        [('topic', 'chromeos-base/chromeos-chrome')],
        o_params=CHROME_UPREV_QUERY_O_PARAMS)
  with api.step.nest(
      'find last 7-day Chrome uprev (chromeos-base/lacros-ash-atomic) CLs'):
    results.extend(
        api.gerrit.query_change_infos(
            GERRIT_HOST, CHROME_UPREV_QUERY_PARAMS_BASE +
            [('topic', 'chromeos-base/lacros-ash-atomic')],
            o_params=CHROME_UPREV_QUERY_O_PARAMS))
    chrome_uprev_commits = list(map(parse_chrome_uprev_change_info, results))

  with api.step.nest('find last 7-day LKGM CLs'):
    results = api.gerrit.query_change_infos(GERRIT_HOST, LKGM_QUERY_PARAMS,
                                            o_params=LKGM_QUERY_O_PARAMS)
    lkgm_commits = [parse_lkgm_change_info(api, x) for x in results]

  api.easy.set_properties_step(
      'set output properties',
      chrome_uprev_commits=list(
          map(
              lambda m: json_format.MessageToDict(
                  m, preserving_proto_field_name=True), chrome_uprev_commits)),
      lkgm_commits=list(
          map(
              lambda m: json_format.MessageToDict(
                  m, preserving_proto_field_name=True), lkgm_commits)),
  )


def GenTests(api: recipe_api.RecipeApi):
  # A simplified returned json object for the chrome uprev commits query.
  chrome_uprev_gerrit_change_info_good = {
      'project':
          'chromiumos/overlays/chromiumos-overlay',
      'branch':
          'main',
      'change_id':
          'I29cf31ceeea219231177258a7bf87cb5d56d4a27',
      'subject':
          'chromeos-chrome: Automatic uprev to 133.0.6862.0.',
      'status':
          'NEW',
      'created':
          '2024-11-27 04:13:33.000000000',
      '_number':
          6047779,
      'revisions': {
          'c89a0ff2988dbd697d4375924dadec75832c79f3': {
              'files': {
                  'chromeos-base/chromium-source/chromium-source-133.0.6862.0_rc-r1.ebuild':
                      {
                          'status':
                              'R',
                          'old_mode':
                              33188,
                          'new_mode':
                              33188,
                          'old_path':
                              'chromeos-base/chromium-source/chromium-source-133.0.6861.0_rc-r1.ebuild',
                          'size_delta':
                              0,
                          'size':
                              494
                      },
              }
          }
      },
      'messages': [
          {
              'id':
                  '59cf36a6bf221ebbd133d35c2da786a2107d395f',
              'tag':
                  'autogenerated:gerrit:code-owners:addReviewer',
              'author': {
                  '_account_id': 1347071
              },
              'date':
                  '2024-11-27 04:13:36.000000000',
              'message':
                  '<GERRIT_ACCOUNT_1513692>, who was added as reviewer owns the following files:\n* `chromeos-base/chromeos-chrome/chromeos-chrome-133.0.6861.0_rc-r1.ebuild`\n* `chromeos-base/chromeos-chrome/chromeos-chrome-133.0.6862.0_rc-r1.ebuild`\n* `chromeos-base/chromium-source/chromium-source-133.0.6861.0_rc-r1.ebuild`\n* `chromeos-base/chromium-source/chromium-source-133.0.6862.0_rc-r1.ebuild`\n',
              'accounts_in_message': [{
                  '_account_id': 1513692
              }],
              '_revision_number':
                  1
          },
          {
              'id':
                  'fdd27b2724acde316dbfb261afa7cfdf6b514303',
              'tag':
                  'autogenerated:cq:dry-run',
              'author': {
                  '_account_id': 1530088
              },
              'date':
                  '2024-11-27 04:18:44.000000000',
              'message':
                  'Patch Set 1:\n\nDry run: CV is trying the patch.\n\nBot data: {\"action\":\"start\",\"triggered_at\":\"2024-11-27T04:13:41Z\",\"revision\":\"c89a0ff2988dbd697d4375924dadec75832c79f3\"}',
              'accounts_in_message': [],
              '_revision_number':
                  1
          },
      ],
  }

  chrome_uprev_gerrit_change_info_revert = {
      'project':
          'chromiumos/overlays/chromiumos-overlay',
      'branch':
          'main',
      'change_id':
          'I04d2973f924558150a243227092f01cf44e49a03',
      'subject':
          'Revert \"chromeos-chrome, chromeos-lacros-parallel: Automatic uprev to 112.0.5589.0.\"',
      'status':
          'MERGED',
      'created':
          '2023-02-11 14:56:09.000000000',
      'submitted':
          '2023-02-12 03:45:17.000000000',
      '_number':
          4242579,
      'revert_of':
          4242666,
      'revisions': {
          '9bbb014843d74f7536a66139067fd082b1a73d19': {
              'kind': 'REWORK',
              '_number': 5,
              'created': '2023-02-11 15:45:17.000000000',
              'uploader': {
                  '_account_id': 1355298
              },
              'ref': 'refs/changes/79/4242579/5',
              'fetch': {
                  'repo': {
                      'url': 'chromiumos/overlays/chromiumos-overlay',
                      'ref': 'refs/changes/79/4242579/5'
                  },
                  'http': {
                      'url':
                          'https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay',
                      'ref':
                          'refs/changes/79/4242579/5'
                  }
              },
              'branch': 'refs/heads/main',
              'files': {
                  'chromeos-base/chromeos-chrome/chromeos-chrome-112.0.5584.0_rc-r1.ebuild':
                      {
                          'status':
                              'R',
                          'old_mode':
                              33188,
                          'new_mode':
                              33188,
                          'old_path':
                              'chromeos-base/chromeos-chrome/chromeos-chrome-112.0.5589.0_rc-r1.ebuild',
                          'size_delta':
                              0,
                          'size':
                              48981
                      },
                  'chromeos-base/chromeos-lacros/Manifest': {
                      'old_mode': 33188,
                      'new_mode': 33188,
                      'lines_inserted': 6,
                      'lines_deleted': 6,
                      'size_delta': 0,
                      'size': 1976
                  }
              },
              'description': 'Rebase'
          },
      },
      'messages': [],
  }

  # A simplified returned json object for the LKGM commits query.
  lkgm_gerrit_change_info_good = {
      'project': 'chromium/src',
      'branch': 'main',
      'change_id': 'Ie5d42742d988003a3deb580e6dec7d5039a45016',
      'subject': 'Automated Commit: LKGM 16110.0.0-1065034 for chromeos.',
      'status': 'MERGED',
      'created': '2024-11-27 00:20:00.000000000',
      'submitted': '2024-11-27 03:27:44.000000000',
      '_number': 6052367,
      'messages': [{
          'id':
              'a0981969bab8f83a4b418efdf24025770bc03742',
          'tag':
              'autogenerated:cq:full-run',
          'author': {
              '_account_id': 1347153
          },
          'date':
              '2024-11-27 00:20:34.000000000',
          'message':
              'Patch Set 2:\n\nCV is trying the patch.\n\nFollow status at: https://luci-change-verifier.appspot.com/ui/run/chromium/8890303965854-1-a9931487c1eabfe0\n\nBot data: {\"action\":\"start\",\"triggered_at\":\"2024-11-27T00:20:31Z\",\"revision\":\"bad8c5823c23887f798b98daaeb94a4d04b8cca7\"}',
          'accounts_in_message': [],
          '_revision_number':
              2
      }, {
          'id':
              '44155dacf26a2bb94a5675e1a40fb954a6625bdb',
          'tag':
              'autogenerated:gerrit:merged',
          'author': {
              '_account_id': 1347153
          },
          'date':
              '2024-11-27 03:27:44.000000000',
          'message':
              'Change has been successfully rebased and submitted as 3256278a456c50c062fd5b8b082b8107e9c77a1f',
          'accounts_in_message': [],
          '_revision_number':
              3
      }],
      'revisions': {
          '3256278a456c50c062fd5b8b082b8107e9c77a1f': {
              'commit': {
                  'parents': [{
                      'commit':
                          '821901f8a13683d50420293f2e14cce7b9ccd49b',
                      'subject':
                          '[Autofill] Fix use-of-uninitialized-value in TestAutofillClient'
                  }],
                  'author': {
                      'name': 'ChromeOS bot',
                      'email': '3su6n15k.default@developer.gserviceaccount.com',
                      'date': '2024-11-27 03:27:44.000000000',
                      'tz': 0
                  },
                  'committer': {
                      'name':
                          'Chromium LUCI CQ',
                      'email':
                          'chromium-scoped@luci-project-accounts.iam.gserviceaccount.com',
                      'date':
                          '2024-11-27 03:27:44.000000000',
                      'tz':
                          0
                  },
                  'subject':
                      'Automated Commit: LKGM 16110.0.0-1065034 for chromeos.',
                  'message':
                      'Automated Commit: LKGM 16110.0.0-1065034 for chromeos.\n'
              },
              'branch': 'refs/heads/main',
              'description': 'Rebase'
          }
      },
  }

  yield api.test(
      'success',
      api.gerrit.set_query_changes_response(
          'find last 7-day Chrome uprev (chromeos-base/chromeos-chrome) CLs', [
              chrome_uprev_gerrit_change_info_good,
              chrome_uprev_gerrit_change_info_revert
          ], 'https://chromium-review.googlesource.com'),
      api.gerrit.set_query_changes_response(
          'find last 7-day Chrome uprev (chromeos-base/lacros-ash-atomic) CLs',
          [], 'https://chromium-review.googlesource.com'),
      api.gerrit.set_query_changes_response(
          'find last 7-day LKGM CLs', [lkgm_gerrit_change_info_good],
          'https://chromium-review.googlesource.com'),
      api.post_process(post_process.PropertyEquals, 'chrome_uprev_commits', [{
          'branch': 'main',
          'cq_tries': '1',
          'created': '2024-11-27 04:13:33.000000000',
          'new_version': '133.0.6862.0',
          'number': '6047779',
          'old_version': '133.0.6861.0',
          'status': 'NEW',
          'subject': 'chromeos-chrome: Automatic uprev to 133.0.6862.0.',
      }, {
          'branch':
              'main',
          'created':
              '2023-02-11 14:56:09.000000000',
          'new_version':
              '112.0.5584.0',
          'number':
              '4242579',
          'old_version':
              '112.0.5589.0',
          'revert_of':
              '4242666',
          'status':
              'MERGED',
          'subject':
              'Revert \"chromeos-chrome, chromeos-lacros-parallel: Automatic uprev to 112.0.5589.0.\"',
          'submitted':
              '2023-02-12 03:45:17.000000000',
      }]),
      api.post_process(post_process.PropertyEquals, 'lkgm_commits', [{
          'branch': 'main',
          'cq_tries': '1',
          'created': '2024-11-27 00:20:00.000000000',
          'new_version': '1065034',
          'number': '6052367',
          'old_version': '1065024',
          'status': 'MERGED',
          'subject': 'Automated Commit: LKGM 16110.0.0-1065034 for chromeos.',
          'submitted': '2024-11-27 03:27:44.000000000',
      }]),
      status='SUCCESS',
  )
