// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.gce_test;

import "chromiumos/common.proto";
import "testplans/generate_test_plan.proto";

message GceTestProperties {
  // A unique name for the test, used to record test results.
  string name = 1;

  // The build target under test.
  chromiumos.BuildTarget build_target = 2;

  // The build payload to test.
  testplans.BuildPayload build_payload = 3;

  // Expressions describing tests to run. It is either a test name
  // ("example.Pass") or involves tast attributes (see go/tast-attr).
  repeated string expressions = 4;

  message GceMetadata {
    // The GCE project in which we create GCE images/instances for test.
    string project = 1;

    // The GCE zone in which we create GCE instances for test.
    string zone = 2;

    // The machine type of the GCE instance (e.g. n2-standard-8).
    string machine_type = 3;

    // The network the GCE instance should be part of.
    string network = 4;

    // The subnet the GCE instance should be part of.
    string subnet = 5;
  }

  // GCE-related metadata fields.
  GceMetadata gce_metadata = 5;

  // TotalShards is the total number of shards to be used in a test run.
  // Note: Each build will only run one shard. It is up to the caller to
  // schedule one build per shard with the appropriate shard_index values.
  int64 total_shards = 6;

  // ShardIndex specifies the index of the shard to used in the current run.
  // Note: This value is 0-indexed.
  int64 shard_index = 7;

  // Which sharding method should we pass to tast.
  string shard_method = 8;
}
