// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.generator;

import "chromiumos/common.proto";

message G3OncallRotation {
  // The name of the oncall rotation, e.g. chromeos-sheriffs-west.
  string name = 1;

  // The rotation position.
  enum Position {
    UNSPECIFIED = 0;
    PRIMARY = 1;
    SECONDARY = 2;
    PRIMARY_AND_SECONDARY = 3;
  }
  Position position = 2;
}

// A reviewer must be some user known by Gerrit. Could be an email
// alias that is processed by GWS.
message Reviewer {
  string email = 1;
}

// Describes how to send a CL to CQ (i.e., dry run, .
enum SendToCqPolicy {
  // Policy was not specified
  UNSPECIFIED = 0;

  // Leave the CL be, add no tags.
  DO_NOTHING = 1;

  // Send the CL through a CQ dry run, but not the real deal.
  DRY_RUN = 2;

  // Send the CL through the full CQ.
  FULL_RUN = 3;

  // Abandon the CL.
  ABANDON = 4;
}

message GeneratorProperties {
  // The package to generate CLs for.
  chromiumos.PackageInfo package_info = 1;

  // The reviewer(s) to tag on generated CLs.
  repeated Reviewer reviewers = 2;

  // Tag to add to all generated CLs. Defaults to qualified package name.
  string topic = 3;

  // Policy to follow when no related CLs exist. Defaults to DO_NOTHING.
  SendToCqPolicy no_existing_cls_policy = 4;

  // Policy to follow when related CLs exist. Defaults to DO_NOTHING.
  SendToCqPolicy existing_cls_policy = 5;
}
