# -*- coding: utf-8 -*-
# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for the PUpr generator.

PUpr is a general uprev pipeline that listens for package releases (via LUCI
Scheduler gitiles triggers), generates ebuild uprev CLs for those releases,
and tags the appropriate reviewers. Think of it as the CrOS autoroller.

See go/pupr and go/pupr-generator for rationale and design decisions.
"""

import collections
import urlparse

from PB.chromiumos.common import PackageInfo
from PB.chromite.api.packages import UprevVersionedPackageRequest
from PB.recipes.chromeos.generator import DO_NOTHING
from PB.recipes.chromeos.generator import DRY_RUN
from PB.recipes.chromeos.generator import FULL_RUN
from PB.recipes.chromeos.generator import GeneratorProperties
from PB.recipes.chromeos.generator import G3OncallRotation
from PB.recipes.chromeos.generator import Reviewer
from PB.recipes.chromeos.generator import SendToCqPolicy
from PB.go.chromium.org.luci.scheduler.api.scheduler.v1 import (
    triggers as triggers_pb2)

from google.protobuf import json_format


DEPS = {
    'depot_tools': 'depot_tools/depot_tools',
    'gerrit': 'depot_tools/gerrit',
    'git_cl': 'depot_tools/git_cl',
    'buildbucket': 'recipe_engine/buildbucket',
    'context': 'recipe_engine/context',
    'file': 'recipe_engine/file',
    'path': 'recipe_engine/path',
    'properties': 'recipe_engine/properties',
    'raw_io': 'recipe_engine/raw_io',
    'scheduler': 'recipe_engine/scheduler',
    'step': 'recipe_engine/step',
    'cros_build_api': 'cros_build_api',
    'cros_cq_depends': 'cros_cq_depends',
    'cros_gerrit': 'gerrit',
    'cros_sdk': 'cros_sdk',
    'cros_source': 'cros_source',
    'g3oncall': 'g3oncall',
    'git': 'git',
    'naming': 'naming',
    'repo': 'repo',
}

PROPERTIES = GeneratorProperties

def RunSteps(api, properties):
  with api.step.nest('validate properties') as step:
    if not properties.HasField('package_info'):
      raise ValueError('must set package_info')

    if not properties.reviewers:
      raise ValueError('need at least one reviewer')

    for reviewer in properties.reviewers:
      if reviewer.WhichOneof('identifier') is None:
        raise ValueError('must set reviewer idenifier')

    step.presentation.step_text = 'all properties good'

  triggers = api.scheduler.triggers
  with api.step.nest('validate triggers') as step:
    if not triggers:
      raise ValueError('found no scheduler triggers')

    for trigger in triggers:
      if not trigger.HasField('gitiles'):
        raise ValueError('found non-gitiles trigger: %r', trigger)

    step.presentation.step_text = 'all {} triggers good'.format(len(triggers))
    step.presentation.logs['list of triggers'] = map(json_format.MessageToJson,
                                                     triggers)

  package = properties.package_info
  cpv = api.naming.get_package_title(package)

  api.cros_source.ensure_synced_cache()
  with api.cros_source.checkout_overlays_context():
    with api.step.nest('try uprev {}'.format(cpv)) as step:
      request = UprevVersionedPackageRequest(
          chroot=api.cros_sdk.chroot,
          package_info=package,
          versions=[
              UprevVersionedPackageRequest.GitRef(
                  repository=urlparse.urlparse(trigger.gitiles.repo).path,
                  ref=trigger.gitiles.ref,
                  revision=trigger.gitiles.revision)
              for trigger in triggers
          ],
      )
      response = api.cros_build_api.PackageService.UprevVersionedPackage(
          request, name='uprev versioned package')

      if not response.modified_ebuilds:
        step.presentation.step_text = 'no new versions for {}'.format(cpv)
        return

    with api.step.nest('commit uprev'):
      commit_lines = [
          'Automatic uprev for package {}.'.format(cpv),
          'Generated by PUpr, see {} for job details.'.format(
              api.buildbucket.build_url()),
      ]
      commit_message = '\n\n'.join(commit_lines)

      ebuilds_by_repository = collections.defaultdict(list)
      for ebuild in response.modified_ebuilds:
        path = ebuild.path
        with api.context(cwd=api.path.abs_to_path(api.path.dirname(path))):
          ebuilds_by_repository[api.git.repository_root()].append(path)

      for repository, ebuilds in ebuilds_by_repository.iteritems():
        name = api.path.basename(repository)
        root = api.path.abs_to_path(repository)
        with api.step.nest('commit in {}'.format(name)), api.context(cwd=root):
          api.git.add(ebuilds)
          api.git.commit(commit_message)

  reviewer_users = set()
  with api.step.nest('resolve reviewers') as step:
    step.presentation.logs['resolved reviewers with reasons'] = logs = []
    for reviewer in properties.reviewers:
      # If it's just a chromium user, easy peasy.
      if reviewer.HasField('chromium_user'):
        user = reviewer.chromium_user
        reviewer_users.add(user)
        logs.append('{} (hardcoded in config)'.format(user))
        continue

      # Otherwise we must resolve an oncall rotation.
      rotation = reviewer.g3oncall_rotation
      oncall = api.g3oncall.status(rotation.name)
      if rotation.position in (G3OncallRotation.PRIMARY,
                               G3OncallRotation.PRIMARY_AND_SECONDARY,
                               G3OncallRotation.UNSPECIFIED):
        user = oncall.primary
        reviewer_users.add(user)
        logs.append('{} (primary for {})'.format(user, rotation.name))
      if rotation.position in (G3OncallRotation.SECONDARY,
                               G3OncallRotation.PRIMARY_AND_SECONDARY):
        user = oncall.secondary
        reviewer_users.add(user)
        logs.append('{} (secondary for {})'.format(user, rotation.name))

  topic = properties.topic or cpv
  with api.step.nest('find existing uprev CLs') as step:
    existing_change_urls = set()
    for host in ('chromium', 'chrome-internal'):
      with api.step.nest('find cls from {} host'.format(host)):
        host_url = 'https://{}-review.googlesource.com'.format(host)
        found = api.gerrit.get_changes(
            host_url, [('topic', topic), ('status', 'open')])

        for change in found:
          number = change['_number']
          date = change['created']
          title = 'found {} (created {})'.format(number, date)
          change_url = '{}/{}'.format(host_url, number)
          step.presentation.links[title] = change_url
          existing_change_urls.add(change_url)

  with api.step.nest('generate CLs') as step:
    repositories = map(api.path.abs_to_path, ebuilds_by_repository.keys())
    for repository in repositories:
      with api.context(cwd=repository), api.depot_tools.on_path():
        args = [
            '--bypass-hooks',
            '--force',
            '--send-mail',
            '--topic', topic,
        ]

        args.append('--reviewers')
        args.extend('{}@chromium.org'.format(ru) for ru in reviewer_users)

        api.git_cl.upload('''
                     ,
                ,.  | \
               |: \ ; :\
               :' ;\| ::\
                \ : | `::\
                _)  |   `:`.
              ,' , `.    ;: ;
            ,' ;:  ;"'  ,:: |_
           /,   ` .    ;::: |:`-.__
        _,' _o\  ,::.`:' ;  ;   . '
    _,-'           `:.          ;""\,
 ,-'                     ,:         `-;,
 \,                       ;:           ;--._
  `.______,-,----._     ,' ;:        ,/ ,  ,`
         / /,-';'  \     ; `:      ,'/,::.:::
       ,',;-'-'_,--;    ;   :.   ,',',;::::::
      ( /___,-'     `.     ;::,,'o/  ,:::::::
       `'             )    ;:,'o /  ;"-   -::
                      \__ _,'o ,'         ,::
                         ) `--'       ,..::::
      -pupr-             ; `.        ,:::::::
                          ;  ``::.    :::::::
        ''', args)

  if len(repositories) > 1:
    with api.step.nest('cq-depend generated CLs'):
      change_urls = []
      for repository in repositories:
        step_name = 'read {} gerrit URL'.format(api.path.dirname(repository))
        with api.step.nest(step_name), api.context(
            cwd=repository), api.depot_tools.on_path():
          change_url = api.git_cl(
              'status', ['--field', 'url', '--fast'],
              stdout=api.raw_io.output(),
              # TODO(evanhernandez): Yuck. Let's put a module around this...
              step_test_data=lambda:
                 api.raw_io.test_api.stream_output(
                     api.cros_gerrit.test_api.test_gerrit_change_url()),
          ).stdout.strip()
          change_urls.append(change_url)

      changes = map(api.cros_gerrit.parse_gerrit_change, change_urls)
      cq_depends = api.cros_cq_depends.get_mutual_cq_depend(changes)

      for repository, change_url, cq_depend in zip(repositories,
                                                   change_urls,
                                                   cq_depends):
        step_name = 'set cq-depend for {} CL'.format(repository)
        with api.step.nest(step_name), api.context(
            cwd=repository), api.depot_tools.on_path():
          description = api.git_cl.get_description(patch_url=change_url,
                                                   codereview='gerrit')
          description = '{}\n{}'.format(description, cq_depend)
          api.git_cl.set_description(description, patch_url=change_url,
                                     codereview='gerrit')

  existing_cls_policy = properties.existing_cls_policy or DO_NOTHING
  no_existing_cls_policy = properties.no_existing_cls_policy or DO_NOTHING
  send_to_cq_policy = (existing_cls_policy
                       if existing_change_urls else no_existing_cls_policy)

  with api.step.nest('update CL labels'):
    for repository in repositories:
      args = ['--bypass-hooks', '--force', '--send-mail']
      upload_message_lines = [
          'Found {} open CL(s) for Gerrit topic {}:'.format(
              len(existing_change_urls), topic),
      ]
      upload_message_lines.append('\n'.join(existing_change_urls))
      upload_message_lines.append(
          'Send-to-cq policy for this case is {}.'.format(
              SendToCqPolicy.Name(send_to_cq_policy)))

      if send_to_cq_policy == DRY_RUN:
        args.append('--cq-dry-run')
        upload_message_lines.append('Therefore, marking CL as CQ+1.')
      elif send_to_cq_policy == FULL_RUN:
        args.append('--use-commit-queue')
        upload_message_lines.append('Therefore, marking CL as CQ+2.')
      else:
        upload_message_lines.append(
            'Therefore, will NOT mark CL as CQ+1/CQ+2. Reviewers must do so. '
            'Reviewers may also want to abandon the existing CL(s).')

      upload_message = '\n\n'.join(upload_message_lines)
      with api.step.nest(api.path.dirname(repository)), api.context(
          cwd=repository), api.depot_tools.on_path():
        # Must set CR+2 to send to CQ. We do this via Gerrit magic.
        if send_to_cq_policy == FULL_RUN:
          with api.step.nest('mark CL with code-review +2'):
            project_infos = api.repo.project_infos(projects=[repository])
            assert project_infos, 'need project info for {}'.format(repository)
            project_info = project_infos[0]
            api.git.push(
                project_info.remote,
                'HEAD:refs/for/{}%l=Code-Review+2'.format(project_info.branch))

        # Then, do the thing.
        api.git_cl.upload(upload_message, args)


def GenTests(api):
  package = PackageInfo(category='chromeos-base', package_name='chromite')
  properties = json_format.MessageToDict(
      GeneratorProperties(
          package_info=package,
          reviewers=[
              Reviewer(chromium_user='evanhernandez'),
              Reviewer(
                  g3oncall_rotation=G3OncallRotation(
                      name='chromeos-ci-eng',
                      position=G3OncallRotation.PRIMARY_AND_SECONDARY,
                  ),
              ),
          ],
      ),
  )
  gitiles_triggers = [
      triggers_pb2.Trigger(
          id='123',
          gitiles=triggers_pb2.GitilesTrigger(
              repo='chromiumos/chromite',
              ref='refs/heads/master',
              revision='deadbeef',
          ),
      ),
  ]

  yield (api.test('with-uprev-do-nothing-policy') +
         api.properties(existing_cls_policy=DO_NOTHING, **properties) +
         api.scheduler(triggers=gitiles_triggers) +
         api.g3oncall.status(
             'resolve reviewers.resolve chromeos-ci-eng rotation status'))

  yield (api.test('with-uprev-dry-run-policy') +
         api.properties(existing_cls_policy=DRY_RUN, **properties) +
         api.scheduler(triggers=gitiles_triggers) +
         api.g3oncall.status(
             'resolve reviewers.resolve chromeos-ci-eng rotation status'))

  yield (api.test('with-uprev-full-run-policy') +
         api.properties(existing_cls_policy=FULL_RUN, **properties) +
         api.scheduler(triggers=gitiles_triggers) +
         api.g3oncall.status(
             'resolve reviewers.resolve chromeos-ci-eng rotation status'))

  yield api.test('no-package-info') + api.expect_exception('ValueError')

  yield (api.test('no-reviewers') +
         api.properties(package_info=package) +
         api.expect_exception('ValueError'))

  yield (api.test('blank-reviewer') +
         api.properties(package_info=package, reviewers=[{}]) +
         api.expect_exception('ValueError'))

  yield (api.test('no-triggers') +
         api.properties(**properties) +
         api.scheduler(triggers=[]) +
         api.expect_exception('ValueError'))

  yield (api.test('non-gitiles-triggers') +
         api.properties(**properties) +
         api.scheduler(triggers=[
             triggers_pb2.Trigger(id='456', webui=triggers_pb2.WebUITrigger()),
         ]) +
         api.expect_exception('ValueError'))

  yield (api.test('without-uprev') +
         api.properties(**properties) +
         api.scheduler(triggers=gitiles_triggers) +
         api.step_data(
             'try uprev chromeos-base/chromite.uprev versioned package'
             '.read output file',
             api.file.read_raw(content='{}')))
