// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.generator;

import "chromiumos/common.proto";

message G3OncallRotation {
  // The name of the oncall rotation, e.g. chromeos-sheriffs-west.
  string name = 1;

  // The rotation position.
  enum Position {
    UNSPECIFIED = 0;
    PRIMARY = 1;
    SECONDARY = 2;
    PRIMARY_AND_SECONDARY = 3;
  }
  Position position = 2;
}

// A reviewer must be a chromium.org user or a g3oncall rotation.
message Reviewer {
  oneof identifier {
    // The rotation in which to look for reviewers. The "name" field
    // identifies the rotation, and the "position" field identifies whether
    // primary, secondary, or both should be added as reviewer. Latter
    // defaults to primary.
    G3OncallRotation g3oncall_rotation = 1;

    // The chromium.org username WITHOUT the @chromium.org extension.
    string chromium_user = 2;
  }
}

// Describes when to mark a CL as CQ+2. Defaults to NO_ACTIVE_CLS.
enum SendToCqPolicy {
  // Policy was not specified
  UNSPECIFIED = 0;

  // Only mark CLs as CQ+2 if no existing CLs are found.
  NO_ACTIVE_CLS = 1;

  // Always mark CLs as CQ+2.
  ALWAYS = 2;

  // Never mark CLs as CQ+2.
  NEVER = 3;
}

message GeneratorProperties {
  // The package to generate CLs for.
  chromiumos.PackageInfo package_info = 1;

  // The reviewer(s) to tag on generated CLs.
  repeated Reviewer reviewers = 2;

  // Policy to follow for sending generated CLs to CQ.
  SendToCqPolicy send_to_cq_policy = 3;

  // Tag to add to all generated CLs. Defaults to qualified package name.
  string tag = 4;
}
