# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for performing various operations against the online HSMs."""

from PB.chromite.api.signing import CreateKeysHsmRequest
from PB.recipes.chromeos.hsm_manager import HSMManagerProperties
from PB.go.chromium.org.luci.buildbucket.proto import (
    builder_common as builder_common_pb2,)
from PB.go.chromium.org.luci.buildbucket.proto import build as build_pb2
from recipe_engine import post_process
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_api import StepFailure
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    "recipe_engine/buildbucket",
    "recipe_engine/context",
    "recipe_engine/file",
    "recipe_engine/path",
    "recipe_engine/properties",
    "recipe_engine/step",
    "build_menu",
    "cros_build_api",
    "cros_try",
    "easy",
    "gerrit",
    "git",
    "signing",
    "src_state",
]

PROPERTIES = HSMManagerProperties


def RunSteps(api: RecipeApi, properties: HSMManagerProperties):
  if not properties.bug:
    raise StepFailure("`bug` is a required property.")

  if not properties.HasField("create_keys_hsm_request"):
    raise StepFailure("`create_keys_hsm_request` is a required property.")

  with api.step.nest("set up dependencies"):
    api.git.clone(
        "https://chromium.googlesource.com/chromiumos/chromite/",
        target_path=api.src_state.workspace_path / "infra/chromite-HEAD",
        branch="main",
        single_branch=True,
    )

    api.git.clone(
        "https://chromium.googlesource.com/chromiumos/chromite/",
        target_path=api.src_state.workspace_path / "infra/chromite",
        branch="main",
        single_branch=True,
    )

    release_keys_path = api.src_state.workspace_path.joinpath(
        "src/platform/signing/keys")
    api.git.clone(
        "https://chrome-internal.googlesource.com/chromeos/platform/release-keys",
        target_path=release_keys_path,
        branch="main",
        single_branch=True,
    )

  with api.step.nest("create HSM keys"):
    api.step(
        "docker auth",
        [
            "gcloud",
            "auth",
            "configure-docker",
            "us-docker.pkg.dev",
        ],
    )
    api.step(
        "docker pull",
        [
            "docker",
            "pull",
            api.signing.signing_docker_image,
        ],
    )

    is_staging = api.build_menu.is_staging
    create_keys_hsm_request = properties.create_keys_hsm_request
    # These fields shouldn't be set by the user, but in any case
    # set them here (potentially overwriting existing values).
    create_keys_hsm_request.docker_image = api.signing.signing_docker_image
    create_keys_hsm_request.release_keys_checkout = str(release_keys_path)
    # Default to dry run in staging.
    if not create_keys_hsm_request.HasField("dry_run"):
      create_keys_hsm_request.dry_run = is_staging
    api.cros_build_api.SigningService.CreateKeysHsm(create_keys_hsm_request)

    # TODO(b/505067933): Notify quorum members that there is a new quorum operation.

    # TODO(b/505067810): Commit keyset to release-keys after files changes.
    # with api.step.nest("commit keyset to release-keys"), api.context(
    #     cwd=release_keys_path):
    #   commit_lines = [
    #       f"Create HSM keys for {create_keys_hsm_request.keyset_name}",
    #       "",
    #       f"Generated by hsm-manager, see {api.buildbucket.build_url()} for job details.",
    #   ]
    #   if is_staging:
    #       commit_lines += [
    #           "This CL was created for staging, it is not meant to be submitted."
    #       ]
    #   commit_lines += [
    #       "",
    #       f"BUG=b:{properties.bug}",
    #       "TEST=CQ",
    #   ]

    #   # Regenerate generated files.
    #   api.step(
    #       "regenerate generated files",
    #       ["./keyset/public/scripts/regenerate_keysets.sh", "--all"],
    #   )

    #   api.git.add_all()
    #   api.git.commit("\n".join(commit_lines) + "\n")

    #   reviewers = [] if is_staging else ["croskeymanagers@google.com"]
    #   invoker = api.cros_try.get_invoker()
    #   change = api.gerrit.create_change(
    #       str(release_keys_path),
    #       project_path=release_keys_path,
    #       non_repo_checkout=True,
    #       reviewers=reviewers,
    #       ccs=[invoker] if invoker else [],
    #   )
    #   api.easy.set_properties_step(
    #       keyset_commit=api.gerrit.parse_gerrit_change_url(change))

    #   if is_staging:
    #       api.gerrit.abandon_change(change)


def GenTests(api: RecipeTestApi):
  yield api.test(
      "hsm-create-keys",
      api.properties(
          HSMManagerProperties(
              create_keys_hsm_request=CreateKeysHsmRequest(
                  keyset_name="FooPreMPKeys"), bug=12345)),
      api.post_check(
          post_process.MustRun,
          "create HSM keys.call chromite.api.SigningService/CreateKeysHsm"),
      # TODO(b/505067810): Commit keyset to release-keys after files changes.
      # api.post_check(
      #     post_process.MustRun,
      #     "create HSM keys.commit keyset to release-keys.regenerate generated files"
      # ),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      "staging-hsm-create-keys",
      api.buildbucket.build(
          build_pb2.Build(
              builder=builder_common_pb2.BuilderID(
                  project="chromeos",
                  bucket="staging",
                  builder="staging-hsm-manager",
              ))),
      api.properties(
          HSMManagerProperties(
              create_keys_hsm_request=CreateKeysHsmRequest(
                  keyset_name="FooPreMPKeys"), bug=12345)),
      api.post_check(
          post_process.MustRun,
          "create HSM keys.call chromite.api.SigningService/CreateKeysHsm"),
      # TODO(b/505067810): Commit keyset to release-keys after files changes.
      # api.post_check(
      #     post_process.MustRun,
      #     "create HSM keys.commit keyset to release-keys.abandon CL 1"),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      "missing-bug",
      api.properties(
          HSMManagerProperties(
              create_keys_hsm_request=CreateKeysHsmRequest(
                  keyset_name="FooPreMPKeys")),
      ),
      api.post_check(post_process.SummaryMarkdown,
                     "`bug` is a required property."),
      api.post_process(post_process.DropExpectation),
      status="FAILURE",
  )

  yield api.test(
      "missing-request",
      api.properties(
          HSMManagerProperties(bug=123),
      ),
      api.post_check(post_process.SummaryMarkdown,
                     "`create_keys_hsm_request` is a required property."),
      api.post_process(post_process.DropExpectation),
      status="FAILURE",
  )
