# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for performing various operations against the online HSMs."""

from PB.chromite.api.signing import CreateKeysHsmRequest
from PB.recipes.chromeos.hsm_manager import HSMManagerProperties
from PB.go.chromium.org.luci.buildbucket.proto import (
    builder_common as builder_common_pb2,)
from PB.go.chromium.org.luci.buildbucket.proto import build as build_pb2
from PB.go.chromium.org.luci.buildbucket.proto import common as common_pb2
from PB.recipe_engine import result as result_pb2
from recipe_engine import post_process
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_api import StepFailure
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    "recipe_engine/buildbucket",
    "recipe_engine/context",
    "recipe_engine/file",
    "recipe_engine/path",
    "recipe_engine/properties",
    "recipe_engine/step",
    "build_menu",
    "cros_build_api",
    "cros_try",
    "easy",
    "gerrit",
    "git",
    "keyset_utils",
    "signing",
    "src_state",
]

PROPERTIES = HSMManagerProperties


def RunSteps(api: RecipeApi, properties: HSMManagerProperties):
  if not properties.bug:
    raise StepFailure("`bug` is a required property.")

  if not properties.HasField("create_keys_hsm_request"):
    raise StepFailure("`create_keys_hsm_request` is a required property.")

  with api.step.nest("set up dependencies"):
    api.git.clone(
        "https://chromium.googlesource.com/chromiumos/chromite/",
        target_path=api.src_state.workspace_path / "infra/chromite-HEAD",
        branch="main",
        single_branch=True,
    )

    api.git.clone(
        "https://chromium.googlesource.com/chromiumos/chromite/",
        target_path=api.src_state.workspace_path / "infra/chromite",
        branch="main",
        single_branch=True,
    )

    release_keys_path = api.src_state.workspace_path.joinpath(
        "src/platform/signing/keys")
    api.git.clone(
        "https://chrome-internal.googlesource.com/chromeos/platform/release-keys",
        target_path=release_keys_path,
        branch="main",
        single_branch=True,
    )

  with api.step.nest("create HSM keys"):
    api.step(
        "docker auth",
        [
            "gcloud",
            "auth",
            "configure-docker",
            "us-docker.pkg.dev",
        ],
    )
    api.step(
        "docker pull",
        [
            "docker",
            "pull",
            api.signing.signing_docker_image,
        ],
    )

    is_staging = api.build_menu.is_staging
    create_keys_hsm_request, error_msg = api.keyset_utils.create_hsm_request(
        properties.create_keys_hsm_request,
        release_keys_path,
        api.signing.signing_docker_image,
        is_staging,
        build_target=properties.build_target,
        is_mp=properties.is_mp if properties.HasField("is_mp") else None,
    )
    if error_msg:
      return result_pb2.RawResult(
          status=common_pb2.FAILURE,
          summary_markdown=f"Keyset Validation Failed\n\n{error_msg}",
      )

    api.cros_build_api.SigningService.CreateKeysHsm(create_keys_hsm_request)

    # TODO(b/505067933): Notify quorum members that there is a new quorum operation.

    with api.step.nest("commit keyset to release-keys"), api.context(
        cwd=release_keys_path):
      commit_lines = [
          f"Create HSM keys for {create_keys_hsm_request.keyset_name}",
          "",
          f"Generated by hsm-manager, see {api.buildbucket.build_url()} for job details.",
      ]
      if is_staging:
        commit_lines += [
            "This CL was created for staging, it is not meant to be submitted."
        ]
      commit_lines += [
          "",
          f"BUG=b:{properties.bug}",
          "TEST=CQ",
      ]

      # Regenerate generated files.
      api.step(
          "regenerate generated files",
          ["./keyset/public/scripts/regenerate_keysets.sh", "--all"],
      )

      api.git.add_all()
      api.git.commit("\n".join(commit_lines) + "\n")

      reviewers = [] if is_staging else ["croskeymanagers@google.com"]
      invoker = api.cros_try.get_invoker()
      change = api.gerrit.create_change(
          str(release_keys_path),
          project_path=release_keys_path,
          non_repo_checkout=True,
          reviewers=reviewers,
          ccs=[invoker] if invoker else [],
      )
      api.easy.set_properties_step(
          keyset_commit=api.gerrit.parse_gerrit_change_url(change))

      if is_staging:
        api.gerrit.abandon_change(change)
    return result_pb2.RawResult(
        status=common_pb2.SUCCESS,
        summary_markdown=f"Keyset created: {create_keys_hsm_request.keyset_name}",
    )


def GenTests(api: RecipeTestApi):
  yield api.test(
      "hsm-create-keys",
      api.properties(
          HSMManagerProperties(
              create_keys_hsm_request=CreateKeysHsmRequest(
                  keyset_name="FooPreMPKeys"), bug=12345)),
      api.post_check(
          post_process.MustRun,
          "create HSM keys.call chromite.api.SigningService/CreateKeysHsm"),
      api.post_check(
          post_process.MustRun,
          "create HSM keys.commit keyset to release-keys.regenerate generated files"
      ),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      "staging-hsm-create-keys",
      api.buildbucket.build(
          build_pb2.Build(
              builder=builder_common_pb2.BuilderID(
                  project="chromeos",
                  bucket="staging",
                  builder="staging-hsm-manager",
              ))),
      api.properties(
          HSMManagerProperties(
              create_keys_hsm_request=CreateKeysHsmRequest(
                  keyset_name="FooPreMPKeys"), bug=12345)),
      api.post_check(
          post_process.MustRun,
          "create HSM keys.call chromite.api.SigningService/CreateKeysHsm"),
      api.post_check(
          post_process.MustRun,
          "create HSM keys.commit keyset to release-keys.abandon CL 1"),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      "missing-bug",
      api.properties(
          HSMManagerProperties(
              create_keys_hsm_request=CreateKeysHsmRequest(
                  keyset_name="FooPreMPKeys")),
      ),
      api.post_check(post_process.SummaryMarkdown,
                     "`bug` is a required property."),
      api.post_process(post_process.DropExpectation),
      status="FAILURE",
  )

  yield api.test(
      "missing-request",
      api.properties(
          HSMManagerProperties(bug=123),
      ),
      api.post_check(post_process.SummaryMarkdown,
                     "`create_keys_hsm_request` is a required property."),
      api.post_process(post_process.DropExpectation),
      status="FAILURE",
  )

  yield api.test(
      "hsm-create-keys-calc-next",
      api.properties(
          HSMManagerProperties(create_keys_hsm_request=CreateKeysHsmRequest(),
                               build_target="atlas", is_mp=True, bug=12345)),
      api.step_data(
          "create HSM keys.calc next keyset version.list existing keysets",
          api.file.listdir(["AtlasMPKeys-v2"]),
      ),
      api.post_check(
          post_process.MustRun,
          "create HSM keys.call chromite.api.SigningService/CreateKeysHsm"),
      api.post_check(post_process.LogEquals, 'create HSM keys.requested keyset',
                     'keyset_name', 'AtlasMPKeys-v3'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      "hsm-create-keyset-exists-failure",
      api.properties(
          HSMManagerProperties(
              create_keys_hsm_request=CreateKeysHsmRequest(
                  keyset_name="AtlasMPKeys-v2"), bug=12345)),
      api.path.exists(api.src_state.workspace_path /
                      "src/platform/signing/keys/keyset/public/AtlasMPKeys-v2"),
      api.post_check(
          post_process.SummaryMarkdownRE,
          r".*Keyset `AtlasMPKeys-v2` already exists.*",
      ),
      api.post_process(post_process.DropExpectation),
      status="FAILURE",
  )
