# -*- coding: utf-8 -*-
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for uprev'ing shadercache DLC ebuilds"""

from RECIPE_MODULES.chromeos.gerrit.api import Label

from PB.recipes.chromeos.kabuto_shadercache_uprev import (
    KabutoShadercacheUprevProperties)
from recipe_engine import post_process
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_api import StepFailure
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    'recipe_engine/bcid_reporter',
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/file',
    'recipe_engine/json',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'depot_tools/depot_tools',
    'build_menu',
    'cros_infra_config',
    'cros_sdk',
    'cros_source',
    'cros_version',
    'failures',
    'gerrit',
    'git',
    'src_state',
    'repo',
]

PROPERTIES = KabutoShadercacheUprevProperties
GERRIT_CL_TOPIC = 'borealis-shadercache-dlc'
GERRIT_CL_REVIEWERS = [
    'davidriley@google.com', 'endlesspring@google.com', 'pobega@google.com'
]

_MILESTONE_USES_KABUTO_UPREV = 118

PYTHON_VERSION_COMPATIBILITY = 'PY3'


def RunSteps(api: RecipeApi,
             properties: KabutoShadercacheUprevProperties) -> None:
  with api.step.nest('validate properties') as presentation:
    if not properties.uprev_info:
      raise StepFailure('must set uprev_info')
    presentation.step_text = 'all properties good'

  with api.failures.ignore_exceptions():
    if not api.cros_infra_config.is_staging:
      api.bcid_reporter.report_stage('start')

  commit = None
  if properties.manifest_branch:
    commit = api.src_state.internal_manifest.as_gitiles_commit_proto
    commit.ref = 'refs/heads/{}'.format(properties.manifest_branch)

  with api.build_menu.configure_builder(commit=commit, missing_ok=True), \
    api.build_menu.setup_workspace(), api.cros_sdk.cleanup_context():
    api.cros_sdk.create_chroot(timeout_sec=None)
    api.cros_sdk.update_chroot(timeout_sec=None)

    return DoRunSteps(api, properties)


def _SetupUpdatedArtifacts(api: RecipeApi, uprev_info: str) -> str:
  """Sets up our updated artifacts json file.

  This file is used by the uprev tooling to figure out which shaders have
  changed and need upreving. uprev_info is provided as an output from
  build_kabuto_shadercache jobs.

  Returns the path to the tempfile with our uprev info input."""
  tempfile = api.path.mkstemp()
  with api.step.nest('write updated artifacts to tempfile'):
    api.file.write_text(f'writing uprev_info to {tempfile}', tempfile,
                        uprev_info, False)
    api.file.read_text('updated artifacts file contents', tempfile)
  return tempfile


def _CommitChanges(api: RecipeApi) -> None:
  """Commit the changes in the current directory.

  This function expects to be run from the cwd that you want to commit the
  changes for."""
  project = api.repo.project_info(project=api.git.repository_root())
  with api.step.nest('commit dlc changes') as presentation:
    # Create our local branch.
    branch = 'uprev-kabuto-dlc'
    api.repo.start(branch, projects=[project.name])

    # Commit all modified files.
    changed_files = api.git.get_working_dir_diff_files()
    api.git.add(changed_files)

    # Simple commit message.
    commit_message = 'uprev shadercache DLCs\n\n'
    commit_message += 'CL generated by job {}'.format(
        api.buildbucket.build_url())

    api.git.commit(commit_message)
    presentation.step_text = f'Shadercache changes committed to {project.name}.'


def _CreateGerritCL(api: RecipeApi) -> None:
  """Create a Gerrit CL for the changes in the current directory.

  This function expects to be run from the cwd that you want to commit the
  changes for, and expects that you have previously run _CommitChanges here
  (or manually created a commit.)"""
  project = api.repo.project_info(project=api.git.repository_root())
  with api.step.nest('upload CL to gerrit') as presentation:
    change = api.gerrit.create_change(project=project.name,
                                      topic=GERRIT_CL_TOPIC,
                                      reviewers=GERRIT_CL_REVIEWERS)
    labels = {
        Label.BOT_COMMIT: 1,
        Label.COMMIT_QUEUE: 2,
    }
    api.gerrit.set_change_labels(change, labels)
    presentation.links['Gerrit CL'] = api.gerrit.parse_gerrit_change_url(change)


def CommitAndUploadCL(api: RecipeApi) -> None:
  """Commit changes and create a Gerrit CL in the current directory."""
  _CommitChanges(api)
  _CreateGerritCL(api)


def _GenerateAndUploadProvenance(api: RecipeApi, dlc_assets_file: str) -> None:
  """Generate and upload Snoopy provenance using Kabuto's dlc_assets.json."""
  dlc_assets = _ReadDlcAssetsFile(api, dlc_assets_file)
  for local_file in dlc_assets:
    gs_uri = dlc_assets[local_file]
    file_hash = _GenerateProvenance(api, local_file)
    _UploadProvenance(api, file_hash, gs_uri)


def _ReadDlcAssetsFile(api: RecipeApi, dlc_assets_file: str) -> list:
  """Read Kabuto's DLC assets file.

  dlc_assets/snoopy.json is generated during the DLC uprev process. It contains
  a dict in which the keys are the path to the local 'dlc.img' file and the
  value is the Google Storage URL for that file.  """
  test_data = '{"/path/to/dlc.img": "gs://bucket/dlc-imgs/dlc.img"}'
  dlc_assets_raw = api.file.read_text(f'Read {dlc_assets_file}',
                                      dlc_assets_file, test_data=test_data)
  dlc_assets = api.json.loads(dlc_assets_raw)
  return dlc_assets


def _GenerateProvenance(api: RecipeApi, file: str) -> str:
  """Generate and return the hash of a file to be reported to Snoopy."""
  return api.file.file_hash(file, test_data='deadbeef')


def _UploadProvenance(api: RecipeApi, file_hash: str, gs_uri: str) -> None:
  """Upload Snoopy provenance for a given file in Google Storage."""
  api.bcid_reporter.report_gcs(file_hash, gs_uri)


def DoRunSteps(api: RecipeApi,
               properties: KabutoShadercacheUprevProperties) -> None:
  chroot_path = api.cros_source.workspace_path

  with api.failures.ignore_exceptions():
    if not api.cros_infra_config.is_staging:
      api.bcid_reporter.report_stage('compile')

  kabuto_path = chroot_path.join('src/platform/borealis/tools/kabuto')
  with api.context(cwd=kabuto_path), api.depot_tools.on_path():
    updated_artifacts_path = _SetupUpdatedArtifacts(api, properties.uprev_info)
    if api.cros_version.version.milestone >= _MILESTONE_USES_KABUTO_UPREV:
      api.step('Upload and uprev', [
          './kabuto', 'dlc-upload-and-uprev', '--updated-artifacts-path',
          updated_artifacts_path
      ])
    else:
      api.step(
          'Upload and uprev',
          ['util/shader-dlc-uprev/upload-and-uprev.py', updated_artifacts_path])

  with api.failures.ignore_exceptions():
    if not api.cros_infra_config.is_staging:
      api.bcid_reporter.report_stage('upload')

  # Create provenance.
  # TODO(b/292108614): Remove ignore_exceptions when stable.
  with api.failures.ignore_exceptions():
    if not api.cros_infra_config.is_staging:
      with api.step.nest('Generate DLC provenance'):
        dlc_assets_file = api.path.join(kabuto_path, 'dlc_assets/snoopy.json')
        _GenerateAndUploadProvenance(api, dlc_assets_file)
        api.bcid_reporter.report_stage('upload-complete')

  partner_overlay_path = chroot_path.join(
      'src/private-overlays/chromeos-partner-overlay')
  with api.context(cwd=partner_overlay_path), api.depot_tools.on_path():
    # A bit of debugging output to make issues easier to spot.
    with api.step.nest('private-overlay git info'):
      api.step('git status', ['git', 'status'])
      api.step('git diff', ['git', 'diff'])

    if not api.build_menu.is_staging:
      CommitAndUploadCL(api)


def GenTests(api: RecipeTestApi) -> None:
  good_props = {
      'uprev_info':
          '{"mesa_hash": {"volteer": "e1d21f72c12a3f9c8b84bcc55fd88b0849253523", "brya": "af3d0ce62bff0c7b567d07b7eee15a7668e35ab8", "guybrush": "a9c55e47e3254e976284695ae7c73b76b3c7113b"}, "game_id_to_board": {}}',
  }

  yield api.test(
      'basic',
      api.properties(**good_props),
  )

  props = good_props.copy()
  del props['uprev_info']
  yield api.test(
      'missing-uprev-info',
      api.properties(**props),
      api.post_process(post_process.DropExpectation),
      # TODO(pobega): change this to test the chroot creation step instead.
      api.post_check(post_process.DoesNotRun, 'Upload and uprev'),
      status='FAILURE',
  )

  props = good_props.copy()
  props['manifest_branch'] = 'release-R105-14989.B'
  yield api.test(
      'branched-manifest',
      api.properties(**props),
      api.post_check(post_process.MustRun,
                     'configure builder.cros_infra_config.gitiles-fetch-ref'),
      api.post_process(
          post_process.StepCommandContains,
          'ensure synced checkout.repo init',
          [
              '--manifest-branch',
              'release-R105-14989.B',
          ],
      ),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'use-old-uprev-method',
      api.cros_version.workspace_version('R113-45678.0.0'),
      api.properties(**props),
      api.post_process(
          post_process.StepCommandContains,
          'Upload and uprev',
          ['util/shader-dlc-uprev/upload-and-uprev.py'],
      ),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'use-new-uprev-method',
      api.cros_version.workspace_version('R118-98765.0.0'),
      api.properties(**props),
      api.post_process(
          post_process.StepCommandContains,
          'Upload and uprev',
          ['./kabuto', 'dlc-upload-and-uprev', '--updated-artifacts-path'],
      ),
      api.post_process(post_process.DropExpectation),
  )
