# -*- coding: utf-8 -*-
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for uprev'ing shadercache DLC ebuilds"""

from RECIPE_MODULES.chromeos.gerrit.api import Label

from PB.recipes.chromeos.kabuto_shadercache_uprev import (
    KabutoShadercacheUprevProperties)
from recipe_engine import post_process
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_api import StepFailure
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/file',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/step',
    'depot_tools/depot_tools',
    'build_menu',
    'cros_sdk',
    'cros_source',
    'gerrit',
    'git',
    'src_state',
    'repo',
]

PROPERTIES = KabutoShadercacheUprevProperties
GERRIT_CL_TOPIC = 'borealis-shadercache-dlc'
GERRIT_CL_REVIEWERS = [
    'davidriley@google.com', 'endlesspring@google.com', 'pobega@google.com'
]

PYTHON_VERSION_COMPATIBILITY = 'PY3'


def RunSteps(api: RecipeApi,
             properties: KabutoShadercacheUprevProperties) -> None:
  with api.step.nest('validate properties') as presentation:
    if not properties.uprev_info:
      raise StepFailure('must set uprev_info')
    presentation.step_text = 'all properties good'

  commit = None
  if properties.manifest_branch:
    commit = api.src_state.internal_manifest.as_gitiles_commit_proto
    commit.ref = 'refs/heads/{}'.format(properties.manifest_branch)

  with api.build_menu.configure_builder(commit=commit, missing_ok=True), \
    api.build_menu.setup_workspace(), api.cros_sdk.cleanup_context():
    api.cros_sdk.create_chroot(timeout_sec=None)
    api.cros_sdk.update_chroot(timeout_sec=None)

    return DoRunSteps(api, properties)


def _SetupUpdatedArtifacts(api: RecipeApi, uprev_info: str) -> str:
  """Sets up our updated artifacts json file.

  This file is used by the uprev tooling to figure out which shaders have
  changed and need upreving. uprev_info is provided as an output from
  build_kabuto_shadercache jobs.

  Returns the path to the tempfile with our uprev info input."""
  tempfile = api.path.mkstemp()
  with api.step.nest('write updated artifacts to tempfile'):
    api.file.write_text(f'writing uprev_info to {tempfile}', tempfile,
                        uprev_info, False)
    api.file.read_text('updated artifacts file contents', tempfile)
  return tempfile


def _CommitChanges(api: RecipeApi) -> None:
  """Commit the changes in the current directory.

  This function expects to be run from the cwd that you want to commit the
  changes for."""
  project = api.repo.project_info(project=api.git.repository_root())
  with api.step.nest('commit dlc changes'):
    # Create our local branch.
    branch = 'uprev-kabuto-dlc'
    api.repo.start(branch, projects=[project.name])

    # Commit all modified files.
    changed_files = api.git.get_working_dir_diff_files()
    api.git.add(changed_files)

    # Simple commit message.
    commit_message = 'uprev shadercache DLCs\n\n'
    commit_message += 'CL generated by job {}'.format(
        api.buildbucket.build_url())

    api.git.commit(commit_message)


def _CreateGerritCL(api: RecipeApi) -> None:
  """Create a Gerrit CL for the changes in the current directory.

  This function expects to be run from the cwd that you want to commit the
  changes for, and expects that you have previously run _CommitChanges here
  (or manually created a commit.)"""
  project = api.repo.project_info(project=api.git.repository_root())
  with api.step.nest('upload CL to gerrit') as presentation:
    change = api.gerrit.create_change(project=project.name,
                                      topic=GERRIT_CL_TOPIC,
                                      reviewers=GERRIT_CL_REVIEWERS)
    labels = {
        Label.BOT_COMMIT: 1,
        Label.COMMIT_QUEUE: 2,
    }
    api.gerrit.set_change_labels(change, labels)
    presentation.links['Gerrit CL'] = api.gerrit.parse_gerrit_change_url(change)


def DoRunSteps(api: RecipeApi,
               properties: KabutoShadercacheUprevProperties) -> None:
  chroot_path = api.cros_source.workspace_path

  kabuto_path = chroot_path.join('src/platform/borealis/tools/kabuto')
  with api.context(cwd=kabuto_path), api.depot_tools.on_path():
    updated_artifacts_path = _SetupUpdatedArtifacts(api, properties.uprev_info)
    # Run upload-and-uprev.py.
    api.step(
        'Upload and uprev',
        ['util/shader-dlc-uprev/upload-and-uprev.py', updated_artifacts_path])

  partner_overlay_path = chroot_path.join(
      'src/private-overlays/chromeos-partner-overlay')
  with api.context(cwd=partner_overlay_path), api.depot_tools.on_path():
    # A bit of debugging output to make issues easier to spot.
    with api.step.nest('private-overlay git info'):
      api.step('git status', ['git', 'status'])
      api.step('git diff', ['git', 'diff'])

    if not api.build_menu.is_staging:
      _CommitChanges(api)
      _CreateGerritCL(api)


def GenTests(api: RecipeTestApi) -> None:
  good_props = {
      'uprev_info':
          '{"mesa_hash": {"volteer": "e1d21f72c12a3f9c8b84bcc55fd88b0849253523", "brya": "af3d0ce62bff0c7b567d07b7eee15a7668e35ab8", "guybrush": "a9c55e47e3254e976284695ae7c73b76b3c7113b"}, "game_id_to_board": {}}',
  }

  yield api.test(
      'basic',
      api.properties(**good_props),
  )

  props = good_props.copy()
  del props['uprev_info']
  yield api.test(
      'missing-uprev-info',
      api.properties(**props),
      # TODO(pobega): change this to test the chroot creation step instead.
      api.post_check(post_process.DoesNotRun, 'Upload and uprev'),
      status='FAILURE',
  )

  props = good_props.copy()
  props['manifest_branch'] = 'release-R105-14989.B'
  yield api.test(
      'branched-manifest',
      api.properties(**props),
      api.post_check(post_process.MustRun,
                     'configure builder.cros_infra_config.gitiles-fetch-ref'),
      api.post_process(
          post_process.StepCommandContains,
          'ensure synced checkout.repo init',
          [
              '--manifest-branch',
              'release-R105-14989.B',
          ],
      ),
  )
