// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.kabuto_orchestrator;

message KabutoOrchestratorProperties {
  // Location of precompiled payload. Can be used to skip paygen step.
  string payload_gs_url = 1;

  // The manifest branch to check out (e.g. 'release-R105-14989.B')
  // Defaults to main tip of tree if not specified.
  string manifest_branch = 2;

  // Number of sharded shadercache builders to spin off.
  // Defaults to 1 if not provided.
  int32 shard_count = 3;

  // Timeout (in hours) to wait for the shadercache builders to return.
  // Defaults to 9 hours if not provided.
  int32 shadercache_timeout = 4;

  // Whether to use release build artifacts instead of building Mesa locally on
  // the spawned kabuto-paygen builder.
  // Defaults to false if not provided.
  bool use_release_build_artifacts = 5;

  // Timeout (in hours) to wait for the Kabuto paygen builder to return.
  // Defaults to 7 hours if not provided.
  int32 paygen_timeout = 6;

  // Timeout (in hours) to wait for the Kabuto uprev builder to return.
  // Defaults to 13 hours if not provided.
  int32 uprev_timeout = 7;

  // The Gerrit CL ref to check out Kabuto to. Passed to all spawned jobs.
  // Optional
  string gerrit_cl_ref = 8;

  // Milestone number we are building. Used to gate flags that only exit in
  // specific branches.
  // Optional.
  int32 milestone = 9;

  // Manual override for Kabuto config (kabuto.json)
  // Optional
  string kabuto_config_override = 10;
}
