# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe to automate kernel version bumps in the release-keys repository."""

from typing import Generator

from PB.go.chromium.org.luci.buildbucket.proto import builder_common as builder_common_pb2
from PB.go.chromium.org.luci.buildbucket.proto import build as build_pb2
from PB.go.chromium.org.luci.buildbucket.proto import common as bb_common_pb2
from PB.recipe_engine import result as result_pb2
from PB.recipes.chromeos.keyset_manager import KeysetManagerProperties
from recipe_engine import post_process
from recipe_engine.recipe_api import RecipeApi, StepFailure
from recipe_engine.recipe_test_api import RecipeTestApi, TestData

DEPS = [
    "recipe_engine/buildbucket",
    "recipe_engine/context",
    "recipe_engine/file",
    "recipe_engine/path",
    "recipe_engine/properties",
    "recipe_engine/step",
    "build_menu",
    "cros_try",
    "gerrit",
    "git",
    "src_state",
]

PROPERTIES = KeysetManagerProperties


def RunSteps(api: RecipeApi,
             properties: KeysetManagerProperties) -> result_pb2.RawResult:
  if not properties.bug:
    raise StepFailure("`bug` is a required property.")

  if properties.keyset and properties.update_all:
    raise StepFailure("Cannot specify both `keyset` and `update_all`.")
  if not properties.keyset and not properties.update_all:
    raise StepFailure("Must specify either `keyset` or `update_all`.")

  # Define path for release-keys repo
  release_keys_path = api.src_state.workspace_path.joinpath(
      "src/platform/signing/keys")

  # 1. Clone release-keys repository
  with api.step.nest("clone release-keys"):
    api.git.clone(
        "https://chrome-internal.googlesource.com/chromeos/platform/release-keys",
        target_path=release_keys_path,
        branch="main",
        single_branch=True,
    )

  # 2. Call increment_kernel_version.py script
  script_path = release_keys_path.joinpath(
      "keyset/public/scripts/increment_kernel_version.py")

  script_args = ["--all"
                ] if properties.update_all else ["-k", properties.keyset]

  dry_run = properties.dry_run or api.build_menu.is_staging

  with api.context(cwd=release_keys_path):
    with api.step.nest("increment kernel version"):
      cmd = ["vpython3", script_path] + script_args
      api.step("run increment_kernel_version.py", cmd)

    # 3. Check for changes in the workspace
    diff_files = api.git.get_working_dir_diff_files()

    if not diff_files:
      return result_pb2.RawResult(
          summary_markdown="No kernel versions changed.",
          status=bb_common_pb2.FAILURE,
      )

    # 4. Commit changes
    target_desc = f"for {properties.keyset}" if properties.keyset else "for all boards"
    commit_lines = [
        f"firmware: Increment kernel version {target_desc}",
        "",
        "Generated by keyset_manager recipe.",
        f"See {api.buildbucket.build_url()} for job details.",
    ]

    if dry_run:
      commit_lines += [
          "",
          "This CL was created as part of a dry run build, it is not meant to be submitted.",
      ]

    commit_lines += [
        "",
        f"BUG=b:{properties.bug}",
        "TEST=CQ",
    ]

    commit_message = "\n".join(commit_lines) + "\n"

    api.git.add_all()
    api.git.commit(commit_message)

    # 5. Upload Gerrit CL
    reviewers = [
        "croskeymanagers@google.com",
        "chromeos-automated-release-platform@google.com",
    ] if not api.build_menu.is_staging else []
    invoker = api.cros_try.get_invoker()

    change = api.gerrit.create_change(
        str(release_keys_path),
        project_path=release_keys_path,
        non_repo_checkout=True,
        reviewers=reviewers,
        ccs=[invoker] if invoker else [],
    )

    # 6. Abandon if dry run or staging
    if dry_run:
      api.gerrit.abandon_change(change)

  status_msg = "Abandoned dry run CL" if dry_run else "Created CL"
  return result_pb2.RawResult(
      summary_markdown=f"{status_msg} {api.gerrit.parse_gerrit_change_url(change)}",
      status=bb_common_pb2.SUCCESS,
  )


def GenTests(api: RecipeTestApi) -> Generator[TestData, None, None]:
  yield api.test(
      "basic",
      api.properties(KeysetManagerProperties(bug=12345, update_all=True)),
      api.git.use_mock(True),
      api.git.get_working_dir_diff_files(
          "M keyset/public/definitions/board1.json\n"),
      api.post_check(post_process.MustRun, "clone release-keys"),
      api.post_check(post_process.MustRun, "increment kernel version"),
      api.post_check(
          post_process.StepCommandContains,
          "increment kernel version.run increment_kernel_version.py",
          ["--all"],
      ),
      api.post_check(post_process.MustRun, "git commit"),
      api.post_check(
          post_process.MustRun,
          "create gerrit change for [CLEANUP]/chromiumos_workspace/src/platform/signing/keys.git_cl upload"
      ),
      api.post_check(
          post_process.StepCommandContains,
          "create gerrit change for [CLEANUP]/chromiumos_workspace/src/platform/signing/keys.git_cl upload",
          [
              "--reviewers", "croskeymanagers@google.com", "--reviewers",
              "chromeos-automated-release-platform@google.com"
          ],
      ),
      api.post_check(post_process.SummaryMarkdownRE, r"Created CL"),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      "basic-board",
      api.properties(KeysetManagerProperties(bug=12345, keyset="atlas")),
      api.git.use_mock(True),
      api.git.get_working_dir_diff_files(
          "M keyset/public/definitions/atlas.json\n"),
      api.post_check(post_process.MustRun, "clone release-keys"),
      api.post_check(post_process.MustRun, "increment kernel version"),
      api.post_check(
          post_process.StepCommandContains,
          "increment kernel version.run increment_kernel_version.py",
          ["-k", "atlas"],
      ),
      api.post_check(post_process.MustRun, "git commit"),
      api.post_check(
          post_process.MustRun,
          "create gerrit change for [CLEANUP]/chromiumos_workspace/src/platform/signing/keys.git_cl upload"
      ),
      api.post_check(post_process.SummaryMarkdownRE, r"Created CL"),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      "dry-run",
      api.properties(
          KeysetManagerProperties(bug=12345, update_all=True, dry_run=True)),
      api.git.use_mock(True),
      api.git.get_working_dir_diff_files(
          "M keyset/public/definitions/board1.json\n"),
      api.post_check(post_process.MustRun, "git commit"),
      api.post_check(
          post_process.MustRun,
          "create gerrit change for [CLEANUP]/chromiumos_workspace/src/platform/signing/keys.git_cl upload"
      ),
      api.post_check(post_process.MustRun, "abandon CL 1"),
      api.post_check(post_process.SummaryMarkdownRE, r"Abandoned dry run CL"),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      "staging",
      api.properties(KeysetManagerProperties(bug=12345, update_all=True)),
      api.buildbucket.build(
          build_pb2.Build(
              builder=builder_common_pb2.BuilderID(
                  project="chromeos",
                  bucket="staging",
                  builder="staging-keyset-manager",
              ))),
      api.git.use_mock(True),
      api.git.get_working_dir_diff_files(
          "M keyset/public/definitions/board1.json\n"),
      api.post_check(post_process.MustRun, "git commit"),
      api.post_check(
          post_process.MustRun,
          "create gerrit change for [CLEANUP]/chromiumos_workspace/src/platform/signing/keys.git_cl upload"
      ),
      api.post_check(
          post_process.StepCommandDoesNotContain,
          "create gerrit change for [CLEANUP]/chromiumos_workspace/src/platform/signing/keys.git_cl upload",
          ["--reviewers"],
      ),
      api.post_check(post_process.MustRun, "abandon CL 1"),
      api.post_check(post_process.SummaryMarkdownRE, r"Abandoned dry run CL"),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      "no-changes",
      api.properties(KeysetManagerProperties(bug=12345, update_all=True)),
      api.git.use_mock(True),
      api.git.get_working_dir_diff_files(""),
      api.post_check(post_process.MustRun, "clone release-keys"),
      api.post_check(post_process.MustRun, "increment kernel version"),
      api.post_check(
          post_process.SummaryMarkdown,
          "No kernel versions changed.",
      ),
      api.post_process(post_process.DropExpectation),
      status="FAILURE",
  )

  yield api.test(
      "missing-bug",
      api.properties(KeysetManagerProperties()),
      api.post_check(
          post_process.SummaryMarkdown,
          "`bug` is a required property.",
      ),
      api.post_process(post_process.DropExpectation),
      status="FAILURE",
  )

  yield api.test(
      "both-specified",
      api.properties(
          KeysetManagerProperties(bug=12345, keyset="atlas", update_all=True)),
      api.post_check(
          post_process.SummaryMarkdown,
          "Cannot specify both `keyset` and `update_all`.",
      ),
      api.post_process(post_process.DropExpectation),
      status="FAILURE",
  )

  yield api.test(
      "neither-specified",
      api.properties(KeysetManagerProperties(bug=12345)),
      api.post_check(
          post_process.SummaryMarkdown,
          "Must specify either `keyset` or `update_all`.",
      ),
      api.post_process(post_process.DropExpectation),
      status="FAILURE",
  )
