// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.local_manifest_presubmit;

import "project_mgmt/project.proto";

message LocalManifestPresubmitProperties {
  // Project we want to run the presubmits of,
  // (e.g. "chromiumos/config" or "chromeos/project/volteer/halvor")
  string project = 1;

  // Manifest groups specifying a subset of repos to sync.
  //
  // The subset of repos in the external manifest + local_manifest matching
  // manifest_groups are synced. For example, say the external manifest
  // contains repos:
  //
  //   <project path="a" name="a" groups="g1" />
  //   <project path="b" name="b" groups="g1" />
  //   <project path="c" name="c" groups="g2" />
  //
  // and the local manifest contains repos:
  //
  //   <project path="d" name="d" groups="g3" />
  //   <project path="e" name="e" groups="g4" />
  //
  // and manifest_groups is ["g1", "g4"]. Repos "a", "b", and "e" will be
  // synced.
  //
  // If empty, all repos are synced.
  repeated string manifest_groups = 2;

  // Local manifest to add to the checkout.
  project_mgmt.LocalManifest local_manifest = 3;
}
