// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.orchestrator;

message OrchestratorProperties {
  // Specifies which refs in the manifest repository should point to the
  // snapshot ref used by the orchestrator, and when.
  message UpdateManifestRefs {
    // The start ref is updated before child builds are launched.
    // An example start ref is 'postsubmit', which should update
    // right when the orchestrator launches.
    string start = 1;

    // The success ref is updated only if all child builds succeed.
    // An example success ref is 'stable', which should update only
    // when postsubmit builds succeed.
    string success = 2;
  }
  UpdateManifestRefs update_manifest_refs = 1;

  // Specifies whether to enable cros_history based resource saving.
  bool enable_history = 2;

  // Specifies whether to enable exiting redundant builds.
  bool assert_singleton = 3;

  // The threshold for the ratio of failed tests to total tests
  // below which baseline verification gets triggered.
  float baseline_verification_threshold = 4;
}
