// Copyright 2022 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.os_install_vm;

import "chromiumos/common.proto";
import "testplans/generate_test_plan.proto";

message OsInstallVmProperties {
  // The build payload to test.
  testplans.BuildPayload build_payload = 1;

  // Maximum duration of the OS install tast test. If this limit is
  // exceeded the test is stopped and marked as a failure. Defaults to
  // 10 minutes.
  float tast_timeout_in_seconds = 2;

  // During the install, amount of time to wait between each check to
  // see if the installer has finished. Defaults to 15 seconds.
  float poll_interval_in_seconds = 3;
}

