# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Pack and sign standalone firmware shellball."""

import re
from typing import List

from google.protobuf.json_format import MessageToDict
from google.protobuf.json_format import MessageToJson

from PB.chromiumos import build_report as build_report_pb2
from PB.chromiumos import common as common_pb2
from PB.chromiumos import signing as signing_pb2
from PB.chromite.api.image import SignImageResponse
from PB.go.chromium.org.luci.scheduler.api.scheduler.v1 import (triggers as
                                                                triggers_pb2)
from PB.go.chromium.org.luci.buildbucket.proto import common as bb_common_pb2
from PB.recipe_engine import result as result_pb2
from PB.recipe_modules.chromeos.signing.signing import SigningProperties

from recipe_engine import post_process
from recipe_engine.config_types import Path
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_api import StepFailure
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    'depot_tools/gsutil',
    'recipe_engine/buildbucket',
    'recipe_engine/cipd',
    'recipe_engine/context',
    'recipe_engine/file',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/scheduler',
    'recipe_engine/step',
    'build_menu',
    'cros_artifacts',
    'cros_build_api',
    'cros_infra_config',
    'cros_release',
    'cros_source',
    'gerrit',
    'git',
    'mutable_output',
    'signing',
    'signing_utils',
    'src_state',
]

TEST_SIGNING_CONFIG = '''build_target_signing_configs {
      build_target: "kukui"
      keyset: "kukui-premp"
      signing_configs {
        image_type: IMAGE_TYPE_SHELLBALL
      }
    }'''

CL_REVIEWERS = [
    'dabros@google.com', 'konrada@google.com', 'bernacki@google.com'
]


def craft_commit_message(api: RecipeApi, version: str, bbid: str,
                         target: str) -> List[str]:
  commit = [
      f'firmware: Update prebuilts to version {version}',
      '',
      'This build triggered by the following:',
  ]

  for trigger in api.scheduler.triggers:
    if trigger.HasField('gitiles'):
      commit.append(f' - {trigger.url}')
    else:
      commit.append(' - Manual trigger')

  commit.append('')
  commit.append(f'Generated by {bbid}.')

  commit.append('')
  commit.append(f'Flag: build.RELEASE_FIRMWARE_{target.upper()}_VERSION')

  return commit


def create_or_update_symlink(api: RecipeApi, directory: Path, file: str,
                             symlink: str):
  with api.context(cwd=directory):
    if api.path.exists(directory / symlink):
      api.file.remove('remove existing symlink', directory / symlink)
    api.step('create symlink', ['ln', '-s', file, symlink])


def upload_firmware_prebuilts(api: RecipeApi, unsigned_shellball_path: Path,
                              shellball_path: Path, target: str, version: str,
                              keyset_is_mp: bool,
                              abandon: bool = True) -> result_pb2.RawResult:
  """Uploads the firmware prebuilts to the android repo."""
  # Check out the android codebase.
  checkout = api.path.mkdtemp()
  with api.context(cwd=checkout):
    api.git.clone(
        f'https://googleplex-android.googlesource.com/device/google/desktop/{target}-prebuilts',
        depth=1)
    # Copy the unsigned shellball into the firmware prebuild repo.
    api.file.ensure_directory('make sure dev-signed exists',
                              api.path.join(checkout, 'firmware', 'dev-signed'))
    api.file.copy(
        'copy unsigned shellball to repo', unsigned_shellball_path,
        api.path.join(checkout, 'firmware', 'dev-signed',
                      f'chromeos-firmwareupdate_{version}'))
    create_or_update_symlink(api, checkout / 'firmware/dev-signed',
                             f'chromeos-firmwareupdate_{version}',
                             'chromeos-firmwareupdate_LATEST')
    # Copy the signed shellball into the firmware prebuild repo.
    directory = 'mp-signed' if keyset_is_mp else 'premp-signed'
    api.file.ensure_directory(f'make sure {directory} exists',
                              api.path.join(checkout, 'firmware', directory))
    api.file.copy(
        'copy signed shellball to repo', shellball_path,
        api.path.join(checkout, 'firmware', directory,
                      f'chromeos-firmwareupdate_{version}'))
    create_or_update_symlink(api, checkout / f'firmware/{directory}',
                             f'chromeos-firmwareupdate_{version}',
                             'chromeos-firmwareupdate_LATEST')

    # Check to make sure there was actually a change.
    diff_lines = api.git.get_working_dir_diff_files()
    if not diff_lines:
      return result_pb2.RawResult(
          summary_markdown='No firmware images changed.',
          status=bb_common_pb2.SUCCESS,
      )
    # Create a cl updating the file.
    api.git.add_all()
    bbid = api.buildbucket.build_url()
    commit_lines = craft_commit_message(api, version, bbid, target)
    api.git.commit('\n'.join(commit_lines))
    change = api.gerrit.create_change(
        f'/device/google/desktop/{target}-prebuilts/',
        ref=api.git.get_branch_ref('main'), project_path=checkout,
        reviewers=CL_REVIEWERS, non_repo_checkout=True)
    if abandon:
      api.gerrit.abandon_change(change)
    return result_pb2.RawResult(
        summary_markdown=f'Updated firmware prebuilts for {target}',
        status=bb_common_pb2.SUCCESS,
    )


def get_shellball_path(api: RecipeApi, response: SignImageResponse) -> Path:
  local_artifact_dir = response.output_archive_dir
  [only_artifact] = response.signed_artifacts.archive_artifacts
  [only_signed] = only_artifact.signed_artifacts

  return api.path.join(local_artifact_dir, only_signed.signed_artifact_name)


def get_keyset_is_mp(response: SignImageResponse) -> bool:
  [only_artifact] = response.signed_artifacts.archive_artifacts
  return only_artifact.keyset_is_mp


def RunSteps(api: RecipeApi) -> result_pb2.RawResult:
  with api.mutable_output.wrap():
    with api.cros_source.checkout_overlays_context():
      api.cros_source.configure_builder(api.buildbucket.gitiles_commit)
      api.cros_source.ensure_synced_cache()
      fw_config_path = api.src_state.workspace_path / 'firmware-config'
      with api.step.nest('clone firmware-config'):
        api.git.clone(
            'https://chrome-internal.googlesource.com/chromeos/firmware-config',
            target_path=fw_config_path, depth=1)

      with api.step.nest('pack firmware') as pres:
        # Ensure cipd packages are present.
        fw_path = api.src_state.workspace_path / 'src/platform/firmware'
        cipd_path = api.path.start_dir / 'cipd'
        api.cipd.ensure(cipd_path, fw_path / 'cipd_manifest.txt',
                        'ensure cipd packages for packing firmware')

        # Call pack_firmware with cipd bins in PATH.
        with api.context(env={
            'PATH': api.path.pathsep.join([str(cipd_path / 'bin'), '%(PATH)s'])
        }):
          # Pack firmware uses config for the base target. Remove prefix if present.
          base_target_name = api.build_menu.build_target.name.split(
              'android-')[-1]
          output_artifact_dir = api.path.mkdtemp('shellball-dir')
          output_artifact_name = api.cros_artifacts.artifacts_by_image_type.get(
              common_pb2.IMAGE_TYPE_SHELLBALL, 'chromeos-firmwareupdate')

          pack_fw_cmd = [
              'vpython3',
              fw_path / 'pack_firmware.py',
              '--imagedir',
              'tmp/distfiles',
              '--config',
              fw_config_path / base_target_name,
              '--output',
              output_artifact_dir / output_artifact_name,
              '--textproto',
              '--download',
          ]
          api.step('call pack_firmware', pack_fw_cmd)

      # Get shellball version for target.
      new_shellball_version = api.signing.get_shellball_version()
      api.signing_utils.custom_artifact_version = new_shellball_version

      # Sign shellball.
      if api._test_data.enabled:  # pylint: disable=protected-access
        api.signing.test_api.signing_config_test_data = api._test_data.get(  # pylint: disable=protected-access
            'signing_config', TEST_SIGNING_CONFIG)
      api.cros_release.validate_sign_types()
      with api.step.nest('sign firmware shellball') as pres:
        signed_image_response = api.signing.sign_artifacts(
            sign_types=[common_pb2.IMAGE_TYPE_SHELLBALL],
            channels=[common_pb2.CHANNEL_AGNOSTIC], include_paygen=False,
            local_artifact_dir=output_artifact_dir, upload_unsigned=False)
        if not signed_image_response:
          raise StepFailure('Empty signing config for build target')
        shellball_path = get_shellball_path(api, signed_image_response)
        pres.logs['signed builds'] = shellball_path

      # Advance LATEST-SHELLBALL for each version.
      api.signing.upload_shellball_latest_file(new_shellball_version)

      # Open a cl with the new firmware prebuilts.
      return upload_firmware_prebuilts(
          api, output_artifact_dir / output_artifact_name, shellball_path,
          base_target_name, new_shellball_version,
          get_keyset_is_mp(signed_image_response),
          abandon=api.cros_infra_config.is_staging)


# Sample SignImageResponse for testing.
sample_response = SignImageResponse(
    output_archive_dir='/archive_dir/',
    signed_artifacts=signing_pb2.BuildTargetSignedArtifacts(archive_artifacts=[
        signing_pb2.ArchiveArtifacts(
            build_target='android-kukui',
            channel=common_pb2.CHANNEL_CANARY,
            image_type=common_pb2.IMAGE_TYPE_SHELLBALL,
            signed_artifacts=[
                signing_pb2.SignedArtifact(
                    signed_artifact_name='signed_firmware.bin',
                ),
            ],
            signing_status=build_report_pb2.BuildReport.SignedBuildMetadata
            .SIGNING_STATUS_PASSED,
        )
    ]))


def GenTests(api: RecipeTestApi):
  yield api.build_menu.test(
      'success',
      api.scheduler(triggers=[
          triggers_pb2.Trigger(
              id='123',
              gitiles=triggers_pb2.GitilesTrigger(
                  repo='https://chromium.googlesource.com/chromium/src',
                  ref='refs/tags/79.0.3945.20',
                  revision='83a1812dddfc24f604d92bf61ad58efe9227a6fc',
              ),
          ),
          triggers_pb2.Trigger(id='123', noop=triggers_pb2.NoopTrigger(
              data='foo')),
      ]),
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_CANARY],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign firmware shellball.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response)),
      api.step_data(
          'get latest shellball version for kukui.gsutil reading LATEST-SHELLBALL version',
          stdout=api.raw_io.output('3.0')),
      api.post_check(
          post_process.DoesNotRun,
          'sign firmware shellball.sign artifacts.upload unsigned artifacts to '
          'signed-firmware bucket.upload unsigned artifacts for CHANNEL_CANARY'
      ),
      api.post_check(post_process.MustRun, 'pack firmware'),
      api.post_check(
          post_process.StepCommandContains,
          'sign firmware shellball.sign artifacts.call BAPI.call chromite.api.ImageService/SignImage.write input file',
          [re.compile('.*"imageType": 20.*')]),
      api.post_check(
          post_process.StepCommandContains,
          'sign firmware shellball.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_CANARY.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/4.0/',
          ]),
      api.post_check(post_process.DoesNotRun, 'remove existing symlink'),
      api.post_check(post_process.MustRun, 'create symlink'),
      api.post_check(post_process.DoesNotRun, 'remove existing symlink (2)'),
      api.post_check(post_process.MustRun, 'create symlink (2)'),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='firmware-packager-android-kukui-main',
  )

  yield api.build_menu.test(
      'signing-skipped',
      api.scheduler(triggers=[
          triggers_pb2.Trigger(
              id='123',
              gitiles=triggers_pb2.GitilesTrigger(
                  repo='https://chromium.googlesource.com/chromium/src',
                  ref='refs/tags/79.0.3945.20',
                  revision='83a1812dddfc24f604d92bf61ad58efe9227a6fc',
              ),
          ),
          triggers_pb2.Trigger(id='123', noop=triggers_pb2.NoopTrigger(
              data='foo')),
      ]),
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_CANARY],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.recipe_test_data(signing_config="""build_target_signing_configs {
  build_target: "kukui"
}"""),
      api.step_data(
          'get latest shellball version for kukui.gsutil reading LATEST-SHELLBALL version',
          stdout=api.raw_io.output('3.0')),
      api.post_check(
          post_process.DoesNotRun,
          'sign firmware shellball.sign artifacts.upload unsigned artifacts to '
          'signed-firmware bucket.upload unsigned artifacts for CHANNEL_CANARY'
      ),
      api.post_check(post_process.MustRun, 'pack firmware'),
      api.post_check(
          post_process.DoesNotRun,
          'sign firmware shellball.sign artifacts.docker prune',
      ),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='firmware-packager-android-kukui-main',
      status='FAILURE',
  )

  yield api.build_menu.test(
      'symlink-exists',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_CANARY],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign firmware shellball.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response)),
      api.step_data(
          'get latest shellball version for kukui.gsutil reading LATEST-SHELLBALL version',
          stdout=api.raw_io.output('3.0')),
      api.path.exists(
          api.path.cleanup_dir /
          'tmp_tmp_1/firmware/dev-signed/chromeos-firmwareupdate_LATEST',
          api.path.cleanup_dir /
          'tmp_tmp_1/firmware/premp-signed/chromeos-firmwareupdate_LATEST'),
      api.post_check(
          post_process.DoesNotRun,
          'sign firmware shellball.sign artifacts.upload unsigned artifacts to '
          'signed-firmware bucket.upload unsigned artifacts for CHANNEL_CANARY'
      ),
      api.post_check(post_process.MustRun, 'pack firmware'),
      api.post_check(
          post_process.StepCommandContains,
          'sign firmware shellball.sign artifacts.call BAPI.call chromite.api.ImageService/SignImage.write input file',
          [re.compile('.*"imageType": 20.*')]),
      api.post_check(
          post_process.StepCommandContains,
          'sign firmware shellball.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_CANARY.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/4.0/',
          ]),
      api.post_check(post_process.MustRun, 'remove existing symlink'),
      api.post_check(post_process.MustRun, 'create symlink'),
      api.post_check(post_process.MustRun, 'remove existing symlink (2)'),
      api.post_check(post_process.MustRun, 'create symlink (2)'),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='firmware-packager-android-kukui-main',
  )

  yield api.build_menu.test(
      'use-dev-keys',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_CANARY],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware',
                                        use_dev_keys=True)),
          }),
      api.step_data(
          'get latest shellball version for kukui.gsutil reading LATEST-SHELLBALL version',
          retcode=1),
      api.step_data('git status', stdout=api.raw_io.output('')),
      api.post_check(
          post_process.LogContains,
          'sign firmware shellball.sign artifacts.call BAPI.call chromite.api.'
          'ImageService/SignImage', 'request',
          ['\"keyset\": \"DevPreMPKeys\"']),
      api.post_check(post_process.SummaryMarkdown,
                     'No firmware images changed.'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='firmware-packager-android-kukui-main',
  )

  yield api.build_menu.test(
      'staging',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_CANARY],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware',
                                        use_dev_keys=True)),
          }),
      api.step_data(
          'get latest shellball version for kukui.gsutil reading LATEST-SHELLBALL version',
          retcode=1),
      api.post_check(
          post_process.LogContains,
          'sign firmware shellball.sign artifacts.call BAPI.call chromite.api.'
          'ImageService/SignImage', 'request',
          ['\"keyset\": \"DevPreMPKeys\"']),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.MustRun, 'abandon CL 1'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      bucket='staging',
      builder='firmware-packager-android-kukui-main',
  )
