# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Pack and sign standalone firmware shellball."""

import re
from typing import List, Tuple

from google.protobuf.json_format import MessageToDict
from google.protobuf.json_format import MessageToJson

from PB.chromiumos import build_report as build_report_pb2
from PB.chromiumos import common as common_pb2
from PB.chromiumos import signing as signing_pb2
from PB.chromiumos.builder_config import BuilderConfig
from PB.chromite.api.image import SignImageResponse
from PB.go.chromium.org.luci.buildbucket.proto.common import GerritChange
from PB.go.chromium.org.luci.scheduler.api.scheduler.v1 import (triggers as
                                                                triggers_pb2)
from PB.go.chromium.org.luci.buildbucket.proto import common as bb_common_pb2
from PB.recipe_engine import result as result_pb2
from PB.recipe_modules.chromeos.signing.signing import SigningProperties

from recipe_engine import post_process
from recipe_engine.config_types import Path
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_api import StepFailure
from recipe_engine.recipe_test_api import RecipeTestApi

DEPS = [
    'depot_tools/gsutil',
    'recipe_engine/archive',
    'recipe_engine/bcid_reporter',
    'recipe_engine/buildbucket',
    'recipe_engine/cipd',
    'recipe_engine/cv',
    'recipe_engine/context',
    'recipe_engine/file',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/scheduler',
    'recipe_engine/step',
    'build_menu',
    'cros_artifacts',
    'cros_build_api',
    'cros_infra_config',
    'cros_release',
    'cros_source',
    'gerrit',
    'git',
    'mutable_output',
    'signing',
    'signing_utils',
    'src_state',
]

TEST_SIGNING_CONFIG = '''build_target_signing_configs {
      build_target: "kukui"
      keyset: "kukui-premp"
      signing_configs {
        image_type: IMAGE_TYPE_SHELLBALL
      }
    }'''

CL_REVIEWERS = [
    'dabros@google.com',
    'konrada@google.com',
    'bernacki@google.com',
    "bensonchen@google.com",
]

ARSP_HOST = 'arsp'


def craft_commit_message(
    api: RecipeApi,
    version: str,
    bbid: str,
    target: str,
    fw_config_path: Path,
    unsigned_package_name: str,
    signed_package_name: str,
) -> Tuple[str, List[str]]:
  commit = [
      f'firmware: Update prebuilts to version {version}',
      '',
      'This build triggered by the following:',
  ]

  with api.context(cwd=fw_config_path):
    ccs = []
    for trigger in api.scheduler.triggers:
      if trigger.HasField('gitiles'):
        commit.append(f' - {trigger.url}')
        ccs.append(api.git.author_email(trigger.gitiles.revision))
      else:
        commit.append(' - Manual trigger')

  commit.append('')
  commit.append(f'1. Unsigned/dev-signed to {unsigned_package_name}')
  commit.append(f'2. Signed to {signed_package_name}')

  commit.append('')
  commit.append(f'Generated by {bbid}.')

  commit.append('')
  commit.append(f'Flag: build.RELEASE_FIRMWARE_{target.upper()}_VERSION')

  return '\n'.join(commit), ccs


def create_or_update_symlink(api: RecipeApi, directory: Path, file: str,
                             symlink: str):
  with api.context(cwd=directory):
    if api.path.exists(directory / symlink):
      api.file.remove('remove existing symlink', directory / symlink)
    api.step('create symlink', ['ln', '-s', file, symlink])


def create_manifest(api: RecipeApi, directory: Path, shellball: str):
  with api.context(cwd=directory):
    manifest_file = api.raw_io.output_text(leak_to=directory /
                                           f'{shellball}.manifest.json')
    api.step('create manifest', [f'./{shellball}', '--manifest'],
             stdout=manifest_file)

def upload_firmware_prebuilts(api: RecipeApi, unsigned_shellball_path: Path,
                              shellball_path: Path,
                              ec_component_manifest_path: Path, target: str,
                              version: str, keyset_is_mp: bool,
                              fw_config_path: Path, abandon: bool = True,
                              host: str = ARSP_HOST) -> str:
  """Uploads the firmware prebuilts to the android repo.

  Returns:
    The message to include in the summary markdown of the build."""
  # Skip upload in CQ.
  if api.cv.active:
    api.step.empty('Skipping CL upload in CQ')
    return ''
  # Check out the android codebase.
  checkout = api.path.mkdtemp()
  with api.context(cwd=checkout):
    api.git.clone(
        f'https://{host}.googlesource.com/device/google/desktop/{target}-prebuilts',
        depth=1)
    # Copy the unsigned shellball into the firmware prebuild repo.
    api.file.ensure_directory('make sure dev-signed exists',
                              api.path.join(checkout, 'firmware', 'dev-signed'))
    api.file.copy(
        'copy unsigned shellball to repo', unsigned_shellball_path,
        api.path.join(checkout, 'firmware', 'dev-signed',
                      f'chromeos-firmwareupdate_{version}'))
    create_or_update_symlink(api, checkout / 'firmware/dev-signed',
                             f'chromeos-firmwareupdate_{version}',
                             'chromeos-firmwareupdate_LATEST')
    create_manifest(api, checkout / 'firmware/dev-signed',
                    f'chromeos-firmwareupdate_{version}')
    # Copy the signed shellball into the firmware prebuild repo.
    directory = 'mp-signed' if keyset_is_mp else 'premp-signed'
    api.file.ensure_directory(f'make sure {directory} exists',
                              api.path.join(checkout, 'firmware', directory))
    api.file.copy(
        'copy signed shellball to repo', shellball_path,
        api.path.join(checkout, 'firmware', directory,
                      f'chromeos-firmwareupdate_{version}'))
    create_or_update_symlink(api, checkout / f'firmware/{directory}',
                             f'chromeos-firmwareupdate_{version}',
                             'chromeos-firmwareupdate_LATEST')

    create_manifest(api, checkout / f'firmware/{directory}',
                    f'chromeos-firmwareupdate_{version}')

    # Copy the EC component manifest zip into the firmware prebuild repo.
    if ec_component_manifest_path:
      api.file.ensure_directory(
          'make sure ec_component_manifest dir exists',
          api.path.join(checkout, 'firmware', 'ec_component_manifest'))
      api.file.copy(
          'copy ec_component_manifest.zip to repo', ec_component_manifest_path,
          api.path.join(checkout, 'firmware', 'ec_component_manifest',
                        f'ec_component_manifest_{version}.zip'))
      create_or_update_symlink(api, checkout / 'firmware/ec_component_manifest',
                               f'ec_component_manifest_{version}.zip',
                               'ec_component_manifest_LATEST.zip')

    def _create_cipd_pkg(signed_type: str) -> str:
      pkg_name = f'android/desktop/firmware/{target}/ap/{signed_type}'
      if api.cros_infra_config.is_staging:
        pkg_name = f'experimental/{pkg_name}'
      pkg_def = api.cipd.PackageDefinition(package_name=pkg_name,
                                           package_root=checkout / 'firmware')
      pkg_def.add_file(checkout / 'firmware' / signed_type /
                       f'chromeos-firmwareupdate_{version}')
      if ec_component_manifest_path:
        pkg_def.add_file(checkout / 'firmware/ec_component_manifest' /
                         f'ec_component_manifest_{version}.zip')
      api.cipd.create_from_pkg(pkg_def=pkg_def, tags={'version': version})
      return pkg_name

    with api.step.nest('upload to cipd'):
      unsigned_pkg = _create_cipd_pkg('dev-signed')
      signed_pkg = _create_cipd_pkg(directory)

    # Check to make sure there was actually a change.
    diff_lines = api.git.get_working_dir_diff_files()
    if not diff_lines:
      return 'No firmware images changed.'
    # Create a cl updating the file.
    api.git.add_all()
    bbid = api.buildbucket.build_url()
    commit_msg, ccs = craft_commit_message(
        api,
        version,
        bbid,
        target,
        fw_config_path,
        unsigned_package_name=unsigned_pkg,
        signed_package_name=signed_pkg,
    )
    api.git.commit(commit_msg)
    # TODO: b/466455984 - Remove skip when no longer needed.
    change = api.gerrit.create_change(
        f'/device/google/desktop/{target}-prebuilts/',
        ref=api.git.get_branch_ref('main'), project_path=checkout,
        reviewers=CL_REVIEWERS if not api.cros_infra_config.is_staging else [],
        ccs=ccs if not api.cros_infra_config.is_staging else [],
        non_repo_checkout=True, upload_options=['banned-words~skip'])
    if abandon:
      api.gerrit.abandon_change(change)
    return f'Updated firmware prebuilts for {target}'


def get_shellball_path(api: RecipeApi, response: SignImageResponse) -> Path:
  local_artifact_dir = response.output_archive_dir
  [only_artifact] = response.signed_artifacts.archive_artifacts
  [only_signed] = only_artifact.signed_artifacts

  return api.path.join(local_artifact_dir, only_signed.signed_artifact_name)


def get_keyset_is_mp(response: SignImageResponse) -> bool:
  [only_artifact] = response.signed_artifacts.archive_artifacts
  return only_artifact.keyset_is_mp


def RunSteps(api: RecipeApi) -> result_pb2.RawResult:
  with api.mutable_output.wrap():
    with api.cros_source.checkout_overlays_context():
      api.bcid_reporter.report_stage('start')
      api.cros_source.configure_builder(api.buildbucket.gitiles_commit)
      api.bcid_reporter.report_stage('fetch')
      api.cros_source.ensure_synced_cache()
      fw_config_path = api.src_state.workspace_path / 'firmware-config'
      with api.step.nest('clone firmware-config'):
        api.git.clone(
            'https://chrome-internal.googlesource.com/chromeos/firmware-config',
            target_path=fw_config_path)

      # In staging, allow cherry picking firmware-config CLs for testing.
      if api.cros_infra_config.is_staging:
        with api.step.nest('apply gerrit changes') as pres, api.context(
            cwd=fw_config_path):
          relevant_changes = [
              x for x in api.buildbucket.build.input.gerrit_changes
              if x.project == 'chromeos/firmware-config'
          ]
          if relevant_changes:
            patch_sets = api.gerrit.fetch_patch_sets(relevant_changes)
            for patch_set in patch_sets:
              commit_id = api.git.fetch_ref(patch_set.git_fetch_url,
                                            patch_set.git_fetch_ref)
              api.git.cherry_pick(commit_id)
          else:
            pres.step_text = 'No chromeos/firmware-config changes to apply.'

      with api.step.nest('pack firmware') as pres:
        # Ensure cipd packages are present.
        fw_path = api.src_state.workspace_path / 'src/platform/firmware'
        cipd_path = api.path.start_dir / 'cipd'
        api.cipd.ensure(cipd_path, fw_path / 'cipd_manifest.txt',
                        'ensure cipd packages for packing firmware')

        # Call pack_firmware with cipd bins in PATH.
        with api.context(env={
            'PATH': api.path.pathsep.join([str(cipd_path / 'bin'), '%(PATH)s'])
        }):
          output_artifact_dir = api.path.mkdtemp('shellball-dir')
          output_shellball_name = api.cros_artifacts.artifacts_by_image_type.get(
              common_pb2.IMAGE_TYPE_SHELLBALL, 'chromeos-firmwareupdate')
          output_artifact_shellball = output_artifact_dir / output_shellball_name
          output_artifact_eccm_dir = output_artifact_dir / 'ec_component_manifest'

          pack_fw_cmd = [
              'vpython3',
              fw_path / 'pack_firmware.py',
              '--imagedir',
              'tmp/distfiles',
              '--config',
              fw_config_path / api.build_menu.build_target.name,
              '--output',
              output_artifact_shellball,
              '--ec_component_manifest_output',
              output_artifact_eccm_dir,
              '--textproto',
              '--download',
          ]
          api.step('call pack_firmware', pack_fw_cmd)

      # Zip EC component manifests.
      with api.step.nest('zip EC component manifests'):
        output_artifact_eccm_zip = None
        if api.path.exists(output_artifact_eccm_dir):
          output_artifact_eccm_zip = api.archive.package(output_artifact_eccm_dir.parent) \
              .with_dir(output_artifact_eccm_dir) \
              .archive('compress ec component manifest', output_artifact_eccm_dir / 'ec_component_manifest.zip', 'zip')

      # Get shellball version for target.
      new_shellball_version = api.signing.get_prebuilt_version(
          latest_filename='LATEST-SHELLBALL')
      api.signing_utils.custom_artifact_version = new_shellball_version

      api.bcid_reporter.report_stage('upload')

      # Sign shellball.
      if api._test_data.enabled:  # pylint: disable=protected-access
        api.signing.test_api.signing_config_test_data = api._test_data.get(  # pylint: disable=protected-access
            'signing_config', TEST_SIGNING_CONFIG)
      api.cros_release.validate_sign_types()
      with api.step.nest('sign firmware shellball') as pres:
        infra_config = api.cros_infra_config.config
        signed_image_response = api.signing.sign_artifacts(
            sign_types=[common_pb2.IMAGE_TYPE_SHELLBALL],
            channels=[common_pb2.CHANNEL_AGNOSTIC], include_paygen=False,
            local_artifact_dir=output_artifact_dir, upload_unsigned=False,
            attestation_eligible=infra_config.artifacts.attestation_eligible
            if infra_config and infra_config.HasField('artifacts') else False)
        if not signed_image_response:
          raise StepFailure('Empty signing config for build target')
        shellball_path = get_shellball_path(api, signed_image_response)
        pres.logs['signed builds'] = shellball_path

      # Advance LATEST-SHELLBALL for each version.
      api.signing.upload_prebuilt_latest_file(
          new_shellball_version, latest_filename='LATEST-SHELLBALL')

      # Open a cl with the new firmware prebuilts.
      desktop_msg = upload_firmware_prebuilts(
          api, output_artifact_shellball, shellball_path,
          output_artifact_eccm_zip,
          api.build_menu.build_target.name, new_shellball_version,
          get_keyset_is_mp(signed_image_response), fw_config_path,
          abandon=api.cros_infra_config.is_staging, host=ARSP_HOST)

      api.bcid_reporter.report_stage('upload-complete')
      return result_pb2.RawResult(
          summary_markdown=f'{desktop_msg}',
          status=bb_common_pb2.SUCCESS,
      )


# Sample SignImageResponse for testing.
sample_response = SignImageResponse(
    output_archive_dir='/archive_dir/',
    signed_artifacts=signing_pb2.BuildTargetSignedArtifacts(archive_artifacts=[
        signing_pb2.ArchiveArtifacts(
            build_target='android-kukui',
            channel=common_pb2.CHANNEL_AGNOSTIC,
            image_type=common_pb2.IMAGE_TYPE_SHELLBALL,
            signed_artifacts=[
                signing_pb2.SignedArtifact(
                    signed_artifact_name='signed_firmware.bin',
                ),
            ],
            signing_status=build_report_pb2.BuildReport.SignedBuildMetadata
            .SIGNING_STATUS_PASSED,
        )
    ]))

# Sample SignImageResponse for MP signed testing.
_SAMPLE_MP_RESPONSE = SignImageResponse(
    output_archive_dir='/archive_dir/',
    signed_artifacts=signing_pb2.BuildTargetSignedArtifacts(archive_artifacts=[
        signing_pb2.ArchiveArtifacts(
            build_target='android-kukui',
            channel=common_pb2.CHANNEL_AGNOSTIC,
            image_type=common_pb2.IMAGE_TYPE_SHELLBALL,
            keyset_is_mp=True,
            signed_artifacts=[
                signing_pb2.SignedArtifact(
                    signed_artifact_name='signed_firmware.bin',
                ),
            ],
            signing_status=build_report_pb2.BuildReport.SignedBuildMetadata
            .SIGNING_STATUS_PASSED,
        )
    ]))


def GenTests(api: RecipeTestApi):
  yield api.build_menu.test(
      'success',
      api.scheduler(triggers=[
          triggers_pb2.Trigger(
              id='123',
              gitiles=triggers_pb2.GitilesTrigger(
                  repo='https://chromium.googlesource.com/chromium/src',
                  ref='refs/tags/79.0.3945.20',
                  revision='83a1812dddfc24f604d92bf61ad58efe9227a6fc',
              ),
          ),
          triggers_pb2.Trigger(id='123', noop=triggers_pb2.NoopTrigger(
              data='foo')),
      ]),
      api.cros_infra_config.use_custom_builder_config(
          BuilderConfig(
              artifacts=BuilderConfig.Artifacts(
                  attestation_eligible=True,
              )),
          step_name='configure builder.cros_infra_config',
      ),
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign firmware shellball.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response)),
      api.post_process(post_process.StepCommandContains, 'git clone', [
          f'https://{ARSP_HOST}.googlesource.com/device/google/desktop/kukui-prebuilts'
      ]),
      api.post_process(post_process.DoesNotRun, 'git clone (2)'),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-SHELLBALL version',
          stdout=api.raw_io.output('3.0')),
      api.path.dirs_exist(api.path.cleanup_dir /
                          'shellball-dir_tmp_1/ec_component_manifest'),
      api.post_check(
          post_process.DoesNotRun,
          'sign firmware shellball.sign artifacts.upload unsigned artifacts to '
          'signed-firmware bucket.upload unsigned artifacts for CHANNEL_AGNOSTIC'
      ),
      api.post_check(post_process.MustRun, 'pack firmware'),
      api.post_check(
          post_process.StepCommandContains,
          'sign firmware shellball.sign artifacts.call BAPI.call chromite.api.ImageService/SignImage.write input file',
          [re.compile('.*"imageType": 20.*')]),
      api.post_check(
          post_process.StepCommandContains,
          'sign firmware shellball.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/4.0/',
          ]),
      api.post_check(post_process.DoesNotRun, 'remove existing symlink'),
      api.post_check(post_process.MustRun, 'create symlink'),
      api.post_check(post_process.DoesNotRun, 'remove existing symlink (2)'),
      api.post_check(post_process.MustRun, 'create symlink (2)'),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_check(post_process.DoesNotRun, 'git commit (2)'),
      api.post_check(post_process.MustRun, 'snoop: report_stage'),
      api.post_check(
          post_process.StepCommandContains,
          'sign firmware shellball.sign artifacts.upload signed artifacts to signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.generate signed provenance.snoop: report_gcs',
          [
              '-report-gcs', '-digest', 'deadbeef', '-gcs-uri',
              'gs://signed-firmware/kukui/4.0/signed_firmware.bin'
          ]),
      api.post_check(
          post_process.StepCommandContains,
          'upload to cipd.create android/desktop/firmware/kukui/ap/premp-signed',
          [
              '-pkg-def',
              re.compile(r'premp-signed/chromeos-firmwareupdate_'),
          ]),
      api.post_check(
          post_process.StepCommandContains,
          'upload to cipd.create android/desktop/firmware/kukui/ap/dev-signed',
          [
              '-pkg-def',
              re.compile(r'dev-signed/chromeos-firmwareupdate_'),
          ]),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='firmware-packager-android-kukui-main',
  )

  yield api.build_menu.test(
      'success-mp',
      api.scheduler(triggers=[
          triggers_pb2.Trigger(
              id='123',
              gitiles=triggers_pb2.GitilesTrigger(
                  repo='https://chromium.googlesource.com/chromium/src',
                  ref='refs/tags/79.0.3945.20',
                  revision='83a1812dddfc24f604d92bf61ad58efe9227a6fc',
              ),
          ),
          triggers_pb2.Trigger(id='123', noop=triggers_pb2.NoopTrigger(
              data='foo')),
      ]),
      api.cros_infra_config.use_custom_builder_config(
          BuilderConfig(
              artifacts=BuilderConfig.Artifacts(
                  attestation_eligible=True,
              )),
          step_name='configure builder.cros_infra_config',
      ),
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign firmware shellball.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(_SAMPLE_MP_RESPONSE)),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-SHELLBALL version',
          stdout=api.raw_io.output('3.0')),
      api.post_check(post_process.MustRun, 'pack firmware'),
      api.post_check(
          post_process.StepCommandContains,
          'upload to cipd.create android/desktop/firmware/kukui/ap/mp-signed', [
              '-pkg-def',
              re.compile(r'mp-signed/chromeos-firmwareupdate_'),
          ]),
      api.post_check(
          post_process.StepCommandContains,
          'upload to cipd.create android/desktop/firmware/kukui/ap/dev-signed',
          [
              '-pkg-def',
              re.compile(r'dev-signed/chromeos-firmwareupdate_'),
          ]),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='firmware-packager-android-kukui-main',
  )

  yield api.build_menu.test(
      'signing-skipped',
      api.scheduler(triggers=[
          triggers_pb2.Trigger(
              id='123',
              gitiles=triggers_pb2.GitilesTrigger(
                  repo='https://chromium.googlesource.com/chromium/src',
                  ref='refs/tags/79.0.3945.20',
                  revision='83a1812dddfc24f604d92bf61ad58efe9227a6fc',
              ),
          ),
          triggers_pb2.Trigger(id='123', noop=triggers_pb2.NoopTrigger(
              data='foo')),
      ]),
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.recipe_test_data(signing_config="""build_target_signing_configs {
  build_target: "kukui"
}"""),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-SHELLBALL version',
          stdout=api.raw_io.output('3.0')),
      api.post_check(
          post_process.DoesNotRun,
          'sign firmware shellball.sign artifacts.upload unsigned artifacts to '
          'signed-firmware bucket.upload unsigned artifacts for CHANNEL_AGNOSTIC'
      ),
      api.post_check(post_process.MustRun, 'pack firmware'),
      api.post_check(
          post_process.DoesNotRun,
          'sign firmware shellball.sign artifacts.docker prune',
      ),
      api.post_check(post_process.DoesNotRun, 'upload to cipd'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='firmware-packager-android-kukui-main',
      status='FAILURE',
  )

  yield api.build_menu.test(
      'symlink-exists',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware'))
          }),
      api.cros_build_api.set_api_return(
          'sign firmware shellball.sign artifacts.call BAPI',
          'ImageService/SignImage', MessageToJson(sample_response)),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-SHELLBALL version',
          stdout=api.raw_io.output('3.0')),
      api.path.exists(
          api.path.cleanup_dir /
          'tmp_tmp_1/firmware/dev-signed/chromeos-firmwareupdate_LATEST',
          api.path.cleanup_dir /
          'tmp_tmp_1/firmware/premp-signed/chromeos-firmwareupdate_LATEST'),
      api.post_check(
          post_process.DoesNotRun,
          'sign firmware shellball.sign artifacts.upload unsigned artifacts to '
          'signed-firmware bucket.upload unsigned artifacts for CHANNEL_AGNOSTIC'
      ),
      api.post_check(post_process.MustRun, 'pack firmware'),
      api.post_check(
          post_process.StepCommandContains,
          'sign firmware shellball.sign artifacts.call BAPI.call chromite.api.ImageService/SignImage.write input file',
          [re.compile('.*"imageType": 20.*')]),
      api.post_check(
          post_process.StepCommandContains,
          'sign firmware shellball.sign artifacts.upload signed artifacts to '
          'signed-firmware bucket.upload signed artifacts for CHANNEL_AGNOSTIC.'
          'gsutil cp', [
              'gs://signed-firmware/kukui/4.0/',
          ]),
      api.post_check(post_process.MustRun, 'remove existing symlink'),
      api.post_check(post_process.MustRun, 'create symlink'),
      api.post_check(post_process.MustRun, 'remove existing symlink (2)'),
      api.post_check(post_process.MustRun, 'create symlink (2)'),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.DoesNotRun, 'abandon CL 1'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='firmware-packager-android-kukui-main',
  )

  yield api.build_menu.test(
      'use-dev-keys',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware',
                                        use_dev_keys=True)),
          }),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-SHELLBALL version',
          retcode=1),
      api.step_data('git status', stdout=api.raw_io.output('')),
      api.post_check(
          post_process.LogContains,
          'sign firmware shellball.sign artifacts.call BAPI.call chromite.api.'
          'ImageService/SignImage', 'request',
          ['\"keyset\": \"DevPreMPKeys\"']),
      api.post_check(post_process.SummaryMarkdown,
                     'No firmware images changed.'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      builder='firmware-packager-android-kukui-main',
  )

  yield api.build_menu.test(
      'staging',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware',
                                        use_dev_keys=True)),
          }),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-SHELLBALL version',
          retcode=1),
      api.post_check(
          post_process.LogContains,
          'sign firmware shellball.sign artifacts.call BAPI.call chromite.api.'
          'ImageService/SignImage', 'request',
          ['\"keyset\": \"DevPreMPKeys\"']),
      api.post_check(post_process.MustRun, 'git commit'),
      api.post_check(post_process.MustRun, 'abandon CL 1'),
      # Omit reviewers and cc in staging.
      api.post_check(
          post_process.StepCommandDoesNotContain,
          'create gerrit change for /device/google/desktop/kukui-prebuilts/.git_cl upload',
          '--reviewers'),
      api.post_check(
          post_process.StepCommandDoesNotContain,
          'create gerrit change for /device/google/desktop/kukui-prebuilts/.git_cl upload',
          '--cc'),
      api.post_check(
          post_process.MustRun,
          'upload to cipd.create experimental/android/desktop/firmware/kukui/ap/premp-signed',
      ),
      api.post_check(
          post_process.MustRun,
          'upload to cipd.create experimental/android/desktop/firmware/kukui/ap/dev-signed',
      ),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      bucket='staging',
      builder='firmware-packager-android-kukui-main',
  )

  test_gerrit_changes = [
      GerritChange(host='chromium-review.googlesource.com', change=1,
                   project='chromeos/firmware-config', patchset=1),
      GerritChange(host='chromium-review.googlesource.com', change=2,
                   project='some-other-project', patchset=1),
  ]
  fetch_changes_response = {
      101: {
          'change_id': '101',
          'revision_info': {
              'commit': {
                  'message': 'test commit',
              },
          },
      }
  }
  yield api.build_menu.test(
      'cq',
      api.properties(
          **{
              '$chromeos/cros_release': {
                  'channels': [common_pb2.CHANNEL_AGNOSTIC],
              },
              '$chromeos/signing':
                  MessageToDict(
                      SigningProperties(local_signing=True,
                                        gs_upload_bucket='signed-firmware',
                                        use_dev_keys=True)),
          }),
      api.gerrit.set_gerrit_fetch_changes_response('apply gerrit changes',
                                                   test_gerrit_changes,
                                                   fetch_changes_response),
      # Only cherry pick the firmware-config change.
      api.post_check(post_process.MustRun,
                     'apply gerrit changes.git cherry-pick'),
      api.post_check(post_process.DoesNotRun,
                     'apply gerrit changes.git cherry-pick (2)'),
      api.step_data(
          'get latest prebuilt version for kukui.gsutil reading LATEST-SHELLBALL version',
          retcode=1),
      api.post_check(
          post_process.LogContains,
          'sign firmware shellball.sign artifacts.call BAPI.call chromite.api.'
          'ImageService/SignImage', 'request',
          ['\"keyset\": \"DevPreMPKeys\"']),
      # Skip CL upload.
      api.post_check(post_process.DoesNotRun, 'git commit'),
      api.post_check(post_process.MustRun, 'Skipping CL upload in CQ'),
      api.post_check(post_process.DoesNotRun, 'upload to cipd'),
      api.post_process(post_process.DropExpectation),
      build_target='kukui',
      bucket='staging',
      builder='firmware-packager-android-kukui-main',
      cq=True,
      gerrit_changes=test_gerrit_changes,
  )
