// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.paygen_orchestrator;

import "chromiumos/common.proto";

message PaygenOrchestratorProperties {
  // Builder name corresponding to paygen.json's convention.
  // See: gs://chromeos-build-release-console/paygen.json
  string builder_name = 1;

  // The version the builder\caller wants payloads to update to.
  // e.g. "13020.54.0".
  string target_chromeos_version = 2;

  // The delta types to generate for, empty for all.
  repeated chromiumos.DeltaType delta_types = 3;

  // TODO(crbug.com/1122854): Replace these with the common definition.
  enum Channel {
    CHANNEL_UNKNOWN = 0;
    CANARY = 1;
    DEV = 2;
    BETA = 3;
    STABLE = 4;
  }

  // The payload channels to generate for, empty requires DeltaType == NO_DELTA.
  repeated Channel channels = 4;

  // The models in which we've enabled AU testing. If empty we will assume
  // that the board name is the builder name (i.e. this isn't a unibuild).
  repeated string au_testing_models = 5;

  // The bucket to look for source artifacts in (e.g, chromeos-releases).
  string src_bucket = 6;

  // The bucket to place resulting artifacts in (e.g.
  // chromes-throw-away-bucket).
  string dest_bucket = 7;

  // The keyset to sign with (e.g. "coral-mp-v16"), if empty do not sign.
  string keyset = 8;

  // Should we not upload any generated artifacts or make other mutations.
  bool dryrun = 9;

  // Enumeration on whether or not to override the configured defaults.
  enum PayloadTestsOverride {
    RESPECT_CONFIG = 0;
    FORCE_TESTS = 1;
    FORCE_NO_TESTS = 2;
  }

  // Should we override the configured delta testing policy?
  PayloadTestsOverride delta_payload_test_override = 10;

  // Should we override the configured full testing policy?
  PayloadTestsOverride full_payload_test_override = 11;
}
