// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.paygen_orchestrator;

import "chromiumos/common.proto";

message PaygenOrchestratorProperties {
  // Builder name corresponding to paygen.json's convention.
  // See: gs://chromeos-build-release-console/paygen.json
  string builder_name = 1;

  // The version the builder\caller wants payloads to update to.
  // e.g. "13020.54.0".
  string target_chromeos_version = 2;

  // The delta types to generate for, empty for all.
  repeated chromiumos.DeltaType delta_types = 3;

  // The payload channels to generate for, empty requires DeltaType == NO_DELTA.
  repeated chromiumos.Channel channels = 4;

  // The bucket to look for source artifacts in (e.g, chromeos-releases).
  string src_bucket = 5;

  // The bucket to place resulting artifacts in (e.g.
  // chromes-throw-away-bucket).
  string dest_bucket = 6;

  // Should we not upload any generated artifacts or make other mutations.
  bool dryrun = 7;

  // Enumeration on whether or not to override the configured defaults.
  enum PayloadTestsOverride {
    RESPECT_CONFIG = 0;
    FORCE_TESTS = 1;
    FORCE_NO_TESTS = 2;
  }

  // Should we override the configured delta testing policy?
  PayloadTestsOverride delta_payload_test_override = 8;

  // Should we override the configured full testing policy?
  PayloadTestsOverride full_payload_test_override = 9;

  // The models for which we've enabled AU testing.
  // If empty (or if there is no overlap with applicable_models), then one test
  // request will be sent, with no model specified, meaning that the test can be
  // run on any model.
  repeated string au_testing_models = 10;

  // The models which should run AU testing for FSI payloads.
  // If empty, behavior will be the same as for empty au_testing_models.
  repeated string au_fsi_testing_models = 11;

  // Whether or not to publish a payload update to the pubsub topic. Defaults to
  // False because when called via a release builder, the release builder owns
  // publishing.
  bool publish_to_pubsub = 12;

  // Whether to generate minios payloads.
  bool minios = 14;

  // QS Account to use instead of whatever is configured. Passed to individual
  // paygen builds.
  string override_qs_account = 15;

  // If set, will use the local signing flow (currently a prototype).
  bool local_signing = 16;

  // Docker image to use for local signing. Should already be pulled down on the
  // host. This consists of the name of the docker image, followed by the tag,
  // i.e. "signing:1234".
  string docker_image = 17;

  // TODO(b/305046854): Temporarily allow MPA bot pool overrides.
  bool paygen_mpa = 18;

  // If set, will use new GenerateUnsignedPayload and FinalizePayload
  // BAPI endpoints for paygen.
  // TODO(b/299105459): Remove when all active builders have been switched
  // over (won't be for a while, since we have long living stabilize branches).
  bool use_split_paygen = 19;
}
