// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.paygen;

import "recipes/chromeos/paygen_orchestrator.proto";

import "chromite/api/payload.proto";
import "chromiumos/common.proto";

message AutoupdateTestConfig {
  // The source image version (e.g. '13373.0.0'). Required if generating a full
  // payload. Required to be empty if generating a delta payload.
  string src_version = 1;

  // The channel of the target payload (e.g. 'canary-channel'). Required if
  // generating a full payload. Required to be empty if generating a delta
  // payload.
  string src_channel = 2;

  // The delta types to generate for.
  chromiumos.DeltaType delta_type = 3;

  // A list of models that this config should run against. Each listed model
  // should run the test. None indicates it can run on any build target.
  repeated string applicable_models = 4;
}

message PaygenProperties {

  message PaygenRequest {
    // The paygen definition as destined for the build api.
    chromite.api.GenerationRequest generation_request = 1;

    // Which autoupdate tests to run with the generated payload.
    repeated AutoupdateTestConfig autoupdate_test_configs = 2;
  }

  // The list of paygen requests to kick off.
  repeated PaygenRequest requests = 1;
}
