// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.presubmit_cq;

message PresubmitCqProperties {
  // Passed to depot_tools/presubmit (Infra Presubmit). See
  // depot_tools/recipes/recipe_modules/presubmit/properties.proto for details.
  bool runhooks = 1;

  // Passed to depot_tools/presubmit (Infra Presubmit). See
  // depot_tools/recipes/recipe_modules/presubmit/properties.proto for details.
  // Passed to presubmit as timeout_s.
  int32 timeout_s = 2;

  // Projects to always run infra-fullcheckout-presubmit for.
  repeated string fullcheckout_projects = 3;
}
