// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.sign_image;

import "chromiumos/common.proto";
import "chromiumos/sign_image.proto";

message SignImageProperties {
  // The build target being built.
  chromiumos.BuildTarget build_target = 1;

  // The artifact type.
  chromiumos.ImageType image_type = 2;

  // The gs:// uri of the archive to sign.
  // (Maps to general.archive and tobesigned/filename.)
  string archive = 3;

  // The channel.
  // (Maps to insns.channel.)
  chromiumos.Channel channel = 4;

  // The keyset to use.
  // (Maps to insns.keyset.)
  string keyset = 5;

  // The signer branch to use
  chromiumos.SignerType signer_type = 6;

   // TODO(b:173049030) Obsolete. Cr50 stamping instructions, used only for
   // artifact_type = CR50_FIRMWARE.
  chromiumos.Cr50Instructions cr50_instructions = 7;

  // GSC stamping instructions, used only for artifact_type = GSC_FIRMWARE.
  chromiumos.GscInstructions gsc_instructions = 8;
}
