// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.source_cache_builder;

// Defines the source cache to generate or update
message SourceCacheDefinition {
  // The name of the cache to be generated or updated.
  string cache_name = 1;
  // Command to utilize to update the cache.
  string command = 3;
  // Default recovery snapshot version.
  string recovery_snapshot = 4;
  // Git branch to sync cache.
  string branch = 5;
  // GCE disk type.
  string disk_type = 6;
  // Whether the cache should be created from the external source.
  bool external_source = 7;
}
message SourceCacheBuilderProperties {
  // The list of the buildbucket pools to monitor and scale.
  repeated SourceCacheDefinition cache_definition = 1;
  // Google Storage bucket to write version files
  string cache_bucket = 2;
  // Number of days of snapshots to retain.0
  int32 retention_days = 3;
  // List of snapshots to exclude from cleanup
  repeated string protected_snapshots = 4;
  // List of images to exclude from cleanup
  repeated string protected_images = 5;
  // Full sync modulo (proportion that should be full syncs).
  // This is based upon the cron trigger generation number.
  int32 full_sync_modulo = 6;
}
