# -*- coding: utf-8 -*-
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for the Star Doctor.

Automatically updates binary config files and updates Goldeneye config
json files.
"""

from PB.recipes.chromeos.star_doctor import StarDoctorProperties

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/cipd',
    'recipe_engine/context',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/step',
    'depot_tools/depot_tools',
    'gerrit',
    'git',
]

INFRA_CONFIG_URL = 'https://chrome-internal.googlesource.com/chromeos/infra/config'
CI_PROD_SERVICE_ACCOUNT = 'chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com'

PROPERTIES = StarDoctorProperties


def RunSteps(api, properties):
  with api.step.nest('set up'):
    workdir = api.path.mkdtemp()
    api.git.clone(INFRA_CONFIG_URL, target_path=workdir, timeout_sec=3 * 60)

  with api.step.nest('generate binary config'):
    # We need lucicfg from depot_tools.
    with api.depot_tools.on_path():
      # We need protoc from cipd.
      cipd_dir = api.path.mkdtemp()
      pkgs = api.cipd.EnsureFile()
      pkgs.add_package('infra/tools/protoc/linux-amd64',
                       'protobuf_version:v3.11.4')
      api.cipd.ensure(cipd_dir, pkgs)
      with api.context(**{'env_suffixes': {'PATH': [cipd_dir]}}):
        with api.context(cwd=workdir):
          api.step('regenerate configs',
                   ['/bin/bash', 'regenerate_configs.sh', '-b'], timeout=3 * 60)

  with api.step.nest('commit changes') as presentation:
    with api.context(cwd=workdir):
      changed_files = api.git.get_working_dir_diff_files()
      if not changed_files:  # pragma: nocover
        presentation.step_text = 'no files changed'
        return
      if not properties.commit_changes:
        presentation.step_text = 'not configured to commit changes'
        return
      commit_lines = [
          'Automatic binary config update',
          'Generated by StarDoctor, see {} for the recipe.'.format(
              api.buildbucket.build_url()),
          'BUG=None\nTEST=regenerated configs',
      ]
      commit_msg = '\n\n'.join(commit_lines)
      api.git.add(changed_files)
      api.git.commit(commit_msg)
      api.git.push(INFRA_CONFIG_URL,
                   'HEAD:refs/for/master%l=Bot-Commit+1,l=Commit-Queue+2')

      # Find the change and link to it.
      changes = api.gerrit.query_changes(
          'https://chrome-internal-review.googlesource.com', [
              ('project', 'chromeos/infra/config'),
              ('owner', CI_PROD_SERVICE_ACCOUNT),
              ('status', 'open'),
          ])
      if len(changes) < 1:  # pragma: nocover
        presentation.step_text = 'did not find change'
        return
      presentation.links['link to change'] = 'https://crrev.com/i/{}'.format(
          changes[0].change)


def GenTests(api):
  yield api.test('dont_commit', api.properties(commit_changes=False))

  yield api.test('full', api.properties(commit_changes=True))
