# -*- coding: utf-8 -*-
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for the Star Doctor.

Automatically updates binary config files and updates Goldeneye config
json files.
"""

from recipe_engine import post_process

from PB.recipes.chromeos.star_doctor import (StarDoctorProperties,
                                             RemoteConfigFile)

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/cipd',
    'recipe_engine/context',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/step',
    'depot_tools/depot_tools',
    'depot_tools/gsutil',
    'gerrit',
    'git',
]

INFRA_CONFIG_URL = 'https://chrome-internal.googlesource.com/chromeos/infra/config'
CI_PROD_SERVICE_ACCOUNT = 'chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com'

PROPERTIES = StarDoctorProperties


def RunSteps(api, properties):
  with api.step.nest('set up'):
    workdir = api.path.mkdtemp()
    api.git.clone(INFRA_CONFIG_URL, target_path=workdir, timeout_sec=3 * 60)

  remote_config_files = properties.remote_config_files
  # If remote_config_files is not specified, build them based on the ge_bucket
  # and branches properties. Note that if remote_config_files is specified,
  # ge_bucket and branches should not be.
  if not remote_config_files:
    remote_config_files.add(
        bucket_name=properties.ge_bucket,
        object_name='build_config.ToT.json',
        dest_path='goldeneye/build_config.ToT.json',
    )

    for branch in properties.branches:
      branched_config = 'build_config.release-{}.json'.format(branch)
      remote_config_files.add(
          bucket_name=properties.ge_bucket,
          object_name=branched_config,
          dest_path='goldeneye/{}'.format(branched_config),
      )
  else:
    if properties.ge_bucket or properties.branches:
      raise ValueError(
          'ge_bucket and branches cannot be set if remote_config_files is set.')

  with api.step.nest('generate binary config'):
    with api.step.nest('copy remote configs') as presentation:
      for remote_config_file in remote_config_files:
        api.gsutil.download(
            remote_config_file.bucket_name, remote_config_file.object_name,
            workdir.join(remote_config_file.dest_path),
            name='download {}/{}'.format(
                remote_config_file.bucket_name,
                remote_config_file.object_name,
            ))

    # We need lucicfg from depot_tools.
    with api.depot_tools.on_path():
      # We need protoc from cipd.
      cipd_dir = api.path.mkdtemp()
      pkgs = api.cipd.EnsureFile()
      pkgs.add_package('infra/tools/protoc/linux-amd64',
                       'protobuf_version:v3.11.4')
      api.cipd.ensure(cipd_dir, pkgs)
      with api.context(**{'env_suffixes': {'PATH': [cipd_dir]}}):
        with api.context(cwd=workdir):
          api.step('regenerate configs',
                   ['/bin/bash', 'regenerate_configs.sh', '-b'], timeout=3 * 60)

  with api.step.nest('commit changes') as presentation:
    with api.context(cwd=workdir):
      changed_files = api.git.get_working_dir_diff_files()
      if not changed_files:  # pragma: nocover
        presentation.step_text = 'no files changed'
        return
      if not properties.commit_changes:
        presentation.step_text = 'not configured to commit changes'
        return
      commit_lines = [
          'Automatic binary config update',
          'Generated by StarDoctor, see {} for the recipe.'.format(
              api.buildbucket.build_url()),
          'BUG=None\nTEST=regenerated configs',
      ]
      commit_msg = '\n\n'.join(commit_lines)
      api.git.add(changed_files)
      api.git.commit(commit_msg)
      api.git.push(INFRA_CONFIG_URL,
                   'HEAD:refs/for/master%l=Bot-Commit+1,l=Commit-Queue+2')

      # Find the change and link to it.
      changes = api.gerrit.query_changes(
          'https://chrome-internal-review.googlesource.com', [
              ('project', 'chromeos/infra/config'),
              ('owner', CI_PROD_SERVICE_ACCOUNT),
              ('status', 'open'),
          ])
      if len(changes) < 1:  # pragma: nocover
        presentation.step_text = 'did not find change'
        return
      presentation.links['link to change'] = 'https://crrev.com/i/{}'.format(
          changes[0].change)


def GenTests(api):
  yield api.test('dont_commit', api.properties(commit_changes=False))

  yield api.test(
      'full',
      api.properties(commit_changes=True, ge_bucket='test_ge_bucket',
                     branches=['R9000']))

  yield api.test(
      'old_and_new_properties_set',
      api.properties(
          StarDoctorProperties(
              ge_bucket='test_ge_bucket',
              branches=['R9000'],
              remote_config_files=[
                  RemoteConfigFile(
                      bucket_name='test_bucket',
                      object_name='test_object',
                      dest_path='ge/test_object',
                  )
              ],
          )),
      api.expect_exception('ValueError'),
      api.post_process(post_process.ResultReasonRE,
                       ('.*ge_bucket and branches cannot be set if'
                        ' remote_config_files is set..*')),
      api.post_process(post_process.DropExpectation),
  )
