# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for Suite Sync.

Suite Sync automatically syncs changes to autotest suites to the
new Centralized Suites format.
"""

from typing import List

from PB.recipes.chromeos.suite_sync import SuiteSyncProperties
from recipe_engine import post_process
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_api import StepFailure
from RECIPE_MODULES.chromeos.gerrit.api import Label

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/properties',
    'recipe_engine/step',
    'build_menu',
    'cros_sdk',
    'cros_source',
    'easy',
    'gerrit',
    'git',
    'gobin',
    'test_util',
    'repo',
]

PROPERTIES = SuiteSyncProperties

CONFIG_PROJECT = 'chromiumos/config'


def RunSteps(api: RecipeApi, properties: SuiteSyncProperties):
  with api.build_menu.configure_builder(missing_ok=True):
    with api.build_menu.setup_workspace_and_chroot(
        bootstrap_chroot=True, force_no_chroot_upgrade=True):
      run_suite_sync(api, properties)


def run_suite_sync(api: RecipeApi, properties: SuiteSyncProperties) -> None:
  """Run Sync for the configured suites

  SuiteSync will
  1. compile tast protobufs for cros-test-finder
  2. sync the autotest suite definition to the startlark definition
     (1 per suite)
  3. run generate.sh for config/test/suite_sets/
  4. create a gerrit change and submit the CL to CQ
  """
  with api.step.nest('Uprev Suite') as presentation:
    update_metadata(api)
    api.repo.start('suite-sync', projects=[CONFIG_PROJECT])
    for config in properties.suite_configs:
      if not config.suite or not config.subdir:
        presentation.step_text = f'invalid suite config{config}'
        raise StepFailure(f'invalid suite config {config}')
      sync_suite(api, config)
    run_generate(api)
    commit_uprev(api, properties.dry_run)


def update_metadata(api: RecipeApi) -> None:
  """Update the Tast metadata.

  This metadata is used by cros-test-finder/suite_migration script.
  """
  run_suite_migration(api, ['--update-metadata'])


def run_suite_migration(api: RecipeApi, args: List[str]) -> None:
  """Run the suite_migration script with the given args."""
  suite_migration_bin = '../third_party/autotest/files/contrib/suite_migration.py'
  cmd = [suite_migration_bin] + args
  api.cros_sdk.run(f'running suite_migration for {args}', cmd)


def sync_suite(api: RecipeApi, config: SuiteSyncProperties.SuiteConfig) -> None:
  """Sync the autotest suite definition.

  Sync autotest suite definition to the startlark definition.
  """
  run_suite_migration(api, [
      '--suite', config.suite, '--output',
      f'../config/test/suite_sets/suite_sets/{config.subdir}/{config.suite}.star'
  ])


def run_generate(api: RecipeApi) -> None:
  """Run the generate.sh script for centralized suites."""
  suite_generation_bin = api.cros_source.workspace_path.join(
      'src/config/test/suite_sets/generate.sh')
  api.easy.step('running generate for centralized suites',
                [suite_generation_bin])


def commit_uprev(api: RecipeApi, dryrun: bool = False) -> None:
  """Commit the uprev changes to gerrit

  Args:
    dryrun: If True change will be abandoned. Otherwise, it will
      be submitted to CQ and bot approved.
  """
  project_dir = api.cros_source.workspace_path.join('src/config')
  with api.context(cwd=project_dir):
    with api.step.nest('commit suite change') as presentation:
      if not api.git.diff_check('test/suite_sets'):
        presentation.step_text = 'no changes to commit'
        return
      commit_lines = [
          'centralized_suites: automatic sync from autotest',
          '',
          'Generated by suite_migration.',
          '',
          f'Cr-Build-Url: {api.buildbucket.build_url()}'
          'Cr-Automation-Id: suite_sync',
          '',
      ]
      commit_message = '\n'.join(commit_lines)
      api.git.add_all()
      api.git.commit(commit_message)
    with api.step.nest('upload cl to gerrit'):
      change = api.gerrit.create_change(CONFIG_PROJECT)
    with api.step.nest('send CL to CQ') as presentation:
      if dryrun:
        presentation.step_text = 'dry-run only'
        api.gerrit.abandon_change(change, message='dry-run only')
        return
      labels = {
          Label.BOT_COMMIT: 1,
          Label.COMMIT_QUEUE: 2,
      }
      api.gerrit.set_change_labels_remote(change, labels)


def GenTests(api):
  DEFAULT_CONFIG = api.properties(
      dry_run=False,
      suite_configs=[{
          'suite': 'bvt-tast-cq',
          'subdir': 'cq'
      }, {
          'suite': 'faft_pd',
          'subdir': 'firmware'
      }],
  )

  yield api.test(
      'build-pass', api.git.diff_check(True),
      api.post_check(post_process.MustRun, 'Uprev Suite.send CL to CQ'),
      DEFAULT_CONFIG)

  yield api.test(
      'build-dry-run', api.git.diff_check(True),
      api.properties(
          dry_run=True, suite_configs=[{
              'suite': 'my_suite',
              'subdir': 'my_subdir'
          }]))

  yield api.test('build-invalid-config', api.git.diff_check(True),
                 api.properties(suite_configs=[{
                     'subdir': 'my_subdir'
                 }]), status='FAILURE')

  yield api.test(
      'build-no-change',
      api.post_check(post_process.DoesNotRun, 'Uprev Suite.send CL to CQ'),
      api.git.diff_check(False), DEFAULT_CONFIG)

  yield api.test(
      'build-fail-suite-migration',
      api.override_step_data(
          'Uprev Suite.running generate for centralized suites', retcode=1),
      DEFAULT_CONFIG, status='FAILURE')
