// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.test_recipes;

message TestRecipesProperties {
  // A list of builders to test the CL on. Only builders in the
  // staging environment should be used.  These builders will only be launched
  // if the CL modifies the recipe, or one of its dependencies.
  repeated string builders = 1;

  // A list of builders to always test the CL with.
  repeated string always_launch_builders = 2;
}
