// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.test_recipes;

message TestRecipesProperties {
  message Verifier {
    // The name of the builder
    string name = 1;

    // Whether the builder is critical.
    bool critical = 2;

    // Whether to always launch the builder.
    bool always_launch = 3;

    // The bucket of the builder. Defaults to 'staging'.
    string bucket = 4;

    // Optional GCE project override for the child led build.
    string gce_project_override = 5;
  }

  // Verifier used to test recipes.  If set, this overrides builders and
  // always_launch_builders.
  repeated Verifier verifiers = 3;
}
