// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.uprev_borealis_deps;

import "chromiumos/common.proto";

message UprevBorealisDepsProperties {
  // Whether or not to attempt to uprev the Arch historic mirror.
  bool uprev_arch_mirror = 1;

  // Whether or not to attempt to uprev the PKGBUILDs.
  bool uprev_pkgbuilds = 2;

  // Path to the Borealis repository relative to the CrOS SDK root.
  // Optional. Defaults to 'src/platform/borealis-vm'.
  string borealis_path = 3;
}
