# -*- coding: utf-8 -*-
# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Recipe for upreving Borealis build dependencies."""

from recipe_engine import post_process
from PB.recipes.chromeos.uprev_borealis_deps import (UprevBorealisDepsProperties
                                                    )

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/properties',
    'recipe_engine/step',
    'depot_tools/depot_tools',
    'build_menu',
    'cros_sdk',
    'cros_source',
    'gerrit',
    'git',
    'repo',
]

PYTHON_VERSION_COMPATIBILITY = 'PY3'

PROPERTIES = UprevBorealisDepsProperties

_BOREALIS_REPO_PATH = 'src/platform/borealis/'


def RunSteps(api, properties):
  with api.build_menu.configure_builder(missing_ok=True), \
    api.build_menu.setup_workspace(), api.cros_sdk.cleanup_context():
    api.cros_sdk.create_chroot(version=None, use_image=False, timeout_sec=None)
    api.cros_sdk.update_chroot(None, None, timeout_sec=None)

    return DoRunSteps(api, properties)


def DoBorealisBuild(api, use_cache=True, skip_termina=False, stage=None):
  """Perform a Borealis build_full.

  Args:
    api: The recipe modules API.
    use_cache: Use cached step results from previous builds.
    skip_termina: Use a prebuilt copy of termina-tools
    stage: The name of the step from the Dockerfile to build. Does not
      perform a full build, will stop after the specified stage is built.
  """
  build_command = [
      './tools/build_full.py', '--licenses-html', "''", '--no-run-tests'
  ]
  if stage:
    build_command.append('--stage')
    build_command.append(stage)
  if not use_cache:
    build_command.append('--no-cache')
  if skip_termina:
    build_command.append('--skip-termina')
  api.step('Borealis build_full.py', build_command)


def _CommitChanges(api, project, commit_message):
  """Commit changes to the Borealis build/ directory.

  Args:
    api: The recipe modules API.
    project: Project object obtained from api.repo.project_info
    commit_message: Git commit message to use.
  """
  borealis_repo_path = api.cros_source.workspace_path.join(_BOREALIS_REPO_PATH)
  with api.step.nest('commit changes'), \
          api.context(cwd=borealis_repo_path):
    api.repo.start('uprev-borealis-deps', projects=[project.name])

    # Commit all changes in platform/borealis/build/
    api.git.add(['build/'])
    api.git.commit(commit_message)


def _CreateCL(api, project, presentation):
  """Upload Git changes as a Gerrit CL.

  Args:
    api: The recipe modules API.
    project: Project object obtained from api.repo.project_info
    presentation: the step to write the CL link to (for LUCI web UI)
  """
  # Upload CL to gerrit as long as not in staging job.
  if not api.build_menu.is_staging:
    with api.step.nest('upload CL to gerrit'):
      # TODO(pobega): Does this CL need a topic?
      change = api.gerrit.create_change(project=project.name)
      labels = {
          api.gerrit.Label.BOT_COMMIT: 1,
          # TODO(pobega): removed for testing, let's not auto commit (:
          #        api.gerrit.Label.COMMIT_QUEUE: 2,
      }
      api.gerrit.set_change_labels(change, labels)
      presentation.links['CL'] = api.gerrit.parse_gerrit_change_url(change)


def CommitChangesAndCreateCL(api, step_name, commit_message):
  """Create Git commit from changes and upload Gerrit CL.

  Args:
    api: The recipe modules API.
    step_name: Name of the step to nest operations from.
    commit_message: Git commit message to use.
  """
  project = api.repo.project_info(project=api.git.repository_root())

  with api.step.nest(step_name) as presentation:
    _CommitChanges(api, project, commit_message)
    _CreateCL(api, project, presentation)


def DoRunSteps(api, properties):
  chroot_path = api.cros_source.workspace_path
  borealis_path = chroot_path.join(_BOREALIS_REPO_PATH)
  with api.depot_tools.on_path(), api.context(cwd=borealis_path):
    # This recipe should only run on bots with docker pre-installed.  Abort
    # immediately if that is not the case.
    api.step('check docker install', ['docker', 'help'])

    # Do an initial stage build to generate termina-tools
    DoBorealisBuild(api, use_cache=False, skip_termina=False, stage="initial")

    # Uprev Arch historic mirror
    if properties.uprev_arch_mirror:
      with api.step.nest('Arch mirror uprev'):
        api.step('Arch mirror uprev', ['./tools/arch_mirror_uprev.py'])
        # Test that build_full still builds
        DoBorealisBuild(api, skip_termina=True)
        # Create Arch mirror uprev CL
        commit_message = 'uprev Arch historic mirror\n\n'
        commit_message += 'CL generated by job {}'.format(
            api.buildbucket.build_url())
        CommitChangesAndCreateCL(api, 'create Arch mirror CL', commit_message)

    # Uprev PKGBUILDs
    if properties.uprev_pkgbuilds:
      with api.step.nest('PKGBUILDs uprev'):
        api.step('PKGBUILD uprev', ['./tools/pkgbuild_uprev.py', '--all'])
        # Test that build_full still builds
        DoBorealisBuild(api, skip_termina=True)
        # Create PKGBUILD uprev CL
        commit_message = 'uprev PKGBUILDs\n\n'
        commit_message += 'CL generated by job {}'.format(
            api.buildbucket.build_url())
        # TODO: on the second run this creates a patchseries CL so the URL
        # provided is the same as the first.
        CommitChangesAndCreateCL(api, 'create PKGBUILDs CL', commit_message)


def GenTests(api):
  good_props = {'uprev_arch_mirror': True, 'uprev_pkgbuilds': True}
  yield api.test('basic', api.properties(**good_props),
                 api.post_check(post_process.StatusSuccess))

  yield api.test(
      'borealis build_full.py args', api.properties(**good_props),
      api.post_process(
          post_process.StepCommandContains,
          'Borealis build_full.py',
          [
              '--licenses-html',
              "''",
              '--no-run-tests',
              '--stage',
              'initial',
              '--no-cache',
          ],
      ),
      api.post_process(
          post_process.StepCommandContains,
          'Arch mirror uprev.Borealis build_full.py',
          [
              '--licenses-html',
              "''",
              '--no-run-tests',
              '--skip-termina',
          ],
      ),
      api.post_process(
          post_process.StepCommandContains,
          'PKGBUILDs uprev.Borealis build_full.py',
          [
              '--licenses-html',
              "''",
              '--no-run-tests',
              '--skip-termina',
          ],
      ), api.post_check(post_process.StatusSuccess))

  props = good_props.copy()
  del props['uprev_arch_mirror']
  yield api.test('no uprev arch', api.properties(**props),
                 api.post_check(post_process.MustRun, 'Borealis build_full.py'),
                 api.post_check(post_process.DoesNotRun, 'Arch mirror uprev'),
                 api.post_check(post_process.MustRun, 'PKGBUILDs uprev'),
                 api.post_check(post_process.StatusSuccess))

  props = good_props.copy()
  del props['uprev_pkgbuilds']
  yield api.test('no uprev pkgbuilds', api.properties(**props),
                 api.post_check(post_process.MustRun, 'Borealis build_full.py'),
                 api.post_check(post_process.MustRun, 'Arch mirror uprev'),
                 api.post_check(post_process.DoesNotRun, 'PKGBUILDs uprev'),
                 api.post_check(post_process.StatusSuccess))

  props = good_props.copy()
  del props['uprev_arch_mirror']
  del props['uprev_pkgbuilds']
  yield api.test('no uprevs', api.properties(**props),
                 api.post_check(post_process.MustRun, 'Borealis build_full.py'),
                 api.post_check(post_process.DoesNotRun, 'Arch mirror uprev'),
                 api.post_check(post_process.DoesNotRun, 'PKGBUILDs uprev'),
                 api.post_check(post_process.StatusSuccess))
