// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.manifest_doctor;

message ManifestDoctorProperties {
  // Cipd package to use for manifest_doctor.
  // Defaults to "chromiumos/infra/manifest_doctor/{$platform}".
  string manifest_doctor_cipd_package = 1;

  // Cipd ref to use for manifest_doctor.
  // Defaults to "staging" or "prod".
  string manifest_doctor_cipd_ref = 2;
}
