#!/usr/bin/env python3
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ./add-stanza  is a filter that adds or replaces the ile-de-france stanza
# of a job description.

import json
import sys

INDENT = '  '

cfg = {
  'enabled': True,
  'ile_de_france_selector': {
    'allow_list': {
      'models': [],
    },
  },
}

if len(sys.argv) > 1 and sys.argv[1]:
  models = sys.argv[1].split(',')
else:
  models = []
cfg['ile_de_france_selector']['allow_list']['models'] = models

job = json.load(sys.stdin)

job['buildbucket']['bbagent_args']['build']['input']['properties']['common_config']['enable_ile_de_france_config'] = cfg

json.dump(obj=job, fp=sys.stdout, indent=INDENT)
