# -*- coding: utf-8 -*-
# Copyright 2018 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""APIs for CrOS Portage."""

from collections import defaultdict
from datetime import datetime, timedelta
import json
import re

from recipe_engine import recipe_api
from recipe_engine.recipe_api import StepFailure

from RECIPE_MODULES.chromeos.util.util import exponential_retry


class PortageApi(recipe_api.RecipeApi):
  """A module for CrOS Portage steps."""

  def initialize(self):
    # Default dict of [step_name][emerge_type] -> count.
    self._portage_emerge_stats = {}

    self._BQ_TABLE_NAME = 'portage_stats.staging' if self.m.cros_infra_config.is_staging else 'portage_stats.prod'

    # Many of these regexs can be best understood by consulting `man emerge`.
    self._START_STATES = ['Emerging binary', 'Emerging']
    self._END_STATES = ['Completed', 'Failed to emerge']

    self._TIME_PART = r'^>>> (?P<time>[\d:\.]+) '
    self._STATE_PART = r'(?P<state>({})) '.format('|'.join(self._START_STATES +
                                                           self._END_STATES))
    self._ORDER_PART = r'(\((?P<job>\d+) of (?P<total>\d+)\) )?'
    self._PACKAGE_PART = r'(?P<category>(\w|-|^\/)+)\/(?P<package>[\w][\w+-]*)-'
    self._VERSION_PART = r'(?P<version>(\d+)((\.\d+)*)([a-z]?)((_(pre|p|beta|alpha|rc)\d*)*)(-r(\d+))?)'

    self._DURATION_REGEX = re.compile(self._TIME_PART + self._STATE_PART +
                                      self._ORDER_PART + self._PACKAGE_PART +
                                      self._VERSION_PART)
    self._PORTAGE_EMERGE_TYPE_RE = re.compile(
        r'^\[(?P<emerge_type>\w+)[ NSUDrRFfIBb#*~]{1,12}\] ' +
        self._PACKAGE_PART + self._VERSION_PART)

  def commit_package_uprevs(self):
    """Uprevs portage packages for all boards.

    Must be run with cwd inside a chromiumos source root.
    """
    cmd = [
        'vpython',
        'chromite/bin/cros_mark_as_stable',
        'commit',
        '--all',
        '--buildroot',
        self.m.src_state.workspace_path,
        '--overlay-type',
        'both',
    ]
    return self.m.step('commit portage package uprevs', cmd)

  @exponential_retry(retries=3, delay=timedelta(minutes=2))
  def push_package_uprevs(self, dryrun=False):
    """Pushes the changes generated by |uprev_portage_packages| to remote.

    Must be run with cwd inside a chromiumos source root.

    Args:
      dryrun (bool): If set, do everything except the actual push.
    """
    # TODO(crbug.com/916197): Pull git operations out of this script
    cmd = [
        'vpython',
        'chromite/bin/cros_mark_as_stable',
        'push',
        '--overlay-type',
        'both',
    ]
    if dryrun:
      cmd.append('--dryrun')
    return self.m.step('push portage package uprevs', cmd)

  def publish_emerge_stats(self, step_name: str, step_stdout: str,
                           set_output_prop: bool = False,
                           publish_to_bq: bool = False) -> dict:
    """Reads portage stdout and tries to glean facts about emerge performance.

    Portage gives us a stdout stream and outputs a formatted representation of
    number of packages that it will emerge, and the method in which it will
    emerge them. In lieu of a _good_ system (formatted output, bapi response,
    etc) we can sniff through this stdout and gather facts about prebuilt use,
    among other things. We produce an output property keyed on the provided
    step_name.

    Args:
      step_name: A unique step name (e.g. the bapi's step) and will be used
          as the output key in the metrics dictionary.
      step_stdout: The full standard out for the bapi call.
      set_output_prop: Should we set an output property with the results of
          the text analysis. Be mindful, it maybe quite large.
      publish_to_bq: Should we publish to the configured 'portage_stats'
          dataset.

    Returns:
      The current value of the output property.
    """
    # Gathering/setting these metrics shouldn't be allowed to fail the build.
    with self.m.step.nest('adding emerge metrics') as pres:
      try:
        # seen_dict are the packages that we've noticed in the output.
        seen_dict = defaultdict(list)

        # Keep a consistent insert time.
        insert_time = self.m.time.utcnow()

        # Pass one, look at the durations.
        lines = step_stdout.splitlines()
        for line in [l for l in lines if self._DURATION_REGEX.match(l)]:
          group_dict = self._DURATION_REGEX.search(line).groupdict()
          dict_key = group_dict['category'] + group_dict[
              'package'] + group_dict['version']
          seen_dict[dict_key].append(group_dict)

        for similar_statlines in seen_dict.values():
          # Assert there's one start and one end.
          if len(similar_statlines) != 2:
            self.m.easy.set_properties_step('set failed portage stats',
                                            failed_portage_stats=True)
            raise StepFailure('incoherent stdout from bapi'
                              ' -- uncertain start or end:\n{}'.format(
                                  str(similar_statlines)))

          # Set the start and the end matches, we previously asserted two exist.
          start_str = [
              x for x in similar_statlines if x['state'] in self._START_STATES
          ][0]
          end_str = [
              x for x in similar_statlines if x['state'] in self._END_STATES
          ][0]

          start = datetime.strptime(start_str['time'], '%H:%M:%S.%f')
          end = datetime.strptime(end_str['time'], '%H:%M:%S.%f')

          # if end < start, assume we started a day ago.
          if end < start:
            start -= timedelta(days=1)
          total_duration = end - start

          result = similar_statlines[0]
          # We only ammend the first found (usually start?) with additional
          # info. We'll strip the 'end' status from the array and move this
          # start to be directly keyed in the dict.
          result['duration'] = int(total_duration / timedelta(milliseconds=1))
          result['start'] = str(start)
          result['end'] = str(end)
          result['insert_time'] = str(insert_time)

        # Pass two look at the emerge method updating the same dict info...
        for line in [l for l in lines if self._PORTAGE_EMERGE_TYPE_RE.match(l)]:
          group_dict = self._PORTAGE_EMERGE_TYPE_RE.search(line).groupdict()
          dict_key = group_dict['category'] + group_dict[
              'package'] + group_dict['version']

          # This is totally normal if we failed half way.
          if not dict_key in seen_dict:
            continue

          seen_dict[dict_key][0]['emerge_type'] = group_dict['emerge_type']

        # Strip all but the element we've been amending (see note above).
        stat_list = []
        for stat in seen_dict.values():
          # Strip some things we've collected and no longer need.
          pack_stat = stat[0]
          pack_stat.pop('state')
          pack_stat.pop('time')
          pack_stat['bbid'] = self.m.buildbucket.build.id
          pack_stat['bucket'] = self.m.buildbucket.build.builder.bucket
          pack_stat['builder'] = self.m.buildbucket.build.builder.builder
          pack_stat['step_name'] = step_name
          stat_list.append(pack_stat)

        if stat_list:
          # Set the internal tracked dict.
          self._portage_emerge_stats[step_name] = stat_list

          if set_output_prop:
            # Set the internal running copy and set the output prop.
            self.m.easy.set_properties_step(
                'set portage stats', portage_stats=self._portage_emerge_stats)
          if publish_to_bq:
            # Do the BQ insert.
            jsonl = '\n'.join([json.dumps(x) for x in stat_list])
            tmp_file = self.m.path.mkstemp()
            self.m.file.write_text('write bq jsonl', tmp_file, jsonl)
            self.m.step('load json', [
                'bq', 'load', '--source_format=NEWLINE_DELIMITED_JSON',
                self._BQ_TABLE_NAME, tmp_file
            ])

      except Exception as e:  # pylint: disable=broad-except
        pres.status = self.m.step.INFRA_FAILURE
        pres.step_summary_text = 'Failure to publish portage stats'
        pres.logs['exception'] = str(e)

      return self._portage_emerge_stats
