# -*- coding: utf-8 -*-
# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""APIs for CrOS Portage."""

import re

from recipe_engine import recipe_api


class PortageApi(recipe_api.RecipeApi):
  """A module for CrOS Portage steps."""

  def regen_cache(self, repo_name, jobs=32):
    """Regenerate the portage cache with 'egencache' in the chroot.

    Must be run with cwd inside a chromiumos source root.

    Args:
      repo_name (str): Portage repo name, passed to 'egencache --repo'.
      jobs (int): Parallel processes to run, passed to 'egencache --jobs'.
    """
    cmd = ['egencache', '--update', '--repo', repo_name, '--jobs', '%d' % jobs]
    self.m.cros_sdk.run('portage regen cache %s' % repo_name, cmd)

  def uprev_packages(self, boards=None):
    """Uprevs portage packages for all boards, but makes no commits.

    Must be run with cwd inside a chromiumos source root.

    Args:
      boards (list[str]): The list of boards to uprev.
    """
    cmd = [
        'vpython',
        'chromite/scripts/cros_uprev',
        '--overlay-type', 'both',
        '--chroot', self.m.cros_sdk.chroot.path,
        '--all',
    ]
    if boards is not None:
      cmd.extend(['--boards', ':'.join(boards)])
    return self.m.step('uprev portage packages', cmd)

  def commit_package_uprevs(self):
    """Uprevs portage packages for all boards.

    Must be run with cwd inside a chromiumos source root.
    """
    cmd = [
        'vpython',
        'chromite/bin/cros_mark_as_stable',
        'commit',
        '--all',
        '--buildroot',
        self.m.cros_source.workspace_path,
        '--overlay-type',
        'both',
    ]
    return self.m.step('commit portage package uprevs', cmd)

  def push_package_uprevs(self):
    """Pushes the changes generated by |uprev_portage_packages| to remote.

    Must be run with cwd inside a chromiumos source root.
    """
    # TODO(crbug.com/916197): Pull git operations out of this script
    cmd = [
        'vpython',
        'chromite/bin/cros_mark_as_stable',
        'push',
        '--dryrun',
        '--overlay-type',
        'both',
    ]
    return self.m.step('push portage package uprevs', cmd)

  def portageq_best_visible_version(self, atom):
    """
    Run portageq best_visible and parse out the version.

    Must be run with cwd inside a chromiumos source root.

    Args:
      atom (str): An atom to pass to portageq, e.g. 'chromeos-chrome'

    Return: The atom version as a string, e.g. '74.0.3726.0'
    """
    cmd = ['portageq', 'best_visible', '.', atom]

    step_data = self.m.cros_sdk.run(
        'portageq best_visible %s' % atom, cmd,
        stdout=self.m.raw_io.output(add_output_log=True), step_test_data=
        lambda: self.m.raw_io.test_api.stream_output('chromeos-base/chromeos-chrome-74.0.3726.0_rc-r1')
    )

    # Expect the return to be like <category>/<package>-<version>_<tag>. Where
    # <category>, <package>, and <tag> can be composed of letters and dashes.
    # Extract the version.
    version_matches = re.findall('[a-z-]+\/[a-z-]+([\d.]+)_[\w-]+',
                                 step_data.stdout)

    if len(version_matches) != 1:
      raise ValueError(
          'Could not parse version from portageq output: %s' % step_data.stdout)

    return version_matches[0]
