# -*- coding: utf-8 -*-
# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""APIs for CrOS Portage."""

from recipe_engine import recipe_api


class PortageApi(recipe_api.RecipeApi):
  """A module for CrOS Portage steps."""

  def regen_cache(self, repo_name, jobs=32):
    """Regenerate the portage cache with 'egencache' in the chroot.

    Must be run with cwd inside a chromiumos source root.

    Args:
      repo_name (str): Portage repo name, passed to 'egencache --repo'.
      jobs (int): Parallel processes to run, passed to 'egencache --jobs'.
    """
    cmd = ['egencache', '--update', '--repo', repo_name, '--jobs', '%d' % jobs]
    self.m.cros_sdk.run('portage regen cache %s' % repo_name, cmd)

  def uprev_packages(self):
    """Uprevs portage packages for all boards.

    Must be run with cwd inside a chromiumos source root.
    """
    cmd = [
        'vpython',
        'chromite/bin/cros_mark_as_stable',
        'commit',
        '--all',
        '--buildroot',
        self.m.cros.workspace_path,
        '--overlay-type',
        'both',
    ]
    return self.m.step('uprev portage packages', cmd)

  def push_package_uprevs(self):
    """Pushes the changes generated by |uprev_portage_packages| to remote.

    Must be run with cwd inside a chromiumos source root.
    """
    # TODO(crbug.com/916197): Pull git operations out of this script
    cmd = [
        'vpython',
        'chromite/bin/cros_mark_as_stable',
        'push',
        '--overlay-type',
        'both',
    ]
    if self.m.dev.dryrun:
      cmd += ['--dryrun']
    return self.m.step('push portage package uprevs', cmd)
