// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_branch;

message CrosBranchProperties {
  reserved 1;

  // Cipd ref to use for branch_util.
  // Defaults to "chromiumos/infra/branch_util/{$platform}".
  string branch_util_cipd_package = 2;

  // Cipd ref to use for branch_util.
  // Defaults to "staging" or "prod".
  string branch_util_cipd_ref = 3;
}
