// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_prebuilts;

message GlobalProperties {
  // Whether to commit BINHOST.conf to git overlay.
  bool commit_overlay_binhost = 1;
}

message CrosPrebuiltsProperties {
  // If true, the prebuilt conf file will be uploaded to a branch
  // named "staging" instead of the real branch. Should only be set in
  // the staging environment.
  bool use_staging_branch = 1;

  // Whether to save package_index_files for a snapshot.
  bool enable_snapshot_prebuilts = 2;

  // How many distinct snapshots for which to pass
  // package_index_files to SysrootService/Create.  By default, none are sent.
  uint32 send_snapshot_prebuilts = 3;

  // (DEPRECATED) Whether to disable commiting BINHOST.conf to git overlay.
  // Using commit_overlay_binhost instead.
  bool disable_overlay_commits = 4;
}
