// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_prebuilts;

message CrosPrebuiltsProperties {
  // If true, the prebuilt conf file will be uploaded to a branch
  // named "staging" instead of the real branch. Should only be set in
  // the staging environment.
  bool use_staging_branch = 1;

  reserved 2, 3;
  reserved "enable_snapshot_prebuilts", "send_snapshot_prebuilts";

  // Whether to commit BINHOST.conf to git overlay.
  bool commit_overlay_binhost = 4;

  // Maximum number of uris to store in the BINHOST.conf.
  uint32 max_binhost_uris = 5;
}
