// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.remoteexec;

message RemoteexecProperties {
  // cipd rbe client version to ensure.
  string reclient_version = 1;
  // file of the config that should be passed when calling reproxy.
  string reproxy_cfg_file = 2;
  // Enable uploading the log files.
  bool enable_logs_upload = 3;
  // name of RBE project
  string rbe_project = 4;
  // name of ReAPI instance
  string reapi_instance = 5;
}
