// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.paygen_orchestration;

message PaygenOrchestrationProperties {

  // The max number of dlc payloads to include in a single generation request.
  // If not provided, dlc payloads will be sent in a single batch.
  int32 max_dlc_batch_size = 1;

  // The time (in seconds) to wait for paygenie builds to finish.
  // Defaults to 8 hours.
  uint32 paygen_children_timeout_sec = 2;

  // Whether to skip N2N batching for this builder.
  bool skip_n2n_batch = 3;
}
