# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Verify that apply_retry_policy() runs the expected process."""
from PB.chromiumos.common import BuildTarget
from PB.chromiumos.common import GerritChange
from PB.chromiumos.common import PackageInfo
from PB.go.chromium.org.luci.buildbucket.proto.common import \
    GerritChange as LuciGerritChange
from PB.recipe_modules.chromeos.pupr_gerrit_interface.tests.tests import \
    ApplyRetryPolicyProperties
from PB.recipes.chromeos.generator import BranchPolicy
from PB.recipes.chromeos.generator import FULL_RUN
from PB.recipes.chromeos.generator import DRY_RUN_NOT_APPROVED
from PB.recipes.chromeos.generator import NO_RETRY
from PB.recipes.chromeos.generator import OUTDATED_LEAVE_COMMENT
from PB.recipes.chromeos.generator import RETRY_LATEST_OR_LATEST_PINNED
from PB.recipes.chromeos.generator import RETRY_LATEST_PINNED
from PB.recipes.chromeos.generator import Reviewer
from PB.recipes.chromeos.generator import SUBMIT
from recipe_engine import post_process
from recipe_engine import recipe_api
from recipe_engine import recipe_test_api
from RECIPE_MODULES.chromeos.pupr_gerrit_interface.api import GerritInterfaceConfig
from RECIPE_MODULES.chromeos.pupr_local_uprev.api import LocalUprevConfig


DEPS = [
    'recipe_engine/assertions',
    'recipe_engine/buildbucket',
    'recipe_engine/path',
    'recipe_engine/properties',
    'cros_build_api',
    'gerrit',
    'git',
    'pupr_gerrit_interface',
    'pupr_local_uprev',
    'repo',
    'src_state',
    'test_util',
]

PROPERTIES = ApplyRetryPolicyProperties

BUILD_TARGETS = [BuildTarget(name='build-target')]
PACKAGE_CHROME = PackageInfo(category='chromeos-base',
                             package_name='chromeos-chrome')
PACKAGES = [PACKAGE_CHROME]

gerrit_changes = [
    GerritChange(
        host='chromium-review.googlesource.com',
        change=1234,
        project='chromium/src',
    ),
]

gerrit_changes_2 = [
    GerritChange(
        host='chromium-review.googlesource.com',
        change=1234,
    ),
    GerritChange(
        host='chromium-review.googlesource.com',
        change=1235,
    ),
]


def RunSteps(api: recipe_api.RecipeApi, properties: ApplyRetryPolicyProperties):
  api.pupr_gerrit_interface.set_generator_config(
      GerritInterfaceConfig.for_test(
          rebase_before_retry=properties.rebase_before_retry))

  # Arrange
  api.pupr_local_uprev.set_generator_config(
      LocalUprevConfig.for_test(
          packages=PACKAGES,
          build_targets=BUILD_TARGETS,
      ))

  mrm = api.pupr_gerrit_interface.find_most_recently_merged_uprev(
      'topic', branch='main') if properties.changes > 0 else None
  api.pupr_gerrit_interface.apply_retry_policy(
      [
          GerritChange(host='chromium-review.googlesource.com', change=1234 + i)
          for i in range(0, properties.changes)
      ], mrm,
      BranchPolicy(pattern='.*', repl='',
                   reviewers=[Reviewer(email='a@example.com')],
                   no_existing_cls_policy=properties.no_existing_cls_policy,
                   existing_cls_policy=properties.existing_cls_policy,
                   retry_cl_policy=properties.retry_cl_policy,
                   outdated_cls_policy=properties.outdated_cls_policy,
                   max_concurrent_cq_runs=properties.max_concurrent_cq_runs),
      'topic', properties.retry_only)


def GenTests(api: recipe_test_api.RecipeTestApi):

  yield api.test(
      'basic',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=1),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'retry-dry-run-no-bot-commit',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=DRY_RUN_NOT_APPROVED,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=1),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:dry-run:1234',
                      'message':
                          'Patch Set 1234: This CL has failed the run. Reason:'
                  }],
              },
          },
      ),
      api.pupr_gerrit_interface.set_retry_cl_response(
          'apply retry policy RETRY_LATEST_PINNED', 1234),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_check(post_process.MustRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_check(
          post_process.LogContains,
          'apply retry policy RETRY_LATEST_PINNED.retry CL 1234.set labels on CL 1234',
          'labels', ['"Commit-Queue": 1']),
      api.post_check(
          post_process.LogDoesNotContain,
          'apply retry policy RETRY_LATEST_PINNED.retry CL 1234.set labels on CL 1234',
          'labels', ['"Bot-Commit": 1']),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'retry-dry-run-cq-2-attempted',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=DRY_RUN_NOT_APPROVED,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=1),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:full-run:1234',
                      'message':
                          'Patch Set 1234:  This CL has failed the run. Reason:'
                  }],
              },
          },
      ),
      api.pupr_gerrit_interface.set_retry_cl_response(
          'apply retry policy RETRY_LATEST_PINNED', 1234),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_check(post_process.MustRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_check(
          post_process.LogContains,
          'apply retry policy RETRY_LATEST_PINNED.retry CL 1234.set labels on CL 1234',
          'labels', ['"Bot-Commit": 1', '"Commit-Queue": 2']),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'rebase-before-retry',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT,
                     rebase_before_retry=True, changes=1),
      api.gerrit.set_get_change_mergeable(
          'apply retry policy RETRY_LATEST_PINNED.test gerrit mergeable',
          'chromium-review.googlesource.com', 1234, 'current', False),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:full-run:1234',
                      'message':
                          'Patch Set 1234:  This CL has failed the run. Reason:'
                  }],
              },
          },
      ),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED.rebase CL 1234.get CL 1234 description',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:full-run:1234',
                      'message':
                          'Patch Set 1234:  This CL has failed the run. Reason:'
                  }],
                  'message':
                      'a quick description\n\nChange-Id: deadbeef\n\nPupr-Upstream-Versions: []\n'
              },
          },
      ),
      api.cros_build_api.set_api_return(
          'apply retry policy RETRY_LATEST_PINNED.rebase CL 1234.try uprev chromeos-base/chromeos-chrome',
          'PackageService/UprevVersionedPackage',
          step_name='uprev versioned package',
          data='{"responses":[{"additional_commit_info": "additional info to be rendered on uprev cl.", "modified_ebuilds": [{"path": "[CLEANUP]/chromiumos_workspace/src/overlay/foo.ebuild"}], "version": "1.2.3"}]}'
      ), api.git.diff_check(True),
      api.test_util.test_build(
          revision=None, extra_changes=[
              LuciGerritChange(host='chromium-review.googlesource.com',
                               change=1234)
          ], created_by='user:lamontjones@chromium.org').build,
      api.pupr_gerrit_interface.set_retry_cl_response(
          'apply retry policy RETRY_LATEST_PINNED', 1234),
      api.post_check(
          post_process.MustRun,
          'apply retry policy RETRY_LATEST_PINNED.upload patch set for Change-Id 1234'
      ),
      api.post_check(post_process.MustRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'rebase-before-retry-remote',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT,
                     rebase_before_retry=True, changes=1),
      api.gerrit.set_get_change_mergeable(
          'apply retry policy RETRY_LATEST_PINNED.test gerrit mergeable',
          'chromium-review.googlesource.com', 1234, 'current', True),
      api.gerrit.simulated_changes_are_submittable(
          False,
          'apply retry policy RETRY_LATEST_PINNED.test cq-orchestrator mergeable'
      ),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:full-run:1234',
                      'message':
                          'Patch Set 1234:  This CL has failed the run. Reason:'
                  }],
              },
          },
      ), api.git.diff_check(True),
      api.test_util.test_build(
          revision=None, extra_changes=[
              LuciGerritChange(host='chromium-review.googlesource.com',
                               change=1234)
          ], created_by='user:lamontjones@chromium.org').build,
      api.pupr_gerrit_interface.set_retry_cl_response(
          'apply retry policy RETRY_LATEST_PINNED', 1234),
      api.post_check(
          post_process.MustRun,
          'apply retry policy RETRY_LATEST_PINNED.rebase CL 1234.curl https://chromium-review.googlesource.com/changes/1234/rebase'
      ),
      api.post_check(post_process.MustRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'rebase-before-retry-already-mergeable',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT,
                     rebase_before_retry=True, changes=1),
      api.gerrit.set_get_change_mergeable(
          'apply retry policy RETRY_LATEST_PINNED.test gerrit mergeable',
          'chromium-review.googlesource.com', 1234, 'current', True),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:full-run:1234',
                      'message':
                          'Patch Set 1234:  This CL has failed the run. Reason:'
                  }],
              },
          },
      ), api.git.diff_check(True),
      api.test_util.test_build(
          revision=None, extra_changes=[
              LuciGerritChange(host='chromium-review.googlesource.com',
                               change=1234)
          ], created_by='user:lamontjones@chromium.org').build,
      api.pupr_gerrit_interface.set_retry_cl_response(
          'apply retry policy RETRY_LATEST_PINNED', 1234),
      api.post_check(post_process.DoesNotRunRE, r'.*\.rebase CL 1234.*'),
      api.post_check(post_process.DoesNotRunRE,
                     r'.*\.upload patch set for Change-Id 1234'),
      api.post_check(post_process.MustRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'rebase-before-retry-already-running-and-mergeable',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN,
                     retry_cl_policy=RETRY_LATEST_OR_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT,
                     rebase_before_retry=True, changes=1),
      api.gerrit.set_get_change_mergeable(
          'apply retry policy RETRY_LATEST_OR_LATEST_PINNED.test gerrit mergeable',
          'chromium-review.googlesource.com', 1234, 'current', True),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_OR_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date': 1234,
                      'tag': 'autogenerated:cq:dry-run:1234',
                      'message': 'Patch Set 5:  Dry run: CV is trying the patch'
                  }],
              },
          },
      ), api.git.diff_check(True),
      api.test_util.test_build(
          revision=None, extra_changes=[
              LuciGerritChange(host='chromium-review.googlesource.com',
                               change=1234)
          ], created_by='user:lamontjones@chromium.org').build,
      api.post_check(post_process.DoesNotRunRE, r'.*\.rebase CL 1234.*'),
      api.post_check(post_process.DoesNotRunRE,
                     r'.*\.upload patch set for Change-Id 1234'),
      api.post_check(post_process.DoesNotRunRE, '.*retry CL 1234'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'rebase-before-retry-already-running-and-rebase',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN,
                     retry_cl_policy=RETRY_LATEST_OR_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT,
                     rebase_before_retry=True, changes=1),
      api.gerrit.set_get_change_mergeable(
          'apply retry policy RETRY_LATEST_OR_LATEST_PINNED.test gerrit mergeable',
          'chromium-review.googlesource.com', 1234, 'current', False),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_OR_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date': 1234,
                      'tag': 'autogenerated:cq:dry-run:1234',
                      'message': 'Patch Set 5:  Dry run: CV is trying the patch'
                  }],
              },
          },
      ),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_OR_LATEST_PINNED.rebase CL 1234.get CL 1234 description',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:full-run:1234',
                      'message':
                          'Patch Set 1234:  This CL has failed the run. Reason:'
                  }],
                  'message':
                      'a quick description\n\nChange-Id: deadbeef\n\nPupr-Upstream-Versions: []\n'
              },
          },
      ),
      api.cros_build_api.set_api_return(
          'apply retry policy RETRY_LATEST_OR_LATEST_PINNED.rebase CL 1234.try uprev chromeos-base/chromeos-chrome',
          'PackageService/UprevVersionedPackage',
          step_name='uprev versioned package',
          data='{"responses":[{"additional_commit_info": "additional info to be rendered on uprev cl.", "modified_ebuilds": [{"path": "[CLEANUP]/chromiumos_workspace/src/overlay/foo.ebuild"}], "version": "1.2.3"}]}'
      ), api.git.diff_check(True),
      api.test_util.test_build(
          revision=None, extra_changes=[
              LuciGerritChange(host='chromium-review.googlesource.com',
                               change=1234)
          ], created_by='user:lamontjones@chromium.org').build,
      api.pupr_gerrit_interface.set_retry_cl_response(
          'apply retry policy RETRY_LATEST_OR_LATEST_PINNED', 1234),
      api.post_check(post_process.MustRunRE, r'.*\.rebase CL 1234.*'),
      api.post_check(
          post_process.MustRunRE,
          'apply retry policy RETRY_LATEST_OR_LATEST_PINNED.upload patch set for Change-Id 1234'
      ),
      api.post_check(
          post_process.MustRun,
          'apply retry policy RETRY_LATEST_OR_LATEST_PINNED.retry CL 1234'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'rebase-before-retry-dry-run-passed',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT,
                     rebase_before_retry=True, changes=2),
      api.gerrit.set_get_change_mergeable(
          'apply retry policy RETRY_LATEST_PINNED.test gerrit mergeable',
          'chromium-review.googlesource.com', 1234, 'current', False),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          [
              GerritChange(
                  host='chromium-review.googlesource.com',
                  change=1234,
              ),
              GerritChange(
                  host='chromium-review.googlesource.com',
                  change=1235,
              ),
          ],
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date': 1234,
                      'tag': 'autogenerated:cq:dry-run:1234',
                      'message': 'Patch Set 1234:  This CL has passed the run'
                  }],
              },
              1235: {
                  'created': '2023-01-09 13:10:20.000000000',
              },
          },
      ),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED.rebase CL 1234.get CL 1234 description',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:dry-run:1234',
                      'message':
                          'Patch Set 1234:  This CL has failed the run. Reason:'
                  }],
                  'message':
                      'a quick description\n\nChange-Id: deadbeef\n\nPupr-Upstream-Versions: []\n'
              },
          },
      ),
      api.cros_build_api.set_api_return(
          'apply retry policy RETRY_LATEST_PINNED.rebase CL 1234.try uprev chromeos-base/chromeos-chrome',
          'PackageService/UprevVersionedPackage',
          step_name='uprev versioned package',
          data='{"responses":[{"additional_commit_info": "additional info to be rendered on uprev cl.", "modified_ebuilds": [{"path": "[CLEANUP]/chromiumos_workspace/src/overlay/foo.ebuild"}], "version": "1.2.3"}]}'
      ), api.git.diff_check(True),
      api.test_util.test_build(
          revision=None, extra_changes=[
              LuciGerritChange(host='chromium-review.googlesource.com',
                               change=1234)
          ], created_by='user:lamontjones@chromium.org').build,
      api.pupr_gerrit_interface.set_retry_cl_response(
          'apply retry policy RETRY_LATEST_PINNED', 1234),
      api.post_check(
          post_process.MustRun,
          'apply retry policy RETRY_LATEST_PINNED.upload patch set for Change-Id 1234'
      ),
      api.post_check(post_process.MustRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_check(
          post_process.LogContains,
          'apply retry policy RETRY_LATEST_PINNED.retry CL 1234.set labels on CL 1234',
          'labels', ['"Commit-Queue": 2', '"Bot-Commit": 1']),
      api.post_check(
          post_process.MustRun,
          'apply retry policy RETRY_LATEST_PINNED.abandon CLs before passed CQ+1 CL'
      ),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'rebase-before-retry-dry-run-passed-staging',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT,
                     rebase_before_retry=True, changes=2),
      api.gerrit.set_get_change_mergeable(
          'apply retry policy RETRY_LATEST_PINNED.test gerrit mergeable',
          'chromium-review.googlesource.com', 1234, 'current', False),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          [
              GerritChange(
                  host='chromium-review.googlesource.com',
                  change=1234,
              ),
              GerritChange(
                  host='chromium-review.googlesource.com',
                  change=1235,
              ),
          ],
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date': 1234,
                      'tag': 'autogenerated:cq:dry-run:1234',
                      'message': 'Patch Set 1234:  This CL has passed the run'
                  }],
              },
              1235: {
                  'created': '2023-01-09 13:10:20.000000000',
              },
          },
      ),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED.rebase CL 1234.get CL 1234 description',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:dry-run:1234',
                      'message':
                          'Patch Set 1234:  This CL has failed the run. Reason:'
                  }],
                  'message':
                      'a quick description\n\nChange-Id: deadbeef\n\nPupr-Upstream-Versions: []\n'
              },
          },
      ),
      api.cros_build_api.set_api_return(
          'apply retry policy RETRY_LATEST_PINNED.rebase CL 1234.try uprev chromeos-base/chromeos-chrome',
          'PackageService/UprevVersionedPackage',
          step_name='uprev versioned package',
          data='{"responses":[{"additional_commit_info": "additional info to be rendered on uprev cl.", "modified_ebuilds": [{"path": "[CLEANUP]/chromiumos_workspace/src/overlay/foo.ebuild"}], "version": "1.2.3"}]}'
      ), api.git.diff_check(True),
      api.test_util.test_build(
          revision=None, extra_changes=[
              LuciGerritChange(host='chromium-review.googlesource.com',
                               change=1234)
          ], created_by='user:lamontjones@chromium.org', bucket='staging',
          builder='staging-my-cool-pupr-generator').build,
      api.pupr_gerrit_interface.set_retry_cl_response(
          'apply retry policy RETRY_LATEST_PINNED', 1234),
      api.post_check(
          post_process.MustRun,
          'apply retry policy RETRY_LATEST_PINNED.upload patch set for Change-Id 1234'
      ),
      api.post_check(post_process.MustRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_check(
          post_process.LogContains,
          'apply retry policy RETRY_LATEST_PINNED.retry CL 1234.set labels on CL 1234',
          'labels', ['"Commit-Queue": 2']),
      api.post_check(
          post_process.LogDoesNotContain,
          'apply retry policy RETRY_LATEST_PINNED.retry CL 1234.set labels on CL 1234',
          'labels', ['"Bot-Commit": 1']),
      api.post_check(
          post_process.MustRun,
          'apply retry policy RETRY_LATEST_PINNED.abandon CLs before passed CQ+1 CL'
      ),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'frozen-skip-retry',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=1),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set': 5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch': 'main',
                  'hashtags': ['pupr-freeze-retries'],
                  'created': '2023-01-09 13:11:20.000000000',
              },
          },
      ),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'no-retry',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN, retry_cl_policy=NO_RETRY,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=1),
      api.post_check(post_process.DoesNotRun, 'apply retry policy NO_RETRY'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'no-uprev',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=0,
                     rebase_before_retry=True),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'retry-limit-exceeded',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=DRY_RUN_NOT_APPROVED,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=2,
                     max_concurrent_cq_runs=1),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes_2,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:dry-run:1234',
                      'message':
                          'Patch Set 1234: This CL has failed the run. Reason:'
                  }],
              },
              1235: {
                  'patch_set': 1,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch': 'main',
                  'created': '2023-01-09 13:11:21.000000000',
                  'labels': {
                      'Commit-Queue': {
                          'all': [{
                              'value': 1
                          }]
                      }
                  },
                  'messages': [],
              },
          },
      ),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_check(post_process.DoesNotRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_check(post_process.StepTextContains,
                     'apply retry policy RETRY_LATEST_PINNED',
                     ['Retry skipped: concurrent CQ run limit of 1 reached']),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'retry-limit-exceeded-with-rebase',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=DRY_RUN_NOT_APPROVED,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=2,
                     max_concurrent_cq_runs=1, rebase_before_retry=True),
      api.gerrit.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes_2,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:dry-run:1234',
                      'message':
                          'Patch Set 1234: This CL has failed the run. Reason:'
                  }],
              },
              1235: {
                  'patch_set': 1,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch': 'main',
                  'created': '2023-01-09 13:11:21.000000000',
                  'labels': {
                      'Commit-Queue': {
                          'all': [{
                              'value': 1
                          }]
                      }
                  },
                  'messages': [],
              },
          },
      ),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_check(
          post_process.DoesNotRun,
          'apply retry policy RETRY_LATEST_PINNED.test gerrit mergeable'),
      api.post_check(post_process.DoesNotRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_check(post_process.StepTextContains,
                     'apply retry policy RETRY_LATEST_PINNED',
                     ['Retry skipped: concurrent CQ run limit of 1 reached']),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'retry-wip',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=DRY_RUN_NOT_APPROVED,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=1,
                     rebase_before_retry=True),
      api.cros_build_api.set_upreved_ebuilds(['src/overlay/foo.ebuild']),
      api.git.diff_check(True),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'work_in_progress':
                      True,
                  'revision_info': {
                      'commit': {
                          'message':
                              'a quick description\n\nChange-Id: deadbeef\n\nPupr-Upstream-Versions: [{"ref": "refs/tags/79.0.3945.20", "repository": "/chromium/src", "revision": "83a1812dddfc24f604d92bf61ad58efe9227a6fc"}]',
                      },
                  },
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:dry-run:1234',
                      'message':
                          'Patch Set 1234: This CL has failed the run. Reason:'
                  }],
              },
          },
      ),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED.rebase CL 1234.get CL 1234 description',
          gerrit_changes,
          {
              1234: {
                  'revision_info': {
                      'commit': {
                          'message':
                              'a quick description\n\nChange-Id: deadbeef\n\nPupr-Upstream-Versions: [{"ref": "refs/tags/79.0.3945.20", "repository": "/chromium/src", "revision": "83a1812dddfc24f604d92bf61ad58efe9227a6fc"}]',
                      },
                  },
              },
          },
      ),
      api.gerrit.set_get_change_mergeable(
          'apply retry policy RETRY_LATEST_PINNED.test gerrit mergeable',
          'chromium-review.googlesource.com', 1234, 'current', True),
      api.gerrit.simulated_changes_are_submittable(
          False,
          'apply retry policy RETRY_LATEST_PINNED.test cq-orchestrator mergeable'
      ), api.path.exists(api.src_state.workspace_path),
      api.repo.project_infos_step_data(
          step='apply retry policy RETRY_LATEST_PINNED.upload patch set for Change-Id 1234',
          data=[{
              'project': 'chromium/src',
              'path': 'src/chromium'
          }],
      ),
      api.pupr_gerrit_interface.set_retry_cl_response(
          'apply retry policy RETRY_LATEST_PINNED', 1234),
      api.post_check(
          post_process.MustRun,
          'apply retry policy RETRY_LATEST_PINNED.upload patch set for Change-Id 1234',
      ),
      api.post_check(
          post_process.DoesNotRun,
          'apply retry policy RETRY_LATEST_PINNED.mark CL 1234 ready for review'
      ),
      api.post_check(post_process.MustRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'retry-wip-no-rebase',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=DRY_RUN_NOT_APPROVED,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=1,
                     rebase_before_retry=False),
      api.cros_build_api.set_upreved_ebuilds(['src/overlay/foo.ebuild']),
      api.git.diff_check(True),
      api.gerrit.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'work_in_progress':
                      True,
                  'revision_info': {
                      'commit': {
                          'message':
                              'a quick description\n\nChange-Id: deadbeef\n\nPupr-Upstream-Versions: [{"ref": "refs/tags/79.0.3945.20", "repository": "/chromium/src", "revision": "83a1812dddfc24f604d92bf61ad58efe9227a6fc"}]',
                      },
                  },
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:dry-run:1234',
                      'message':
                          'Patch Set 1234: This CL has failed the run. Reason:'
                  }],
              },
          },
      ),
      api.post_check(
          post_process.DoesNotRun,
          'apply retry policy RETRY_LATEST_PINNED.upload patch set for Change-Id 1234',
      ),
      api.post_check(
          post_process.MustRun,
          'apply retry policy RETRY_LATEST_PINNED.mark CL 1234 ready for review'
      ),
      api.post_check(post_process.MustRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_process(post_process.DropExpectation))

  yield api.test(
      'untrusted-uploader-strips-approvals-on-retry',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=FULL_RUN,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=1),
      api.pupr_gerrit_interface.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {},
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:full-run:1234',
                      'message':
                          'Patch Set 1234:  This CL has failed the run. Reason:'
                  }],
              },
          },
      ),
      api.pupr_gerrit_interface.set_retry_cl_response(
          'apply retry policy RETRY_LATEST_PINNED', 1234,
          uploader_account_id=200),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_check(post_process.MustRun,
                     'apply retry policy RETRY_LATEST_PINNED.retry CL 1234'),
      api.post_check(
          post_process.MustRun,
          'apply retry policy RETRY_LATEST_PINNED.retry CL 1234.add comment on CL 1234'
      ),
      api.post_check(
          post_process.MustRun,
          'apply retry policy RETRY_LATEST_PINNED.retry CL 1234.add hashtags on CL 1234'
      ),
      api.post_check(
          post_process.LogContains,
          'apply retry policy RETRY_LATEST_PINNED.retry CL 1234.add hashtags on CL 1234',
          'hashtags', ['"pupr-ignored"']),
      api.post_check(
          post_process.DoesNotRun,
          'apply retry policy RETRY_LATEST_PINNED.retry CL 1234.set labels on CL 1234'
      ),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'rebase-before-retry-with-merged-uprev',
      api.properties(existing_cls_policy=SUBMIT,
                     no_existing_cls_policy=DRY_RUN_NOT_APPROVED,
                     retry_cl_policy=RETRY_LATEST_PINNED,
                     outdated_cls_policy=OUTDATED_LEAVE_COMMENT, changes=1,
                     rebase_before_retry=True),
      api.gerrit.set_query_changes_response(
          'examine outdated CLs.merged CLs from chromium host (within 30 days)',
          [
              {
                  '_number': 91827,
                  'change_number': 91827,
                  'project': 'chromium/src',
                  'host': 'chromium-review.googlesource.com',
                  'status': 'MERGED',
              },
          ], 'https://chromium-review.googlesource.com'),
      api.gerrit.set_gerrit_fetch_changes_response(
          'examine outdated CLs.merged CLs from chromium host (within 30 days)',
          [GerritChange(change=91827, host='chromium-review.googlesource.com')],
          {
              91827: {
                  'change_number': 91827,
                  'project': 'chromium/src',
                  'status': 'MERGED',
                  'created': '2020-01-01 00:00:00.000000000',
                  'submitted': '2020-01-02 00:00:00.000000000',
              },
          },
      ),
      api.gerrit.set_gerrit_fetch_changes_response(
          'apply retry policy RETRY_LATEST_PINNED',
          gerrit_changes,
          {
              1234: {
                  'patch_set':
                      5,
                  'files': {
                      'a/b/d/test.txt': {}
                  },
                  'branch':
                      'main',
                  'hashtags': ['pupr-retry-pinned'],
                  'created':
                      '2023-01-09 13:11:20.000000000',
                  'messages': [{
                      'date':
                          1234,
                      'tag':
                          'autogenerated:cq:dry-run:1234',
                      'message':
                          'Patch Set 1234: This CL has failed the run. Reason:'
                  }],
              },
          },
      ),
      api.gerrit.set_get_change_mergeable(
          'apply retry policy RETRY_LATEST_PINNED.test gerrit mergeable',
          'chromium-review.googlesource.com', 1234, 'current', True),
      api.post_check(post_process.StepSuccess,
                     'apply retry policy RETRY_LATEST_PINNED'),
      api.post_process(post_process.DropExpectation),
  )
