# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Verify that handle_open_changes() runs the expected process."""

from typing import List, Dict, Tuple

from PB.chromiumos.common import BuildTarget
from PB.chromiumos.common import GerritChange
from PB.chromiumos.common import PackageInfo
from PB.recipe_modules.chromeos.pupr_gerrit_interface.tests.tests import \
  HandleRepeatedlyFailingChangesProperties
from PB.recipes.chromeos.generator import MAX_CQ_RETRY_ACTION_IGNORE
from PB.recipes.chromeos.generator import MAX_CQ_RETRY_ACTION_VERIFIED_MINUS_ONE
from RECIPE_MODULES.chromeos.gerrit.api import JSONObject
from RECIPE_MODULES.chromeos.gerrit.api import change_info_to_gerrit_change
from recipe_engine import post_process
from recipe_engine import recipe_api
from recipe_engine import recipe_test_api

DEPS = [
    'recipe_engine/assertions',
    'recipe_engine/properties',
    'cros_build_api',
    'gerrit',
    'git',
    'pupr_gerrit_interface',
    'pupr_local_uprev',
    'src_state',
    'test_util',
]

PROPERTIES = HandleRepeatedlyFailingChangesProperties

BUILD_TARGETS = [BuildTarget(name='build-target')]
PACKAGE_CHROME = PackageInfo(category='chromeos-base',
                             package_name='chromeos-chrome')
PACKAGES = [PACKAGE_CHROME]

merged_value_dict = {
    91827: {
        'change_number': 91827,
        'project': 'chromium/src',
        'status': 'MERGED'
    }
}


def RunSteps(api: recipe_api.RecipeApi,
             properties: HandleRepeatedlyFailingChangesProperties):
  # Arrange
  api.pupr_local_uprev.set_generator_attributes(
      packages=PACKAGES,
      build_targets=BUILD_TARGETS,
  )

  remaining_changes = api.pupr_gerrit_interface.handle_repeatedly_failing_changes(
      properties.open_changes,
      max_cq_retry=properties.max_cq_retry,
      should_count_dry_run=properties.should_count_dry_run,
      max_cq_retry_action=properties.max_cq_retry_action,
  )
  api.assertions.assertEqual(
      properties.expected_remaining_changes_number,
      [gerrit_change.change for gerrit_change in remaining_changes])


def GenTests(api: recipe_test_api.RecipeTestApi):
  CHANGE_ID_START = 1234

  def _create_gerrit_changes(num_changes) -> List[GerritChange]:
    """Return a list of |num_changes| GerritChange."""
    return [
        change_info_to_gerrit_change(
            {
                'id': f'chromium/src~main~{change_number}',
                'status': 'OPEN',
                '_number': change_number,
                'change_id': 'Ideadbeef',
                'project': 'chromium/src',
                'branch': 'main',
                'subject': 'Change title',
                'revisions': {
                    '184ebe53805e102605d11f6b143486d15c23a09c': {
                        '_number': 1,
                        'commit': {
                            'message': 'Change commit message',
                        },
                    },
                },
            }, 'https://chromium-review.googlesource.com')
        for change_number in range(CHANGE_ID_START, CHANGE_ID_START +
                                   num_changes)
    ]

  def _create_gerrit_fetch_changes_response(
      change_numbers: List[int],
      cl_specs: List[Tuple[int, bool, bool]]) -> Dict[int, JSONObject]:
    assert len(change_numbers) == len(cl_specs)
    return {
        change: {
            'patch_set': 1,
            'files': {
                'a/b/d/test.txt': {},
            },
            'branch': 'main',
            'hashtags': ['pupr-retry-pinned'] if is_pinned else [],
            'created': '2023-01-09 13:11:20.000000000',
            'messages': [{
                'date':
                    1234 + i,
                'tag':
                    f'autogenerated:cq:{"dry-run" if cq_dry_run else "full-run"}:{change}',
                'message':
                    'Patch Set 1:  This CL has failed the run. Reason:'
            } for i in range(retries)],
            'message': 'Change commit message'
        } for change, (retries, is_pinned,
                      cq_dry_run) in zip(change_numbers, cl_specs)
    }

  def test(name: str, max_cq_retry: int, based_on_dry_run: bool,
           cl_specs: List[Tuple[int, bool, bool]]):
    """Helper method to generate a test.

    Args:
      name: name of test
      max_cq_retry: the allowed number of CQ failures
      based_on_dry_run: use failed dry-run count as cq retry count
      cl_specs: tuple of int and bool to indicate the number of times each faked
        CL has failed CQ and whether or not it is pinned.
    """
    gerrit_changes = _create_gerrit_changes(len(cl_specs))
    gerrit_fetch_changes_response = _create_gerrit_fetch_changes_response(
        [gerrit_change.change for gerrit_change in gerrit_changes], cl_specs)

    # If configured to not abandon CLs due to CQ failures,
    # gerrit.fetch_patch_sets will not be called and should not set response.
    if max_cq_retry < 0:
      return api.test(
          name,
          api.properties(
              HandleRepeatedlyFailingChangesProperties(
                  open_changes=gerrit_changes, max_cq_retry=max_cq_retry,
                  expected_remaining_changes_number=[
                      gerrit_change.change for gerrit_change in gerrit_changes
                  ])),
          api.post_check(post_process.DoesNotRun,
                         'get CLs repeatedly failing CQ'),
          api.post_check(post_process.DoesNotRun,
                         'abandon unpinned CLs repeatedly failing CQ'),
      )

    return api.test(
        name,
        api.properties(
            HandleRepeatedlyFailingChangesProperties(
                open_changes=gerrit_changes, max_cq_retry=max_cq_retry,
                expected_remaining_changes_number=[
                    gerrit_changes[i].change
                    for i, (retries, is_pinned,
                            cq_dry_run) in enumerate(cl_specs)
                    if is_pinned or retries <= max_cq_retry
                ], should_count_dry_run=based_on_dry_run)),
        api.gerrit.set_gerrit_fetch_changes_response(
            'get CLs repeatedly failing CQ', gerrit_changes,
            gerrit_fetch_changes_response),
        api.post_check(post_process.LogEquals, 'get CLs repeatedly failing CQ',
                       'max CQ retry', str(max_cq_retry)),
        *[
            api.post_check(
                post_process.MustRun,
                f'abandon unpinned CLs repeatedly failing CQ.abandon CL {gerrit_changes[i].change}'
            )
            for i, (retries, is_pinned, cq_dry_run) in enumerate(cl_specs)
            if not is_pinned and retries > max_cq_retry
        ],
    )

  yield test('configured to never abandon', -1, False, [(3, False, False)])

  yield test('abandon unpinned CLs failed too many times', 1, False,
             [(1, False, False), (3, False, False), (0, False, False),
              (5, True, False)])

  yield test('Count dry-run for DRY_RUN policy', 1, True, [(1, False, True),
                                                           (3, False, True),
                                                           (0, False, True),
                                                           (5, True, True)])

  yield api.test(
      'no open changes',
      api.properties(
          HandleRepeatedlyFailingChangesProperties(
              open_changes=[], max_cq_retry=1,
              expected_remaining_changes_number=[])),
      api.post_check(post_process.DoesNotRun, 'get CLs repeatedly failing CQ'),
      api.post_check(post_process.DoesNotRun,
                     'abandon unpinned CLs repeatedly failing CQ'),
  )

  yield api.test(
      'set Verified-1 on unpinned CLs failed too many times',
      api.properties(
          HandleRepeatedlyFailingChangesProperties(
              open_changes=_create_gerrit_changes(4),
              max_cq_retry=1,
              expected_remaining_changes_number=[1234, 1236, 1237],
              should_count_dry_run=False,
              max_cq_retry_action=MAX_CQ_RETRY_ACTION_VERIFIED_MINUS_ONE,
          )),
      api.gerrit.set_gerrit_fetch_changes_response(
          'get CLs repeatedly failing CQ',
          _create_gerrit_changes(4),
          _create_gerrit_fetch_changes_response(
              [1234, 1235, 1236, 1237],
              [(1, False, False), (3, False, False), (0, False, False),
               (5, True, False)],
          ),
      ),
      api.post_check(
          post_process.MustRun,
          'set Verified-1 on unpinned CLs repeatedly failing CQ',
      ),
      api.post_check(
          post_process.MustRun,
          'set Verified-1 on unpinned CLs repeatedly failing CQ.add comment on CL 1235',
      ),
      api.post_check(
          post_process.MustRun,
          'set Verified-1 on unpinned CLs repeatedly failing CQ.set labels on CL 1235',
      ),
  )

  yield api.test(
      'ignore unpinned CLs failed too many times',
      api.properties(
          HandleRepeatedlyFailingChangesProperties(
              open_changes=_create_gerrit_changes(4),
              max_cq_retry=1,
              expected_remaining_changes_number=[1234, 1236, 1237],
              should_count_dry_run=False,
              max_cq_retry_action=MAX_CQ_RETRY_ACTION_IGNORE,
          )),
      api.gerrit.set_gerrit_fetch_changes_response(
          'get CLs repeatedly failing CQ',
          _create_gerrit_changes(4),
          _create_gerrit_fetch_changes_response(
              [1234, 1235, 1236, 1237],
              [(1, False, False), (3, False, False), (0, False, False),
               (5, True, False)],
          ),
      ),
      api.post_check(
          post_process.MustRun,
          'ignore unpinned CLs repeatedly failing CQ',
      ),
      api.post_check(
          post_process.MustRun,
          'ignore unpinned CLs repeatedly failing CQ.add comment on CL 1235',
      ),
      api.post_check(
          post_process.MustRun,
          'ignore unpinned CLs repeatedly failing CQ.add hashtags on CL 1235',
      ),
  )
