// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.chrome;

message ChromeProperties {

  message DepsCas { string digest = 1; }

  // Used to specify a custom DEPS file to gclient sync to as a
  // DEPS file residing in the isolate.
  DepsCas deps_cas = 1;

  // Custom version to build, if any, used in gclient sync.
  string version = 2;

  // Gclient sync timeout. Default: 5400 seconds (1.5 hours).
  int64 gclient_sync_timeout_seconds = 3;
}
