// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.chrome;

message ChromeProperties {

  // Specifies how many SCM commands can run in parallel. Corresponds to
  // the -j## argument of gclient sync. Defaults to 72 if not set.
  int64 parallel_sync_jobs = 1;

  message DepsCas {
    string digest = 1;
  }

  message DepsIsolate {
    string isolated_hash = 1;
    string isolate_server = 2;
  }

  // Used to specify a custom DEPS file to gclient sync to as a
  // DEPS file residing in the isolate.
  DepsCas deps_cas = 2;
  DepsIsolate deps_isolate = 3;

  // Custom version to build, if any, used in gclient sync.
  string version = 4;

  // By default, isolate usage is disallowed, since that is being turned down
  // 2021 Q1.  This re-enables the use, which may no longer work.
  // See crbug.com/1150957.
  bool allow_deps_isolate = 5;
}
