// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.git_cl.examples;

message UploadProperties {
  // Expected command output
  bytes expected_output = 1;
  // Whether to upload local diff instead of tip-of-branch diff
  bool use_local_diff = 2;
  // Title for the patchset
  string title = 3;
  // Commit description for the patchset.
  string description = 4;
}
