// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cq_fault_attribution;

message CqFaultAttributionApiProperties {
  // Whether to attribute failures.
  bool enable_fault_attribution = 1;
}

enum CqFailureAttribute {
  STATUS_UNSPECIFIED = 0;
  // Used when a failure in a snapshot and in a CQ run have the same failure
  // reason.
  MATCHING_FAILURE_FOUND = 1;
  // Used when a failure in a snapshot and in a CQ run have differing failure
  // reason.
  DIFFERING_FAILURE_FOUND = 2;
  // Used when a failure exists in a CQ run but the same test passed in the
  // compared snapshot.
  SUCCESS_FOUND = 3;
  // Used when a failure exists in a CQ run but the same test was either skipped
  // or does not exist in the snapshot run.
  NO_COMPARISON = 4;
}

message CqTestFailureFaultAttributionStats {
  // Fault attributed tests grouped by build targets.
  repeated FaultAttributedBuildTarget test_failure_attributions = 1;

  // The snapshots used for fault attribution.
  repeated SnapshotProperties compared_snapshots = 2;
}

message FaultAttributedBuildTarget {
  // Build target of the failure. e.g. brya
  string build_target = 1;

  // Model the failure occurred on e.g. redrix
  optional string model = 2;

  // All fault attributed tests under this build target.
  repeated FaultAttributionProperties fault_attributes = 3;
}

message FaultAttributionProperties {
  // The test name e.g. tast.cq-medium
  string test_name = 1;

  // The attempt number of this test run. Only relevant for retries.
  int32 attempt = 2;

  // The fault attribute of this test.
  CqFailureAttribute snapshot_comparison_fault_attribution = 3;

  // Whether this test has been determined to be likely flaky.
  bool likely_flaky = 4;

  // The snapshot used for determining the snapshot_comparison_fault_attribution
  // property.
  SnapshotProperties comparison_snapshot = 5;

  // Whether a different model other than the one specified in the test variant
  // was used for the comparison. This is possible if there were no snapshot
  // tests executed with the CQ test variant model, but results were present
  // for the same test on a different model (and the same build target).
  bool diff_model_used = 7;

  // The snapshots used for determining the likely_flaky property.
  repeated SnapshotProperties flakiness_criteria_snapshots = 6 [deprecated = true];
}

message SnapshotProperties {
  // The bbid of the snapshot build.
  int64 source_build_id = 1;

  // The commit sha of the snapshot build.
  string source_snapshot_sha = 2;

  // The start_time of the snapshot build in unix format.
  int64 source_started_unix_timestamp = 4;

  // The end_time of the snapshot build in unix format.
  int64 source_completed_unix_timestamp = 3;
}
