// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.auto_retry_util;

message RetryDetails {
  // The length of time since the last orchestrator completed until the retry
  // was initiated in seconds.
  uint32 retry_age_seconds = 1;

  // The original orchestrator's build bucket id.
  int64 original_orch_id = 2;

  // True if the original orchestrator was a dry-run (i.e. triggered by a CQ+1).
  bool original_orch_was_dry_run = 6;

  // The specific build failures that were retryable.
  repeated string retryable_builders = 3;

  // The specific test suite failures that were retryable.
  repeated string retryable_test_suites = 4;

  // A list of any experimental reasons why this run is being retried.
  repeated string experimental_features = 5;
}

message ExperimentalFeature {
  // The name of the experimental auto retry feature.
  string name = 1;

  // The name of the experiment that the build under consideration must have
  // had enabled to trigger this feature.
  // If unset, the feature will be enable by default.
  string experiment_flag = 2;
}

message AutoRetryUtilProperties {

  // The window in which we will consider CLs that have recently been labeled.
  // Default: 1 day (86400 seconds).
  uint32 lookback_seconds = 1;

  // The maximum number of builds to place in the description of the retry.
  // Default: 5.
  uint32 builds_comment_limit = 2;

  // The maximum number of suites to place in the description of the retry.
  // Default: 5.
  uint32 suites_comment_limit = 3;

  // If true, actually retry the CLs. By default, the retrier will just analyze
  // candidate CLs but not take action on them.
  bool enable_retries = 4;

  // The list of service accounts used by auto retry.
  // e.g. 'chromeos-auto-retry@chromeos-bot.iam.gserviceaccount.com'
  repeated string service_accounts = 5;

  // The maximum CLs we will vote on in a 2hr period.
  uint32 throttle_2hr = 6;

  // The maximum CLs we will vote on in a 24hr period.
  uint32 throttle_24hr = 7;

  reserved 8;

  // A list of experimental auto retry experimental features to enable.
  repeated ExperimentalFeature experimental_features = 9;

  // The Chromeos LUCI service account. Used to filter out builds where CV was
  // no longer active.
  string chromeos_luci_service_account = 10;
}
