// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_relevance.examples;

import "chromiumos/builder_config.proto";
import "go.chromium.org/luci/buildbucket/proto/common.proto";

message ForcedRelevanceTest {
  // The gerrit changes to use.
  repeated buildbucket.v2.GerritChange gerrit_changes = 1;

  // The builder configs to use.
  repeated chromiumos.BuilderConfig configs = 2;

  // The expected targets as a response.
  repeated string expected_forced_targets = 4;
}
