// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.build_menu.tests;

import "google/protobuf/wrappers.proto";

message StagingProperties {
  // The is_staging value to pass configure_builder.
  google.protobuf.BoolValue is_staging = 1;

  // Whether to even pass is_staging.
  bool provide_is_staging = 2;

  // Expected value for is_staging.
  bool expected_is_staging = 3;
}
