// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.build_menu.tests.test;

import "go.chromium.org/luci/resultdb/proto/v1/common.proto";

message TestProperties {

  // The expected Sources message uploaded.
  luci.resultdb.v1.Sources expected_sources = 1;

  // Manifest branch the builder is tracking.
  string manifest_branch = 2;

  // Whether to include symbols for upload_symbols.
  bool include_symbols = 3;
}

message SetupChrootProperties {
  // OptionalBool lets us specify True, False, or None.
  // This is useful for testing optional kwargs (like force_no_chroot_upgrade).
  enum OptionalBool {
    NONE = 0;
    TRUE = 1;
    FALSE = 2;
  }

  // force_no_chroot_upgrade is the value we'll pass into
  // api.build_menu.setup_chroot().
  OptionalBool force_no_chroot_upgrade = 1;
}
