// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.build_menu.tests;

import "go.chromium.org/luci/resultdb/proto/v1/invocation.proto";

message TestProperties {

  // The expected Sources message uploaded.
  luci.resultdb.v1.Sources expected_sources = 1;

  // Manifest branch the builder is tracking.
  string manifest_branch = 2;
}

message SetupChrootProperties {
  enum Update {
    NONE = 0;
    TRUE = 1;
    FALSE = 2;
  }
  Update update_sdk = 1;
  Update force_no_chroot_upgrade = 2;
}
