// Copyright 2022 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_lkgm;

message CrosLkgmProperties {
  // Feature flag for LKGM.
  bool enable_lkgm = 1;

  // Whether or not to submit the LKGM CL.
  bool full_run = 2;

  // Percent of release and public builders that must be green for the build
  // to be considered an LKGM candidate. Should be a value in [0, 100].
  int32 builder_threshold_percentage = 3;

  // The list of trybots we require LKGM updates to run and pass on before
  // landing. Since they're internal trybots, the CQ won't automatically trigger
  // them, so we have to explicitly tell it to.
  // e.g. [
  //    'chromeos-betty-pi-arc-chrome',
  //    'chromeos-eve-chrome',
  //    'chromeos-kevin-chrome',
  //    'chromeos-octopus-chrome',
  //    'chromeos-reven-chrome',
  //    'lacros-amd64-generic-chrome',
  // ]
  repeated string presubmit_trybots = 4;
}
