// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_lkgm;

message CrosLkgmProperties {
  // Feature flag for LKGM.
  bool enable_lkgm = 1;

  // Whether or not to submit the LKGM CL.
  bool full_run = 2;

  // Percent of release and public builders that must be green for the build
  // to be considered an LKGM candidate. Should be a value in [0, 100].
  int32 builder_threshold_percentage = 3;

  reserved 4;

  // Enable triggering PUpr for LKGM uprev.
  bool enable_pupr = 5;

  // The name of the PUpr builder to trigger.
  string pupr_builder_name = 6;

  // Particular list of builders that must all be green (and at least one of
  // them relevant) for LKGM uprev to trigger.
  repeated string required_green_builders = 7;
}
