// Copyright 2022 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.exonerate;

message ExonerateProperties {
  // Whether to actually perform exoneration.
  // Used to flag the feature and unittesting.
  bool enable_exoneration = 1;

  // Whether to run in dry_run mode. Exoneration logic will be
  // executed but results won't be changed.
  bool dry_run = 2;
}

message ExonerateStats {
  // Whether exoneration was run in dry_run mode.
  bool dry_run = 1;

  // Number of tests exonerated.
  int64 test_count = 2;

  // Number of test suites exonerated.
  int64 suite_count = 3;

  // Track the names of tests and suites exonerated for dashboarding.
  message GranularStats {
    // Name of the dimension.
    string name = 1;

    // Number of exonerations.
    int64 count = 2;
  }
  repeated GranularStats test_stats = 4;
  repeated GranularStats suite_stats = 5;
}
