// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.exonerate;

message ExonerateProperties {
  // Whether to actually perform exoneration.
  // Used to flag the feature and unittesting.
  bool enable_exoneration = 1;

  // Whether to run in dry_run mode. Exoneration logic will be
  // executed but results won't be changed.
  bool dry_run = 2;

  // Number of consistent failure(s) in the 10 last results to merit
  // exoneration.
  int32 consistent_failure_threshold = 3;

  // Percent of flaky results in the last 24 hour period to merit exoneration.
  // In conjunction with the flaky_verdict_threshold below.
  float flaky_percent_threshold = 4;

  // The number of flaky verdict(s) needed to check for flaky percent.
  int32 flaky_verdict_threshold = 5;

  // The number of auto exonerations should never exceed this limit.
  int32 overall_autoex_limit = 6;

  // The number of auto exonerations per target should never exceed this limit.
  int32 per_target_autoex_limit = 7;
}

message ExonerateStats {
  // Whether to run automatic exoneration in dry_run mode.
  bool dry_run = 1;

  // Number of tests exonerated.
  int64 test_count = 2;

  // Number of test suites exonerated.
  int64 suite_count = 3;

  // Track the names of tests and suites exonerated for dashboarding.
  message GranularStats {
    // Name of the dimension.
    string name = 1;

    // Number of exonerations.
    int64 count = 2;
  }
  repeated GranularStats test_stats = 4;
  repeated GranularStats suite_stats = 5;
}

// This stat will be published for each failed test.
message FailedTestStats {
  // Name of the test that failed.
  string test_id = 1;

  // Build target of the failure.
  string build_target = 2;

  // Board the test ran on.
  string board = 7;

  // Model the test ran on if specifically requested.
  string model = 8;

  // Whether this test been manually exonerated.
  bool manually_exonerated = 3;

  // Whether this test would be automatically exonerated.
  bool automatically_exonerated = 4;

  // Number of failure in the last ten executions.
  int32 consistent_failure_count = 5;

  // Number of consecutive failures at the query position.
  int32 query_position_consecutive_failure_count = 9;

  // Percent of flaky verdicts in
  // all verdicts for the last 24 hour period.
  int32 flaky_verdict_percent = 6;
}

message OverallTestStats {
  enum OverrideReason {
    UNSPECIFIED = 0;
    TOO_MANY_TESTS_EXONERATED_TOTAL = 1;
    TOO_MANY_TESTS_EXONERATED_PER_TARGET = 2;
  }

  message OverrideInfo {
    // Record why we skipped auto exoneration.
    OverrideReason override_reason = 1;

    // Record which target exceeded the limit. Empty if target limits were not
    // exceeded.
    string build_target = 2;
  }
  // All failed test stats.
  repeated FailedTestStats failed_tests = 2;

  // Record whether exoneration was skipped and why.
  OverrideInfo override_info = 3;

  // Whether auto exoneration was actually applied.
  bool dry_run = 4;

  reserved 1;
}
