// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_artifacts.examples.test;

import "chromite/api/artifacts.proto";

message TestInputProperties {
  // Expected relevance
  chromite.api.PrepareForBuildResponse.BuildRelevance relevance = 1;

  // Test_data for Build API call.
  string api_response = 3;

  // Whether or not the build is failing.
  bool failing_build = 4;

  // Whether or not to set publish_conditions to PUBLISH_ALWAYS.
  bool publish_always = 5;

  // Relevance of the kernel AFDO build.
  chromite.api.PrepareForBuildResponse.BuildRelevance kernel_afdo_relevance = 6;
}
