// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_test_proctor;

import "google/protobuf/duration.proto";

message ProctorProperties {
  reserved 1, 2;

  // Timeout for the proctor execution.
  google.protobuf.Duration timeout = 5;

  // Buildbucket Bucket for VM execution.
  string vm_bucket = 6;

  // TODO(b/201608160): Remove upon experiment completion.
  // Projects on which to enable uploading to resultdb in prod.
  repeated string resultdb_elegible_projects = 7;
}
