// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.test_platform.cros_test_platform;

import "test_platform/request.proto";
import "test_platform/steps/execution.proto";
import "test_platform/config/config.proto";

message CrosTestPlatformProperties {
  reserved 1;

  // request describes a request to the cros_test_platform recipe, as
  // described by a caller.
  //
  // Exactly one of request or requests must be set.
  .test_platform.Request request = 2;

  // requests describes a set of requests to the cros_test_platform recipe, as
  // described by a caller. The key in the dictionary is an opaque tag used to
  // group the responses for the individual requests.
  //
  // Exactly one of request or requests must be set.
  map<string, .test_platform.Request> requests = 5;

  // config describes configuration information for the cros_test_platform
  // recipe.
  //
  // This property should not be specified by callers, but instead set by
  // builder properties.
  .test_platform.config.Config config = 3;

  // response describes the response from a cros_test_platform recipe.
  // response is only set for builds with a single request.
  //
  // This property is set by the recipe execution, not by the caller.
  .test_platform.steps.ExecuteResponse response = 4;

  // responses describes the responses from a cros_test_platform recipe.
  //
  // This property is set by the recipe execution, not by the caller.
  map<string, .test_platform.steps.ExecuteResponse> responses = 6;
}
