// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.test_platform.cros_test_platform;

import "test_platform/request.proto";
import "test_platform/config/config.proto";

message CrosTestPlatformProperties {
  reserved 1;

  // request describes a request to the cros_test_platform recipe, as
  // described by a caller.
  .test_platform.Request request = 2;

  // config describes configuration information for the cros_test_platform
  // recipe.
  //
  // This property should not be specified by callers, but instead set by builder
  // properties.
  .test_platform.config.Config config = 3;
}