// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.test_platform.cros_test_postprocess;

import "test_platform/common/task.proto";

message TestResult {
  string path = 1 [deprecated=true];

  // LogData specifies the location of the logs of a test.
  .test_platform.common.TaskLogData log_data = 2;
}

message CrosTestPostprocessRequest {
  // A Google Storage path to the image archive. For example,
  // "gs://chromeos-image-archive/arkham-release/R57-9202.10.11".
  string image_archive_path = 1;

  // TestResults to process.
  repeated TestResult test_results = 2;
}