// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.test_platform.test_runner;

import "test_platform/skylab_test_runner/config.proto";
import "test_platform/skylab_test_runner/request.proto";
import "test_platform/skylab_test_runner/cft_request.proto";
import "test_platform/skylab_test_runner/result.proto";
import "test_platform/skylab_test_runner/common_config.proto";
import "google/protobuf/timestamp.proto";


message TestRunnerProperties {
  // request describes the input into the test_runner recipe; is set by the
  // caller.
  .test_platform.skylab_test_runner.Request request = 1;

  // results describes the output of a test_runner recipe; is set by the recipe
  // execution, not the caller.
  .test_platform.skylab_test_runner.Result result = 2;

  // config describes configuration information for the cros_test_platform
  // recipe; is set by the builder properties, not the caller.
  .test_platform.skylab_test_runner.Config config = 3;

  // if cft is enabled for current test_runner execution.
  // if true, will use cft_test_request instead of request.
  bool cft_is_enabled = 4;

  // cft_test_request describes the input related to cft workflow execution
  // into the test_runner recipe; is set by the caller.
  .test_platform.skylab_test_runner.CFTTestRequest cft_test_request = 5;

  // common_config describes global configuration that will be consumed
  // by both legacy and cft for the test_runner recipe;
  // The common_config is set by the builder properties, not the caller.
  .test_platform.skylab_test_runner.CommonConfig common_config = 6;
}
