# -*- coding: utf-8 -*-
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Tests for the filter_candidates function."""

import typing

from recipe_engine import post_process

from PB.go.chromium.org.luci.buildbucket.proto import common as common_pb2
from RECIPE_MODULES.chromeos.auto_retry_util.api import CHROMEOS_LUCI_SERVICE_ACCOUNT

DEPS = [
    'recipe_engine/assertions',
    'recipe_engine/buildbucket',
    'recipe_engine/properties',
    'auto_retry_util',
    'gerrit',
    'git_footers',
    'test_util',
]

PYTHON_VERSION_COMPATIBILITY = 'PY3'


def RunSteps(api):
  build = api.buildbucket.build
  build.input.properties['$recipe_engine/cq'] = {
      'runMode': api.properties.get('runMode', 'FULL_RUN')
  }
  builds = [build]
  filtered_builds = api.auto_retry_util.filter_retry_candidates(builds)
  expected_filter_reasons = api.properties.get('filter_reasons', [])
  expected_filtered_builds = [] if expected_filter_reasons else builds
  api.assertions.assertCountEqual(expected_filtered_builds, filtered_builds)
  api.assertions.assertCountEqual(
      api.auto_retry_util.per_build_stats[build.id].filter_reasons,
      expected_filter_reasons)


def GenTests(api):

  def _filtered_build_stats(**kwargs) -> typing.Dict:
    return {
        'non_latest_patch_set': kwargs.get('non_latest_patch_set', 0),
        'non_mergeable': kwargs.get('non_mergeable', 0),
        'non_multi_retry_eligible': kwargs.get('non_multi_retry_eligible', 0),
        'non_submittable': kwargs.get('non_submittable', 0),
        'opt_out': kwargs.get('opt_out', 0),
        'removed_label': kwargs.get('removed_label', 0),
        'unresolved_comments': kwargs.get('unresolved_comments', 0),
        'wip': kwargs.get('wip', 0),
        'negative_labels': kwargs.get('negative_labels', 0),
    }

  gerrit_changes = [
      common_pb2.GerritChange(change=123456,
                              host='chromium-review.googlesource.com',
                              patchset=7)
  ]

  cv_active_message = {
      'id':
          '123' * 10,
      'author': {
          '_account_id': 1234
      },
      'date':
          '2022-09-26 19:59:27.000000000',
      'message':
          'Patch Set:\n\nThis CL has failed the run. Reason: Tryjob [cq-orch](https://11}) failed',
      'tag':
          'autogenerated:cq:full-run',
  }

  cr_labels = {
      'Code-Review': {
          'optional': True,
          'all': [
              {
                  '_account_id': 1234567,
                  'value': 0
              },
              {
                  '_account_id': 2345678,
                  'value': 2
              },
          ],
          'values': {
              ' 0': 'No score',
              '+1': 'Looks good to me, but someone else must approve',
              '+2': 'Looks good to me, approved',
              '-1': 'I would prefer that you did not submit this',
              '-2': 'Do not submit'
          }
      },
  }

  eligible_value_dict = {
      c.change: {
          'change_number': c.change,
          'submittable': True,
          'messages': [cv_active_message],
          'labels': cr_labels,
      } for c in gerrit_changes
  }

  changes_mergeable_test_data = api.gerrit.set_get_change_mergeable(
      'filter candidates.filter out merge conflicts',
      gerrit_host='chromium-review.googlesource.com',
      change_num=123456,
      revision=7,
      value=True,
  )

  set_cv_account_id_test_data = api.gerrit.set_get_account_id(
      gerrit_host='chromium-review.googlesource.com',
      email=CHROMEOS_LUCI_SERVICE_ACCOUNT, value=1234,
      parent_step_name='filter candidates.filter out unmet CL requirements')

  retryable_build = api.test_util.test_orchestrator(
      build_id=11,
      cq=True,
      status='FAILURE',
      create_time=11,
      output_properties={'has_child_failures': True},
      tags={'cq_equivalent_cl_group_key': 'group_key1'},
  )

  yield api.test(
      'basic',
      retryable_build.build,
      changes_mergeable_test_data,
      set_cv_account_id_test_data,
      api.gerrit.set_gerrit_fetch_changes_response(
          'filter candidates.filter out unmet CL requirements', gerrit_changes,
          eligible_value_dict,
          step_name=f'fetch changes for {retryable_build.message.id}'),
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats()),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'filter-out-non-mergeable',
      retryable_build.build,
      api.gerrit.set_get_change_mergeable(
          'filter candidates.filter out merge conflicts',
          gerrit_host='chromium-review.googlesource.com',
          change_num=123456,
          revision=7,
          value=False,
      ),
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats(non_mergeable=1)),
      api.properties(filter_reasons=['non_mergeable']),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'defer-error-on-mergeability-check',
      retryable_build.build,
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats(non_mergeable=1)),
      api.properties(filter_reasons=['non_mergeable']),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'opt-out-via-footer',
      retryable_build.build,
      changes_mergeable_test_data,
      api.properties(filter_reasons=['opt_out']),
      api.git_footers.simulated_get_footers(
          ['None'], 'filter candidates.filter out opt-out runs'),
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats(opt_out=1)),
      api.post_process(post_process.DropExpectation),
  )

  # Basic eligibility tests.
  non_submittable_value_dict = {
      123456: {
          'change_number': 123456,
          'submittable': False,
          'messages': [cv_active_message],
          'labels': cr_labels,
      }
  }
  wip_value_dict = {
      123456: {
          'change_number': 123456,
          'submittable': True,
          'work_in_progress': True,
          'messages': [cv_active_message],
          'labels': cr_labels,
      }
  }

  non_latest_value_dict = {
      123456: {
          'change_number': 123456,
          'submittable': True,
          'current_revision': 'f000' * 10,
          'patch_set_revision': 'c111' * 10,
          'messages': [cv_active_message],
          'labels': cr_labels,
      }
  }

  unresolved_comments_value_dict = {
      123456: {
          'change_number': 123456,
          'submittable': True,
          'unresolved_comment_count': 2,
          'messages': [cv_active_message],
          'labels': cr_labels,
      }
  }

  negative_labels_value_dict = {
      123456: {
          'change_number': 123456,
          'submittable': True,
          'messages': [cv_active_message],
          'labels': {
              'Code-Review': {
                  'optional': True,
                  'all': [{
                      '_account_id': 1234567,
                      'value': -1
                  }],
                  'values': {
                      ' 0': 'No score',
                      '+1': 'Looks good to me, but someone else must approve',
                      '+2': 'Looks good to me, approved',
                      '-1': 'I would prefer that you did not submit this',
                      '-2': 'Do not submit'
                  }
              },
          },
      }
  }

  yield api.test(
      'filter-out-wip',
      retryable_build.build,
      changes_mergeable_test_data,
      set_cv_account_id_test_data,
      api.gerrit.set_gerrit_fetch_changes_response(
          'filter candidates.filter out unmet CL requirements', gerrit_changes,
          wip_value_dict,
          step_name=f'fetch changes for {retryable_build.message.id}'),
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats(wip=1)),
      api.properties(filter_reasons=['wip']),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'filter-out-non-latest',
      retryable_build.build,
      changes_mergeable_test_data,
      set_cv_account_id_test_data,
      api.gerrit.set_gerrit_fetch_changes_response(
          'filter candidates.filter out unmet CL requirements', gerrit_changes,
          non_latest_value_dict,
          step_name=f'fetch changes for {retryable_build.message.id}'),
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats(non_latest_patch_set=1)),
      api.properties(filter_reasons=['non_latest_patch_set']),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'cv-not-active',
      retryable_build.build,
      changes_mergeable_test_data,
      set_cv_account_id_test_data,
      api.gerrit.set_get_account_id(
          gerrit_host='chromium-review.googlesource.com',
          email=CHROMEOS_LUCI_SERVICE_ACCOUNT, value=4321,
          parent_step_name='filter candidates.filter out unmet CL requirements'
      ),
      api.gerrit.set_gerrit_fetch_changes_response(
          'filter candidates.filter out unmet CL requirements', gerrit_changes,
          eligible_value_dict,
          step_name=f'fetch changes for {retryable_build.message.id}'),
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats(removed_label=1)),
      api.properties(filter_reasons=['removed_label']),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'filter-out-non-submittable',
      retryable_build.build,
      changes_mergeable_test_data,
      set_cv_account_id_test_data,
      api.gerrit.set_gerrit_fetch_changes_response(
          'filter candidates.filter out unmet CL requirements', gerrit_changes,
          non_submittable_value_dict,
          step_name=f'fetch changes for {retryable_build.message.id}'),
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats(non_submittable=1)),
      api.properties(filter_reasons=['non_submittable']),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'dry-run-no-filter-out-non-submittable',
      retryable_build.build,
      changes_mergeable_test_data,
      set_cv_account_id_test_data,
      api.gerrit.set_gerrit_fetch_changes_response(
          'filter candidates.filter out unmet CL requirements', gerrit_changes,
          non_submittable_value_dict,
          step_name=f'fetch changes for {retryable_build.message.id}'),
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats()),
      api.properties(filtered_out=False, runMode='DRY_RUN'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'filter-out-unresolved-comments',
      retryable_build.build,
      changes_mergeable_test_data,
      set_cv_account_id_test_data,
      api.gerrit.set_gerrit_fetch_changes_response(
          'filter candidates.filter out unmet CL requirements', gerrit_changes,
          unresolved_comments_value_dict,
          step_name=f'fetch changes for {retryable_build.message.id}'),
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats(unresolved_comments=1)),
      api.properties(filter_reasons=['unresolved_comments']),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'filter-out-negative-code-review',
      retryable_build.build,
      changes_mergeable_test_data,
      set_cv_account_id_test_data,
      api.gerrit.set_gerrit_fetch_changes_response(
          'filter candidates.filter out unmet CL requirements', gerrit_changes,
          negative_labels_value_dict,
          step_name=f'fetch changes for {retryable_build.message.id}'),
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats(negative_labels=1)),
      api.properties(filter_reasons=['negative_labels'], runMode='DRY_RUN'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'full-run-no-filter-out-negative-code-review',
      retryable_build.build,
      changes_mergeable_test_data,
      set_cv_account_id_test_data,
      api.gerrit.set_gerrit_fetch_changes_response(
          'filter candidates.filter out unmet CL requirements', gerrit_changes,
          negative_labels_value_dict,
          step_name=f'fetch changes for {retryable_build.message.id}'),
      api.post_process(post_process.PropertyEquals, 'filtered_build_stats',
                       _filtered_build_stats()),
      api.properties(filtered_out=False),
      api.post_process(post_process.DropExpectation),
  )

  auto_retried_build = api.test_util.test_orchestrator(
      build_id=11,
      cq=True,
      tags={
          'cq_triggerer':
              'chromeos-auto-retry@chromeos-bot.iam.gserviceaccount.com',
          'cq_equivalent_cl_group_key':
              'group_key1',
      },
      status='FAILURE',
      create_time=11,
      output_properties={'has_child_failures': True},
  )

  yield api.test(
      'filter-out-multi-retry-runs',
      auto_retried_build.build,
      api.properties(filter_reasons=['non_multi_retry_eligible']),
      changes_mergeable_test_data,
      api.post_process(
          post_process.StepTextEquals,
          'filter candidates.filter multi-retry eligible runs',
          'filtered out 1 run(s)',
      ),
      api.buildbucket.simulated_search_results([
          auto_retried_build.message
      ], step_name='filter candidates.filter multi-retry eligible runs.find previous auto-retries for 11.buildbucket.search'
                                              ),
      api.post_process(post_process.DropExpectation),
  )
