# -*- coding: utf-8 -*-
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Tests of multi-retry filtering."""

from recipe_engine import post_process

from PB.go.chromium.org.luci.buildbucket.proto import common as common_pb2
from RECIPE_MODULES.chromeos.auto_retry_util.api import CHROMEOS_LUCI_SERVICE_ACCOUNT

DEPS = [
    'recipe_engine/assertions',
    'recipe_engine/buildbucket',
    'recipe_engine/properties',
    'recipe_engine/time',
    'auto_retry_util',
    'gerrit',
    'test_util',
]



def RunSteps(api):
  builds = [api.buildbucket.build]
  api.auto_retry_util.experimental_retries[builds[0].id].update(
      api.properties.get('experimental_retries', []))
  filtered_builds = api.auto_retry_util.filter_retry_candidates(builds)
  expected_filtered_builds = [] if api.properties['filtered_out'] else builds
  api.assertions.assertCountEqual(expected_filtered_builds, filtered_builds)


def GenTests(api):

  gerrit_changes = [
      common_pb2.GerritChange(change=123456,
                              host='chromium-review.googlesource.com',
                              patchset=7)
  ]

  cv_active_message = {
      'id':
          '123' * 10,
      'author': {
          '_account_id': 1234
      },
      'date':
          '2022-09-26 19:59:27.000000000',
      'message':
          'Patch Set:\n\nThis CL has failed the run. Reason: Tryjob [cq-orch](https://11}) failed',
      'tag':
          'autogenerated:cq:full-run',
  }

  cr_labels = {
      'Code-Review': {
          'optional': True,
          'all': [
              {
                  '_account_id': 1234567,
                  'value': 0
              },
              {
                  '_account_id': 2345678,
                  'value': 2
              },
          ],
          'values': {
              ' 0': 'No score',
              '+1': 'Looks good to me, but someone else must approve',
              '+2': 'Looks good to me, approved',
              '-1': 'I would prefer that you did not submit this',
              '-2': 'Do not submit'
          }
      },
  }

  eligible_value_dict = {
      c.change: {
          'change_number': c.change,
          'submittable': True,
          'messages': [cv_active_message],
          'labels': cr_labels,
      } for c in gerrit_changes
  }

  changes_mergeable_test_data = api.gerrit.set_get_change_mergeable(
      'filter candidates.filter out merge conflicts',
      gerrit_host='chromium-review.googlesource.com',
      change_num=123456,
      revision=7,
      value=True,
  )

  set_cv_account_id_test_data = api.gerrit.set_get_account_id(
      gerrit_host='chromium-review.googlesource.com',
      email=CHROMEOS_LUCI_SERVICE_ACCOUNT, value=1234,
      parent_step_name='filter candidates.filter out unmet CL requirements')

  def candidate_build(
      cq_triggerer:
      str = 'chromeos-auto-retry@chromeos-bot.iam.gserviceaccount.com',
      include_group_key: bool = True,
  ):
    tags = {
        'cq_triggerer': cq_triggerer,
    }
    if include_group_key:
      tags['cq_equivalent_cl_group_key'] = 'group_key1'
    return api.test_util.test_orchestrator(
        build_id=11,
        cq=True,
        status='FAILURE',
        create_time=11,
        end_time=13,
        input_properties={'$recipe_engine/cv': {
            'runMode': 'FULL_RUN'
        }},
        output_properties={'has_child_failures': True},
        tags=tags,
    )

  # The candidate is an auto-retry. Set max_retries to 2, so this candidate is
  # eligible for a retry. The build ended at 13s and it is now 20s, so the
  # constant_backoff_duration (5s) has passed.
  yield api.test(
      'allow-two-retries',
      candidate_build().build,
      api.time.seed(20),
      api.time.step(0),
      changes_mergeable_test_data,
      set_cv_account_id_test_data,
      api.gerrit.set_gerrit_fetch_changes_response(
          'filter candidates.filter out unmet CL requirements', gerrit_changes,
          eligible_value_dict,
          step_name=f'fetch changes for {candidate_build().message.id}'),
      api.properties(
          filtered_out=False,
          **{
              '$chromeos/auto_retry_util': {
                  'multi_retry_config': {
                      'max_retries': 2,
                      'constant_backoff_duration': '5s'
                  }
              }
          },
      ),
      api.buildbucket.simulated_search_results([
          candidate_build().message
      ], step_name='filter candidates.filter multi-retry eligible runs.find previous auto-retries for 11.buildbucket.search'
                                              ),
      api.post_process(
          post_process.LogContains,
          'filter candidates.filter multi-retry eligible runs.find previous auto-retries for 11.buildbucket.search',
          'request',
          [
            '"predicate": {\n          "builder": {\n            "bucket": "cq",\n            "builder": "cq-orchestrator",\n            "project": "chromeos"\n          },'\
            '\n          "tags": [\n            {\n              "key": "cq_equivalent_cl_group_key",\n              "value": "group_key1"\n            },\n            {\n              "key": "cq_triggerer",\n              "value": "chromeos-auto-retry@chromeos-bot.iam.gserviceaccount.com"\n            }\n          ]\n        }'
          ]),
      api.post_process(post_process.DropExpectation),
  )

  # The build ended at 13s and it is now 15s, so the constant_backoff_duration
  # (5s) has not passed.
  yield api.test(
      'within-backoff-window-no-retry',
      candidate_build().build,
      api.time.seed(15),
      api.time.step(0),
      changes_mergeable_test_data,
      api.properties(
          filtered_out=True,
          **{
              '$chromeos/auto_retry_util': {
                  'multi_retry_config': {
                      'max_retries': 2,
                      'constant_backoff_duration': '5s'
                  }
              }
          },
      ),
      api.buildbucket.simulated_search_results([
          candidate_build().message
      ], step_name='filter candidates.filter multi-retry eligible runs.find previous auto-retries for 11.buildbucket.search'
                                              ),
      api.post_process(post_process.DropExpectation),
  )

  # Candidate doesn't have a cq_equivalent_cl_group_key, so it isn't eligble for
  # a retry.
  yield api.test(
      'candidate-without-group-key',
      candidate_build(include_group_key=False).build,
      changes_mergeable_test_data,
      api.properties(
          filtered_out=True,
      ),
      api.post_process(post_process.DropExpectation),
  )

  # If there are no previous auto-retries the constant_backoff_duration window
  # shouldn't apply.
  yield api.test(
      'human-triggered-candidate',
      candidate_build(cq_triggerer='user1@google.com').build,
      api.time.seed(15),
      api.time.step(0),
      changes_mergeable_test_data,
      set_cv_account_id_test_data,
      api.gerrit.set_gerrit_fetch_changes_response(
          'filter candidates.filter out unmet CL requirements', gerrit_changes,
          eligible_value_dict,
          step_name=f'fetch changes for {candidate_build().message.id}'),
      api.properties(
          filtered_out=False,
          **{
              '$chromeos/auto_retry_util': {
                  'multi_retry_config': {
                      'max_retries': 2,
                      'constant_backoff_duration': '5s'
                  }
              }
          },
      ),
      api.buildbucket.simulated_search_results(
          [],
          step_name='filter candidates.filter multi-retry eligible runs.find previous auto-retries for 11.buildbucket.search'
      ),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'dont-retry-attribution-experiment',
      candidate_build().build,
      api.time.seed(20),
      api.time.step(0),
      changes_mergeable_test_data,
      api.properties(
          filtered_out=True,
          experimental_retries=['retry-attributed-failures'],
          **{
              '$chromeos/auto_retry_util': {
                  'multi_retry_config': {
                      'max_retries': 2,
                      'constant_backoff_duration': '5s'
                  }
              }
          },
      ),
      api.buildbucket.simulated_search_results([
          candidate_build().message
      ], step_name='filter candidates.filter multi-retry eligible runs.find previous auto-retries for 11.buildbucket.search'
                                              ),
      api.post_process(
          post_process.LogContains,
          'filter candidates.filter multi-retry eligible runs.find previous auto-retries for 11.buildbucket.search',
          'request',
          [
            '"predicate": {\n          "builder": {\n            "bucket": "cq",\n            "builder": "cq-orchestrator",\n            "project": "chromeos"\n          },'\
            '\n          "tags": [\n            {\n              "key": "cq_equivalent_cl_group_key",\n              "value": "group_key1"\n            },\n            {\n              "key": "cq_triggerer",\n              "value": "chromeos-auto-retry@chromeos-bot.iam.gserviceaccount.com"\n            }\n          ]\n        }'
          ]),
      api.post_process(post_process.DropExpectation),
  )
