logsBucket: 'gs://${PROJECT_ID}-logs'
steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        set -ev
        git init
        git remote add origin ${_URL}
        git fetch --depth ${_FETCH_DEPTH} ${_URL} ${_REF}
        git checkout FETCH_HEAD
substitutions:
  _URL: https://chromium.googlesource.com/chromiumos/third_party/kernel
  _REF: beef0fabada
  _FETCH_DEPTH: '2'
timeout: '1200s'