logsBucket: 'gs://${PROJECT_ID}-logs'
steps:
- name: 'gcr.io/cloud-builders/git'
  id: 'init'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        set -ev
        git init
        git remote add origin ${_URL}
        for i in $(seq 18); do
          git fetch --depth ${_FETCH_DEPTH} ${_URL} ${_REF} && break
          sleep 10
        done
        git checkout FETCH_HEAD
substitutions:
  _URL: https://chromium.googlesource.com/chromiumos/third_party/kernel
  _REF: beef0fabada
  _FETCH_DEPTH: '2'
timeout: '1800s'
