# -*- coding: utf-8 -*-
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""APIs for PUpr."""

from PB.recipes.chromeos.generator import (
    RETRY_LATEST_OR_LATEST_PINNED,
    RETRY_LATEST_PINNED,
)

from recipe_engine import recipe_api

import re

DRY_RUN_TAG = "autogenerated:cq:dry-run"
FULL_RUN_TAG = "autogenerated:cq:full-run"

FAILED_RE = re.compile(r"^Patch Set \d+:\s*Failed builds")
RUNNING_RE = re.compile(r"^Patch Set \d+:\s*C[QV] is trying the patch")
# Won't be used in practice (because submitted changes won't be in the open change set),
# but included for symmetry's sake.
PASSED_RE = re.compile(
    r"^Patch Set \d+:\s*Change has been successfully rebased and submitted")

FAILED_DRY_RUN_RE = re.compile(r"^Patch Set \d+:\s*Dry run: Failed builds")
RUNNING_DRY_RUN_RE = re.compile(
    r"^Patch Set \d+:\s*Dry run: C[QV] is trying the patch")
PASSED_DRY_RUN_RE = re.compile(
    r"^Patch Set \d+:\s*Dry run: This CL passed the C[QV] dry run")


def get_patterns(dry_run):
  """
  Get appropriate tag/regexes for the CQ mode (CQ+1 or CQ+2).
  """
  if dry_run:
    return (DRY_RUN_TAG, FAILED_DRY_RUN_RE, RUNNING_DRY_RUN_RE,
            PASSED_DRY_RUN_RE)
  return (FULL_RUN_TAG, FAILED_RE, RUNNING_RE, PASSED_RE)


def is_failed_cl(c, dry_run=False):
  """
  Determine if the CL in question has previously failed for a full/dry run.
  Note that if dry_run is False (i.e. we're looking for CQ+2 failures)
  and the most recent failure is a CQ+1 failure, this function will return False.
  Similarly, if dry_run is True and the most recent failure is a CQ+2
  failure, this function will return false.
  """
  for m in sorted(c.messages, key=lambda m: m["date"], reverse=True):
    if "tag" not in m or m["tag"] not in [DRY_RUN_TAG, FULL_RUN_TAG]:
      continue  # pragma: nocover
    # If there's a CQ+2 failure, return True if dry_run = False and False o.w.
    if FAILED_RE.match(m["message"]):
      return not dry_run
    # If there's a CQ+1 failure, return True if dry_run = True and False o.w.
    elif FAILED_DRY_RUN_RE.match(m["message"]):
      return dry_run
  return False


def is_running_cl(c, dry_run=False):
  """
  Determine if the CL in question is currently running.
  Checks either for CQ+1 or CQ+2 depending on the value of dry_run.
  """
  run_tag, failed_re, running_re, passed_re = get_patterns(dry_run)

  for m in sorted(c.messages, key=lambda m: m["date"], reverse=True):
    if "tag" not in m or m["tag"] != run_tag:
      continue  # pragma: nocover
    # If the CQ run has concluded (pass or fail), not running.
    if failed_re.match(m["message"]) or passed_re.match(m["message"]):
      return False
    # If we encounter a running message first, running.
    elif running_re.match(m["message"]):
      return True
  return False


def needs_retry(c, dry_run=False):
  """
    Determine if the CL in question needs a retry
    (i.e. it is not running or passed).
    Assumes that is_failed(c) = True or is_failed(c, dry_run=True) = True,
    and that the dry_run parameter has the same value as whichever is_failed
    call returned true.
  """
  run_tag, failed_re, running_re, passed_re = get_patterns(dry_run)

  for m in sorted(c.messages, key=lambda m: m["date"], reverse=True):
    if "tag" not in m or m["tag"] != run_tag:
      continue  # pragma: nocover
    # If we hit a try message before a failed message, the change
    # hasn't failed yet for the most recent run.
    if running_re.match(m["message"]) or passed_re.match(m["message"]):
      return False
    if failed_re.match(m["message"]):
      break
  return True


def sorted_cls(cls):
  """Return cls sorted by create date, descending."""
  return sorted(cls, key=lambda cl: cl.created, reverse=True)


class PuprApi(recipe_api.RecipeApi):
  """A module for PUpr steps."""
  HASHTAG_FREEZE_RETRIES = "pupr-freeze-retries"
  HASHTAG_PINNED_RETRY = "pupr-retry-pinned"

  def retries_frozen(self, changes):
    """Examine open CLs for the HASHTAG_FREEZE_RETRIES hashtag.

    Args:
      changes (List[gerrit.PatchSet]): List of CLs.

    Returns:
      bool: Whether or not a HASHTAG_FREEZE_RETRIES hashtag is present.
    """
    return any([self.HASHTAG_FREEZE_RETRIES in c.hashtags for c in changes])

  def identify_retry(self, retry_policy, open_cls):
    """Identify the CL to be retried based on retry_policy.

    Args:
      retry_policy (RetryClPolicy): The retry policy to follow. Can be NO_RETRY,
        LATEST_OR_LATEST_PINNED, or LATEST_PINNED.
      open_cls (List[gerrit.PatchSet]): List of CLs.

    Returns:
      (PatchSet, int, str): (The CL to be retried (or None if no retry),
                             CQ label to be applied,
                             The description of the action)
    """
    if retry_policy not in [RETRY_LATEST_OR_LATEST_PINNED, RETRY_LATEST_PINNED]:
      return (None, 0, 'Not set to retry.')

    # Pinned CLs (i.e. CLs with the HASHTAG_PINNED_RETRY) take precendence.
    # Here, we looked for the most recent pinned CL.
    retry_cl = None
    is_dry_run = False
    for cl in open_cls:
      if self.HASHTAG_PINNED_RETRY in cl.hashtags:
        # (Most recent) pinned CL identified. If the CL has not previously
        # failed, no retry is necessary and we can return.

        # Identify most recent failure type (if any).
        if is_failed_cl(cl):
          retry_cl = cl
        elif is_failed_cl(cl, dry_run=True):
          retry_cl = cl
          is_dry_run = True
        else:  # Pinned CL has not failed, do not attempt any retry.
          return (None, 0,
                  'Pinned retry CL {} has not failed.'.format(cl.display_url))
        break

    # Check to see if there is a CL (previously failed or not) currently running with CQ+2.
    # If a CL is in the process of running, no retry will occur.
    running_cls = filter(is_running_cl, open_cls)
    if running_cls:
      return (None, 0, 'There are CQ+2 run(s) ongoing: {}'.format(' '.join(
          [cl.display_url for cl in running_cls])))

    # If we haven't identified a pinned CL and the retry policy is not RETRY_PINNED_ONLY
    # (i.e it is RETRY_LATEST_OR_LATEST_PINNED) find most recent failed CL.
    # CQ+2 retries take priority over CQ+1 retries, so look for a failed CQ+2 run first.
    # If there are no CLs whose most recent failure is CQ+2, look for failed CQ+1 runs.
    if retry_policy != RETRY_LATEST_PINNED and not retry_cl:
      # Look for CLs with failed full runs first.
      failed_cls = list(filter(is_failed_cl, open_cls))
      if failed_cls:
        retry_cl = sorted_cls(failed_cls)[0]
      else:  # Look for failed dry runs.
        failed_cls = [c for c in open_cls if is_failed_cl(c, dry_run=True)]
        if failed_cls:
          retry_cl = sorted_cls(failed_cls)[0]
          is_dry_run = True

    # Only want to retry a CL that has not passed/is currently running.
    if retry_cl and needs_retry(retry_cl, dry_run=is_dry_run):
      return (retry_cl, 1 if is_dry_run else 2,
              'Found cl: {}'.format(retry_cl.display_url))
    return (None, 0, 'No open CL was found to retry.')
