// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.signing;

message BcidEnforcement {
  // Defines whether failures to generate signed provenance should be fatal.
  // Defaults to false.
  bool signed_provenance_generation_fatal = 1;
  // Defines whether a failure to verify the provenance for unsigned artifacts
  // should be fatal. Setting this to true will ensure that unsigned artifacts
  // which cannot have their provenance verified will not be signed.
  // Defaults to false.
  bool unsigned_provenance_verification_fatal = 2;

  // The name of the BCID Policy to provide to provide to Software Verifier.
  string bcid_policy = 3;

  // Whether a failure to verify the provenance of paygen inputs should be
  // fatal. Defaults to false.
  bool paygen_input_provenance_verification_fatal = 4;
}

message SigningProperties {
  // Timeout for waiting for signing to fully complete (in seconds) for all
  // signing operations.
  int32 timeout = 1;

  // How long to sleep between polls (in seconds).
  int32 sleep_duration = 2;

  // Whether to throw an error on ImageAlreadyExistsError errors.
  // Primarily used when we want to reinitiate signing (because of failed
  // artifacts) without failing on the originally-successful artifacts.
  bool ignore_already_exists_errors = 3;

  // Whether to use the local signing flow instead of sending out instructions
  // files to the legacy signing fleet. Defaults to false.
  bool local_signing = 4;

  // GS upload bucket, not including gs:// prefix. E.g. 'chromeos-releases'.
  string gs_upload_bucket = 5;

  // Whether to override configured keyset configured in config-internal with
  // dev keys. Useful for testing with CQ.
  bool use_dev_keys = 6;

  // Sets BCID enforcement properties used when signing artifacts.
  BcidEnforcement bcid_enforcement = 7;

  // Timeout for waiting for BAPI signing to complete (in seconds).
  int32 bapi_timeout_sec = 8;

  // Number of retries for BAPI signing operations when failures or timeouts
  // occur.
  optional int32 bapi_retries = 9;
}
