// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_history;

message CrosHistoryProperties {
  // Number of seconds to look back for passed builds.
  int64 lookback_seconds = 1;

  // Whether to disable using cq_equivalent_cl_group_key.
  bool disable_group_key = 2;
}

// Used to unittest is_build_broken().
message IsBuildBrokenProperties { bool expected_result = 1; }

// Used to unittest HoursSinceBreakageProperties().
message HoursSinceBreakageProperties { int32 expected_result = 1; }
