// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_artifacts;

message CrosArtifactsProperties {
  // The maximum number of Build API calls to make when bundling artifacts.
  int32 max_concurrent_bundling_requests = 1;

  // Path to upload artifacts. If not set, defaults to whatever is set in code,
  // i.e. {builder}/{version}-{bid}.
  string gs_upload_path = 2;

  // If True, skip copying artifacts to canonical location.
  bool skip_publish = 3;
}
