// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.analysis_service;

message AnalysisServiceProperties {
  // The Cloud Pub/Sub project to publish events to.
  string pubsub_project_id = 1;

  // The Cloud Pub/Sub topic to publish events to.
  string pubsub_topic_id = 2;

  // Should the analysis service be disabled and not publish.
  bool disable_publish = 3;
}
