// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.orch_menu;

message OrchMenuProperties {
  // Specifies which refs in the manifest repository should point to the
  // snapshot ref used by the orchestrator, and when.
  message UpdateManifestRefs {
    // The start ref is updated before child builds are launched.
    // An example start ref is 'postsubmit', which should update
    // right when the orchestrator launches.
    string start = 1;

    // The "build" ref is updated only if max_build_failure_ratio is met.
    string build = 2;

    // The maximum fraction of builds that can fail when considering if we
    // should update the ref. Default (0.0) means all must succeed.
    float max_build_failure_ratio = 4;

    // The "test" ref is updated only if ALL tests succeed.
    string test = 3;
  }
  UpdateManifestRefs update_manifest_refs = 1;

  // Time delay between each child build.
  float stagger_children_seconds = 2;

  // Specifies whether to enable cros_history based resource saving.
  bool enable_history = 3;

  // Specifies whether to enable exiting redundant builds.
  bool assert_singleton = 4;

  // Feature flag: Whether to defer COLLECT_AFTER_HW_TEST builders to after HW
  // testing.
  // bool collect_after_hw_test = 5;
  reserved 5;

  // Should we collect failures after test proctor is ran or continue without
  // referencing or setting status on test results.
  bool run_tests_async = 6;

  // GS path to upload buildspecs to. Only used for release builders.
  // Defaults to 'gs://chromeos-manifest-versions/release/'.
  string buildspec_gs_path = 7;

  // Whether to bump the version for a release builder. Will be ignored if
  // the builder is a staging builder.
  bool bump_version = 8;

  // Branch of manifest-versions to upload to. Only used for release builders.
  // Defaults to 'release'.
  string manifest_versions_branch = 9;

  // If non-empty, only launch child builders with child_spec.name listed here.
  repeated string filter_child_builds = 10;
}
