// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_prebuilts.tests;

import "chromiumos/common.proto";
import "go.chromium.org/luci/buildbucket/proto/common.proto";

// The files for a (snapshot, build_target, profile), mapping filename to
// contents.
message ProfileTestMap { map<string, chromiumos.PackageIndexInfo> files = 1; }
// The profiles for a (snapshot, build_target).
message TargetTestMap { map<string, ProfileTestMap> profiles = 1; }

// The entries for a snapshot.
message SnapshotTestMap { map<string, TargetTestMap> targets = 1; }

message TestDataMap { map<string, SnapshotTestMap> snapshots = 1; }

message GetPkgIdxInfoProperties {
  // Snapshots
  repeated buildbucket.v2.GitilesCommit gitiles_commits = 1;

  // The build_target for this builder.
  chromiumos.BuildTarget build_target = 2;

  // The name of the profile to use.
  chromiumos.Profile profile = 3;

  // The gs_bucket to use.
  string gs_bucket = 4;

  // Test data (contents of the metadata in storage.)
  TestDataMap test_data_dict = 5;

  // Expected get_package_index_info() return.
  repeated chromiumos.PackageIndexInfo expected_package_index_info = 6;
}
