// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.paygen_orchestration.examples;

import "chromite/api/payload.proto";

message TestPaygenProperties {
  // Builder name to use.
  string builder_name = 1;

  // Expected result length.
  int32 expected_length = 2;

  // Delta type requested.
  string delta_type = 3;

  // Builder name to expect in the test config. Potentially different than
  // build_name because of variant boards.
  string expected_test_build_target = 4;

  // Build target name, not expected to change to accomomdate the deployed
  // 'board' name, as opposed to 'expected_test_build_target'.
  string expected_build_target_name = 5;

  // The expected quota scheduler account paygen should be using.
  string expected_quota_scheduler_account = 6;

  // The expected quota scheduler label pool paygen should be using.
  string expected_quota_scheduler_label_pool = 7;
}

message GetRequestTestInputProperties {
  // The json payload config to pass to GetRequest.
  string payload_cfg = 1;

  // What can we expect to unpack?
  enum GetRequestType {
    MISMATCHED = 0;
    SIGNED = 1;
    UNSIGNED = 2;
    FULL = 3;
    DLC = 4;
  }

  GetRequestType request_type = 2;

  // The following are the possible input images (see GenerationRequest).
  repeated chromite.api.SignedImage signed_srcs = 3;
  repeated chromite.api.SignedImage signed_tgts = 4;

  repeated chromite.api.UnsignedImage unsigned_srcs = 5;
  repeated chromite.api.UnsignedImage unsigned_tgts = 6;

  repeated chromite.api.DLCImage dlc_srcs = 9;
  repeated chromite.api.DLCImage dlc_tgts = 10;

  bool full_update = 7;

  // The expected results of calling gen_requests.
  repeated chromite.api.GenerationRequest expected_reqs = 8;
}
