# -*- coding: utf-8 -*-
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

DEPS = [
    'recipe_engine/assertions',
    'gerrit',
    'pupr',
]

import collections

from PB.recipes.chromeos.generator import (
    RetryClPolicy,
    NO_RETRY,
    RETRY_LATEST_OR_LATEST_PINNED,
    RETRY_LATEST_PINNED,
)


def patch_set_from_dict(api, changes):
  return [
      api.gerrit.PatchSet(
          collections.defaultdict(str, dict(revision_info={}, **change)))
      for change in changes
  ]


def RunSteps(api):
  api.assertions.assertEqual(api.pupr.identify_retry(NO_RETRY, [])[0], None)

  changes = [{
      "info": {
          "_number":
              1,
          "created":
              "2020-10-22 18:54:00.000000000",
          "hashtags": [],
          "messages": [{
              "message": "Patch Set 1:\n\nFailed builds: ...",
              "date": "2020-10-23T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }]
      }
  }, {
      "info": {
          "_number":
              2,
          "created":
              "2020-10-23 18:54:00.000000000",
          "hashtags": [],
          "messages": [{
              "message": "Patch Set 1:\n\nFailed builds: ...",
              "date": "2020-10-24T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }],
      }
  }, {
      "info": {
          "_number": 3,
          "created": "2020-10-24 18:54:00.000000000",
          "hashtags": [],
          "messages": [],
      }
  }, {
      "info": {
          "_number":
              4,
          "created":
              "2020-11-22 18:54:00.000000000",
          "hashtags": [],
          "messages": [{
              "message": "Patch Set 1:\n\nDry run: CQ is trying the patch...",
              "date": "2020-11-22T18:54:00Z",
              "tag": "autogenerated:cq:dry-run"
          }, {
              "message": "Patch Set 1:\n\nDry run: Failed builds: ...",
              "date": "2020-11-23T18:54:00Z",
              "tag": "autogenerated:cq:dry-run"
          }],
      }
  }, {
      "info": {
          "_number":
              5,
          "created":
              "2020-11-25 18:54:00.000000000",
          "hashtags": [],
          "messages": [{
              "message": "Patch Set 1:\n\nDry run: CQ is trying the patch...",
              "date": "2020-11-25T18:54:00Z",
              "tag": "autogenerated:cq:dry-run"
          }],
      }
  }]
  open_cls = patch_set_from_dict(api, changes)
  # Latest CL. Failed CQ+2 CL should be chosen over failed/running CQ+1 CLs.
  cl, cq_label = api.pupr.identify_retry(RETRY_LATEST_OR_LATEST_PINNED,
                                         open_cls)
  api.assertions.assertEqual(cl.change_id, 2)
  api.assertions.assertEqual(cq_label, 2)
  # No pinned CLs, so no retry CL.
  api.assertions.assertEqual(
      api.pupr.identify_retry(RETRY_LATEST_PINNED, open_cls), (None, 0))

  changes = [{
      "info": {
          "_number":
              1,
          "created":
              "2020-10-22 18:54:00.000000000",
          "hashtags": [api.pupr.HASHTAG_PINNED_RETRY],
          "messages": [{
              "message": "Patch Set 1:\n\nFailed builds: ...",
              "date": "2020-10-24T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }, {
              "message": "Patch Set 1:\n\nCQ is trying the patch...",
              "date": "2020-10-23T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }, {
              "message": "Quote: Patch Set 1:\n\nCQ is trying the patch...",
              "date": "2020-10-25T18:54:00Z",
          }],
      }
  }, {
      "info": {
          "_number":
              2,
          "created":
              "2020-10-23 18:54:00.000000000",
          "hashtags": [],
          "messages": [{
              "message": "Patch Set 1:\n\nFailed builds: ...",
              "date": "2020-10-23T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }],
      }
  }]
  open_cls = patch_set_from_dict(api, changes)
  # Pinned CL should be selected despite the presence of a more recent failed CL.
  cl, cq_label = api.pupr.identify_retry(RETRY_LATEST_OR_LATEST_PINNED,
                                         open_cls)
  api.assertions.assertEqual(cl.change_id, 1)
  api.assertions.assertEqual(cq_label, 2)

  changes = [{
      "info": {
          "_number":
              1,
          "created":
              "2020-10-22 18:54:00.000000000",
          "hashtags": [],
          "messages": [{
              "message": "Patch Set 1:\n\nCQ is trying the patch...",
              "date": "2020-10-22T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }, {
              "message": "Patch Set 1:\n\nFailed builds: ...",
              "date": "2020-10-23T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }, {
              "message": "Patch Set 2:\n\nCQ is trying the patch...",
              "date": "2020-10-24T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }],
      }
  }]
  open_cls = patch_set_from_dict(api, changes)
  # Most recent failed CL is currently running, no retry.
  api.assertions.assertEqual(
      api.pupr.identify_retry(RETRY_LATEST_OR_LATEST_PINNED, open_cls),
      (None, 0))

  changes = [{
      "info": {
          "_number":
              1,
          "created":
              "2020-10-22 18:54:00.000000000",
          "hashtags": [api.pupr.HASHTAG_PINNED_RETRY],
          "messages": [{
              "message": "Patch Set 2:\n\nCQ is trying the patch...",
              "date": "2020-10-24T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }],
      }
  }]
  open_cls = patch_set_from_dict(api, changes)

  # Pinned CL never failed, no retry.
  api.assertions.assertEqual(
      api.pupr.identify_retry(RETRY_LATEST_OR_LATEST_PINNED, open_cls),
      (None, 0))

  changes = [{
      "info": {
          "_number":
              1,
          "created":
              "2020-10-22 18:54:00.000000000",
          "hashtags": [],
          "messages": [{
              "message": "Patch Set 1:\n\nDry run: CQ is trying the patch...",
              "date": "2020-10-22T18:54:00Z",
              "tag": "autogenerated:cq:dry-run"
          }, {
              "message": "Patch Set 1:\n\nDry run: Failed builds: ...",
              "date": "2020-10-23T18:54:00Z",
              "tag": "autogenerated:cq:dry-run"
          }, {
              "message":
                  "Quote: Patch Set 1:\n\nDry run: CQ is trying the patch...",
              "date":
                  "2020-10-22T18:54:00Z",
          }],
      }
  }]
  open_cls = patch_set_from_dict(api, changes)

  # Latest Dry Run CL.
  cl, cq_label = api.pupr.identify_retry(RETRY_LATEST_OR_LATEST_PINNED,
                                         open_cls)
  api.assertions.assertEqual(cl.change_id, 1)
  api.assertions.assertEqual(cq_label, 1)

  changes = [{
      "info": {
          "_number":
              1,
          "created":
              "2020-10-22 18:54:00.000000000",
          "hashtags": [],
          "messages": [{
              "message": "Patch Set 1:\n\nDry run: CQ is trying the patch...",
              "date": "2020-10-22T18:54:00Z",
              "tag": "autogenerated:cq:dry-run"
          }, {
              "message": "Patch Set 1:\n\nDry run: Failed builds: ...",
              "date": "2020-10-23T18:54:00Z",
              "tag": "autogenerated:cq:dry-run"
          }, {
              "message":
                  "Patch Set 1:\n\nDry run: This CL passed the CQ dry run",
              "date":
                  "2020-10-24T18:54:00Z",
              "tag":
                  "autogenerated:cq:dry-run"
          }],
      }
  }]
  open_cls = patch_set_from_dict(api, changes)
  # Latest Dry Run CL has passed the dry run, do not retry.
  api.assertions.assertEqual(
      api.pupr.identify_retry(RETRY_LATEST_OR_LATEST_PINNED, open_cls),
      (None, 0))

  changes = [{
      "info": {
          "_number":
              1,
          "created":
              "2020-11-22 18:54:00.000000000",
          "hashtags": [],
          "messages": [{
              "message": "Patch Set 1:\n\nFailed builds: ...",
              "date": "2020-10-23T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }]
      }
  }, {
      "info": {
          "_number":
              2,
          "created":
              "2020-10-22 18:54:00.000000000",
          "hashtags": [api.pupr.HASHTAG_PINNED_RETRY],
          "messages": [{
              "message": "Patch Set 1:\n\nFailed builds: ...",
              "date": "2020-10-22T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }, {
              "message": "Patch Set 2:\n\nDry run: CQ is trying the patch...",
              "date": "2020-10-23T18:54:00Z",
              "tag": "autogenerated:cq:dry-run"
          }, {
              "message": "Patch Set 2:\n\nDry run: Failed builds: ...",
              "date": "2020-10-24T18:54:00Z",
              "tag": "autogenerated:cq:dry-run"
          }],
      }
  }]
  open_cls = patch_set_from_dict(api, changes)
  # Pinned Dry Run CL should be chosen over failed full run CL..
  cl, cq_label = api.pupr.identify_retry(RETRY_LATEST_OR_LATEST_PINNED,
                                         open_cls)
  api.assertions.assertEqual(cl.change_id, 2)
  # Additionally, check that the full/dry run status of the most recent failure
  # is properly detected.
  api.assertions.assertEqual(cq_label, 1)


  changes = [{
      "info": {
          "_number":
              1,
          "created":
              "2020-11-22 18:54:00.000000000",
          "hashtags": [],
          "messages": [{
              "message": "Patch Set 1:\n\nFailed builds: ...",
              "date": "2020-11-22T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }]
      }
  }, {
      "info": {
          "_number":
              1,
          "created":
              "2020-11-25 18:54:00.000000000",
          "hashtags": [],
          "messages": [{
              "message": "Patch Set 2:\n\nCQ is trying the patch...",
              "date": "2020-11-25T18:54:00Z",
              "tag": "autogenerated:cq:full-run"
          }],
      }
  }]

  open_cls = patch_set_from_dict(api, changes)
  # Even though there's a failed CQ+2 CL, there's a more recent CL that is
  # /currently/ running with CQ+2, so no retry should take place.
  api.assertions.assertEqual(
      api.pupr.identify_retry(RETRY_LATEST_OR_LATEST_PINNED, open_cls),
      (None, 0))


def GenTests(api):
  yield api.test('basic')
