// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.paygen_orchestration.tests;

import "recipes/chromeos/paygen.proto";

message BatchPaygenRequestDictsBatchingProperties {
  // Max batch size value.
  int32 max_batch_size = 1;
  // Tuple of serialized paygen requests for batching.
  repeated recipes.chromeos.paygen.PaygenProperties.PaygenRequest paygen_requests = 2;
  // Tuple of serialized paygen requests expected for the batches.
  repeated recipes.chromeos.paygen.PaygenProperties.PaygenRequest expected_batches = 3;
}

message CreateAuTestConfigsProperties {

}