// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.build_menu.examples;

import "chromiumos/common.proto";

message FullProperties {
  // The build target for the build.
  chromiumos.BuildTarget build_target = 1;

  // Is this an artifact builder (needs to prepare).
  bool artifact_build = 2;

  // Is this forced_relevant (pointless builds still build.)
  bool forced_relevant = 3;

  // Whether to disable sysroot creation.
  bool no_sysroot = 4;

  // Whether no config is OK.
  bool missing_config_ok = 5;

  // Whether we expect to find no config.
  bool expect_missing_config = 6;

  // Expected packages.
  repeated chromiumos.PackageInfo expected_packages = 7;

  // Whether to call upload_prebuilts.
  bool upload_prebuilts = 8;

  // Value of cherry_pick_changes to pass to setup_workspace_and_chroot.
  // Inverted so that `false` is the default.
  bool dont_cherry_pick_changes = 9;

  // Whether to call upload_devinstall_prebuilts.
  bool upload_devinstall_prebuilts = 10;

  // Whether to publish image size data.
  bool publish_image_sizes = 11;

  // Whether to call upload_chrome_prebuilts.
  bool upload_chrome_prebuilts = 12;

  // Whether to call upload_host_prebuilts.
  bool upload_host_prebuilts = 13;
}
