// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.build_menu;

import "chromiumos/common.proto";
import "chromiumos/builder_config.proto";

message BuildMenuProperties {
  // The build target being built.
  chromiumos.BuildTarget build_target = 1;

  // Override for pointless build check.
  bool force_relevant_build = 2;

  // Whether this is an artifact build (calls ArtifactsService/PrepareForBuild.)
  bool artifact_build = 3;

  // Whether to run unit tests with code coverage or not.
  bool test_with_code_coverage = 4;

  // Whether to force an empty toolchain_targets to update_chroot.
  // Also set by the chromeos.build_menu.force_empty_toolchain_targets
  // experiment.
  bool force_empty_toolchain_targets = 5;

  // If set, call the BuildTestServiceContainers endpoint when collecting
  // artifacts.  The version string for tagging container images is generated
  // from the format string.
  //
  // This must form a value tag for Docker, as such it has a few rules:
  //   * May contain [A-Za-z0-9_.-]
  //   * May not start with . or -
  //   * Must be at most 128 characters
  //
  // The format string is taken as-is and any fields delimited by {} are
  // replaced with their respective value. Supported fields:
  //   * {build-target}  The build target for the board (eg: amd64-generic)
  //   * {cros-version}  The current chromeos version string (eg: R86-1.2.3)
  //   * {bbid}          The buildbucket Id of the current builder.
  //   * {staging?}      If running in staging, then evaluates to 'staging-',
  //                     otherwise the empty string
  //
  // Example, for CQ we use:
  //   {staging?}{build-target}-cq.{cros-version}-{bbid}
  string container_version_format = 6;

  // Whether to run unit tests with rust code coverage or not.
  // We need different flags for rust as it is triggered by a different builder.
  // Check b/246409134 for details.
  bool test_with_rust_code_coverage = 7;

  // Whether to force an prebuilt target on uploading the prebuilts. If the
  // value is not PREBUILTS_UNSPECIFIED, it overrides the original value. This
  // field is for testing.
  chromiumos.BuilderConfig.Artifacts.Prebuilts override_prebuilts_config = 8;

  // Whether we want to skip the unit tests step.
  bool skip_unit_tests = 9;
}
