// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_bisect.examples;

import "chromiumos/common.proto";

message TestInputProperties {
  repeated .chromiumos.PackageInfo expected_packages = 1;
  repeated .chromiumos.PackageInfo failed_packages = 2;
  repeated string expected_test_child_builders = 3;
  float expected_test_bisection_percent = 4;
  int32 expected_test_bisection_count = 5;
}
