// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.looks_for_green.tests;

import "go.chromium.org/luci/buildbucket/proto/common.proto";

message CalcApproxSnapAgeHoursProperties {
  int32 expected_approx_snap_age_hours = 1;
  string test_start_str = 2;
}

message FindGreenSnapshotProperties {
  bool expect_result = 1;
  int32 expected_bbid = 2;
  int32 expected_greenness = 3;
  string expected_commit_sha = 4;
  string expected_builder_greenness = 5;
  string latest_start = 6;
}

message GetLatestSnapshotGreennessProperties {
  int32 expected_greenness = 1;
  bool expected_is_snap_orch_green = 2;
  bool expected_staging = 3;
}

message ShouldLfgProperties {

  // Whether a test is expected to LFG.
  bool expected_should_lfg = 1;

  // Map of experiments to enablement.
  map<string, bool> experiments = 2;

  // Whether to test with multiple changes..
  bool enable_test_on_multiple_changes = 3;

  // Stacked or CQ-Depended changes not already included in a CQ run.
  string related_to_apply = 4;
}

message IsGreenForLocalProperties { bool expected_result = 1; }
