# -*- coding: utf-8 -*-
# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""APIs for running CrOS infra scripts."""

from recipe_engine import recipe_api


class CrosApi(recipe_api.RecipeApi):
  """A module for CrOS infra script steps.

  These steps will run in one of two CrOS source checkouts:

  * The "master" checkout is a recent version of the source which should not be
    modified (apart from incidental changes like caching) during a build.
    "Top of tree" logic will run from this checkout.

  * The "workspace" checkout is where the build is processed. It will contain
    the target base checkout and any modifications made by the build.
  """

  def initialize(self):
    self._master_path = self.m.path['start_dir'].join('chromiumos_master')
    self._workspace_path = self.m.path['start_dir'].join('chromiumos_workspace')

  @property
  def master_path(self):
    return self._master_path

  @property
  def workspace_path(self):
    return self._workspace_path

  def _chroot_step(self, name, cmd, **kwargs):
    """Runs a step within the configured workspace and cros_sdk chroot.

    Args:
      * name (str): The name of the step.
      * cmd (list[str]): A command and arguments to run.
      * kwargs: Keyword arguments to pass to 'cros_sdk.run'.

    Returns:
      See 'step.__call__'.
    """
    with self.m.context(cwd=self.workspace_path):
      return self.m.cros_sdk.run(name, cmd, **kwargs)

  def find_project_path(self, project, branch):
    """Find the source path for a given project.

    Args:
      project (str): The project name to find a source path for.
      branch (str): The branch name to find a source path for.

    Returns:
      The path value for the found project.
    """
    cmd = [
        'chromite/scripts/find_project_path', '--project', project, '--branch',
        branch
    ]
    with self.m.context(cwd=self.master_path):
      step_data = self.m.step(
          'find %s [%s]' % (project, branch), cmd,
          stdout=self.m.raw_io.output(), step_test_data=
          lambda: self.m.raw_io.test_api.stream_output('src/project'))
      return step_data.stdout.strip()

  def cherry_pick_changes(self, changes):
    """Apply changes to the workspace.

    Args:
      changes (list[change.Change]): A list of Changes to cherry-pick.
    """
    with self.m.step.nest('cherry-pick changes'):
      for change in changes:
        project_path = self.find_project_path(change.project, change.branch)
        with self.m.context(self.workspace_path.join(project_path)):
          commit_id = self.m.git.fetch_ref(change.git_fetch_url,
                                           change.git_fetch_ref)
          self.m.git.cherry_pick(commit_id)

  def regen_portage_cache(self, repo_name, jobs=32):
    """Regenerate the portage cache with 'egencache' in the chroot.

    Args:
      repo_name (str): Portage repo name, passed to 'egencache --repo'.
      jobs (int): Parallel processes to run, passed to 'egencache --jobs'.
    """
    cmd = ['egencache', '--update', '--repo', repo_name, '--jobs', '%d' % jobs]
    self._chroot_step('regen_portage_cache %s' % repo_name, cmd)

  def uprev_portage_packages(self):
    """Uprevs portage packages for all boards."""
    cmd = [
      'vpython','chromite/bin/cros_mark_as_stable', 'commit',
      '--all',
      '--buildroot', self.workspace_path,
      '--overlay-type', 'both'
    ]
    if self.m.dev.dryrun:
      cmd += ['--dryrun']
    with self.m.context(cwd=self.workspace_path):
      return self.m.step('uprev portage packages', cmd)

  def push_portage_package_uprevs(self):
    """Pushes the changes generated by |uprev_portage_packages| to remote."""
    # TODO(crbug.com/916197): Pull git operations out of this script
    cmd = [
      'vpython', 'chromite/bin/cros_mark_as_stable', 'push',
      '--buildroot', self.workspace_path,
      '--overlay-type', 'both'
    ]
    if self.m.dev.dryrun:
      cmd += ['--dryrun']
    with self.m.context(cwd=self.workspace_path):
      return self.m.step('push portage package uprevs', cmd)
