// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.paygen_testing;

import "google/protobuf/duration.proto";

message TestRequestOpts {
  // Max retry attempts. Set to 0 to disable retries.
  int64 max_retries = 1;

  // Timeout for the test execution.
  google.protobuf.Duration timeout = 2;
}

message QuotaSchedulerConfig {
  // Quota Scheduler account to use. Defaults to "legacypool-bvt".
  string account = 1;
  // Swarming pool label. Defaults to "quota".
  string label_pool = 2;
}

message PaygenTestingProperties {
  // test_platform.Request override options for scheduling autoupdate tests.
  TestRequestOpts test_request_opts = 1;

  // Override options for Quote Scheduler.
  QuotaSchedulerConfig quota_scheduler_config = 2;

  // List of QS accounts for which retries are enabled.
  // See b/293879623 for context.
  repeated string retry_allowlist_qs_account = 3;

  // List of build targets for which retries are enabled.
  // See b/293879623 for context.
  repeated string retry_allowlist_build_target = 4;
}
