// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.test_util.examples.full;

import "go.chromium.org/luci/buildbucket/proto/common.proto";

message TestProperties {
  // Expected project name.
  string expected_project = 1;

  // The expected bucket name.
  string expected_bucket = 2;

  // The expected builder name.
  string expected_builder = 3;

  // Whether we expect a gitiles_commit.
  bool expect_commit = 4;

  // The expected CL count.
  int32 expected_cl_count = 5;

  // Executable for the builder.
  buildbucket.v2.Executable expected_executable = 6;

  // Expected build_target
  string expected_build_target = 7;

  // Expected value for force_relevant_build.
  bool expected_force_relevant_build = 8;

  // Expected value for create_time, if non-zero (seconds since epoch).
  int64 expected_create_time = 9;

  // Expected value for start_time (seconds since epoch).
  int64 expected_start_time = 10;

  // Expected value for update_time (seconds since epoch).
  int64 expected_update_time = 11;

  // Expected value for end_time (seconds since epoch).
  int64 expected_end_time = 12;

  // Expected critical value.
  buildbucket.v2.Trinary expected_critical = 13;

  // Expected output.properties.build_target.name.
  string expected_output_build_target_name = 14;
}
