// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.tast_exec;

// import "chromiumos/common.proto";

message TastExecProperties {
  // Timeout for tast exec (in seconds).
  int32 exec_timeout = 1;
  // DEPRECATED: tests will be retied if the builder is critical.
  // Should the exec retry for eligible failed tests.
  bool should_retry = 2;
  // Whether this is a public target.
  bool public_builder = 3;
  // System services timeout for tast exec for VM tests (in seconds).
  // Controls how long to wait for the VM to start when running tests.
  int32 vm_system_services_timeout = 4;
}
