// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.debug_symbols;

message DebugSymbolsProperties {
  reserved 1;

  // Location in Google storage in which to fetch debug symbols from.
  // E.g. gs://chromeos-debug-symbols/some-release-area/debug.tgz
  string gs_path = 2;

  // Maximum number of concurrent workers to be ran in the builder.
  int32 worker_count = 3;

  // The total number of retries allowed.
  int32 retry_quota = 4;

  // Bool stating if the builder being ran in a staging environment.
  bool staging = 5;

  // Bool stating whether or not to dry run the uploads.
  bool dryrun = 6;
}