// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.chromeos.lab_platform.sync_stable_version;

message SyncStableVersionProperties {
  // TODO(xixuan): pass in real parameters for stable_version2 tool.
  // The Google Storage path of omaha status json file.
  string omaha_status_gs_url = 1;

  // The stable version config path relative to chromiumos config repo:
  // https://chrome-internal.googlesource.com/chromeos/infra/config
  // e.g. lab_platform/stable_version_data/stable_versions.cfg
  string stable_version_config_path = 2;
}