// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_sdk;

message CrosSdkProperties {
  // Whether to force toolchain_cls=False in build_api calls.
  // This is used to verify that the SDK is compatible with the toolchain CL
  // being landed.  See crbug.com/1130707.
  bool force_off_toolchain_changed = 1;

  // Whether to mount the named cache as an overlayfs.
  bool mount_named_cache = 2;
}
