# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Verify that rebase_cl() locally rebases existing commits as expected."""

from typing import Generator

from PB.chromiumos.common import BuildTarget
from PB.chromiumos.common import PackageInfo
from PB.go.chromium.org.luci.buildbucket.proto.common import GerritChange
from recipe_engine import post_process
from recipe_engine.recipe_api import RecipeApi
from recipe_engine.recipe_test_api import RecipeTestApi
from recipe_engine.recipe_test_api import TestData
from RECIPE_MODULES.chromeos.pupr_local_uprev.api import LocalUprevConfig

DEPS = [
    'cros_build_api',
    'cros_source',
    'gerrit',
    'git',
    'pupr_local_uprev',
]


BUILD_TARGETS = [BuildTarget(name='build-target')]
CHANGE_1234 = GerritChange(host='chromium-review.googlesource.com', change=1234)
CHANGE_5678 = GerritChange(host='chromium-review.googlesource.com', change=5678)
OPEN_CHANGES = [CHANGE_1234, CHANGE_5678]
PACKAGE_CHROME = PackageInfo(category='chromeos-base',
                             package_name='chromeos-chrome')
PACKAGE_LACROS = PackageInfo(category='chromeos-base',
                             package_name='chromeos-lacros')
PACKAGES = [PACKAGE_CHROME, PACKAGE_LACROS]


def RunSteps(api: RecipeApi):
  api.pupr_local_uprev.set_generator_config(
      LocalUprevConfig.for_test(
          packages=PACKAGES,
          build_targets=BUILD_TARGETS,
      ))
  api.pupr_local_uprev.rebase_cl(OPEN_CHANGES, 'cool_topic', 1234)


def GenTests(api: RecipeTestApi) -> Generator[TestData, None, None]:
  CHANGE_ID = 'deadbeef'
  VERSION = '79.0.3945.20'
  REF = f'refs/tags/{VERSION}'
  REPOSITORY = '/chromium/src'
  REVISION = '83a1812dddfc24f604d92bf61ad58efe9227a6fc'
  # As expected by api.gerrit.set_gerrit_fetch_changes_response().
  gerrit_fetch_changes_values_dict = {
      1234: {
          'change_id': 1234,
          'created': '2020-10-22 18:54:00.000000000',
          'messages': [{
              'message':
                  'Quote: Patch Set 3:\n\nThis CL has failed the run. Reason: ...',
              'date':
                  '2020-10-26T18:54:00Z',
          }, {
              'message': 'Patch Set 3:\n\nCV is trying the patch...',
              'date': '2020-10-24T18:54:00Z',
              'tag': 'autogenerated:cv:full-run'
          }, {
              'message':
                  'Patch Set 3:\n\nThis CL has failed the run. Reason: ...',
              'date':
                  '2020-10-25T18:54:00Z',
              'tag':
                  'autogenerated:cv:full-run'
          }],
          'revision_info': {
              'ref': 'refs/change/foo',
              'commit': {
                  'message':
                      'a quick description\n\n' +
                      f'Change-Id: {CHANGE_ID}\n\n' +
                      f'Pupr-Upstream-Versions: [{{"ref": "{REF}", "repository": "{REPOSITORY}", "revision": "{REVISION}"}}]',
              },
          },
      }
  }

  # By default, the BAPI call to PackageService/UprevVersionedPackage returns
  # two modified ebuilds in different repos. This would trigger a failure,
  # since we currently can't rebase a multi-repo uprev.
  # Use api.cros_build_api.set_upreved_ebuilds to override this.
  yield api.test(
      'basic',
      api.gerrit.set_gerrit_fetch_changes_response(
          'rebase CL 1234.get CL 1234 description',
          [CHANGE_1234],
          gerrit_fetch_changes_values_dict,
      ),
      api.git.diff_check(True),
      api.cros_build_api.set_upreved_ebuilds(['src/overlay/foo.ebuild']),
      api.post_check(post_process.MustRun, 'rebase CL 1234.commit uprev'),
      api.post_process(post_process.DropExpectation),
  )

  # Like basic, but don't override PackageService/UprevVersionedPackage.
  yield api.test(
      'multi-repo',
      api.gerrit.set_gerrit_fetch_changes_response(
          'rebase CL 1234.get CL 1234 description',
          [CHANGE_1234],
          gerrit_fetch_changes_values_dict,
      ),
      api.git.diff_check(True),
      api.post_process(post_process.DropExpectation),
      status='FAILURE',
  )

  # We cannot rebase if the new uprev produces no diff.
  yield api.test(
      'no-diff',
      api.gerrit.set_gerrit_fetch_changes_response(
          'rebase CL 1234.get CL 1234 description',
          [CHANGE_1234],
          gerrit_fetch_changes_values_dict,
      ),
      api.git.diff_check(False),
      api.post_process(post_process.DropExpectation),
      status='FAILURE',
  )

  yield api.test(
      'cl-has-no-pupr-uprev-metadata',
      api.post_process(post_process.DropExpectation),
      status='FAILURE',
  )
