# -*- coding: utf-8 -*-

# Copyright 2022 The ChromiumOS Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from recipe_engine import recipe_api
from PB.testplans.generate_test_plan import BuildPayload, TestUnitCommon
from PB.chromiumos.common import BuildTarget
from PB.testplans.target_test_requirements_config import TestSuiteCommon
from PB.testplans.generate_test_plan import HwTestUnit
from PB.testplans.target_test_requirements_config import HwTestCfg

CROS_ADDITIONAL_TEST_SUITES = 'Cros-Add-Test-Suites'
CROS_ADDITIONAL_TS_BOARDS_BUILDTARGET = 'Cros-Add-TS-Boards-BuildTarget'
CROS_ADDITIONAL_TS_POOL = 'Cros-Add-TS-Pool'


class CrosCqAdditionalTests(recipe_api.RecipeApi):

  def __init__(self, properties, *args, **kwargs):
    super(CrosCqAdditionalTests, self).__init__(*args, **kwargs)
    self._properties = properties
    self._missing_board_build_target_footer_addtnl_ts_run = False
    self._unmatched_build_targets_addtnl_ts_run = []

  def append_user_provided_test_suites_to_test_plan(self, builds,
                                                    gerrit_changes, test_plan):
    """Reads additional test suites related Git footers and appends them
        to test plan.
      Below footers are read.
      Cros-Add-Test-Suites-list of test suites to run.
      Cros-Add-TS-Boards-BuildTarget-list of boards and build targets provided.
        for example: coral, octopus|octopus|octopus-kernelNext.
        Run test suites for board:coral and build_target:coral
        for board - octopus and build target = octopus, octopus-kernelNext.
      Cros-Add-TS-Pool - pool to run against - defaulted to DUT_POOL_QUOTA.

      There are 2 possible soft error scenarios
      Both doesnt result in error and the test plan is left unchanged.
        1. build target/boards are not provided
        The state of this error can be checked invoking -
        is_missing_board_build_target_footer_addtnl_ts_run()
        2. Build targets provided were not built in this CQ run -
        The unmatched build targets can
        be checked using  unmatched_build_targets_addtnl_ts_run

      Args:
        builds (list[build_pb2.Build]): builds to test.
        gerrit_changes(list[common_pb2.GerritChange]): changes that resulted
        in the provided builds, or None.
        test_plan: test plan generated by ctp.
      Returns:
    """
    ## TODO - add check for CQ orchestrator run only.
    if self._properties.enable_running_additional_tests:
      with self.m.step.nest('process additional test suites') as pres:
        test_suites, test_boards_buildTargets, pool = (
            self._read_additional_test_suites_related_footers(gerrit_changes))
        #check additional test suites are provided.
        if len(test_suites) == 0:
          return

        #check if footers are correctly provided
        if len(test_boards_buildTargets) == 0:
          pres.step_text = (
              'No additional test suites run. '
              'Board and/or board build target combination is required')
          self._missing_board_build_target_footer_addtnl_ts_run = True
          return

        #pre process
        bt_build_map = self._extract_build_target_name_to_build_map(builds)
        bt_hw_test_cfg_map, bt_tests_map = self._extract_build_target_test_maps(
            test_plan)

        #process additional test suites -
        # cross product - board, build target, test suites
        for tbb in test_boards_buildTargets:
          self._process_each_test_board_build_target(tbb, bt_build_map,
                                                     bt_hw_test_cfg_map,
                                                     bt_tests_map, test_plan,
                                                     test_suites, pool)
        #check for errors in additional test suite processing.
        if self._unmatched_build_targets_addtnl_ts_run:
          pres.step_text = ('Additional TestSuite cannot be run on build '
                            'targets that are not built or failed building'
                            ' as part of cq: %s') % ', '.join(
                                self._unmatched_build_targets_addtnl_ts_run)
        else:
          pres.step_text = 'Additional TestSuite added to test plan'

  def unmatched_build_targets_addtnl_ts_run(self):
    return self._unmatched_build_targets_addtnl_ts_run

  def is_missing_board_build_target_footer_addtnl_ts_run(self):
    return self._missing_board_build_target_footer_addtnl_ts_run

  def _read_additional_test_suites_related_footers(self, gerrit_changes):
    """Reads additional test suites related Git footers. Below footers are read.
        Cros-Add-Test-Suites - list of test suites to run.
        Cros-Add-TS-Boards-BuildTarget-list of boards and build targets.
          for example: coral, octopus|octopus|octopus-kernelNext.
          run test suites for board=coral and build_target=coral
          for board - octopus and build target = octopus, octopus-kernelNext.
        Cros-Add-TS-Pool - pool to run against - defaulted to DUT_POOL_QUOTA.
    """
    test_suites = self._read_footers(CROS_ADDITIONAL_TEST_SUITES,
                                     gerrit_changes)
    test_boards_buildTargets = self._read_footers(
        CROS_ADDITIONAL_TS_BOARDS_BUILDTARGET, gerrit_changes)
    pool_footer = self._read_footers(CROS_ADDITIONAL_TS_POOL, gerrit_changes)
    pool = 'DUT_POOL_QUOTA'
    if len(pool_footer) > 0:
      pool = list(pool_footer)[0]
    return test_suites, test_boards_buildTargets, pool

  def _read_footers(self, key, gerrit_changes):
    return self.m.git_footers.get_footer_values(
        gerrit_changes, key,
        step_test_data=self.m.git_footers.test_api.step_test_data_factory(''))

  def _extract_build_target_name_to_build_map(self, builds):
    return {
        self.m.cros_infra_config.get_build_target_name(b): b for b in builds
    }

  def _extract_build_target_test_maps(self, test_plan):
    bt_hw_test_cfg_map = {}
    bt_tests_map = {}
    for test in test_plan.hw_test_units:
      bt_hw_test_cfg_map[test.common.build_target.name] = test.hw_test_cfg
      for hw_test in test.hw_test_cfg.hw_test:
        bt_tests_map[test.common.build_target.name + hw_test.suite +
                     hw_test.skylab_board + hw_test.pool] = hw_test
    return bt_hw_test_cfg_map, bt_tests_map

  def _process_each_test_board_build_target(self, tbb, bt_build_map,
                                            bt_hw_test_cfg_map, bt_tests_map,
                                            test_plan, test_suites, pool):
    board, build_targets = self._extract_board_build_target(tbb)
    for build_target in build_targets:
      matched_build = bt_build_map.get(build_target)
      #build targets given by user but not built in CQ are not added
      #to test plan
      if matched_build is None:
        self._unmatched_build_targets_addtnl_ts_run.append(build_target)
        continue

      for ts in test_suites:
        existing_hw_test_cfg = bt_hw_test_cfg_map.get(build_target)
        addition_hw_test = self._create_hw_test_entry(ts, build_target, board,
                                                      pool)
        #check if build target already has tests.
        if existing_hw_test_cfg != None:
          matched_hw_test = bt_tests_map.get(build_target + ts + board + pool)
          #check if test is already configured for build target
          #the matching is done by build target,board,pool and ts
          if matched_hw_test is None:
            existing_hw_test_cfg.hw_test.append(addition_hw_test)
        else:
          bp = self._create_build_payload_For_TestPlan(matched_build)
          test_common = TestUnitCommon(
              build_target=BuildTarget(name=build_target), build_payload=bp,
              builder_name=build_target + '-cq')
          hwTestUnit = HwTestUnit(
              common=test_common, hw_test_cfg=HwTestCfg(
                  hw_test=[addition_hw_test],
              ))
          test_plan.hw_test_units.append(hwTestUnit)

  def _extract_board_build_target(self, tbb):
    board_build_target = tbb.split('|')
    board = board_build_target[0]

    build_targets = []
    if len(board_build_target) > 1:
      build_targets = board_build_target[1:len(board_build_target)]
    else:
      build_targets.append(board)
    return board, build_targets

  def _create_build_payload_For_TestPlan(self, build):
    artifacts = build.output.properties['artifacts']
    return BuildPayload(artifacts_gs_bucket=artifacts['gs_bucket'],
                        artifacts_gs_path=artifacts['gs_path'],
                        files_by_artifact=artifacts['files_by_artifact'])

  def _create_hw_test_entry(self, ts, build_target, board, pool):
    return HwTestCfg.HwTest(
        common=TestSuiteCommon(
            display_name=build_target + '.hw.' + ts, critical={
                'value': self._properties.run_additional_tests_as_critical
            }),
        suite=ts,
        skylab_board=board,
        pool=pool,
        hw_test_suite_type=HwTestCfg.TAST,
    )
