# -*- coding: utf-8 -*-

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from recipe_engine import recipe_api
from PB.chromiumos.common import BuildTarget
from PB.testplans.generate_test_plan import BuildPayload
from PB.testplans.generate_test_plan import HwTestUnit
from PB.testplans.generate_test_plan import TestUnitCommon
from PB.testplans.target_test_requirements_config import HwTestCfg
from PB.testplans.target_test_requirements_config import TestSuiteCommon

CROS_ADDITIONAL_TEST_SUITES = 'Cros-Add-Test-Suites'
CROS_ADDITIONAL_TS_BOARDS_BUILDTARGET = 'Cros-Add-TS-Boards-BuildTarget'
CROS_ADDITIONAL_TS_POOL = 'Cros-Add-TS-Pool'


class CrosCqAdditionalTestsInvalidFooterError(Exception):
  """invalid footer exception """


class CrosCqAddnlTestsMissingBuildTargetsError(Exception):
  """This exception captures additional tests that could not be run
  because either the build target was not built or it failed
  building. Call not_runnable_addtnl_tests to get list of not run
  test suites"""

  def __init__(self, _not_runnable_addtnl_tests):
    super().__init__()
    self._not_runnable_addtnl_tests = _not_runnable_addtnl_tests

  @property
  def not_runnable_addtnl_tests(self):
    return self._not_runnable_addtnl_tests


class CrosCqAdditionalTests(recipe_api.RecipeApi):

  #Recipe Quirks: this is needed to have the exception visible externally.
  CrosCqAdditionalTestsInvalidFooterError = CrosCqAdditionalTestsInvalidFooterError
  CrosCqAddnlTestsMissingBuildTargetsError = CrosCqAddnlTestsMissingBuildTargetsError

  def __init__(self, properties, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self._properties = properties
    self._not_runnable_addtnl_tests = []

  def append_user_provided_test_suites_to_test_plan(self, builds,
                                                    gerrit_changes, test_plan):
    """Reads additional test suites related Git footers and appends them
        to test plan.
      Below footers are read.
      Cros-Add-Test-Suites-list of test suites to run.
      Cros-Add-TS-Boards-BuildTarget-list of boards and build targets provided.
        for example: coral, octopus|octopus|octopus-kernelNext.
        Runs test suites for board:coral and build_target:coral
        for board - octopus and build target = octopus, octopus-kernelNext.
      Cros-Add-TS-Pool - pool to run against - defaulted to DUT_POOL_QUOTA.
      Args:
        builds (list[build_pb2.Build]): builds to test.
        gerrit_changes(list[common_pb2.GerritChange]): changes that resulted
        in the provided builds, or None.
        test_plan: test plan generated by ctp.
      Returns:
      Raises:
        CrosCqAdditionalTestsInvalidFooterError - when Cros-Add-Test-Suites footer
        is present but Cros-Add-TS-Boards-BuildTarget is missing
        CrosCqAddnlTestsMissingBuildTargetsError - when there are test suites not run
        due to failed or not built build targets.
    """
    if (self._properties.enable_running_additional_tests and
        'cq-orchestrator' in self.m.buildbucket.build.builder.builder):
      with self.m.step.nest('process additional test suites') as pres:
        test_suites, test_boards_build_targets, pool = (
            self._read_additional_test_suites_related_footers(gerrit_changes))
        #check additional test suites are provided.

        if len(test_suites) == 0:
          return
        pres.logs[
            'read_git_footer_result'] = 'footer data: test suites: %s \nboards_build_targets: %s\npool : %s\n' % (
                ','.join(test_suites), ','.join(test_boards_build_targets),
                pool)

        #check if footers are correctly provided
        if len(test_boards_build_targets) == 0:
          pres.step_text = (
              'No additional test suites run. '
              'Board and/or board build target combination is required')
          raise CrosCqAdditionalTestsInvalidFooterError()

        #pre process
        bt_build_map = self._extract_build_target_name_to_build_map(builds)
        bt_hw_test_cfg_map, bt_tests_map = self._extract_build_target_test_maps(
            test_plan)

        #process additional test suites -
        # cross product - board, build target, test suites
        for tbb in test_boards_build_targets:
          self._process_each_test_board_build_target(tbb, bt_build_map,
                                                     bt_hw_test_cfg_map,
                                                     bt_tests_map, test_plan,
                                                     test_suites, pool)

        pres.logs['updated_test_plan'] = str(test_plan)
        #check for errors in additional test suite processing.
        if self._not_runnable_addtnl_tests:
          not_run_for_build_targets_str = ', '.join({
              t.common.display_name.split('.hw', 1)[0]
              for t in self._not_runnable_addtnl_tests
          })
          not_run_test_suites = ', '.join(
              {t.common.display_name for t in self._not_runnable_addtnl_tests})
          pres.logs['not_runnable_addtnl_test_suites'] = not_run_test_suites
          pres.step_text = (
              'Additional TestSuites cannot be run on build '
              'targets that are not built or failed building'
              ' as part of cq: %s') % not_run_for_build_targets_str
          raise CrosCqAddnlTestsMissingBuildTargetsError(
              self._not_runnable_addtnl_tests)
        pres.step_text = 'Additional TestSuite added to test plan'

  def _read_additional_test_suites_related_footers(self, gerrit_changes):
    """Reads additional test suites related Git footers. Below footers are read.
        Cros-Add-Test-Suites - list of test suites to run.
        Cros-Add-TS-Boards-BuildTarget-list of boards and build targets.
          for example: coral, octopus|octopus|octopus-kernelNext.
          run test suites for board=coral and build_target=coral
          for board - octopus and build target = octopus, octopus-kernelNext.
        Cros-Add-TS-Pool - pool to run against - defaulted to DUT_POOL_QUOTA.
    """
    test_suites = self._read_footers(CROS_ADDITIONAL_TEST_SUITES,
                                     gerrit_changes)
    test_boards_build_targets = self._read_footers(
        CROS_ADDITIONAL_TS_BOARDS_BUILDTARGET, gerrit_changes)
    pool_footer = self._read_footers(CROS_ADDITIONAL_TS_POOL, gerrit_changes)
    pool = 'DUT_POOL_QUOTA'
    if len(pool_footer) > 0:
      pool = list(pool_footer)[0]
    return test_suites, test_boards_build_targets, pool

  def _read_footers(self, key, gerrit_changes):
    return self.m.git_footers.get_footer_values(
        gerrit_changes, key,
        step_test_data=self.m.git_footers.test_api.step_test_data_factory(''))

  def _extract_build_target_name_to_build_map(self, builds):
    return {
        self.m.cros_infra_config.get_build_target_name(b): b for b in builds
    }

  def _extract_build_target_test_maps(self, test_plan):
    bt_hw_test_cfg_map = {}
    bt_tests_map = {}
    for test in test_plan.hw_test_units:
      bt_hw_test_cfg_map[test.common.build_target.name] = test.hw_test_cfg
      for hw_test in test.hw_test_cfg.hw_test:
        bt_tests_map[test.common.build_target.name + hw_test.suite +
                     hw_test.skylab_board + hw_test.pool] = hw_test
    return bt_hw_test_cfg_map, bt_tests_map

  def _process_each_test_board_build_target(self, tbb, bt_build_map,
                                            bt_hw_test_cfg_map, bt_tests_map,
                                            test_plan, test_suites, pool):
    board, build_targets = self._extract_board_build_target(tbb)
    for build_target in build_targets:
      matched_build = bt_build_map.get(build_target)
      #build targets given by user but not built in CQ are not added
      #to test plan. Instead they are added to not_runnable_addtnl_tests
      #which is later thrown as an exception
      if matched_build is None:
        for ts in test_suites:
          self._not_runnable_addtnl_tests.append(
              self._create_hw_test_entry(ts, build_target, board, pool))
        continue
      for ts in test_suites:
        existing_hw_test_cfg = bt_hw_test_cfg_map.get(build_target)
        addition_hw_test = self._create_hw_test_entry(ts, build_target, board,
                                                      pool)
        #check if build target already has tests.
        if existing_hw_test_cfg is not None:
          matched_hw_test = bt_tests_map.get(build_target + ts + board + pool)
          #check if test is already configured for build target
          #the matching is done by build target,board,pool and ts
          if matched_hw_test is None:
            existing_hw_test_cfg.hw_test.append(addition_hw_test)
        else:
          bp = self._create_build_payload_For_TestPlan(matched_build)
          test_common = TestUnitCommon(
              build_target=BuildTarget(name=build_target), build_payload=bp,
              builder_name=build_target + '-cq')
          hwTestUnit = HwTestUnit(
              common=test_common, hw_test_cfg=HwTestCfg(
                  hw_test=[addition_hw_test],
              ))
          test_plan.hw_test_units.append(hwTestUnit)

  def _extract_board_build_target(self, tbb):
    board_build_target = tbb.split('|')
    board = board_build_target[0]

    build_targets = []
    if len(board_build_target) > 1:
      build_targets = board_build_target[1:len(board_build_target)]
    else:
      build_targets.append(board)
    return board, build_targets

  def _create_build_payload_For_TestPlan(self, build):
    artifacts = build.output.properties['artifacts']
    return BuildPayload(artifacts_gs_bucket=artifacts['gs_bucket'],
                        artifacts_gs_path=artifacts['gs_path'],
                        files_by_artifact=artifacts['files_by_artifact'])

  def _create_hw_test_entry(self, ts, build_target, board, pool):
    return HwTestCfg.HwTest(
        common=TestSuiteCommon(
            display_name=build_target + '.hw.' + ts, critical={
                'value': self._properties.run_additional_tests_as_critical
            }),
        suite=ts,
        skylab_board=board,
        pool=pool,
        hw_test_suite_type=HwTestCfg.TAST,
    )
