// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_test_plan;

message CrosTestPlanProperties {
  reserved 1 to 3;

  // TODO(b:191392307): Consider keeping this unbranched, currently the
  // cros_test_plan will use the same git repo/branch pair to fetch all these
  // files but since this is based on lab capacity we might not want to have
  // to push the current state to each branch.
  // Path to the board priority binary proto.
  // (e.g. board_config/generated/board_priority.binaryproto)
  string board_priority_config_path = 4;

  // Path to the source tree test config binary proto.
  // (e.g. board_config/generated/source_tree_test_config.binaryproto)
  string source_tree_test_config_path = 5;

  // Path to the target test requirements input proto.
  // (e.g. board_config/generated/target_test_requirements.binaryproto)
  string target_test_requirements_path = 6;

  // Parameters to set which branched test plan is selected.
  // Which gitiles repo to select from (e.g. chromeos/config-internal).
  string source_gitiles_repo = 7;

  // Which branch from the repo to use (e.g. release-R93-14092.B).
  string source_gitiles_branch = 8;

  // Whether or not to generate target rest requirements at runtime from
  // src/config-internal. Takes precedent over all other properties.
  bool generate_target_test_requirements_from_source = 9;

  // Whether staging should use testing config from the corresponding
  // production builder(s) instead of staging config. Used for tryjobs.
  bool use_prod_config = 10;
}
