// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_test_plan;

message CrosTestPlanProperties {
    reserved 1;

    // Cipd ref to use for test plan generator.
    // Defaults to "chromiumos/infra/test_plan_generator/{$platform}".
    string test_plan_generator_cipd_package = 2;

    // Cipd ref to use for test plan generator.
    // Defaults to "staging" or "prod".
    string test_plan_generator_cipd_ref = 3;
}
