// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.phosphorus;

import "test_platform/skylab_local_state/common.proto";

message PhosphorusProperties {
  // Version describes which cros_test_platform binary version to use.
  message Version {
    // Use the CIPD version with this label.
    string cipd_label = 1;
  }

  Version version = 1;

  // config describes configuration information for interaction with
  // skylab_local_state. Is set by the builder properties, not the caller.
  .test_platform.skylab_local_state.Config config = 2;
}

message PhosphorusEnvProperties {
  string SWARMING_BOT_ID = 1;
  string SWARMING_TASK_ID = 2;
  string SKYLAB_DUT_ID = 3;
  string CLOUDBOTS_DUT_HOSTNAME = 4;
}
