// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.gerrit;

message GerritProperties { RelatedChanges related_changes = 1; }

message RelatedChanges {
  // Cipd ref to use for gerrit_related_changes.
  // Defaults to "chromiumos/infra/gerrit_related_changes/{$platform}".
  string related_changes_cipd_package = 1;

  // Cipd ref to use for gerrit_related_changes.
  // Defaults to "staging" or "prod".
  string related_changes_cipd_ref = 2;
}
