// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_history.examples;

import "go.chromium.org/luci/buildbucket/proto/build.proto";
import "go.chromium.org/luci/buildbucket/proto/common.proto";

message GetPassedBuildsProperties {
  repeated buildbucket.v2.GerritChange input_build_patches = 1;
  repeated buildbucket.v2.GerritChange input_target_patches = 2;
  repeated buildbucket.v2.Build output_builds = 3;
  repeated string output_targets = 4;
}
