// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_prebuilts.examples.full;

import "chromiumos/common.proto";
import "chromite/api/sysroot.proto";
import "chromiumos/builder_config.proto";

message FullProperties {
  // The build_target for this builder.
  chromiumos.BuildTarget build_target = 1;

  // The sysroot for this builder.
  chromite.api.Sysroot sysroot = 2;

  // Expected builder name, if any.  See BuilderConfig.Id.name.
  bool private = 3;

  // The gs_bucket to use.
  string gs_bucket = 4;

  // The name of the profile to use.
  chromiumos.Profile profile = 5;

  // Expected PackageIndexInfo data
  repeated chromiumos.PackageIndexInfo expected_package_indexes = 6;

  // Whether to make the source appear dirty.
  bool dirty_source = 7;

  // Type of builder to override. The builder_config_id is overridden by this
  // value if the value is not "BuilderConfig.Id.TYPE_UNSPECIFIED".
  // The default value is BuilderConfig.Id.TYPE_UNSPECIFIED.
  chromiumos.BuilderConfig.Id.Type overridden_builder_config = 8;

  // Chroot to work with.
  chromiumos.Chroot chroot = 9;
}
