// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_prebuilts.examples;

import "chromiumos/common.proto";
import "go.chromium.org/luci/buildbucket/proto/common.proto";

message FullProperties {
  // The build_target for this builder.
  chromiumos.BuildTarget build_target = 1;

  // Expected builder name, if any.  See BuilderConfig.Id.name.
  bool private = 2;

  // The gs_bucket to use.
  string gs_bucket = 3;

  // The name of the profile to use.
  chromiumos.Profile profile = 4;

  // Expected PackageIndexInfo data
  repeated chromiumos.PackageIndexInfo expected_package_indexes = 5;
}
