// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_release_config;

message Email {
  // Email address, e.g. "foo@google.com".
  string email = 1;
}

message CrosReleaseConfigProperties {
  // Reviewers for config CLs.
  repeated Email reviewers = 1;

  // CCs for config CLs.
  repeated Email ccs = 2;

  // Whether or not to auto-submit CLs.
  bool auto_submit = 3;

  // How many milestones to maintain release builders for.
  // If set and a newly added builder exceeds this number,
  // the builders for the release branches will be pruned in
  // ascending order of milestone number.
  int32 keep_n_milestones = 4;
}