// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.sysroot_util.examples;

import "chromiumos/common.proto";

message FullTestProperties {
  // Image types to build.
  repeated chromiumos.ImageType image_types = 1;

  // ImageService.Test response JSON.
  string image_test_json = 2;

  // Whether this is an artifact build.
  bool artifact_build = 3;

  // Whether to use remoteexec.
  bool use_remoteexec = 4;

  // Name of the test builder config to use.
  string builder_name = 5;

  // Copy the base image to recovery_image.bin for ChromeOS Flex.
  bool base_is_recovery = 6;

  // Whether or not image unit tests should be skipped.
  bool skip_tests = 7;

  // Whether to do the image size regression check.
  bool verify_image_size_delta = 8;

  // Whether to check out the chrome source as part of the test setup.
  bool checkout_chrome = 9;

  // Whether to build an official image.
  bool is_official = 10;
}
