// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_paygen;

import "google/protobuf/duration.proto";

message TestRequestOpts {
  // Max retry attempts. Set to 0 to disable retries.
  int64 max_retries = 1;

  // Timeout for the test execution.
  google.protobuf.Duration timeout = 2;
}

message QuotaSchedulerConfig {
  // Quota Scheduler account to use. Defaults to "legacypool-bvt".
  string account = 1;
  // Swarming pool label. Defaults to "quota".
  string label_pool = 2;
}

message CrosPaygenProperties {
  // test_platform.Request override options for scheduling autoupdate tests.
  TestRequestOpts test_request_opts = 1;

  // The max number of dlc payloads to include in a single generation request.
  // If not provided, dlc payloads will be sent in a single batch.
  int32 max_dlc_batch_size = 2;

  // Override options for Quote Scheduler.
  QuotaSchedulerConfig quota_scheduler_config = 3;

  // The models for which we've enabled AU testing.
  // Generally, this should be set when running the PaygenOrchestrator recipe,
  // to certain models exported by GoldenEye.
  // If empty (or if there is no overlap with applicable_models), then one test
  // request will be sent, with no model specified, meaning that the test can be
  // run on any model.
  repeated string au_testing_models = 4;

  // The models which should run AU testing for FSI payloads.
  // Generally, this should be set when running the PaygenOrchestrator recipe,
  // to all models exported by GoldenEye.
  // If empty, behavior will be the same as for empty au_testing_models.
  repeated string au_fsi_testing_models = 5;
}
