// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_build_api;

message CrosBuildApiProperties {
  // If true, capture output from Build API steps into a Placeholder object
  // and send to Analysis Service. Note that this currently has some drawbacks/
  // behavior changes:
  // * Stdout/err appear as separate links in Milo.
  // * Stdout/err only appear in Milo after the step is complete.
  // * Stdout/err will not appear in Milo if the build is cancelled.
  bool capture_stdout_stderr = 1;
  // Log level used when calling build_api, currently the following values
  // supported by build_api: fatal,critical,error,warning,notice,info,debug.
  // Using a string type because these values are not proto-enums, but are
  // strings specified in chromite/lib/commandline.py, and the value will be
  // used as a string by recipe_modules/cros_build_api/api.py.
  string log_level = 2;
  // Publish emerge stats to BigQuery. The recipe will scrape the bapi
  // output and determine what actions emerge took and process durations
  // and other valuable insights. It will then push to a table 'portage_stats'
  // inside of the cloud project configured.
  bool publish_emerge_stats_to_bq = 3;
  // Also add the emerge stats to an output property.
  bool publish_emerge_stats_to_prop = 4;
}
