// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_lkgm.examples;

import "go.chromium.org/luci/buildbucket/proto/build.proto";

message DoLkgmProperties {
  // The release builds to pass to do_lkgm.
  repeated buildbucket.v2.Build release_builds = 1;

  // Whether to pass `use_branch` to do_lkgm.
  bool use_branch = 2;

  // Whether to skip public builds on preparation.
  bool skip_public_build = 3;

  reserved 4;

  uint32 internal_manifest_position = 5;
  uint32 external_manifest_position = 6;
}
