// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.sysroot_util.tests;

import "go.chromium.org/luci/buildbucket/proto/common.proto";
import "chromite/api/artifacts.proto";

message TestInputProperties {
  // The name of the builder config to fetch.
  string builder_name = 1;

  // Whether to force build relevance.
  bool force_build_relevance = 2;

  // Expected response to update_for_artifact_build
  chromite.api.PrepareForBuildResponse.BuildRelevance expected_relevance = 3;

  // Whether to create a chroot first.
  bool with_chroot = 4;

  // Response data for Build API call.
  string api_response = 5;
}
