// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_infra_config.examples;

import "chromiumos/common.proto";
import "go.chromium.org/luci/buildbucket/proto/common.proto";
import "google/protobuf/wrappers.proto";

message BuilderProperties {
  // The build_target for this builder.
  chromiumos.BuildTarget build_target = 1;

  // Expected builder name, if any.  See BuilderConfig.Id.name.
  string builder = 2;

  reserved 3;

  // Expected value for is_staging.
  bool expected_is_staging = 4;

  // Whether to expect an unset gitiles_commit.
  bool expect_empty_gitiles_commit = 5;

  // Expected gitiles commit.  If not set and expect_empty_gitiles_commit is
  // False, then defaults are provided.
  buildbucket.v2.GitilesCommit expected_gitiles_commit = 6;

  // Whether to pass choose_branch=False
  bool no_choose_branch = 7;
}
