// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_infra_config.examples;

import "chromiumos/common.proto";
import "go.chromium.org/luci/buildbucket/proto/common.proto";
import "google/protobuf/wrappers.proto";

message BuilderProperties {
  // The build_target for this builder.
  chromiumos.BuildTarget build_target = 1;

  // Expected builder name, if any.  See BuilderConfig.Id.name.
  string builder = 2;

  // is_staging argument to configure_builder.
  google.protobuf.BoolValue is_staging = 3;

  // Expected value for is_staging.
  bool expected_is_staging = 4;

  // Expected gitiles commit.  If not set, defaults are provided.
  buildbucket.v2.GitilesCommit expected_gitiles_commit = 5;
}
