# -*- coding: utf-8 -*-
# Copyright 2019 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

""" API for breakpad."""

import os

from recipe_engine.recipe_api import RecipeApi, StepFailure

# The file in an image archive containing debug symbols.
# TODO(crbug.com/973172): Pass as an argument instead of hardcoding.
SYMBOLS_FILE_NAME = 'debug_breakpad.tar.xz'


class SymbolsFileNotFoundException(StepFailure):
  """Raised when the symbol file is not found, letting us skip gracefully."""


class BreakpadApi(RecipeApi):

  def initialize(self):
    self._breakpad_ensured = False

  @property
  def _breakpad_root(self):
    return self.m.path.start_dir / 'breakpad'

  @property
  def _minidump_stackwalk_path(self):
    return self._breakpad_root / 'minidump_stackwalk'

  def _ensure_breakpad(self):
    """Ensure the breakpad CIPD package is installed."""
    if not self._breakpad_ensured:
      with self.m.step.nest('ensure breakpad'):
        ensure_file = self.m.cipd.EnsureFile()
        ensure_file.add_package(name='chromiumos/infra/tools/breakpad',
                                version='latest')

        self.m.cipd.ensure(self._breakpad_root, ensure_file)
        self._breakpad_ensured = True

  def _download_and_log_gs_url(self, url, dest, args=None, **kwargs):
    """Call gsutil.download_url and log a link to the GS path.

    Args: See args to gsutil.download_url
    """
    step = self.m.gsutil.download_url(url, dest, args, **kwargs)
    step.presentation.links[url] = self.m.urls.get_gs_path_url(url)

  def _download_and_extract_symbols(self, image_archive_path):
    """Download and extract symbols from `image_archive_path`.

    Args:
      image_archive_path (str): A Google Storage path to the image archive.

    Returns:
      A Path object pointing to the dir with the extracted symbols.
    """
    debug_breakpad_local_path = self.m.path.mkdtemp(
        prefix='image_archive').join(SYMBOLS_FILE_NAME)
    try:
      self._download_and_log_gs_url(
          os.path.join(image_archive_path, SYMBOLS_FILE_NAME),
          debug_breakpad_local_path)
    except StepFailure as e:
      raise SymbolsFileNotFoundException('Symbols file not found in GS.') from e

    # Extract debug_breakpad.tar.xz. Has a directory structure debug/breakpad.
    # Note that the `recipe_engine/archive` module cannot handle tar.xz files.
    extracted_symbols_local_path = self.m.path.mkdtemp(
        prefix='extracted_symbols')
    self.m.step('extract symbols', [
        'tar', 'xf', debug_breakpad_local_path, '-C',
        extracted_symbols_local_path
    ])

    return extracted_symbols_local_path

  def _write_stackwalk_output(self, dmp_file, stackwalk_output):
    """Write `stackwalk_output` to `dmp_file`.txt.

    Args:
      dmp_file (str): A relative (to `context.cwd`) path to the .dmp file. The
        output is written to a new file that is the .dmp file name and path with
        a .txt output. Note that a str is taken instead of a
        `recipe_engine/path` Path object because the Path object does not
        support appending to the filename (only adding new elements separated
        by a '/'.
      stackwalk_output (str): The output to write.

    Returns:
      A Path to the written output.
    """

    # `dmp_file` is a str, not a Path object from the
    # `recipe_engine/path` module. To use it with the
    # `recipe_engine/file` module, it needs to be converted to a
    # Path object, which requires stripping the leading './'.
    stackwalk_output_path = self.m.context.cwd.join(
        dmp_file.lstrip('./') + '.txt')
    self.m.file.write_raw('write .dmp.txt', stackwalk_output_path,
                          stackwalk_output)
    return stackwalk_output_path

  def _find_dmp_files(self):
    """Find '.dmp' files in the cwd.

    Returns:
      A list[str] of relative paths to .dmp files.
    """
    return self.m.easy.stdout_step(
        'find .dmp files',
        ['find', '.', '-name', '*.dmp']).decode().strip().splitlines()

  def symbolicate_dump(self, image_archive_path, test_results):
    """Converts minidumps generated by tests into text files.

    For each of `test_results`, walks the directory, converts all found
    minidump files to text, and copies the text files back to `test_results`.

    Args:
      image_archive_path (str): A Google Storage path to the image archive.
      test_results (list[(DownloadedTestResult)]): A list of
          DownloadedTestResult which has both GS path and local path of the
          test result to process.

    Returns:
      A list[Path] of symbolicated files written.
    """
    stackwalk_output_paths = []
    with self.m.step.nest('symbolicate dump') as symbolicate_dump_pres:
      self._ensure_breakpad()

      try:
        symbols_path = self._download_and_extract_symbols(image_archive_path)
      except SymbolsFileNotFoundException:
        symbolicate_dump_pres.step_summary_text = (
            'Skipped because symbols file was not found in GS')
      else:
        for test_result in test_results:
          with self.m.step.nest('symbolicate dumps from {}'.format(
              test_result.gs_path)) as pres:
            with self.m.context(cwd=test_result.local_path):
              # Get all '.dmp' files in the test results dir. Note that the
              # `recipe_engine/file` module does not provide recursive search
              # functionality. The `glob` function does not recurse directory
              # structure.
              dmp_files = self._find_dmp_files()
              pres.logs['.dmp files'] = dmp_files

              for dmp_file in dmp_files:
                with self.m.step.nest(
                    'symbolicate {}'.format(dmp_file)) as pres2:
                  # Failures on a single minidump_stackwalk call should not crash
                  # the entire recipe. Catch and log StepFailures.
                  try:
                    stackwalk_output = self.m.easy.stdout_step(
                        'minidump_stackwalk',
                        [self._minidump_stackwalk_path, dmp_file, symbols_path])

                    pres2.logs['minidump_stackwalk output'] = stackwalk_output

                    stackwalk_output_path = self._write_stackwalk_output(
                        dmp_file, stackwalk_output)
                    stackwalk_output_paths.append(stackwalk_output_path)
                  except StepFailure as step_failure:
                    pres2.logs['caught StepFailure'] = str(step_failure)

              # `test_result_local_path` will not contain the final path component
              # of the remote test result path , e.g. "swarming-1234". This final
              # path component needs to be appeneded to the local path for the
              # rsync command so the directory structure lines up, e.g.
              # "rsync [local tmp dir]/test_result/swarming-1234
              #  gs://chromeos-autotest-results/swarming-1234"
              test_result_basename = os.path.basename(test_result.gs_path)
              self.m.gsutil([
                  'rsync', '-r', test_result.local_path / test_result_basename,
                  test_result.gs_path
              ], name='upload symbolicated files', multithreaded=True)

    return stackwalk_output_paths
