// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.code_coverage;

message CodeCoverageProperties {
  // GS bucket to which coverage data should be saved.
  // Defaults to cros-code-coverage-data.
  string gs_bucket = 1;

  // The Chrome OS project that holds the code that coverage is being generated
  // for. The project should be visible on https://chromium.googlesource.com/.
  string project = 2;

  // The branch that the code coverage is being generated for.
  // This almost always will be refs/heads/main and can be left blank.
  string branch = 3;

  // The coverage backend to upload(and store) results to.
  // Accepted values are `autopush` or `prod`.
  string coverage_env = 4;

  // Whether we need to skip uploading to chromium coverage.
  bool skip_chromium_upload = 5;

  // Whether invoked by the incremental(CQ) builder.
  // This is analogous to the cq.active flag. But, sometimes that flag can be false if
  // builder is manually triggered and this flag will still be true. Details in b/239721591.
  bool cq_builder = 6;
}
