// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.skylab;

message SkylabProperties {
  string ctp_builder = 5;
  string skylab_server = 1;
  string skylab_version = 2;
  string skylab_qs_account = 3;
  int32 skylab_priority = 4;
  bool enable_retries = 6;
  bool add_resultdb_settings = 7;
  // TODO(b/201608160): Remove upon experiment completion.
  // Projects on which to enable uploading to resultdb in prod.
  repeated string resultdb_elegible_projects = 8;

  // TODO(b/209497087): Experiment flag to enable passing container information
  // to CTP, remove once support is stabilized.
  bool enable_container_support = 9;
}
