// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.skylab;

message SkylabProperties {
  string ctp_builder = 5;
  string skylab_server = 1;
  string skylab_version = 2;
  string skylab_qs_account = 3;
  int32 skylab_priority = 4;
  reserved 6, 7, 8;

  // TODO(b/209497087): Experiment flag to enable passing container information
  // to CTP, remove once support is stabilized.
  bool enable_container_support = 9;

  // Set to true if the ResultDB invocations for scheduled CTP builds should NOT
  // be included in the ResultDB invocation for the current build. Defaults to
  // false (i.e. defaults to including scheduled CTP builds in the current
  // build's ResultRB invocation).
  bool exclude_sub_invs = 10;

  // Projects which have direct Tast testing enabled.
  repeated string direct_tast_testing_projects = 11;

  // Projects which are blocklisted from direct Tast testing.
  repeated string direct_tast_testing_blocklist_projects = 12;
}
