// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.looks_for_green;

message LooksForGreenProperties {
  // Whether to actually look-for-green.
  // Used to flag the feature and unittesting.
  bool enable_looks_for_green = 1;

  // Maximum hours to look back for a known-green snapshot.
  int32 lookback_hours = 3;

  // Threshold at which a snapshot is called "green". Score is assigned by the
  // greenness module - greenness is [0,100].
  int32 greenness_threshold = 4;

  // Whether to use a snapshot that has finished running with
  // snapshot-orchestrator rather than the latest created snapshot. If this
  // flag is not set, CQ will run with the latest minted or scored snapshot
  // (unless the greenness of the latest snapshot-orchestrator run is below the
  // greenness threshold, suggesting that the latest minted snapshot may be
  // broken).
  bool use_complete_snapshot = 5;

  reserved 2, 6, 7;
}

enum LooksForGreenStatus {
  STATUS_UNSPECIFIED = 0;
  // The most recent scored snapshot-orchestrator is green. Using the latest
  // snapshot that has been created.
  STATUS_RAN_LATEST_MINTED = 1;
  // Found an older snapshot within the configured lookback period.
  STATUS_RAN_OLDER = 2;
  // Couldn't find a green snapshot within the configured lookback period.
  STATUS_FOUND_NONE = 3;
  // Skipped the LFG due to Cq-Depend.
  STATUS_SKIPPED_CQ_DEPEND = 4;
  // Skipped the LFG due to stacked changes.
  STATUS_SKIPPED_STACKED_CHANGES = 5;
  // Skipped the LFG due to disallow.
  STATUS_SKIPPED_DISALLOW = 6;
  // Skipped the LFG due to merge commit.
  STATUS_SKIPPED_MERGE_COMMIT = 7;
  // Skipped the LFG as cherry-pick failed.
  STATUS_SKIPPED_FAILED_CHERRY_PICK = 8;
}

message LooksForGreenStats {
  message SnapshotStats {
    // Whether the snapshot-orchestrator is green compared to
    // greenness_threshold.
    bool is_snap_orch_green = 1;

    // Aggregate greenness (set in output props by greennness module) of
    // snapshot-orchestrator.
    int32 snap_orch_greenness = 2;

    // BBID of snapshot-orchestrator.
    int64 snap_orch_bbid = 3;

    // Approximate age of snapshot manifest tested with snapshot-orchestrator.
    int32 approx_snap_age_hours = 4;

    // SHA of snapshot manifest tested with snapshot-orchestrator.
    string snap_commit_sha = 5;
  }
  // Details of latest snapshot with greenness score.
  SnapshotStats latest_scored = 1;

  // Details of suggested snapshot.
  SnapshotStats suggested = 2;

  // Outcome of the Looks logic.
  LooksForGreenStatus status = 3;
}
