# -*- coding: utf-8 -*-
# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""APIs for CrOS Build."""

from recipe_engine import recipe_api


class CrosBuildApi(recipe_api.RecipeApi):
  """A module for CrOS Build steps."""

  def _chroot_step(self, name, cmd, **kwargs):
    """Runs a step within the configured workspace and cros_sdk chroot.

    Args:
      * name (str): The name of the step.
      * cmd (list[str]): A command and arguments to run.
      * kwargs: Keyword arguments to pass to 'cros_sdk.run'.

    Returns:
      See 'step.__call__'.
    """
    with self.m.context(cwd=self.m.cros.workspace_path):
      return self.m.cros_sdk.run(name, cmd, **kwargs)

  def regen_portage_cache(self, repo_name, jobs=32):
    """Regenerate the portage cache with 'egencache' in the chroot.

    Args:
      repo_name (str): Portage repo name, passed to 'egencache --repo'.
      jobs (int): Parallel processes to run, passed to 'egencache --jobs'.
    """
    cmd = ['egencache', '--update', '--repo', repo_name, '--jobs', '%d' % jobs]
    self._chroot_step('regen_portage_cache %s' % repo_name, cmd)

  def uprev_portage_packages(self):
    """Uprevs portage packages for all boards."""
    cmd = [
      'vpython','chromite/bin/cros_mark_as_stable', 'commit',
      '--all',
      '--buildroot', self.m.cros.workspace_path,
      '--overlay-type', 'both'
    ]
    if self.m.dev.dryrun:
      cmd += ['--dryrun']
    with self.m.context(cwd=self.m.cros.workspace_path):
      return self.m.step('uprev portage packages', cmd)

  def push_portage_package_uprevs(self):
    """Pushes the changes generated by |uprev_portage_packages| to remote."""
    # TODO(crbug.com/916197): Pull git operations out of this script
    cmd = [
      'vpython', 'chromite/bin/cros_mark_as_stable', 'push',
      '--buildroot', self.m.cros.workspace_path,
      '--overlay-type', 'both'
    ]
    if self.m.dev.dryrun:
      cmd += ['--dryrun']
    with self.m.context(cwd=self.m.cros.workspace_path):
      return self.m.step('push portage package uprevs', cmd)
