// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.goma;

import "chromiumos/common.proto";

message GomaProperties {
  // cipd goma client version to ensure, will use "latest" if not set.
  string client_version = 1;
  // GomaApproach to use, will use default if not set.
  .chromiumos.GomaConfig.GomaApproach goma_approach = 2;
  // Disable 'gsutil cp' to upload goma logs.
  bool disable_goma_logs_upload = 3;
  // Disable uploading stats/counterz data.
  bool disable_stats_counterz_upload = 4;
}
