// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.goma;

import "chromiumos/common.proto";

message GomaProperties {
  // cipd goma client version to ensure, will use "latest" if not set.
  string client_version = 1;
  // GomaApproach to use, will use RBE_CHROMEOS if not set.
  .chromiumos.GomaConfig.GomaApproach goma_approach = 2;
  // Disable 'gsutil cp' to upload goma logs.
  bool disable_goma_logs_upload = 3;
  // Disable uploading stats/counterz data.
  bool disable_stats_counterz_upload = 4;
  // BigQuery project in which a query is executed for stats/counterz upload.
  string bigquery_project_id = 5;
  // BigQuery dataset containing the table.
  string bigquery_dataset_id = 6;
  // BigQuery table_name where data is added for stats/counterz upload.
  string bigquery_table_name = 7;
  // Set the verbose flag in the bq-insert's input json.
  bool bigquery_verbose = 8;

  reserved 10;
  reserved "enable_goma_client_json";
}
