# -*- coding: utf-8 -*-
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""An API for providing release related operations (e.g. paygen, signing)."""

from recipe_engine import recipe_api
from recipe_engine.recipe_api import StepFailure

from PB.chromite.api.sysroot import Sysroot
from PB.chromiumos.common import (Channel, IMAGE_TYPE_RECOVERY,
                                  IMAGE_TYPE_FACTORY, IMAGE_TYPE_FIRMWARE,
                                  IMAGE_TYPE_ACCESSORY_USBPD,
                                  IMAGE_TYPE_ACCESSORY_RWSIG, IMAGE_TYPE_BASE,
                                  IMAGE_TYPE_GSC_FIRMWARE)
from PB.recipe_modules.chromeos.cros_source.cros_source import ManifestLocation

MANIFEST_VERSIONS_URL = 'https://chrome-internal.googlesource.com/chromeos/manifest-versions'


class CrosReleaseApi(recipe_api.RecipeApi):

  @property
  def _supported_sign_types(self):
    """Supported image types for signing.

    These are kept in sync with chromite/scripts/pushimage.py.

    Returns:
      A set of image type enum values.
    """
    return set([
        IMAGE_TYPE_RECOVERY, IMAGE_TYPE_FACTORY, IMAGE_TYPE_FIRMWARE,
        IMAGE_TYPE_ACCESSORY_USBPD, IMAGE_TYPE_ACCESSORY_RWSIG, IMAGE_TYPE_BASE,
        IMAGE_TYPE_GSC_FIRMWARE
    ])

  def validate_sign_types(self, sign_types):
    """Takes an array of IMAGE_TYPE enums and validates them or raises StepFailure."""
    if not set(sign_types).issubset(self._supported_sign_types):
      raise StepFailure('attempting to sign type not in supported sign types')

  @staticmethod
  def massage_channels(channels):
    """Takes an array of common_pb2.Channel & validates & strings them."""
    channels_strs = [Channel.Name(x) for x in channels]
    if 'CHANNEL_UNSPECIFIED' in channels_strs:
      raise StepFailure('invalid channel CHANNEL_UNSPECIFIED')
    return [x.replace('CHANNEL_', '') for x in channels_strs]

  def __init__(self, properties, **kwargs):
    super(CrosReleaseApi, self).__init__(**kwargs)
    self._release_bucket = properties.release_bucket
    self._channels = properties.channels
    self._keyset = properties.keyset
    self._sign_types = properties.sign_types
    self._ensure_no_password = properties.ensure_no_password
    self._firmware_update = properties.firmware_update
    self._dryrun = properties.dryrun
    self._paygen_dryrun = properties.paygen_dryrun
    self._releasespec = None

  @property
  def releasespec(self):
    """Return the releasespec as created by this module, or None."""
    return self._releasespec

  def create_releasespec(self, specs_dir='releasespecs', branch='release',
                         step_name='create releasespec', dry_run=False,
                         gs_location=None):
    """Create a pinned manifest and upload to manifest-versions/releasespecs.

    Args:
      specs_dir (str): Relative path in manifest-versions in which to place the
        pinned manifest.
      branch (str): The branch of manifest-versions that will be used, or None
        to use the default branch.
      step_name (str): The step name to use.
      dry_run (bool): Whether the git push is --dry-run.
      gs_location (string): If set, will also upload the pinned manifest to GS.

    Returns:
      Full URL path to newly-uploaded manifest.
    """
    with self.m.step.nest(step_name):
      with self.m.context(cwd=self.m.src_state.workspace_path):
        manifest_data = self.m.repo.manifest(step_name='create pinned manifest',
                                             pinned=True)

      tmp_dir = self.m.path.mkdtemp(prefix='manifest-versions')
      with self.m.context(cwd=tmp_dir):
        # Clone manifest-versions repo to current path.
        with self.m.step.nest('clone manifest-versions'):
          self.m.git.clone(MANIFEST_VERSIONS_URL, branch=branch,
                           single_branch=True)
          branch = branch or self.m.git.current_branch()

        version = self.m.cros_version.version
        manifest_file = self.m.path.join(specs_dir, version.buildspec_filename)
        manifest_path = self.m.path.join(tmp_dir, manifest_file)
        manifest_dir = self.m.path.dirname(manifest_path)
        self.m.file.ensure_directory('ensure {} exists'.format(manifest_dir),
                                     manifest_dir)
        self.m.file.write_raw('write {}'.format(manifest_file), manifest_path,
                              manifest_data)

        commit_lines = [
            'Add {}'.format(manifest_file),
            '',
            'Generated by Rubik.',
            '',
            'Cr-Build-Url: {}'.format(self.m.buildbucket.build_url()),
            'Cr-Automation-Id: cros_release/create_releasespec',
        ]
        commit_message = '\n'.join(commit_lines) + '\n'
        with self.m.step.nest('commit {} to {}'.format(manifest_file, branch)):
          self.m.git.add([manifest_file])
          self.m.git.commit(commit_message)
          self.m.git.push('origin', 'HEAD:refs/for/{}%submit'.format(branch),
                          dry_run=dry_run)

        manifest_gs_path = ''
        if gs_location:
          with self.m.step.nest('upload {} to {}'.format(
              manifest_file, gs_location)):
            # Split bucket off, and then append buildspec to the rest of the path (if any).
            # If a filename is not supplied in gs_location, we use the buildspec_filename.
            gs_toks = self.m.path.dirname(gs_location).split("/", 1)
            gs_bucket = gs_toks[0]
            gs_path = gs_toks[1]
            if self.m.path.basename(gs_location) == "":
              gs_path = self.m.path.join(gs_path, version.buildspec_filename)
            self.m.gsutil.upload(manifest_path, gs_bucket, gs_path)
            manifest_gs_path = 'gs://{}/{}'.format(gs_bucket, gs_path)

      self._releasespec = ManifestLocation(
          manifest_repo_url=MANIFEST_VERSIONS_URL, branch=branch,
          manifest_file=manifest_file, manifest_gs_path=manifest_gs_path)

  def schedule_payload_generation(self):
    """Schedule the generation of release payloads using the context of a build.

    This is nonblocking, will launch and return the id for the paygen
    orchestrator. It assumes its being ran after a local build has been made.

    Args:
      build_target_name (str): The builder target name.
      target_chromeos_version (str): The target chromeos version (e.g. '13337.0.1').
      milestone (int): The milestone number.

    Returns:
      The int build id for the launched orchestrator.
    """
    pg_orch_builder = ('staging-paygen-orchestrator' if
                       self.m.build_menu.is_staging else 'paygen-orchestrator')
    bucket = 'staging' if self.m.build_menu.is_staging else 'release'

    version = self.m.cros_version.version
    with self.m.step.nest('generate payloads'):
      paygen_properties = {
          'builder_name': self.m.build_menu.build_target.name,
          'target_chromeos_version': version.platform_version,
          'delta_types': [],
          'channels': CrosReleaseApi.massage_channels(self._channels),
          'au_testing_models': [],
          'src_bucket': self._release_bucket,
          'dest_bucket': self._release_bucket,
          'keyset': self._keyset,
          'dryrun': self._paygen_dryrun,
          'delta_payload_test_override': 'RESPECT_CONFIG',
          'full_payload_test_override': 'RESPECT_CONFIG',
      }
      request = self.m.buildbucket.schedule_request(
          builder=pg_orch_builder, bucket=bucket, properties=paygen_properties)
      return self.m.buildbucket.run(
          [request], timeout=self.m.cros_paygen.paygen_orchestrator_timeout_sec,
          step_name='running paygen orchestrator')

  def push_and_sign_images(self):
    """Call the Push Image Build API endpoint for the build.

    This pushes the image files to the appropriate bucket and prepares them
    for signing. The actual execution of these procedures is handled in the
    underlying script, chromite/scripts/push_image.py. Must be used in the
    context of a build.
    """
    version = str(self.m.cros_version.version)
    with self.m.step.nest('push images') as presentation:
      gs_bucket = self.m.build_menu.config.artifacts.artifacts_gs_bucket
      gs_path = '{target}-release/{version}'.format(
          target=self.m.build_menu.build_target.name, version=version)
      gs_image_dir = 'gs://{gs_bucket}/{gs_path}'.format(
          gs_bucket=gs_bucket, gs_path=gs_path)
      presentation.step_text = (
          'https://console.cloud.google.com/storage/browser/{gs_bucket}/{gs_path}'
          .format(gs_bucket=gs_bucket, gs_path=gs_path))
      sysroot = Sysroot(build_target=self.m.build_menu.build_target)
      # Validate sign types given.
      self.validate_sign_types(self._sign_types)
      return self.m.cros_artifacts.push_image(
          self.m.build_menu.chroot, gs_image_dir, sysroot,
          sign_types=self._sign_types,
          dest_bucket='gs://' + self._release_bucket)
