// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_release;

import "chromiumos/common.proto";

message CrosReleaseProperties {

  // The bucket where should push images to (e.g. 'chromeos-releases').
  string release_bucket = 1;

  // The bucket where we should source paygen images from, defaults to
  // release_bucket.
  string src_paygen_bucket = 2;

  // The channels to consider when pushing and signing the image.
  repeated chromiumos.Channel channels = 3;

  // The types of images to sign for.
  repeated chromiumos.ImageType sign_types = 4;

  // This also ignores paygen_dryrun, as the step is never reached.
  bool dryrun = 5;

  // Only dryrun creation of playloads, don't place.
  bool paygen_dryrun = 6;

  // If set, don't upload buildspecs to manifest-versions.
  // The buildspec still may be uploaded to GS, depending on the situation.
  bool dont_upload_to_manifest_versions = 7;

  // Whether to upload the buildspec to the corresponding -snapshot branch.
  // See go/upload-chromeos-test-source-information-proposal for context.
  bool commit_buildspec_as_snapshot = 10;

  // Whether the build supports minios.
  bool minios_unsupported = 8;

  // Whether to dynamically compute the QS account to use for release.
  bool dynamic_qs_account = 9;

  // Whether to run paygen on MPA bots.
  bool paygen_mpa = 11;

  // The threshold percentage of child builds that must succeed for a build
  // to be considered successful for throttling purposes.
  // If not set or 0, defaults to 80.
  int32 throttling_threshold_percent = 12;
}
