// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_release;

import "chromiumos/common.proto";

message CrosReleaseProperties {

  // The bucket where should push images to (e.g. 'chromeos-releases').
  string release_bucket = 1;

  // The channels to consider when pushing and signing the image.
  repeated chromiumos.Channel channels = 2;

  // The types of images to sign for.
  repeated chromiumos.ImageType sign_types = 3;

  // This also ignores paygen_dryrun, as the step is never reached.
  bool dryrun = 4;

  // Only dryrun creation of playloads, don't place.
  bool paygen_dryrun = 5;

  // If set, don't upload releasespecs to manifest-versions.
  // The releasespec still may be uploaded to GS, depending on the situation.
  bool dont_upload_to_manifest_versions = 6;
}
