// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.incremental;

message IncrementalProperties {
  // Incremental builder will perform first build using checkout as old as
  // specified by build_time_delta. Example value: "7.days.ago".
  string build_time_delta = 1;

  // Whether to run cros clean-outdated-pkgs.
  bool cop_enabled = 2;

  // Whether to use Local Looks For Green for recent build
  // (old build is not currently LLFG)
  bool use_llfg = 3;

  // Whether to run pointless build check.
  bool run_relevancy_check = 4;
}

enum ErrorType {
  UNKNOWN = 0;
  NON_INCREMENTAL = 1;
  INCREMENTAL = 2;
}
