// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_source;

message CrosSourceProperties {

  message SnapshotIsolate {
    string isolated_hash = 1;
    string isolate_server = 2;
  }

  // Used to specify a custom manifest snapshot to sync to as a
  // snapshot.xml file residing in the isolate.
  SnapshotIsolate snapshot_isolate = 2;

  // Feature flag: whether to allow mounting the external or custom overlay.
  bool enable_custom_overlays = 3;

  // Feature flag: whether to make any manifest changes active when applying
  // patches.  Without this, the patches are present in the manifest repo, but
  // the unpatched manifest is used for all repo commands (including syncing the
  // source tree).  With this, manifest changes are applied, and the source tree
  // is re-synced using the patched manifest.
  bool make_manifest_changes_active = 4;
}
