// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.chromeos.cros_test_plan_v2;

message CrosTestPlanV2Properties {
  reserved 1 to 2;

  // Name of the Docker image to use for the platform-owned half of test plan.
  // The image name should be an image under gcr.io/chromeos-bot. Defaults to
  // "testplan".
  string platform_test_plan_docker_image = 3;

  // Tag to pull platform_test_plan_docker_image.
  // Defaults to "staging" or "prod", based on the
  // cros_infra_config.is_staging property.
  string platform_test_plan_docker_tag = 4;

  // Configure changes in a project to be migrated to v2 test planning.
  // NEXT ID: 11
  message ProjectMigrationConfig {
    // Gerrit hostname of the project being migrated, e.g.
    // "chromium-review.googlesource.com". Required.
    string host = 1;

    // Gerrit project being migrated, e.g. "chromium/src". Required.
    // Regular expressions are allowed. Expressions must be compatible with the
    // re module in the Python standard library. When checking a match, '^' and
    // '$' are added at the front and back of the pattern, respectively, i.e.
    // the pattern must match the entire path string.
    string project = 2;

    // Blocklist of projects to not migrate. Optional. If a project is matched
    // by the above "project" field regexp, but is matched by any of the regexps
    // in this blocklist field, it will not be migrated. The same regular
    // expression rules as for the above "project" field apply.
    repeated string project_blocklist = 10;

    // Allowlist of branch regexps that will be migrated. Required.
    //
    // At least one entry is required (to migrate all branches, specify ".*").
    //
    // Expressions must be compatible with the re module in the Python standard
    // library. When checking a match, '^' and '$' are added at the front and
    // back of the pattern, respectively, i.e. the pattern must match the entire
    // path string.
    repeated string branch_allowlist_regexps = 5;

    // Allowlist and blocklist of file regexps that can be migrated. The
    // allowlist is required (to migrate all changes in a project, specify
    // ".*"). The blocklist is not required (default is no files are
    // blocklisted). A change will be migrated iff all affected files are in at
    // least one expression in the allowlist, and none are in any expressions in
    // the blocklist.
    //
    // Expressions must be compatible with the re module in the Python standard
    // library. When checking a match, '^' and '$' are added at the front and
    // back of the pattern, respectively, i.e. the pattern must match the entire
    // path string.
    repeated string file_allowlist_regexps = 3;
    repeated string file_blocklist_regexps = 4;

    // If true, if no SourceTestPlans are found for this project, the default
    // set of files will be used ("legacy_default*.star" files). If false, if
    // no SourceTestPlans are found for this project, no tests will be run. If
    // any SourceTestPlans are found, this field has no effect.
    bool fallback_to_default = 9;
  }

  // Projects to be migrated to v2 test planning. Note that a CQ run will use v2
  // test planning only if all Gerrit changes is the CQ are allowed by these
  // migration configs.
  repeated ProjectMigrationConfig migration_configs = 5;

  // If true, the testplan tool will return a GenerateTestPlanResponse proto
  // instead of HWTestPlans, for backwards compatibility with CTPV1.
  bool generate_ctpv1_format = 6;
}
